<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCerrarConsultaAliasCBU</name>
   <tag></tag>
   <elementGuidId>7b453560-547b-4434-b232-a556de24f2fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsDetailsBccl_Panel_lblCloseIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsDetailsBccl_Panel_lblCloseIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48a8b436-ec20-4ff6-88d8-377b70d97aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl_Panel_lblCloseIcon</value>
      <webElementGuid>185ec32c-dfba-46b9-a281-e83b1405d348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>90bc3e50-14f8-4d8b-8738-c7c416cda25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl</value>
      <webElementGuid>7abe2475-4989-4348-a094-b3e15984491c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Panel</value>
      <webElementGuid>9d643baf-ef06-448f-84ac-ce453078ce94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddlecenteralign disableSelection sknLblPanelCloseIcon</value>
      <webElementGuid>96e08126-1cf5-4ea0-832a-eb5353ede0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2bc6db3e-eecb-4564-b440-98469c0ef2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_Panel_lblCloseIcon&quot;)</value>
      <webElementGuid>25ff4ec7-58a9-450a-a648-6afb3a2a2e88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_Panel_lblCloseIcon']</value>
      <webElementGuid>cd2fab2c-16d4-400f-aa9f-57f3378c2ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_Panel_flxCloseIcon']/div/div</value>
      <webElementGuid>2095e3e4-4a01-42c1-952e-0a8dfb972592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El máximo permitido es 50 caracteres'])[1]/following::div[33]</value>
      <webElementGuid>437dfd1f-410a-42c2-8c7a-03dd9e16fae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Máximo 50 caracteres'])[1]/following::div[35]</value>
      <webElementGuid>32c0a783-dd51-4bb9-979c-499ea03db4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>8a4686ed-d070-4db3-9ebc-efe6789dcb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de la Cuenta'])[1]/preceding::div[9]</value>
      <webElementGuid>c5c9aa9b-1180-439a-961d-c29232b06701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>db7d0e1a-4f44-4149-866b-4ed07a2cf110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsDetailsBccl_Panel_lblCloseIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>91cb73c4-6f7a-42da-ab1f-7920f5b66812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
