<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoCtaFavoritoCA</name>
   <tag></tag>
   <elementGuidId>3d1b0aea-2f00-4b62-8e03-d1a1046ac366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxAccountsHomeTableRow_lblAccountFavourite'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kcell.middlecenteralignsknLblEmptyStarAccounts > #flxAccountsHomeTableRow_lblAccountFavourite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f3dc3c7-099d-4391-b206-7e69368870e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow_lblAccountFavourite</value>
      <webElementGuid>ff9a6fae-d685-41ff-a63c-63aec939ff23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>b72a93ed-7d33-41fc-9cb1-8302716e8087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow</value>
      <webElementGuid>87d45232-6026-4609-8784-6d956687d9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>a1d745e9-d29e-450f-8ab7-4e8bcb47c81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>B2DB70DD-C20E-4366-AFA4-12B559A81E95</value>
      <webElementGuid>984a774f-3dd2-400a-a3c3-cc080c997e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblEmptyStarAccounts cntmiddlecenteralign disableSelection</value>
      <webElementGuid>7de3b9f0-bc97-41a8-8f7d-37129ee07cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>60f0e18d-f526-443b-9773-cbded864be3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_segAccounts&quot;)/ul[1]/li[@class=&quot;sknSegAccountTable&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountsHomeTableRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxFavouriteContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxFavoriteWrapper&quot;]/div[@class=&quot;kcell middlecenteralignsknLblEmptyStarAccounts&quot;]/div[@id=&quot;flxAccountsHomeTableRow_lblAccountFavourite&quot;]</value>
      <webElementGuid>6e4b1e92-b599-4d84-875e-e9da909854af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountsHomeTableRow_lblAccountFavourite'])[2]</value>
      <webElementGuid>3eeffc6b-896c-460f-90a3-6fe2397fb6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountsHomeTableRow_flxFavoriteWrapper']/div/div)[2]</value>
      <webElementGuid>7abc0e7e-2fa1-4862-a31c-48fd1a582fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 001-054864/8'])[1]/following::div[8]</value>
      <webElementGuid>df5ffedf-51cf-4e50-b6dd-cf9ca130e969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro $$'])[1]/following::div[10]</value>
      <webElementGuid>38c4e35f-2eec-41c9-b8b7-fbcfae10869f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/preceding::div[1]</value>
      <webElementGuid>ca30432b-288f-4475-8cbf-295c7c7ba79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 90.937,03'])[1]/preceding::div[9]</value>
      <webElementGuid>bd0b7fb2-cc7d-4f84-a4a0-a231b1d6c047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>e92a1d72-0a44-4999-b106-806b665c0c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountsHomeTableRow_lblAccountFavourite' and (text() = '' or . = '')]</value>
      <webElementGuid>3f417d37-1c36-4c86-95df-dbf9162ffcfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
