<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoCtaFavoritoCC</name>
   <tag></tag>
   <elementGuidId>648eca06-85af-4d80-b81b-938aa0b3dfe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxAccountsHomeTableRow_lblAccountFavourite']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmAccountsHome_segAccounts&quot;)/ul[1]/li[@class=&quot;sknSegAccountTable&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountsHomeTableRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxFavouriteContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxFavoriteWrapper&quot;]/div[@class=&quot;kcell middlecenteralignsknLblEmptyStarAccounts&quot;]/div[@id=&quot;flxAccountsHomeTableRow_lblAccountFavourite&quot;][count(. | //*[@id = 'flxAccountsHomeTableRow_lblAccountFavourite' and @kuid = '8998846A-DFA6-44BB-B565-C17598020D45']) = count(//*[@id = 'flxAccountsHomeTableRow_lblAccountFavourite' and @kuid = '8998846A-DFA6-44BB-B565-C17598020D45'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxAccountsHomeTableRow_lblAccountFavourite</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dcead273-3492-4761-8006-e73f3ead2eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow_lblAccountFavourite</value>
      <webElementGuid>c8b7c94b-eaa2-445a-9a5c-6eef71d3755b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>d2f1ae91-12bd-43bd-99ba-468248e3c8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow</value>
      <webElementGuid>2d0de6ea-74c2-49a2-99e2-60835c7d1a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>0668959e-4662-472b-9af6-cb276039fc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>8998846A-DFA6-44BB-B565-C17598020D45</value>
      <webElementGuid>73e6c60f-8f5b-489c-9506-3aabee708a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblEmptyStarAccounts cntmiddlecenteralign disableSelection</value>
      <webElementGuid>e58317b5-d36a-4686-ad1b-218b65c058e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>3b003230-0abd-472d-9cfe-ccbf6c1c84b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_segAccounts&quot;)/ul[1]/li[@class=&quot;sknSegAccountTable&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountsHomeTableRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxFavouriteContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxFavoriteWrapper&quot;]/div[@class=&quot;kcell middlecenteralignsknLblEmptyStarAccounts&quot;]/div[@id=&quot;flxAccountsHomeTableRow_lblAccountFavourite&quot;]</value>
      <webElementGuid>cd1be600-e402-41ee-99bb-cc29b4674545</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxAccountsHomeTableRow_lblAccountFavourite']</value>
      <webElementGuid>445b9a7f-5fde-4c12-a004-169526adbc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxAccountsHomeTableRow_flxFavoriteWrapper']/div/div</value>
      <webElementGuid>0e2bf4bf-7f46-48da-a004-d81836088616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 001-065350/4'])[1]/following::div[8]</value>
      <webElementGuid>5a77ebff-b98a-46ae-ba06-b352f5949c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SZIR MARIA ALEJANDRA'])[1]/following::div[10]</value>
      <webElementGuid>5e219439-1c78-459f-8d4f-4f088fa1c398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/preceding::div[1]</value>
      <webElementGuid>5044aa57-745e-49a8-b2bf-8f04e4de7400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- $ 16.256,71'])[1]/preceding::div[9]</value>
      <webElementGuid>0ce32af7-74cf-4e09-a565-b6b61a397eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>4c3cb4c8-ab5e-49d1-b134-40d515496783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>6f2c9ed3-e986-4633-8513-14de2502020b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountsHomeTableRow_lblAccountFavourite' and (text() = '' or . = '')]</value>
      <webElementGuid>0a48b614-77a9-4894-bef4-72f831d0cd83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
