<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCtaTituloCuentaTabla</name>
   <tag></tag>
   <elementGuidId>fd2657c9-ad14-4f9d-9069-6cc87d6574c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsHome_lblAccountHeader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsHome_lblAccountHeader</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'frmAccountsHome_lblAccountHeader' and (text() = 'Cuenta' or . = 'Cuenta')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0fc9afc9-2031-476a-8404-8e75c8a4b60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsHome_lblAccountHeader</value>
      <webElementGuid>67209c08-a8e2-4226-b170-95d68262679d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>3c4845a6-05c7-4607-9048-01499514e9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsHome</value>
      <webElementGuid>49b8f202-41ba-4aa6-9814-e302943f9819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableHeader cntmiddleleftalign disableSelection</value>
      <webElementGuid>3a21633b-dfba-481e-933a-cc0688ea9155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cuenta</value>
      <webElementGuid>3a6e113c-f7f5-470c-b020-f5684e16b678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_lblAccountHeader&quot;)</value>
      <webElementGuid>fd240187-3209-457e-92e5-095c8373eafe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsHome_lblAccountHeader']</value>
      <webElementGuid>0bbcf56a-abd2-4410-99e5-d10b595879c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsHome_flxAccountsTableHeader']/div/div</value>
      <webElementGuid>24c1c7eb-829c-45ac-8ed7-5df9bdf79d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TUS CUENTAS'])[1]/following::div[5]</value>
      <webElementGuid>70ef2244-6753-4f83-8f7e-5bb0b8f888c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[3]/following::div[17]</value>
      <webElementGuid>9f741782-f02d-4f1c-aaf2-c0d1a74e582d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorita'])[1]/preceding::div[1]</value>
      <webElementGuid>02a852f9-e6ea-4db6-8092-1c878b89a818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moneda'])[1]/preceding::div[3]</value>
      <webElementGuid>e036b330-2834-48b0-997f-cb0cf806bfbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cuenta']/parent::*</value>
      <webElementGuid>ac3d487e-64b0-4bc1-b230-bae766d87164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>16214d0b-f066-46c3-8478-669e6778ae67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsHome_lblAccountHeader' and (text() = 'Cuenta' or . = 'Cuenta')]</value>
      <webElementGuid>b1606175-1ef8-4d34-98a1-51a98a33d143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
