<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCtaTituloCuentas</name>
   <tag></tag>
   <elementGuidId>013e142d-8ea6-454b-b2c6-774bf6cacaa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsHome_flxLeftContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsHome_flxLeftContainer</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmAccountsHome_flxLeftContainer&quot;)[count(. | //*[@id = 'frmAccountsHome_flxLeftContainer' and @kformname = 'frmAccountsHome']) = count(//*[@id = 'frmAccountsHome_flxLeftContainer' and @kformname = 'frmAccountsHome'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9997f637-ef95-43dc-b0e9-0f6f55731319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>90600418-5ce0-40a8-8fa0-950b733d7e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsHome_flxLeftContainer</value>
      <webElementGuid>337a9add-475f-4908-a302-aa4ecc0b044e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>f2229648-f589-4945-b770-6c335964af9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsHome</value>
      <webElementGuid>32fef439-44cd-46f6-9dca-d9665d40e8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cuentas</value>
      <webElementGuid>9a9c3bc5-3f38-461d-b6a4-c63630cf1f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_flxLeftContainer&quot;)</value>
      <webElementGuid>2522eb6d-26e3-408e-be27-a18ce1b794d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsHome_flxLeftContainer']</value>
      <webElementGuid>f9e95822-d313-47c8-936a-abf9e41272c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[225]</value>
      <webElementGuid>500336dd-e63c-495c-83cc-2b08ea5196a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis cuentas'])[1]/following::div[32]</value>
      <webElementGuid>e987d5f0-4dc3-4703-a573-9f7aa314a237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuentas'])[2]/following::div[55]</value>
      <webElementGuid>959ca773-5514-43f5-ba40-7160179c5b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>3070f14e-1c26-4883-a8c7-a800b050a058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsHome_flxLeftContainer' and (text() = 'Cuentas' or . = 'Cuentas')]</value>
      <webElementGuid>ce169dd0-1bf8-47f5-a072-a439660046f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
