<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCtaTituloSaldoTabla</name>
   <tag></tag>
   <elementGuidId>661e0188-0a29-4d92-af31-05105c6d41a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsHome_lblAccountAmountHeader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsHome_lblAccountAmountHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a49a6832-6a5f-47a1-af65-61d841411557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsHome_lblAccountAmountHeader</value>
      <webElementGuid>b94cfbb1-a1e2-42ef-86b9-d5dd4d4fecf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>d26537c3-350f-4c9d-be32-9abf78f8cbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsHome</value>
      <webElementGuid>cf81f5d6-0f55-4fb5-a05c-c94c72b0a2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableHeader cntmiddlerightalign disableSelection</value>
      <webElementGuid>6e6a6f00-9977-41b3-a45c-1eccad28500d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saldo</value>
      <webElementGuid>54ce7656-1ae4-4f0a-b42e-f27952ae4849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_lblAccountAmountHeader&quot;)</value>
      <webElementGuid>5cce7aae-50a5-40df-be6b-a8fa842b8e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsHome_lblAccountAmountHeader']</value>
      <webElementGuid>0809d5be-9ef0-4e31-aba9-8eb397f805ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsHome_flxAmountContainer']/div/div</value>
      <webElementGuid>de033a98-696a-41b3-9cd8-546dc5d91828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moneda'])[1]/following::div[5]</value>
      <webElementGuid>35147bbe-0bd3-463f-9b9c-6c6eb5b99f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorita'])[1]/following::div[7]</value>
      <webElementGuid>541b0323-fd1a-4778-8940-380579c35ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Querés guardar los cambios realizados?'])[1]/preceding::div[1]</value>
      <webElementGuid>8226118b-0412-4d16-8e88-7517c85b0948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[4]</value>
      <webElementGuid>726088f2-9aba-42d6-b58d-1a4d2b8d5235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saldo']/parent::*</value>
      <webElementGuid>e99b2080-f1af-46e9-826a-cc6b70c4cdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[2]/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>a6656a20-31c9-40f2-ac03-28f4680ba872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsHome_lblAccountAmountHeader' and (text() = 'Saldo' or . = 'Saldo')]</value>
      <webElementGuid>ffc2f7e1-0d0c-42cf-b44c-e4ea8c85b9af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
