<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkCtaNombreEtiqueta</name>
   <tag></tag>
   <elementGuidId>35f147f7-97d8-471b-b43c-c6e4dd31722e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxAccountsHomeTableRow_lblAccountTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxAccountsHomeTableRow_lblAccountTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f8e24096-b5de-4eeb-9de6-0eba31355039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow_lblAccountTitle</value>
      <webElementGuid>517a9b9e-92d5-43a6-b5ba-203afbcefe7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>bd550d01-3465-49b9-b198-e9edba7ab33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow</value>
      <webElementGuid>bc69dcfe-ce06-498e-91b7-dcc89d35217b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>d96cdf33-6923-4001-aa5e-0559ec351638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>23415A38-6FA6-4797-B77D-8278BA37CEF2</value>
      <webElementGuid>b0c702d4-7664-4882-ab77-4545d55b2af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountEllipsisLato14042 cntmiddleleftalign disableSelection</value>
      <webElementGuid>4863922e-be94-4fa5-96cc-4375bc844dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modificacion Nombre Cta modificacion.</value>
      <webElementGuid>52ef6e79-cbd8-47bb-a2c3-9ccf82e10e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_segAccounts&quot;)/ul[1]/li[@class=&quot;sknSegAccountTable&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountsHomeTableRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxLeftContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountTitleContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblAccountEllipsisLato14042&quot;]/div[@id=&quot;flxAccountsHomeTableRow_lblAccountTitle&quot;]</value>
      <webElementGuid>f16e2306-26ca-4e32-86b6-06f1e10df255</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxAccountsHomeTableRow_lblAccountTitle']</value>
      <webElementGuid>7989ed99-47d6-4d73-b953-ed59e17ee9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxAccountsHomeTableRow_flxAccountTitleContainer']/div/div</value>
      <webElementGuid>96e24834-bce3-4c0c-a8ab-1f158b005383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[5]</value>
      <webElementGuid>07aee169-8d71-4b2f-a299-9f17dcc24b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[17]</value>
      <webElementGuid>9687484c-03b5-420e-ae85-8c53fc481778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 094-002281/8'])[1]/preceding::div[1]</value>
      <webElementGuid>425f8d6f-7f26-420a-9a11-5d1e7b675334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[3]</value>
      <webElementGuid>5da3646e-4624-4984-9b25-c6f52be94ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modificacion Nombre Cta modificacion.']/parent::*</value>
      <webElementGuid>6b74ccd9-ae42-4f2d-aeb0-506a9cbc59d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>d3987397-8b85-4d15-b923-fb7519f103b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountsHomeTableRow_lblAccountTitle' and (text() = 'Modificacion Nombre Cta modificacion.' or . = 'Modificacion Nombre Cta modificacion.')]</value>
      <webElementGuid>46f18c6d-8745-4dd1-af43-22374f79b9a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
