<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtaConsultarAliasCBU</name>
   <tag></tag>
   <elementGuidId>788ccd59-0327-4b1b-8b57-80bd4b7b46e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsHome_CFloatingMenu_lblgetAlias</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsHome_CFloatingMenu_lblgetAlias']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>397a39c9-bd76-4eb4-9ceb-3fe252d66c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsHome_CFloatingMenu_lblgetAlias</value>
      <webElementGuid>2179a470-9621-456b-8809-8891f467f15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>1f1edb42-0683-42a6-ac44-4332eedfbc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsHome</value>
      <webElementGuid>3b908bc6-9c20-4839-b30d-8e7f1cf294d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CFloatingMenu</value>
      <webElementGuid>0792b9cc-53f6-49f9-9ed4-65f18ab8f7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>ab6c04e6-3c9b-4f63-8421-22d363f90360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consultar Alias y CBU</value>
      <webElementGuid>4b34d329-48b5-4637-9e06-3f35f67784f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_CFloatingMenu_lblgetAlias&quot;)</value>
      <webElementGuid>41bce50d-7881-458f-a98e-4c73531e151f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsHome_CFloatingMenu_lblgetAlias']</value>
      <webElementGuid>32644f0f-9d85-432f-a6b2-16fa7b22ccf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsHome_CFloatingMenu_flxgetAlias']/div/div</value>
      <webElementGuid>5716830a-8bbb-4699-a935-cf1a983bb3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[7]/following::div[8]</value>
      <webElementGuid>9fae83b1-d2df-4953-804f-1b89a92d0193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[12]/following::div[33]</value>
      <webElementGuid>9794cf5b-cf10-4cc7-8b19-8d85a9790b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baja de cuenta'])[1]/preceding::div[1]</value>
      <webElementGuid>8e658436-d791-4e43-a3b3-c555e9529b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta detalle Débito automático'])[1]/preceding::div[6]</value>
      <webElementGuid>9cd8b3c8-9c36-4aba-ace8-16cde12e07e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consultar Alias y CBU']/parent::*</value>
      <webElementGuid>d3c2b47e-9c4d-465e-be0d-e8c5043046bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>0374920c-38bb-4508-bd81-94ea7202d89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsHome_CFloatingMenu_lblgetAlias' and (text() = 'Consultar Alias y CBU' or . = 'Consultar Alias y CBU')]</value>
      <webElementGuid>920e6a58-b510-4b8d-90b1-40d3dae323c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
