<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtaNumeroCBU</name>
   <tag></tag>
   <elementGuidId>9cbf07d6-eba7-4257-bb7f-5ca9f20d5bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxCbuAliasRow_lblCbu']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmCbuAliasBccl_segCbuAlias&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCbuAliasRow_flxCbuAliasRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxCbuAliasRow_lblCbu&quot;][count(. | //*[@id = 'flxCbuAliasRow_lblCbu' and (text() = '19100018-55000106530096' or . = '19100018-55000106530096')]) = count(//*[@id = 'flxCbuAliasRow_lblCbu' and (text() = '19100018-55000106530096' or . = '19100018-55000106530096')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxCbuAliasRow_lblCbu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83164096-2d7f-4b5d-afeb-a5f80a929f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCbuAliasRow_lblCbu</value>
      <webElementGuid>906d0f70-95ea-4129-af4c-4319b78f67c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>adee2ac0-1616-4e3f-9e06-decbc025c153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCbuAliasRow</value>
      <webElementGuid>b65fa383-91a4-4d1e-841d-4f78f6aba8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segCbuAlias</value>
      <webElementGuid>1ca7e4a5-596b-4703-987b-651651736970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>9595B9B1-4C46-492C-96DA-AF129A64C8D6</value>
      <webElementGuid>871a08ae-5800-4341-a717-95d1371e825e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddleleftalign disableSelection</value>
      <webElementGuid>1284afab-f2da-4f0d-83df-8728ef09aec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19100018-55000106530096</value>
      <webElementGuid>5bca1252-c190-4edf-9391-7da16f4bb07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCbuAliasBccl_segCbuAlias&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCbuAliasRow_flxCbuAliasRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxCbuAliasRow_lblCbu&quot;]</value>
      <webElementGuid>d1f295ea-7407-4a34-84c9-9f822d0616ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxCbuAliasRow_lblCbu']</value>
      <webElementGuid>a32b4374-cf98-4e67-8818-e8e8c17a2089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxCbuAliasRow_flxCbuAliasRow']/div[3]/div</value>
      <webElementGuid>b3cb5f4e-abd1-4cca-9ddf-ef842a9c15dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 001-065300/9'])[1]/following::div[2]</value>
      <webElementGuid>2407e856-bc76-467a-923b-ea922808c2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENRICO EDIE AGUSTIN'])[1]/following::div[7]</value>
      <webElementGuid>143657d6-b5e5-405a-bafa-b6fab769158d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cielo.estrella.mar'])[1]/preceding::div[1]</value>
      <webElementGuid>cbb570de-a9b8-41ce-921e-c64b45c0dc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[3]</value>
      <webElementGuid>af635aa8-71b4-4c25-9f32-0e1c41ac0ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19100018-55000106530096']/parent::*</value>
      <webElementGuid>012a4413-5453-44d9-8b50-2db412231820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div[3]/div</value>
      <webElementGuid>b1e892b2-e62d-4f43-96f1-e1389d9613ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCbuAliasRow_lblCbu' and (text() = '19100018-55000106530096' or . = '19100018-55000106530096')]</value>
      <webElementGuid>535db40b-06d2-4962-addc-2228413d29cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
