<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtaCambiarNombreModificado</name>
   <tag></tag>
   <elementGuidId>80c1e30e-e769-426e-ba29-92446df54045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsDetailsBccl_CFloatingMenu_lblEditName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsDetailsBccl_CFloatingMenu_lblEditName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>284c0db5-e100-42df-bfe6-2129efeb8c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl_CFloatingMenu_lblEditName</value>
      <webElementGuid>62151de5-7fad-4617-8fcc-95a46fc6f756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e206c04c-faa7-448b-a66c-5b0e1a1e68a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl</value>
      <webElementGuid>3192ef80-5433-4b73-8565-25e39d0a4a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CFloatingMenu</value>
      <webElementGuid>e813cbf5-26f8-4406-bc94-a3ccccdb63fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>2589069a-f468-4a5c-aafb-121391259b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cambiar nombre de la cuenta</value>
      <webElementGuid>de51dc40-d49d-4a58-987e-641a729be991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_CFloatingMenu_lblEditName&quot;)</value>
      <webElementGuid>209b93f1-5871-4b02-b7b7-95abc586a52d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_CFloatingMenu_lblEditName']</value>
      <webElementGuid>9b866abb-33fc-4ef7-8674-d08ba7ac1ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_CFloatingMenu_flxEditName']/div/div</value>
      <webElementGuid>fc659d41-6f24-4a12-82b0-7a157448d7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver Resúmenes electrónicos'])[1]/following::div[5]</value>
      <webElementGuid>a0405fe6-bae7-40fa-a7ef-0c157db0e816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultar Alias / CBU'])[1]/following::div[10]</value>
      <webElementGuid>6664b233-ff56-4fec-88da-c6395026e71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar Nombre'])[1]/preceding::div[2]</value>
      <webElementGuid>91af7398-e51e-469e-b772-da7219658961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[3]</value>
      <webElementGuid>822b89cc-280c-4817-91e6-6b0675d2312e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cambiar nombre de la cuenta']/parent::*</value>
      <webElementGuid>6b66942d-1c47-40af-9e75-3e3057f1f989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>e8c23e0f-3bd1-48a3-9425-e74378c1d046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsDetailsBccl_CFloatingMenu_lblEditName' and (text() = 'Cambiar nombre de la cuenta' or . = 'Cambiar nombre de la cuenta')]</value>
      <webElementGuid>89beefb8-8f02-4841-844b-2d29495a2991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
