<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtaNombreAlias</name>
   <tag></tag>
   <elementGuidId>2e07d258-b23d-4fc1-9c7c-47924cfbc0d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxCbuAliasRow_lblAlias']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmCbuAliasBccl_segCbuAlias&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCbuAliasRow_flxCbuAliasRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxCbuAliasRow_lblAlias&quot;][count(. | //*[@id = 'flxCbuAliasRow_lblAlias' and (text() = 'cielo.estrella.mar' or . = 'cielo.estrella.mar')]) = count(//*[@id = 'flxCbuAliasRow_lblAlias' and (text() = 'cielo.estrella.mar' or . = 'cielo.estrella.mar')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxCbuAliasRow_lblAlias</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36b9a963-7a84-4143-8ec9-73b667662b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCbuAliasRow_lblAlias</value>
      <webElementGuid>20ebdfb8-5961-43dc-a4a2-723384ae6da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>2461be89-7418-4cf6-b5fe-152a7908f34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCbuAliasRow</value>
      <webElementGuid>c905b583-6f28-43f2-a0ba-9771cc4a1da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segCbuAlias</value>
      <webElementGuid>5c7c5bb6-a6b8-4e18-a2a5-ec755774d6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>3919031A-B98E-48BC-BABA-0C9F5C9E2792</value>
      <webElementGuid>b0f189e8-ebca-4314-80e9-50f68587d63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddleleftalign disableSelection</value>
      <webElementGuid>0f7d5f1a-51a3-4b10-87fb-6995072f83f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>cielo.estrella.mar</value>
      <webElementGuid>a87a17de-ce2b-417f-b89b-40ec8158ee97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmCbuAliasBccl_segCbuAlias&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCbuAliasRow_flxCbuAliasRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxCbuAliasRow_lblAlias&quot;]</value>
      <webElementGuid>89b8c173-5882-4d0a-b08b-f4c4fd512b47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxCbuAliasRow_lblAlias']</value>
      <webElementGuid>d50cf72d-4e24-4fca-9eb7-0ef08de15ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxCbuAliasRow_flxCbuAliasRow']/div[4]/div</value>
      <webElementGuid>cbac3f58-fd4c-4e29-8f5f-dc44a89f662d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 001-065300/9'])[1]/following::div[4]</value>
      <webElementGuid>14815f32-d94a-4536-95d8-1c2f34133c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENRICO EDIE AGUSTIN'])[1]/following::div[9]</value>
      <webElementGuid>5379f018-b03c-4f52-98c0-4a53ec22b19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>ed1ff506-50d3-43a5-a8e6-5f055d4297e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENRICO EDIE AGUSTIN'])[2]/preceding::div[6]</value>
      <webElementGuid>9c1ba6d3-395b-4668-91b8-f314332caf33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='cielo.estrella.mar']/parent::*</value>
      <webElementGuid>46caeb2c-14f4-4365-8c46-fc4744d594f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[4]/div</value>
      <webElementGuid>c38b9de2-e7e2-4279-98d2-e461a0622f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCbuAliasRow_lblAlias' and (text() = 'cielo.estrella.mar' or . = 'cielo.estrella.mar')]</value>
      <webElementGuid>1ba88d95-a4bd-4f14-aae6-6a87ca9afccc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
