<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCBUBeneficiario</name>
   <tag></tag>
   <elementGuidId>ad84df18-87b9-4981-98d0-5f7db29d53f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_flxCbuContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_NewBeneficiary_flxCbuContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9720c626-4d84-4029-90cd-777fd3b9b72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  sknFlxCursorPointer </value>
      <webElementGuid>8445ed83-218a-4047-91ee-66ed19a170e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_NewBeneficiary_flxCbuContainer</value>
      <webElementGuid>ebb21dc7-a76f-44a6-afed-dfc59e8870d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>d2f7597c-0251-417c-b544-23634c34344b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>2fd9c658-f179-4d78-99bb-aa0cb53930d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>NewBeneficiary</value>
      <webElementGuid>0f1ecb31-8411-415f-aef7-537add3bb374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CBU / CVU</value>
      <webElementGuid>67bc553a-b8f7-43fc-841c-a27b3bd2ce84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_NewBeneficiary_flxCbuContainer&quot;)</value>
      <webElementGuid>d2af3d8e-a504-47ec-bc58-d394e6e6a3f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_flxCbuContainer']</value>
      <webElementGuid>779329db-8687-4f65-935a-0f735e66b54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[390]</value>
      <webElementGuid>5a1c2ae7-7c77-4c20-9bfc-05066a2918d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cómo deseás ingresar el nuevo beneficiario?'])[1]/following::div[9]</value>
      <webElementGuid>1be4f276-04b8-47a2-887b-af6fa9dd65b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo beneficiario'])[1]/following::div[14]</value>
      <webElementGuid>2d7ff700-b4ea-40a4-a268-973f75d1f34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div/div/div[4]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>e8607fce-f48a-44e9-b811-38133984a8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_NewBeneficiary_flxCbuContainer' and (text() = 'CBU / CVU' or . = 'CBU / CVU')]</value>
      <webElementGuid>739fea4a-163c-470a-bb21-fba63b9b5d4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
