<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTrxGuardarNombreEditadoBenf</name>
   <tag></tag>
   <elementGuidId>efc1d439-6862-4f6f-a1f4-ecacac0ae858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader_btnWithLoader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader_btnWithLoader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d980bce7-ec19-4da9-8f91-7eefdf0b7fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>e5d7a53d-1891-40e8-b207-e924588ad0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader_btnWithLoader-hint</value>
      <webElementGuid>a0edc6a5-4aa6-4377-8e20-93e5cd1370c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader_btnWithLoader</value>
      <webElementGuid>db98f657-8cc5-4025-b325-64e390de428b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>de4d68ff-2ae9-4441-b1cf-1e5cfd568238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>f8802c3d-f456-43b2-85c5-ee15b48b32d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader</value>
      <webElementGuid>38b1fa51-df62-43c6-b31d-d336304347e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5706347-fcb7-4f82-bab5-9f3f94b46ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>e4f42443-771c-411f-861c-db968817e372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>7a7eebce-9e50-495b-9014-e94bff937606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>e7d7c281-7477-4358-9256-36d5bc12644a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader_btnWithLoader&quot;)</value>
      <webElementGuid>42e19e1a-f807-4a70-8325-2a9db4f352d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader_btnWithLoader']</value>
      <webElementGuid>9e39b861-68d0-41c3-85cc-9586e7812e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader']/div/input</value>
      <webElementGuid>967d1a3b-2d1d-4b81-b6b0-849c357e6cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[6]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>7a5af15b-e94d-4e99-af6b-9ae1ae74ee3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_ButtonWithLoader_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>e4382c1a-847f-4cc3-8849-d9f9dbb128da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
