<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxEditarBeneficiario</name>
   <tag></tag>
   <elementGuidId>034c73d3-3c2d-4384-90ed-f26cd62f86b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_lblEditIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_lblEditIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5478d26-6b49-4d9e-93c5-5157736025b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_lblEditIcon</value>
      <webElementGuid>79af47bd-87ef-49bb-a822-21b47219c58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e0a1afd8-2f2c-4dbc-81cc-5b23156517da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>2aa7c30d-f584-4d61-8eb9-c52620530a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBeneficiary_BeneficiaryDetails_BeneficiaryName</value>
      <webElementGuid>3c656634-09db-44dd-b594-1f89266eef77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblEditIcon cntmiddlecenteralign disableSelection</value>
      <webElementGuid>87275953-ea99-409b-9ca1-bfdb90b77df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e8b03884-be18-4fb0-b273-8abf2ac6a102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_lblEditIcon&quot;)</value>
      <webElementGuid>eb055af6-f179-49fd-ac54-bdfa51ab016a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_lblEditIcon']</value>
      <webElementGuid>4b3a27ce-5ca4-49f6-8f58-c94f291220fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_flxEditIcon']/div/div</value>
      <webElementGuid>49fa6a31-0b44-4753-8aad-fbfc514d46d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L ANNETTA'])[1]/following::div[5]</value>
      <webElementGuid>a5f353ff-3329-4bcf-902f-011e82ca2486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre del beneficiario'])[2]/following::div[13]</value>
      <webElementGuid>6ff875fd-befa-48ff-bbeb-85f0886d130a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/preceding::div[2]</value>
      <webElementGuid>00d0dd1a-9b4a-4789-81da-74cb13602fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[45]/preceding::div[10]</value>
      <webElementGuid>a2bb5878-266e-4b31-8ad7-52a8a085b449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>93d8bcf1-d681-4ab5-9e1b-2b1c582afbe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_lblEditIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>ae4bb8f6-aa4f-4382-b5eb-88af84ebc2c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
