<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuTrfTipoNuevoBeneficiario</name>
   <tag></tag>
   <elementGuidId>e256698b-663f-4bd4-a5ff-3a2cd7e54647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_OperationType_lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_NewBeneficiary_OperationType_lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>056ae78f-321a-4bee-9299-642be953dfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_NewBeneficiary_OperationType_lblOptionTitle</value>
      <webElementGuid>fef2b298-ca91-405e-913a-c054b09b7ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>3c30e20c-fe09-4377-a050-d988a616e651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>a06d8d9a-54ff-4e1a-9647-38a4d1256dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>NewBeneficiary_OperationType</value>
      <webElementGuid>11322d9f-dae8-4d2a-9783-c857b0136353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDownDisabled cntmiddleleftalign</value>
      <webElementGuid>214fda56-e157-4c1a-9b23-841d5dfaa1ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccioná tipo</value>
      <webElementGuid>579f4ba8-2a1b-4770-8f02-25df78f5e8f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_NewBeneficiary_OperationType_lblOptionTitle&quot;)</value>
      <webElementGuid>8db3d153-368d-4c69-a1b9-8111ef2171fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_OperationType_lblOptionTitle']</value>
      <webElementGuid>70ca7e9b-5f32-441d-9a92-a388ed777eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_OperationType_flxOptionInfo']/div/div</value>
      <webElementGuid>1c975f71-fba6-4a5f-a62b-e98017342999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='obligatorio'])[3]/following::div[14]</value>
      <webElementGuid>99504b9f-a7ec-4ac9-b93b-ab416b61c8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[16]</value>
      <webElementGuid>47bf7288-7360-4828-8390-32a1e9ec84d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[10]/preceding::div[1]</value>
      <webElementGuid>fade4708-f073-4c12-a9fe-9a03ffdf0f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccioná tipo'])[2]/preceding::div[3]</value>
      <webElementGuid>e26d77fa-4600-4a2c-8840-0db72ebd117d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seleccioná tipo']/parent::*</value>
      <webElementGuid>f199784d-428c-4b57-9976-2980cb140c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>abaf42ba-0751-4aa1-877f-d461c3f60cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_NewBeneficiary_OperationType_lblOptionTitle' and (text() = 'Seleccioná tipo' or . = 'Seleccioná tipo')]</value>
      <webElementGuid>b48c9549-f6db-4838-a251-a6c13c1621c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
