<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuTrxBeneficiarioDesplegable</name>
   <tag></tag>
   <elementGuidId>5d197d80-fff2-49bd-a97b-3453a90b230c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxBeneficiariesRow_lblSubMenuIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxBeneficiariesRow_lblSubMenuIcon</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;flxBeneficiariesRow_lblSubMenuIcon&quot;)[count(. | //*[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and @kformname = 'flxBeneficiariesRow' and @kcontainerid = 'segBeneficiaries' and (text() = '' or . = '')]) = count(//*[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and @kformname = 'flxBeneficiariesRow' and @kcontainerid = 'segBeneficiaries' and (text() = '' or . = '')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18dbbacd-01ff-4c04-922a-4832416bfe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxBeneficiariesRow_lblSubMenuIcon</value>
      <webElementGuid>3f995903-d7e3-4be6-9f7c-93793f0bedfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>1c2c32a5-2ddc-4391-830f-ec4e03e3f17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxBeneficiariesRow</value>
      <webElementGuid>8d3837ed-f59d-45ef-a3ab-33969fa4fc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segBeneficiaries</value>
      <webElementGuid>e030f57e-f349-4cf8-8cbf-06d896f50eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>45E691D9-D413-43BE-8E02-A74151B73D7A</value>
      <webElementGuid>babc44d2-22f4-46cf-a24d-983a17ad5b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSubMenuDashboard cntmiddlecenteralign disableSelection</value>
      <webElementGuid>67c6bef4-a312-43bf-97c3-3524e3af960b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>60e21ee7-f732-485a-bbe2-9faca31f71ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flxBeneficiariesRow_lblSubMenuIcon&quot;)</value>
      <webElementGuid>4c4bedee-98e5-4f43-9b85-a7f03c38e76d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxBeneficiariesRow_lblSubMenuIcon']</value>
      <webElementGuid>7e6eeb9c-a859-4035-9497-1974eb9eccdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxBeneficiariesRow_flxSubMenuContainer']/div/div</value>
      <webElementGuid>dd5ccfda-73e0-483a-bf95-e6462d130f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/following::div[5]</value>
      <webElementGuid>b56a9559-6fdd-4002-9d5d-edc31b92dcdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banco Credicoop Cooperativo Limitado'])[1]/following::div[13]</value>
      <webElementGuid>113396ba-3145-4351-9024-534b0a443263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultados por página'])[1]/preceding::div[1]</value>
      <webElementGuid>e888c0cb-461f-439b-9564-3f666bd59e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/preceding::div[5]</value>
      <webElementGuid>b567c84e-05f8-4f03-9376-13e384b14e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[6]/div/div/div/div</value>
      <webElementGuid>6bc8ef28-e883-41b1-ab73-3df359daed4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>84b93204-3846-489a-9380-47f417bca894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
