<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNombreAnteriorBenef</name>
   <tag></tag>
   <elementGuidId>e25355fb-88f2-428f-af91-5dc2fdd6cf8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue&quot;)[count(. | //*[@id = 'frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue' and @value = 'Label' and @type = 'text']) = count(//*[@id = 'frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue' and @value = 'Label' and @type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>def244f0-adde-49de-beed-07af3f2bf3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue</value>
      <webElementGuid>90719ec8-0902-4b51-8ab4-2726dff07d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>e5a11cb2-5b11-443a-b11e-de1bce1c9263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>d31b54ce-3be7-4263-91bf-f17947ae4ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBeneficiary_BeneficiaryDetails_BeneficiaryName</value>
      <webElementGuid>8b30e2ac-0c21-4946-8b91-6992f7f8ed3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>124c1e58-eb2a-44c9-8e9d-a1dbcb8843f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknTbxInputMaskedNew</value>
      <webElementGuid>3e0144ac-176b-40ae-9699-0182c39bc9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1b672de5-97b9-4d78-b14e-6c40b7ff7718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f783c78c-25b8-4b13-a4d6-56bb96549ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33420ede-742f-421b-b425-01d9055d7a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1949cf5-cdc8-4039-8e10-d9c3ce8c0998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>369d34f9-fde0-4379-8936-bb1de9473115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>01c84a58-4a89-4986-805e-0602a2d23182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d78bd46a-dff5-4569-8c4a-20cd20bee028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue&quot;)</value>
      <webElementGuid>2ad4c91f-b7a7-4585-81f1-b3a2a398e136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue']</value>
      <webElementGuid>af17219f-112b-4060-ab2f-069f0b57d807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_flxInput']/div/input</value>
      <webElementGuid>dd1e1083-85c7-443e-b26b-0aa0df702857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>5e7ab6e2-857f-4cf8-9b03-0786fb1771b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue' and @type = 'text']</value>
      <webElementGuid>4cf64cec-0730-4baa-9e0f-f3c9d39d9b72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
