<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrfNuevoBeneficiarioEliminar</name>
   <tag></tag>
   <elementGuidId>06a2d90c-6581-46d9-b5fc-ed36ed6591aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lbldeleteBeneficiary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lbldeleteBeneficiary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fafb0a8f-cead-44b7-bab8-3c89a85c7027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lbldeleteBeneficiary</value>
      <webElementGuid>b7983249-4be7-4a75-a231-2bfdc298c21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>41d45c9f-2a58-4981-ab2d-c798c8313155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>961dd5e2-380d-4700-b0f5-bfa584e7c891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>flxBeneficiariesRowFloatingMenu</value>
      <webElementGuid>96eafcee-df02-4288-b965-9f7ca185bba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>62f19049-c7e5-44a0-b709-c624f5e4b93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>ae116e58-2e4b-4d77-bcdd-9b09df23606c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lbldeleteBeneficiary&quot;)</value>
      <webElementGuid>87df3662-6666-4556-b5e4-6c06cb012ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lbldeleteBeneficiary']</value>
      <webElementGuid>f0732ac8-6d21-4526-b250-e4e32d48ce83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxdeleteBeneficiary']/div/div</value>
      <webElementGuid>ee3526a1-365c-4f74-b0f1-2590484c482d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[3]/following::div[5]</value>
      <webElementGuid>7321da88-9c9d-4130-a2b2-6cadb42f3300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva transferencia'])[1]/following::div[10]</value>
      <webElementGuid>d5d4d6a2-bede-460d-8059-fc7170dc4373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[2]/preceding::div[4]</value>
      <webElementGuid>83a06eb8-6a6f-4062-88b8-40a77f655139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[5]</value>
      <webElementGuid>a9ef47f9-a580-4513-82e9-ce2168507675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>ee9fad0f-d542-4cf2-8431-48039b829bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lbldeleteBeneficiary' and (text() = 'Eliminar' or . = 'Eliminar')]</value>
      <webElementGuid>ca10dbf9-66e9-4ed6-885b-9d98c4b4ec60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
