<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxNuevoNombreBeneficiario</name>
   <tag></tag>
   <elementGuidId>805ea667-c7a6-4d69-9084-e6453af5cd3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9365122b-3f38-4d3d-b5d1-41fabbe94b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue</value>
      <webElementGuid>95f25fcf-ecc7-4544-b930-510bed7ee6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>629c62b3-9dc2-48fa-9eab-a9f73b114814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>20a93ced-d93b-4272-b9e4-cb3337c17c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBeneficiary_BeneficiaryDetails_BeneficiaryName</value>
      <webElementGuid>d0c71064-c62e-4974-80ea-d64ae9cfe7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>49de2fd9-2278-41cc-89ee-4c5a638bbaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknTbxInputMaskedNew</value>
      <webElementGuid>1ef7c37b-84ed-4f29-af01-dcad8cec260e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2bc2548a-c3a0-4e0d-a5a3-eba12daabfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6f7f34eb-1da9-4e65-9b8a-1d066115a57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>571e9431-7971-4277-9971-4f63cc8b5984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c49b353f-5907-4d92-a54d-7716efcbbd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>772d78ca-96c9-4ab1-a8a1-2644df717ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>8ba721ea-ba26-447b-8e4e-ac8aac3de9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9802f376-3a30-4ed8-85bb-d2b2ac5ec502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue&quot;)</value>
      <webElementGuid>9a183fea-1611-4903-92f0-bacf62b4b535</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue']</value>
      <webElementGuid>3295c0ed-7533-4cbb-9553-4498f43ae077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_flxInput']/div/input</value>
      <webElementGuid>4fd6296a-97b2-45a0-b45c-c616cf7087a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>14168b7e-33fa-49c0-a9cc-85383cc4cee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_BeneficiaryName_tbxNewValue' and @type = 'text']</value>
      <webElementGuid>39ddf20a-b308-40fa-b1f4-40d1d45d2e26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
