<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbldsbUltimaSesion</name>
   <tag></tag>
   <elementGuidId>8feced0c-fb8e-4518-8d00-f0bc842fe018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsLanding_customheader_WelcomeProfile_lblLastSessionMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_lblLastSessionMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac893c2d-3d56-4a6b-9c1a-761124091056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsLanding_customheader_WelcomeProfile_lblLastSessionMessage</value>
      <webElementGuid>6a1dfda1-db57-42e5-ba74-1df9e5bac541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>dd69dbd2-843e-4a04-99e2-8ba8957010db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsLanding</value>
      <webElementGuid>b2b7841a-675b-4410-9353-f7b9f4e89fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>customheader_WelcomeProfile</value>
      <webElementGuid>9dd0a424-ea46-47d7-970c-af4e336105c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLastSessionMessageLarge cntmiddleleftalign disableSelection</value>
      <webElementGuid>565d9ee3-359b-45a0-b05a-e07294de8c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Última sesión: 17/01/2023 10:29 hs.</value>
      <webElementGuid>0754c239-ea17-4a7e-877d-6975ca265ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsLanding_customheader_WelcomeProfile_lblLastSessionMessage&quot;)</value>
      <webElementGuid>11345468-5e21-43e9-9169-8e483b4fca6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_lblLastSessionMessage']</value>
      <webElementGuid>9f29e918-f679-4633-af77-1b532f7243c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_flxWelcomeMessageContainer']/div[2]/div</value>
      <webElementGuid>6e120e89-c0dc-4f03-8f39-c93f2d1bd4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hola, Edie!'])[1]/following::div[2]</value>
      <webElementGuid>4ac6f973-cb71-477d-94d8-1dfb7f09576e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EE'])[1]/following::div[7]</value>
      <webElementGuid>dc49e196-56ac-4f99-9e53-3025823b4b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>f98842de-858a-4ed7-a6bb-0388c76e49e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[7]</value>
      <webElementGuid>61936235-e2f6-4d27-9058-162dc6673cf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Última sesión: 17/01/2023 10:29 hs.']/parent::*</value>
      <webElementGuid>42c85506-1670-4301-8f32-118d962c9264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>281f567e-30cc-4523-a29e-f412e58bb9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsLanding_customheader_WelcomeProfile_lblLastSessionMessage' and (text() = 'Última sesión: 17/01/2023 10:29 hs.' or . = 'Última sesión: 17/01/2023 10:29 hs.')]</value>
      <webElementGuid>54225f82-80d3-4643-84e5-8a313f35c549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
