<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblDsbNombreUsuario</name>
   <tag></tag>
   <elementGuidId>8c86a006-f560-424c-8c9e-73470ff2a9dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsLanding_customheader_WelcomeProfile_lblWelcomeMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_lblWelcomeMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e24e4272-7775-4564-b073-94f640492d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsLanding_customheader_WelcomeProfile_lblWelcomeMessage</value>
      <webElementGuid>3ca2add3-88cb-4ef0-8b18-1a4dc271872b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>dc9945c7-3822-4d8b-9fa9-117d8acae9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsLanding</value>
      <webElementGuid>5b743e72-d1a6-4aea-b6b8-0f9533887c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>customheader_WelcomeProfile</value>
      <webElementGuid>b18c502b-1c0f-47ea-9052-13c0b398e2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblWelcomeMessageLarge cntmiddleleftalign disableSelection</value>
      <webElementGuid>528bfb74-d7d9-4370-a869-1403cef7a23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hola, Edie!</value>
      <webElementGuid>7a9ffbde-d95b-4b62-b12c-317543a65c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsLanding_customheader_WelcomeProfile_lblWelcomeMessage&quot;)</value>
      <webElementGuid>d2f22668-8076-418b-ac43-dd877c9be103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_lblWelcomeMessage']</value>
      <webElementGuid>066ca1e0-e238-4e35-96f5-22222ca1818e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_flxWelcomeMessageContainer']/div/div</value>
      <webElementGuid>b359a7f8-eeea-4e6e-b47a-a6c57bd35010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EE'])[1]/following::div[5]</value>
      <webElementGuid>3bcd2fa0-7b9f-49bc-80fd-e3e5fb555674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[30]</value>
      <webElementGuid>6c177533-a35d-47f3-bd04-0cacbf7ec50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Última sesión: 17/01/2023 10:29 hs.'])[1]/preceding::div[1]</value>
      <webElementGuid>7d07cad4-7da8-4343-b858-5ae4b0ea40c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[3]</value>
      <webElementGuid>7113a2a0-ab75-42dd-9daf-4b3f6a794ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hola, Edie!']/parent::*</value>
      <webElementGuid>a752e99e-d5a4-43b9-9e06-66d28084f87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>404e193d-4a56-4f11-bf59-e8b15f7aa3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsLanding_customheader_WelcomeProfile_lblWelcomeMessage' and (text() = 'Hola, Edie!' or . = 'Hola, Edie!')]</value>
      <webElementGuid>312d1754-005e-4679-b71c-146e8699e574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
