<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkDsbIconoSalir</name>
   <tag></tag>
   <elementGuidId>4b9bf488-4d8d-4b98-855e-ba92b09a1118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsLanding_customheader_headermenu_lblIconLogOut</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmAccountsLanding_customheader_headermenu_lblIconLogOut&quot;)[count(. | //*[@id = 'frmAccountsLanding_customheader_headermenu_lblIconLogOut' and @kmasterid = 'customheader_headermenu' and @class = ' sknLblIconHeaderMenu cntmiddlecenteralign disableSelection' and (text() = '' or . = '')]) = count(//*[@id = 'frmAccountsLanding_customheader_headermenu_lblIconLogOut' and @kmasterid = 'customheader_headermenu' and @class = ' sknLblIconHeaderMenu cntmiddlecenteralign disableSelection' and (text() = '' or . = '')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c36eabad-03f7-48bf-bfe1-0dbdfd8ff1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsLanding_customheader_headermenu_lblIconLogOut</value>
      <webElementGuid>96915588-21e6-4322-b8c8-91e36f56a4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>6ff1992b-498b-4b0f-8572-686b14e1552f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsLanding</value>
      <webElementGuid>d5480ae3-195b-4114-8f78-01b434fa16d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>customheader_headermenu</value>
      <webElementGuid>e3f334dd-c9e4-456d-a0c7-e1cbbd88ac14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblIconHeaderMenu cntmiddlecenteralign disableSelection</value>
      <webElementGuid>318ff14f-076b-4e1b-adc9-b8e5c9aba0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e3ce5618-7106-4d8d-ae42-36a54b20da0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsLanding_customheader_headermenu_lblIconLogOut&quot;)</value>
      <webElementGuid>2f170f22-3128-4084-b6a9-df0805d119da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customheader_headermenu_lblIconLogOut']</value>
      <webElementGuid>7227156a-24c1-4c02-86f8-d28571c23826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customheader_headermenu_flxLblIconLogout']/div/div</value>
      <webElementGuid>509c470c-ae43-4303-b5dc-4027030aef4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>0cce0a5a-2ccf-49df-9fc6-9cc59b79dccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[3]</value>
      <webElementGuid>5a56507f-beb8-4997-95b1-6a33d22e021d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>9edbe1f7-9103-4627-8129-467cf1de7b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>e952b6b1-d182-416a-9a9f-c33e22801105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsLanding_customheader_headermenu_lblIconLogOut' and (text() = '' or . = '')]</value>
      <webElementGuid>0192cf28-59ee-49e2-a6dc-16dd18459738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
