<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkDsbInicioEstado2</name>
   <tag></tag>
   <elementGuidId>8a4ff38b-599b-46ae-8554-2a4d62eebc29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmNewTransferBccl_customhamburger_HOMElblAccounts</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmNewTransferBccl_customhamburger_HOMElblAccounts']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c409815-78fe-4d28-a945-14fa91eac438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Accounts </value>
      <webElementGuid>330a46bd-d2d3-4645-8ba5-706038e2da24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>314e4bae-d97c-4245-acbc-b591d9ae5018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmNewTransferBccl_customhamburger_HOMElblAccounts</value>
      <webElementGuid>8c26d8e5-ff03-40a6-96e1-3f1bbc2d9721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>26e10b06-4ed4-4c87-a94c-b2f5a654a37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmNewTransferBccl</value>
      <webElementGuid>38f889c8-25ad-43a8-ade6-efd77a5f3bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>customhamburger</value>
      <webElementGuid>e896a2c5-3f73-48e3-b11a-8b767a86e751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddleleftalign disableSelection sknLblItemMenu</value>
      <webElementGuid>f2f837a7-8f56-4b8f-97e7-a15b70421f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inicio</value>
      <webElementGuid>0fb8113e-5322-4add-bee2-c79d7d9730ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_customhamburger_HOMElblAccounts&quot;)</value>
      <webElementGuid>30c06fe9-febe-4019-b5b6-578cc0733285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmNewTransferBccl_customhamburger_HOMElblAccounts']</value>
      <webElementGuid>62a0bc22-71e2-430c-bba5-ac09880c735f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmNewTransferBccl_customhamburger_HOMEflxAccountsMenu']/div[3]/div</value>
      <webElementGuid>90d21550-7443-4675-9f6f-992120c71341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activar correo seguro'])[2]/following::div[13]</value>
      <webElementGuid>14e571e3-5039-4762-8302-543d08ed13a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activar celular seguro'])[2]/following::div[18]</value>
      <webElementGuid>4a8880f8-b909-4cde-b256-4dd945ff258b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuentas'])[1]/preceding::div[13]</value>
      <webElementGuid>fe2bbcab-106d-424b-ab97-a0c5c9d59103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencias'])[1]/preceding::div[30]</value>
      <webElementGuid>a5db1873-4068-4fa3-b55e-f9fa47570a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inicio']/parent::*</value>
      <webElementGuid>7811d099-1252-4645-9ac6-2c02d07b61c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[3]/div</value>
      <webElementGuid>05db3d54-c198-4c79-80ea-940f3e1ad380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmNewTransferBccl_customhamburger_HOMElblAccounts' and (text() = 'Inicio' or . = 'Inicio')]</value>
      <webElementGuid>8d97d142-302a-4c7f-b1e1-08590ae29568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
