<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkDsbOtrasOperaciones</name>
   <tag></tag>
   <elementGuidId>340db929-e604-42b5-aa9b-edc0baffee29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsLanding_customhamburger_OTHEROPERATIONSlblIconLogOut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsLanding_customhamburger_OTHEROPERATIONSlblIconLogOut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e0a44d9-eb9e-4492-9265-242a9429db73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Logout </value>
      <webElementGuid>08ae0d9b-c30f-4e88-9ae7-6f8fd0f3b913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7eeb39ea-a292-425c-803c-40b45183b9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsLanding_customhamburger_OTHEROPERATIONSlblIconLogOut</value>
      <webElementGuid>b1edf123-9d97-47ee-936e-90c5b36472e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>6f0a0e1e-5ad2-4b28-b936-001cc4b61a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsLanding</value>
      <webElementGuid>83309f77-b1ea-435f-b30e-ffbbda0113e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>customhamburger</value>
      <webElementGuid>62c7ef0b-682b-4d8d-87a6-a060bb329a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblFASolid16454446 cntmiddlecenteralign disableSelection</value>
      <webElementGuid>70854888-64af-4474-8849-a923c980d3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7620495a-eead-4212-b32c-c8c75267cd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsLanding_customhamburger_OTHEROPERATIONSlblIconLogOut&quot;)</value>
      <webElementGuid>d31aac04-c377-4535-a293-d3f8b0e6e6dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customhamburger_OTHEROPERATIONSlblIconLogOut']</value>
      <webElementGuid>45e72804-9103-49d0-b863-bc0a60a18856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customhamburger_OTHEROPERATIONSflxAccountsMenu']/div[6]/div</value>
      <webElementGuid>a5d5aa8e-a442-4e19-aec3-303a4624c8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otras operaciones'])[1]/following::div[9]</value>
      <webElementGuid>7c6aadea-374b-420f-9b98-28e15625443c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis operaciones'])[1]/following::div[32]</value>
      <webElementGuid>b11a92d9-9319-482c-a4bf-2bffc28fc870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Pagos DEBIN'])[1]/preceding::div[4]</value>
      <webElementGuid>e41beefe-1af3-45eb-9bc9-4e7849e0c848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Extracción sin tarjeta'])[1]/preceding::div[21]</value>
      <webElementGuid>b65f9c2b-db45-4414-b0f5-22ea7ab45998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>0e689ae2-04b9-4880-9ed5-b858c2d21e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div[6]/div</value>
      <webElementGuid>c8dfee04-4c27-4b0a-9f75-f464385effc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsLanding_customhamburger_OTHEROPERATIONSlblIconLogOut' and (text() = '' or . = '')]</value>
      <webElementGuid>370c2254-04fa-4ca7-9ab3-ec12eb684056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
