<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkDsbPagosDebin</name>
   <tag></tag>
   <elementGuidId>28f74993-9592-405d-a39f-6241a94991af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsLanding_customhamburger_DEBINlblAccounts']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsLanding_customhamburger_DEBINlblAccounts</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27d968f2-9324-43c0-889f-ec6d4a7d4509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Accounts </value>
      <webElementGuid>7a0eb844-ab77-4774-8e7b-4a67404a2100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b21e21c-2af0-434a-a446-62a5856edd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsLanding_customhamburger_DEBINlblAccounts</value>
      <webElementGuid>ed9f4e3a-978e-4bb5-b50b-b84f62014e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>5b068cff-1e29-4720-a4db-15520cd9059b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsLanding</value>
      <webElementGuid>73c953bd-c486-4e3b-bb5c-c7fa58e765d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>customhamburger</value>
      <webElementGuid>d230a006-c15f-4bcf-a9d9-7a5ec597bcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddleleftalign disableSelection sknLblItemMenu</value>
      <webElementGuid>697c0a78-ccf5-4904-a52a-0eb9c7edeefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Pagos DEBIN</value>
      <webElementGuid>5dcd5141-ebee-4584-b668-d088f8b6da02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsLanding_customhamburger_DEBINlblAccounts&quot;)</value>
      <webElementGuid>ceb48a6a-284b-4406-bb28-38e4db0e9f78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customhamburger_DEBINlblAccounts']</value>
      <webElementGuid>3b9c54b1-9cf7-43c4-b93d-2565cb2b0730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customhamburger_DEBINflxAccountsMenu']/div[3]/div</value>
      <webElementGuid>5da0afb8-e6c2-4d3e-8e45-5c2ffcbb89a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[8]</value>
      <webElementGuid>7285e0e9-70ef-48d7-8069-05e6de0786d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otras operaciones'])[1]/following::div[17]</value>
      <webElementGuid>a4d78e41-eac1-4a04-88e5-bc951434ba54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Extracción sin tarjeta'])[1]/preceding::div[13]</value>
      <webElementGuid>ebf91648-180d-45ca-862f-b06ea135ac94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Préstamos'])[1]/preceding::div[30]</value>
      <webElementGuid>c77f154e-0a95-43ee-918e-e4835a134e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='- Pagos DEBIN']/parent::*</value>
      <webElementGuid>93bf3a60-c62c-4f6e-8eab-16ab705f88bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/div/div[3]/div</value>
      <webElementGuid>9f4b5e80-30fc-44ac-b1b6-0527ccc4f4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsLanding_customhamburger_DEBINlblAccounts' and (text() = '- Pagos DEBIN' or . = '- Pagos DEBIN')]</value>
      <webElementGuid>2e87c7e8-0509-4369-aabb-ee7bbacb5c04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
