<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chqNtfMovimientoSeguridadCambioTelefonoCorreo</name>
   <tag></tag>
   <elementGuidId>8a85fa86-7324-407e-90e3-22f299c517d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclNotificationsManagement_Panel_edit_Checkbox63700099746550']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclNotificationsManagement_Panel_edit_Checkbox63700099746550</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>419cfffe-b552-4b72-bbfd-0f022cbd04b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>335bf4e7-6242-4d0e-bf7e-d06248a99f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclNotificationsManagement_Panel_edit_Checkbox63700099746550</value>
      <webElementGuid>63302765-f69f-4618-90a3-12734658be52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>582fe48e-b635-416a-b13f-3950ad2c2724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclNotificationsManagement</value>
      <webElementGuid>2de09d17-3b68-4a2d-8c5b-b7cbdbb70d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Panel_edit</value>
      <webElementGuid>2ba4b16a-5e3f-4859-bf0e-6bb9199bb1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9a6e4cd8-b22a-4428-8736-1b6c70c97c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cambio de teléfono/correo electrónico/dirección principal</value>
      <webElementGuid>6a7ab86b-3611-4c8e-830e-0de2494947a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclNotificationsManagement_Panel_edit_Checkbox63700099746550&quot;)</value>
      <webElementGuid>287ccd0b-0d24-4299-9b52-e8b7bc71230b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclNotificationsManagement_Panel_edit_Checkbox63700099746550']</value>
      <webElementGuid>515e3e57-76cd-4d29-b782-aa13a3ef782f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[398]</value>
      <webElementGuid>0db50a3c-3e8a-416c-b0a3-13df382fbf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actualización de credenciales'])[1]/following::div[9]</value>
      <webElementGuid>b63c789f-8476-4e8f-bb89-f8ba6eb6ca73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/following::div[11]</value>
      <webElementGuid>7d44b6ea-bb53-432a-b3bf-c14a6fd5051d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[4]/div/div/div[3]/div/div/div/div/div</value>
      <webElementGuid>0bea3e62-e313-4490-80d9-5f39c3315631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclNotificationsManagement_Panel_edit_Checkbox63700099746550' and (text() = 'Cambio de teléfono/correo electrónico/dirección principal' or . = 'Cambio de teléfono/correo electrónico/dirección principal')]</value>
      <webElementGuid>781fbb65-451c-4dcd-a2a5-1001a5838e6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
