<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chqNtfMovimientoSeguridadActualizacionCredenciales</name>
   <tag></tag>
   <elementGuidId>fa6f4215-0e02-4219-845c-69a6e838975f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclNotificationsManagement_Panel_edit_Checkbox114282190759323']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclNotificationsManagement_Panel_edit_Checkbox114282190759323</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>81d6c3cd-5ed6-4030-afad-2d7b14bf35d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>50f3d225-5326-4f3e-99b5-e7506c4fc2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclNotificationsManagement_Panel_edit_Checkbox114282190759323</value>
      <webElementGuid>b84a5bac-ca19-479e-8537-e4388eb2274a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>8a9ad73d-50d9-43a7-8e42-77e309bf62ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclNotificationsManagement</value>
      <webElementGuid>42320adc-acc5-45a3-8861-02fe33e6f045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Panel_edit</value>
      <webElementGuid>a9ceec68-6d5b-45fa-8d1b-50e445f69534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e563120-a81a-489a-b495-c3000d562da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actualización de credenciales</value>
      <webElementGuid>90ec059f-0583-4e9c-ba16-7f1770f9db80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclNotificationsManagement_Panel_edit_Checkbox114282190759323&quot;)</value>
      <webElementGuid>0f1e075e-c3c4-43cd-82dd-5f004a6d6f8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclNotificationsManagement_Panel_edit_Checkbox114282190759323']</value>
      <webElementGuid>6cc37f87-7a0e-45ab-bcfb-955db1b91dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[393]</value>
      <webElementGuid>1707b902-1255-4feb-a735-a517372305e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio de sesión'])[1]/following::div[9]</value>
      <webElementGuid>de61433f-9f1a-4bc7-a83e-0d3076f2f76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[11]</value>
      <webElementGuid>6346d498-1938-4cde-b7f0-5b7c285fb751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[4]/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>fb396379-ece9-40a0-b2f9-18bc4eb69314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclNotificationsManagement_Panel_edit_Checkbox114282190759323' and (text() = 'Actualización de credenciales' or . = 'Actualización de credenciales')]</value>
      <webElementGuid>d6402d88-d14f-4757-831b-47f0ab67e416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
