<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chqNftNotificacionesPush</name>
   <tag></tag>
   <elementGuidId>5971b628-05c1-4c25-92e0-376e99b5a0b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclNotificationsManagement_Panel_edit_Checkbox64170428275062_flxCustomCheckbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclNotificationsManagement_Panel_edit_Checkbox64170428275062_flxCustomCheckbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>870d50bb-a087-4a60-a8d4-26f2a56108f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  sknFlxCustomCheckbox </value>
      <webElementGuid>8b832d7d-4487-41ee-aab9-16cb74883016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclNotificationsManagement_Panel_edit_Checkbox64170428275062_flxCustomCheckbox</value>
      <webElementGuid>9d866702-b765-44ea-80fe-24c4453bf4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>e60669dd-eefe-40ca-a7b8-422eddba7baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclNotificationsManagement</value>
      <webElementGuid>95174a2a-23be-443d-8fc6-6ddb3d6139c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Panel_edit_Checkbox64170428275062</value>
      <webElementGuid>03327788-a82b-4b02-ae07-833fc01446e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8ca2628f-3f45-4d63-84f2-c99416af4890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclNotificationsManagement_Panel_edit_Checkbox64170428275062_flxCustomCheckbox&quot;)</value>
      <webElementGuid>1ecc3829-a860-471a-9119-633ded45ea56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclNotificationsManagement_Panel_edit_Checkbox64170428275062_flxCustomCheckbox']</value>
      <webElementGuid>dd2cefb1-619e-46f1-81d1-b87edd2fb182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[385]</value>
      <webElementGuid>b2322551-10a3-496c-8908-f528ce337914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notificaciones en la Banca'])[2]/following::div[15]</value>
      <webElementGuid>a3062823-2ce1-4f79-80b4-89531fc5fa77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[17]</value>
      <webElementGuid>54623d1c-c0fb-4289-8192-b92faeddc306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notificaciones Push'])[2]/preceding::div[3]</value>
      <webElementGuid>14dabf28-fb6d-4db7-a841-94e8945fc651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>c719cc16-4948-4c47-8590-c8ebc4e52e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclNotificationsManagement_Panel_edit_Checkbox64170428275062_flxCustomCheckbox' and (text() = '' or . = '')]</value>
      <webElementGuid>74e6e1a2-f6a1-4bf7-8641-a6c35724edd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
