<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>liNtfListaEditarNotificaciones</name>
   <tag></tag>
   <elementGuidId>27bf5583-f116-41fb-929b-e54865b7e10c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclNotificationsManagement_Panel_edit_flxCheckBoxContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclNotificationsManagement_Panel_edit_flxCheckBoxContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c97c9b5-9c89-455c-97be-484167c034b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>3e3002f0-bd79-45c5-8ad9-a0c77489d583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclNotificationsManagement_Panel_edit_flxCheckBoxContainer</value>
      <webElementGuid>a667e7db-11e1-4a70-befa-0e02b5543526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>7373ac49-808f-4fdb-a6ac-78501d030bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclNotificationsManagement</value>
      <webElementGuid>4b70d656-7b6c-4502-a56f-02dabdc6a3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Panel_edit</value>
      <webElementGuid>48bddf43-c197-4863-8ec5-75838a2b59e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Canales habilitadosNotificaciones en la BancaNotificaciones PushTipo de movimiento de seguridadInicio de sesiónActualización de credencialesCambio de teléfono/correo electrónico/dirección principal</value>
      <webElementGuid>e0580065-4a7d-4ed8-98d2-701db4256192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclNotificationsManagement_Panel_edit_flxCheckBoxContainer&quot;)</value>
      <webElementGuid>3a868d14-14c1-40a5-8e50-ec6083e5a340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclNotificationsManagement_Panel_edit_flxCheckBoxContainer']</value>
      <webElementGuid>f410aa64-0eb5-48ef-8041-b54d6ac8ad33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[375]</value>
      <webElementGuid>62e02f71-deb5-43fa-b17f-d07f5576b9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[6]</value>
      <webElementGuid>dc750151-4291-41da-8909-d80de1c9a2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar notificación'])[1]/following::div[20]</value>
      <webElementGuid>9902faa4-03e8-478f-9053-47f3eb891392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>ac32691e-727a-4e61-994b-f235dfaab819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclNotificationsManagement_Panel_edit_flxCheckBoxContainer' and (text() = 'Canales habilitadosNotificaciones en la BancaNotificaciones PushTipo de movimiento de seguridadInicio de sesiónActualización de credencialesCambio de teléfono/correo electrónico/dirección principal' or . = 'Canales habilitadosNotificaciones en la BancaNotificaciones PushTipo de movimiento de seguridadInicio de sesiónActualización de credencialesCambio de teléfono/correo electrónico/dirección principal')]</value>
      <webElementGuid>eddc3b20-5001-477a-92ba-b814c818c07e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
