<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoOprCalendarioMesAnteriorDesde</name>
   <tag></tag>
   <elementGuidId>94c7277f-bfa6-4d5e-9b09-7ab5552dbd01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-k-w-c-month-cmp-6-2023']/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.-kony-w-c-prev-nav-left-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8a3bdc0a-fe5f-49b6-bb56-f00828562c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>79e40a1f-b89d-442a-8f69-9fd2c04f9853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-w-c-prev-nav-left-link</value>
      <webElementGuid>4ab62c72-eb03-4459-a597-0984e053c678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Previous Month</value>
      <webElementGuid>f0ea3733-0483-4368-9b39-a5849bef1f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/left-arrow.png</value>
      <webElementGuid>4bed71ac-5b97-4edf-b90c-6001fae3d5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_Filter_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>6f9c07b0-1c62-4078-8c4a-e872703ddf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-k-w-c-month-cmp-6-2023&quot;)/div[@class=&quot;-kony-w-c-topSection&quot;]/div[@class=&quot;-kony-w-c-table&quot;]/div[@class=&quot;-kony-w-c-row&quot;]/div[@class=&quot;-kony-w-c-cell -kony-w-c-prev-nav&quot;]/img[@class=&quot;-kony-w-c-prev-nav-left-link&quot;]</value>
      <webElementGuid>359b48e6-eda9-4a59-87a6-172dc89e9717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-6-2023']/div/div/div/div/img</value>
      <webElementGuid>d932e330-435e-45f5-99d2-e67d4b4e0754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Previous Month']</value>
      <webElementGuid>3ea38e28-9940-43ea-8b8b-818185d73eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/img</value>
      <webElementGuid>18913aec-bff3-4a4e-8992-60bd0e9165f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Previous Month' and @src = 'desktopweb/images/left-arrow.png']</value>
      <webElementGuid>27c21b9c-065a-4dd7-95ef-5ed9baa5f25d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
