<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoOprCalendarioDiaDesde</name>
   <tag></tag>
   <elementGuidId>bd3d0f39-1b00-4a11-8493-11769ee027b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-kony-w-c-cell-16']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = '-kony-w-c-cell-16' and (text() = '8' or . = '8')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#-kony-w-c-cell-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83520518-c10d-430d-a0ad-cd9458dccb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>3e4836b6-2d44-4bcf-8806-74f889551ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Filter_DateFilter</value>
      <webElementGuid>066b7956-b841-49b7-800b-fa5d7029bae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>ff112cc2-63e7-47f2-bcf9-25fc05530738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-k-w-c-weekday-1 -kony-w-c-day- sknCalendar</value>
      <webElementGuid>417fce1b-a964-4ed9-8640-809ed743b996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-kony-w-c-cell-16</value>
      <webElementGuid>2b67c1a0-8a4c-40c7-9e98-b037b1dae288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_Filter_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>6a6eaa62-7953-48bd-a3b6-c0297b22d091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weekday</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7bf5f318-20b0-4f7e-8702-60a835f4e4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-hold-day</name>
      <type>Main</type>
      <value>8,5,2023</value>
      <webElementGuid>13d779bd-406b-42a4-afc3-f0f1b494b11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-date-retrieve</name>
      <type>Main</type>
      <value>8,5,2023</value>
      <webElementGuid>adf5c430-c6b4-4d36-80a7-107544d06c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>59494c7b-8bb2-46a3-bdbb-c9a6c41bac06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value> 8th May 2023</value>
      <webElementGuid>eb010e27-50fe-4d10-8f0f-4cb946bf387a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>525ab7b8-eba6-4b96-b864-641314a76237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-kony-w-c-cell-16&quot;)</value>
      <webElementGuid>8cde0385-0d81-48d5-bc48-bdfdcfabfcc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='-kony-w-c-cell-16']</value>
      <webElementGuid>0e879ddf-c835-439c-ab3e-aa7fb3dafd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-5-2023']/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>db115b00-2a68-4e51-aad3-557c00e1dad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sáb'])[1]/following::div[14]</value>
      <webElementGuid>58ee7c29-0f2f-476c-bbae-ec1910406d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vie'])[1]/following::div[15]</value>
      <webElementGuid>3b497648-959c-4bca-a40c-26e1d62c2153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[44]</value>
      <webElementGuid>57f99dd9-dc4c-457a-8da9-51385f7d5954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[46]</value>
      <webElementGuid>1a6d24d5-ae1e-4dad-8b4b-d28082bbbc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>c81caff7-60ac-47fa-90bc-448138662941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]</value>
      <webElementGuid>57790a0d-d993-4d26-8929-1e51d943217c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '-kony-w-c-cell-16' and (text() = '8' or . = '8')]</value>
      <webElementGuid>76617f81-ac00-410b-bc8d-a8e9bedd6739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
