<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoOprCalendarioAtras</name>
   <tag></tag>
   <elementGuidId>88801f24-2173-464d-8e1f-6a6168fea54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-k-w-c-month-cmp-07-2023']/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.-kony-w-c-prev-nav-left-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>535239cc-4e37-40e2-91b4-e4a6de994191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>cb89c1d6-cf41-4c6e-8c95-438aed69f85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-w-c-prev-nav-left-link</value>
      <webElementGuid>bb8b42e1-ab8b-47af-8a66-49388aa95008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Previous Month</value>
      <webElementGuid>c14ddc86-f922-47ff-afab-9fdb357aa305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/left-arrow.png</value>
      <webElementGuid>8d2820ca-36bf-4f12-9833-89cfb2b8bc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_Filter_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>228741b9-6bb6-46b7-bbbb-c6c8af075ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-k-w-c-month-cmp-07-2023&quot;)/div[@class=&quot;-kony-w-c-topSection&quot;]/div[@class=&quot;-kony-w-c-table&quot;]/div[@class=&quot;-kony-w-c-row&quot;]/div[@class=&quot;-kony-w-c-cell -kony-w-c-prev-nav&quot;]/img[@class=&quot;-kony-w-c-prev-nav-left-link&quot;]</value>
      <webElementGuid>a2997d08-8f3e-4e7c-8b8f-b219cca6feaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-07-2023']/div/div/div/div/img</value>
      <webElementGuid>91aaaea7-ba92-4931-813b-232efe5a9b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Previous Month']</value>
      <webElementGuid>28e79c78-b283-4136-8b9d-b1651df40c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/img</value>
      <webElementGuid>9690c7b0-7834-417b-ae36-bf2c162d347c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Previous Month' and @src = 'desktopweb/images/left-arrow.png']</value>
      <webElementGuid>7c1a13ad-96e6-47ac-a759-ae7f596705e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
