<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblOprTablaCuentaOrigen</name>
   <tag></tag>
   <elementGuidId>5ef5a0f5-aef4-474b-bc3c-68c113822c0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmOperationsHomeBccl_lblSourceAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmOperationsHomeBccl_lblSourceAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7804cdff-5fca-4ce6-a96e-85019c42b93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_lblSourceAccount</value>
      <webElementGuid>6cf927de-8851-41aa-a5a2-8b5333c1d27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e2871ea1-b034-4da0-afd5-68cc605a28ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl</value>
      <webElementGuid>2a4b71cc-4197-4ac7-938f-062fffa15975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTitleTableBox cntmiddleleftalign disableSelection</value>
      <webElementGuid>db23894d-c359-4bf4-8cb9-00f5a9a10893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cuenta de origen</value>
      <webElementGuid>10168cba-77eb-412b-9933-83402669933b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_lblSourceAccount&quot;)</value>
      <webElementGuid>1e711d08-09b8-471a-89aa-6098ab6714ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_lblSourceAccount']</value>
      <webElementGuid>975e5de0-cdb6-4300-b30a-c5472fdcaa81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_flxTableHeaderSourceAccount']/div/div</value>
      <webElementGuid>9ff7dea4-2070-484c-bafb-84ce24703f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/following::div[5]</value>
      <webElementGuid>dbe3604f-0466-410b-8441-8667a256adde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Operación'])[2]/following::div[10]</value>
      <webElementGuid>27a17ca1-487a-4529-8507-254e2b6c9a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referencia'])[1]/preceding::div[1]</value>
      <webElementGuid>d5035b9c-ca53-4eb1-ae74-34164c1ea1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Importe'])[1]/preceding::div[6]</value>
      <webElementGuid>13ba8489-ef8b-4467-839e-6a6007e26c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cuenta de origen']/parent::*</value>
      <webElementGuid>b6b6efb4-0835-4fb6-858d-091ce61712c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div[6]/div/div/div/div</value>
      <webElementGuid>11fe37ef-8642-431d-accb-453057d7ef2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmOperationsHomeBccl_lblSourceAccount' and (text() = 'Cuenta de origen' or . = 'Cuenta de origen')]</value>
      <webElementGuid>372428a9-cedb-48d0-8a67-1b0e7d91ad88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
