<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblOprTablaImporte</name>
   <tag></tag>
   <elementGuidId>adf0e933-e931-40c8-8768-2d042ee6ba2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmOperationsHomeBccl_lblImport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmOperationsHomeBccl_lblImport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3e34904-87d0-4e14-8afe-55b43ba53758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_lblImport</value>
      <webElementGuid>12020c9e-a2d3-4709-98bc-4bac34a42f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0d37c4ff-0163-4163-bbbb-7712cb54e7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl</value>
      <webElementGuid>26ca7408-ddca-45bf-87f5-7c28298a3bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTitleTableBox cntmiddlerightalign disableSelection</value>
      <webElementGuid>7d0b2e79-6802-4143-97e4-200c0ed611ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Importe</value>
      <webElementGuid>7d2e0e86-a83b-40cd-bb50-3234798efbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_lblImport&quot;)</value>
      <webElementGuid>0a9753df-8b3f-4425-b1bb-e6dbd3e303fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_lblImport']</value>
      <webElementGuid>3c4684ea-82b5-4f9e-9569-5cfada0f83e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_flxTableHeaderImport']/div/div</value>
      <webElementGuid>311b5b9b-098b-4e8c-a1cc-9685cb22964d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referencia'])[1]/following::div[5]</value>
      <webElementGuid>4ffe9d5b-2510-4f47-8e42-3bb3f91eb2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta de origen'])[1]/following::div[10]</value>
      <webElementGuid>0d7f249a-f7da-44bb-965e-28a06809c4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia entre cuentas propias'])[3]/preceding::div[8]</value>
      <webElementGuid>198efae8-78e4-401f-b631-5d326afa58f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia realizada'])[1]/preceding::div[10]</value>
      <webElementGuid>023fc1af-a76a-41d3-b70f-1aa631e06ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Importe']/parent::*</value>
      <webElementGuid>beb51a2f-093f-4e88-9aa4-1fbe7decc602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/div/div/div[8]/div/div/div/div</value>
      <webElementGuid>025037c0-68a4-4164-a722-da54250d2ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmOperationsHomeBccl_lblImport' and (text() = 'Importe' or . = 'Importe')]</value>
      <webElementGuid>1784b244-5faf-49d3-bddf-45fe05d97cd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
