<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtImporteDetalle</name>
   <tag></tag>
   <elementGuidId>4d409a69-462d-45b1-a63c-33fcd7b8043a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclOperationDetails_lblMontoOperacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclOperationDetails_lblMontoOperacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66ade096-28b9-4db2-81bf-fee4686767de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclOperationDetails_lblMontoOperacion</value>
      <webElementGuid>53bd3ebb-b6d3-45c2-873b-08cae5e97ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>d4187612-61c3-4212-a28e-cc5b43a35362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclOperationDetails</value>
      <webElementGuid>8110f33b-3a14-43eb-8ee3-740921b400ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1466 cntmiddleleftalign disableSelection</value>
      <webElementGuid>6e7ffb51-f794-4fea-bfb9-5a384e277a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 1,00</value>
      <webElementGuid>09424c30-b5da-4a8b-8111-4953a3ec588d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclOperationDetails_lblMontoOperacion&quot;)</value>
      <webElementGuid>acbbbb8c-9185-4e9a-8001-3dd2e22cd8ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclOperationDetails_lblMontoOperacion']</value>
      <webElementGuid>8b8ab4a4-6b56-4a30-a3f5-b3dbb0894a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclOperationDetails_flxMontoOperacion']/div[2]/div</value>
      <webElementGuid>11c08c3f-b155-4a3b-b400-0bf5d7c4aa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto de la Operación'])[1]/following::div[2]</value>
      <webElementGuid>358b89f8-54e9-48ca-98be-797a30f6f3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia realizada'])[1]/following::div[10]</value>
      <webElementGuid>2cdb30bb-65bd-44e3-98be-463a5460765a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canal'])[1]/preceding::div[1]</value>
      <webElementGuid>fc973094-ad4a-40e1-b916-a0a6e10bc9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banca Web'])[1]/preceding::div[3]</value>
      <webElementGuid>0721f1a2-e3e9-4961-aa65-1a2224d3a818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 1,00']/parent::*</value>
      <webElementGuid>4621975c-1e35-4d43-9ecf-30e0629f5098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>0f6ba16d-d963-4438-b157-12481f463366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclOperationDetails_lblMontoOperacion' and (text() = '$ 1,00' or . = '$ 1,00')]</value>
      <webElementGuid>8f4176e7-2f74-4c53-a05d-af016e9ac23c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
