<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtImporte</name>
   <tag></tag>
   <elementGuidId>16156d68-fbb5-4400-95c3-b2368f863324</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxOperationsRow_lblImport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxOperationsRow_lblImport</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5edabe7-b942-4209-a2ab-6741faf371e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxOperationsRow_lblImport</value>
      <webElementGuid>e9bb2230-c146-4fb2-ad0a-a163599a9257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>dee4c305-a103-4d33-b8bc-8c9ad96be22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxOperationsRow</value>
      <webElementGuid>f107b74b-0669-49c6-a787-78c906c08e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segOperations</value>
      <webElementGuid>473cc200-8e32-472f-a745-a3df2a26cc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>ADECD34F-A862-47EF-A7CB-FE8F57ED8B24</value>
      <webElementGuid>4073dbb1-f525-4a0a-8816-69427e1c091b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddlerightalign disableSelection</value>
      <webElementGuid>57fb789a-fc39-4c10-bb7e-dc943f041f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 1,00</value>
      <webElementGuid>85cd26c0-43f5-4fa0-b96d-57496575a513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_segOperations&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxOperationsRow_flxOperationsRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxOperationsRow_lblImport&quot;]</value>
      <webElementGuid>6b276c87-6c7b-4a43-a6f7-86687282da7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxOperationsRow_lblImport']</value>
      <webElementGuid>45f4bc6f-4776-4184-9d3f-faccc833d8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxOperationsRow_flxOperationsRow']/div[7]/div</value>
      <webElementGuid>6821fcf2-87a7-409b-adea-a7a4c39f8fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU 19101196-55111901183599'])[1]/following::div[2]</value>
      <webElementGuid>ae872250-63ec-40c2-b9e9-08d85a852043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>7aea9034-39f4-4647-bbe0-ef2b6951d5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia Judicial'])[2]/preceding::div[13]</value>
      <webElementGuid>2ddbc6ef-d2bb-481e-a544-618ef831b4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 1,00']/parent::*</value>
      <webElementGuid>48d4d9d8-8b0a-4f2c-a2c2-5cc101a97360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[7]/div</value>
      <webElementGuid>da9e6998-66b8-4adb-9713-038aa895f74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxOperationsRow_lblImport' and (text() = '$ 1,00' or . = '$ 1,00')]</value>
      <webElementGuid>d347900c-01fe-4bb1-a606-3179e420171b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
