<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtOprTablaTipoOperacion</name>
   <tag></tag>
   <elementGuidId>93324721-3286-4ca5-af87-2878c883e1a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxOperationsRow_lblOperationType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxOperationsRow_lblOperationType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9b07c12-d97d-4dbf-8aba-629ee38ece82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxOperationsRow_lblOperationType</value>
      <webElementGuid>bdbe2997-7854-443c-a16d-97f5666e7d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>a05c009b-7947-49ed-b79e-fe247ceb7042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxOperationsRow</value>
      <webElementGuid>0eddb2bd-2004-44f7-b011-3dca5eb0dafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segOperations</value>
      <webElementGuid>07d597d5-905b-4cf4-b981-0db925125510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>125FA127-D49E-437D-A34D-AD460511774C</value>
      <webElementGuid>e61d422b-79b4-4c4c-944f-e06eee3499a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddleleftalign disableSelection</value>
      <webElementGuid>98ec01a4-c55f-458d-96bb-9c567c8dda4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencia entre cuentas propias</value>
      <webElementGuid>4a80163f-70d1-4077-a734-709cad6fa60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_segOperations&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxOperationsRow_flxOperationsRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableCommonData&quot;]/div[@id=&quot;flxOperationsRow_lblOperationType&quot;]</value>
      <webElementGuid>04d6c685-1ffd-4e9d-bf68-63f7cb3d901b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxOperationsRow_lblOperationType']</value>
      <webElementGuid>470a5925-c369-446b-862a-d0ac486373e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxOperationsRow_flxOperationsRow']/div[3]/div</value>
      <webElementGuid>caefd54b-09e9-43ef-a726-bcf5ff248299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Importe'])[1]/following::div[16]</value>
      <webElementGuid>7c441f54-39dd-4598-b8ca-8a70f1419187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referencia'])[1]/following::div[21]</value>
      <webElementGuid>0f4a455b-e150-4779-ac40-6f972d843ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia realizada'])[1]/preceding::div[1]</value>
      <webElementGuid>f1c6429b-aeb2-4949-969c-f8b34495c91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 001-065298/3'])[1]/preceding::div[9]</value>
      <webElementGuid>2a711568-3c9f-4841-8bf6-f1b6b873b388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div[3]/div</value>
      <webElementGuid>f5e369cb-0b5b-4340-83f0-2c7b3590c174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxOperationsRow_lblOperationType' and (text() = 'Transferencia entre cuentas propias' or . = 'Transferencia entre cuentas propias')]</value>
      <webElementGuid>fe92ab47-d22b-4b78-be9b-e4bc186a5846</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
