<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtOprDetalleTipoTransferenciaOperacn</name>
   <tag></tag>
   <elementGuidId>66a7aeaf-a4de-4047-b478-97f2d4cbe7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclOperationDetails_lblTipoOperacion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclOperationDetails_flxOperationType']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f96bcdb-de55-4e5e-80a8-755f47176494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclOperationDetails_lblTipoOperacion</value>
      <webElementGuid>cdaaa992-513d-401b-a621-86ebb8cabd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>77c702db-32f3-412c-b5d3-d14b0371699a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclOperationDetails</value>
      <webElementGuid>c77d6caa-91d5-4215-a281-8fa7a66b35b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1466 cntmiddleleftalign disableSelection</value>
      <webElementGuid>7b6574dc-eabb-4078-b5ea-fb6c9c317cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencia inmediata a otras entidades</value>
      <webElementGuid>75d58637-da3b-46b6-94ee-d274a4878ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclOperationDetails_lblTipoOperacion&quot;)</value>
      <webElementGuid>68eca0a3-eb4a-488d-947e-6d39614a922a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclOperationDetails_lblTipoOperacion']</value>
      <webElementGuid>710b4594-49ef-4300-831c-db462299c9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclOperationDetails_flxOperationType']/div/div</value>
      <webElementGuid>091cfe70-140c-49b6-94ce-e34941e85427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Operación'])[1]/following::div[5]</value>
      <webElementGuid>4e853318-6d6b-4d4d-a99d-721194d925ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Adherente'])[1]/following::div[12]</value>
      <webElementGuid>5127e92f-20f1-40eb-b7d5-3ce1edfd6d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Operación'])[1]/preceding::div[1]</value>
      <webElementGuid>030940e3-3cda-431d-8ac1-830f5a200c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/preceding::div[8]</value>
      <webElementGuid>8cc982a5-5eb0-44cf-bfbc-269ec99151c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transferencia inmediata a otras entidades']/parent::*</value>
      <webElementGuid>68fd6da9-5e1d-4ca3-85b8-89e00f8a16cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>186e6673-bf3f-4054-a57c-cf7ef458f35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclOperationDetails_lblTipoOperacion' and (text() = 'Transferencia inmediata a otras entidades' or . = 'Transferencia inmediata a otras entidades')]</value>
      <webElementGuid>146827d2-ecbc-448a-b6c8-a989a98132df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
