<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtOprTarjetas</name>
   <tag></tag>
   <elementGuidId>c1f56180-3026-422b-9939-c3d3621dd4c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon8lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon8lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e5aba86-2475-42ba-9f79-ee3d48818fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon8lblOptionTitle</value>
      <webElementGuid>4e602d34-c30d-4a4b-a449-3e057c28cf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>cc9923d6-247a-415f-8cbc-694048c98ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl</value>
      <webElementGuid>55078bbb-9b8d-43d5-9280-aa6810a267a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Filter_DropDownFilter</value>
      <webElementGuid>16b78fb2-8c53-479f-a5df-a33ba143cad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d597006-1af8-4553-ad69-4ecf4af4ed67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>8d04796b-9947-46be-b477-0ccf7aa49d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tarjetas</value>
      <webElementGuid>e2ded049-12a9-429e-bda0-ed0dc8e07139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon8lblOptionTitle&quot;)</value>
      <webElementGuid>bcaa46e5-5758-4b9a-aa8d-cac26a7a4ac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon8lblOptionTitle']</value>
      <webElementGuid>3d9676b5-d135-41e6-ba58-d6e82184d4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon8flxOptionInfo']/div/div</value>
      <webElementGuid>e81f8df6-83a6-4807-a91d-14a22cda742c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[11]/following::div[8]</value>
      <webElementGuid>630bd091-bf9f-4e0d-931e-be5f73622e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagos y Recargas'])[2]/following::div[10]</value>
      <webElementGuid>7bdd9d91-7540-41e3-b451-aa1d8f777379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[12]/preceding::div[1]</value>
      <webElementGuid>76703ab8-2a91-496a-ab84-952095571aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ahorro e inversión'])[1]/preceding::div[3]</value>
      <webElementGuid>67bcf7ce-9683-4304-90a5-1bbdd1f6cd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[8]/div/div/div/div/div/div/div</value>
      <webElementGuid>1bcd76f1-870d-41e8-aa7b-f533b5f706b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon8lblOptionTitle' and (text() = 'Tarjetas' or . = 'Tarjetas')]</value>
      <webElementGuid>4ff6dfcd-1b85-43bd-b8af-22b4fb350726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
