<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtOpVerDetalle</name>
   <tag></tag>
   <elementGuidId>aba224b3-e634-46db-abc2-83e5056adada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail&quot;)[count(. | //*[@id = 'frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail' and @class = ' sknLblOptionFloatMenu cntmiddleleftalign disableSelection' and (text() = 'Ver detalle' or . = 'Ver detalle')]) = count(//*[@id = 'frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail' and @class = ' sknLblOptionFloatMenu cntmiddleleftalign disableSelection' and (text() = 'Ver detalle' or . = 'Ver detalle')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dac34a0f-d664-4fd5-8fa3-e5798ec8462b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail</value>
      <webElementGuid>d8e9b9c2-5db5-4170-8045-14ba9d0d793f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>7e04a375-3e82-43dc-b35f-eb7b3fcce077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl</value>
      <webElementGuid>dc5c9b6e-014b-4e9e-8e0e-9079ce996fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>flxOperationsRowFloatingMenu</value>
      <webElementGuid>51bae5cb-4f14-4750-92e2-0e47f514f375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>53662de5-68b5-4da3-af45-c2eba56b296e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver detalle</value>
      <webElementGuid>6ecaf0f4-cf36-4660-801a-fdbdd7a5ddfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail&quot;)</value>
      <webElementGuid>d52d69b3-7f1e-4e7e-9efa-f9c2fcc7cefa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail']</value>
      <webElementGuid>c754597b-2f36-46ba-b05c-f85d7c232fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_flxOperationsRowFloatingMenu_flxviewDetail']/div/div</value>
      <webElementGuid>6cb1080d-d38e-47e0-8929-567a93abedc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver comprobante'])[1]/following::div[5]</value>
      <webElementGuid>43e0b00e-13d5-4d57-a306-e3efabe4d882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[13]/following::div[13]</value>
      <webElementGuid>eb96ca2e-2ce4-4084-a1ff-7ee14d9e238c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[3]</value>
      <webElementGuid>067ac46f-2c11-4cf0-99c2-9b9566354e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[5]</value>
      <webElementGuid>564d94c8-a97c-4909-a9d8-2b6b4ba16b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver detalle']/parent::*</value>
      <webElementGuid>0c2dcd49-4db1-41bf-a7f7-0c21382de9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>e540b1d5-80e3-4666-a7ac-d298497225a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail' and (text() = 'Ver detalle' or . = 'Ver detalle')]</value>
      <webElementGuid>b527f785-3fd2-476b-ae81-18829c439da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
