<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtOprListaTipoOperacion</name>
   <tag></tag>
   <elementGuidId>a5164349-2697-440a-b737-a68b755e0bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'flxOperationsRow_lblOperationType' and (text() = 'Transferencia inmediata a otras entidades' or . = 'Transferencia inmediata a otras entidades')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxOperationsRow_lblOperationType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxOperationsRow_flxOperationsRow']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fbe35d99-4242-443f-9fea-f304fd27d792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxOperationsRow_lblOperationType</value>
      <webElementGuid>01454081-ea2e-4554-b1c3-f82f5719e849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e8d83954-24c0-459f-9ad1-4c8f3bc8afbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxOperationsRow</value>
      <webElementGuid>06f84ca4-d66b-43a5-8740-ccb256f7e8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segOperations</value>
      <webElementGuid>5cfe5572-2821-485b-8906-4684357b45a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>CA035CA3-F998-44AF-8B2E-C66E9A247B6B</value>
      <webElementGuid>223cb644-0454-4c80-9eab-03db59edf606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddleleftalign disableSelection</value>
      <webElementGuid>b4320b84-da10-4c0c-9e67-247893528c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencia inmediata a otras entidades</value>
      <webElementGuid>d44f5bd6-c653-4fdc-9b33-4cdcbc516eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_segOperations&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxOperationsRow_flxOperationsRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableCommonData&quot;]/div[@id=&quot;flxOperationsRow_lblOperationType&quot;]</value>
      <webElementGuid>102ac949-219e-4e45-b917-d506c07e4921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxOperationsRow_lblOperationType']</value>
      <webElementGuid>35748a0f-6f13-45a8-827d-9bbb213b0661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxOperationsRow_flxOperationsRow']/div[3]/div</value>
      <webElementGuid>7994b6c7-e12b-400c-8734-aab21082d834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Importe'])[1]/following::div[16]</value>
      <webElementGuid>1ec767d1-8758-4cd1-8275-19fa821152e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referencia'])[1]/following::div[21]</value>
      <webElementGuid>5af93b6e-217e-40c2-b278-a748121344cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enviada a proceso...'])[1]/preceding::div[1]</value>
      <webElementGuid>45bb6573-f45b-4574-b706-94053f5c1029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[12]/preceding::div[3]</value>
      <webElementGuid>af31c80b-9448-4edf-8491-2965f210c4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div[3]/div</value>
      <webElementGuid>581545e1-208a-4181-bb71-66f6c8ca2d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxOperationsRow_lblOperationType' and (text() = 'Transferencia inmediata a otras entidades' or . = 'Transferencia inmediata a otras entidades')]</value>
      <webElementGuid>a3c06cb4-0c69-4026-a101-29dbd00caa3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
