<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtOprVerDetalleOperacion</name>
   <tag></tag>
   <elementGuidId>cb9cd7bf-f8e7-4b7e-8b0b-d38ac2183c51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ad8800b-3df0-4191-8fc4-ea88a8d8c158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail</value>
      <webElementGuid>9a0776b3-abeb-4fb6-861e-8618ae107542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>4802623e-50d1-452f-ac7d-7546147e9c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl</value>
      <webElementGuid>5c674032-ecc5-420a-9ed5-e7d7891ff27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>flxOperationsRowFloatingMenu</value>
      <webElementGuid>b8a5f607-1bae-4d9e-a7b9-9d5e4da94deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>4fec3483-0846-4a32-9744-e6945d25b49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver detalle</value>
      <webElementGuid>1701bfc2-1f9a-423f-bc7a-5119a34162b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail&quot;)</value>
      <webElementGuid>93ee7929-33e3-4030-acb3-354a4d0de27e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail']</value>
      <webElementGuid>d6517612-11d9-45ad-bd59-b0224045c6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_flxOperationsRowFloatingMenu_flxviewDetail']/div/div</value>
      <webElementGuid>1eebc980-a4f0-4a92-81cf-2244b4d5826a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver comprobante'])[1]/following::div[5]</value>
      <webElementGuid>9c0f47c7-9acc-4cd0-92c0-e216d0dde7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[13]/following::div[13]</value>
      <webElementGuid>49f0a24c-37d5-4bf3-ae6b-50b042af1751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[3]</value>
      <webElementGuid>ad772304-4554-4b16-b4b0-14b7aa613ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[5]</value>
      <webElementGuid>2595c92a-ca9a-41e1-8fcf-469c89770d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver detalle']/parent::*</value>
      <webElementGuid>9cdf1500-8ea8-4bba-a682-66e853c98411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>987fa42b-d177-4b38-950a-2abcd45844ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmOperationsHomeBccl_flxOperationsRowFloatingMenu_lblviewDetail' and (text() = 'Ver detalle' or . = 'Ver detalle')]</value>
      <webElementGuid>be6e54d2-b5e4-41f7-9114-d70eb84dd158</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
