<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtOprTipoTransferenciaCuentasPropias</name>
   <tag></tag>
   <elementGuidId>7f7891dd-c0d9-4f9a-a2df-847c744fa18a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilterType_flxOptionCommon2lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmOperationsHomeBccl_Filter_DropDownFilterType_flxOptionCommon2lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f8654f8-0690-4632-8e3c-05c2da98b675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_Filter_DropDownFilterType_flxOptionCommon2lblOptionTitle</value>
      <webElementGuid>10c05eb8-2a4b-42b0-80f7-94c8f27cdc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9bfb01b1-c8ff-414e-b63f-f4c820f4fc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl</value>
      <webElementGuid>1a2bfe1c-cf53-45c5-a1d2-e7283f871f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Filter_DropDownFilterType</value>
      <webElementGuid>f5c572da-2295-4539-ac86-6f223029936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>9f788504-2024-43c2-873f-ff2a061d0ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencia entre cuentas propias</value>
      <webElementGuid>735d5f88-72f8-4a00-8fe1-3f630588d7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_Filter_DropDownFilterType_flxOptionCommon2lblOptionTitle&quot;)</value>
      <webElementGuid>d74328fc-2a86-4f10-a212-4b4f8f7ed02b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilterType_flxOptionCommon2lblOptionTitle']</value>
      <webElementGuid>874e9922-93bb-47db-89a2-7a460c5920a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilterType_flxOptionCommon2flxOptionInfo']/div/div</value>
      <webElementGuid>c7fba589-5d8e-4a9f-8653-76083aa22c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[19]/following::div[8]</value>
      <webElementGuid>bdd13c6c-d6d5-42bf-a3bf-4824568d765f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todas'])[3]/following::div[10]</value>
      <webElementGuid>e7fd0d98-aba5-4ea8-a5d1-ac198cb6b473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[20]/preceding::div[1]</value>
      <webElementGuid>0e7d1427-c8fb-4917-a0ce-7909806ae0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia a terceros en el banco'])[1]/preceding::div[3]</value>
      <webElementGuid>323d3e3e-cef2-4d2f-a4cc-ebb4e83b8c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transferencia entre cuentas propias']/parent::*</value>
      <webElementGuid>70d1305e-0796-4976-9991-a3d2cbd8d544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>420e71d4-2d33-4bfd-b422-28e3d838bb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmOperationsHomeBccl_Filter_DropDownFilterType_flxOptionCommon2lblOptionTitle' and (text() = 'Transferencia entre cuentas propias' or . = 'Transferencia entre cuentas propias')]</value>
      <webElementGuid>02cb4815-0b75-4912-8073-8090a999a38c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
