<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPagosRecargas</name>
   <tag></tag>
   <elementGuidId>cb70a77d-3c5a-4fb0-9807-f92fe91b069f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon7lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon7lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7959b47c-a92b-46fb-9212-818ae2feb22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon7lblOptionTitle</value>
      <webElementGuid>45bcab3f-e4e3-4806-9f98-f9884f583fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>d82182b0-fe47-421a-a13a-5fef69fe0f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl</value>
      <webElementGuid>cbf58078-72a4-4a96-937a-97d290ad6320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Filter_DropDownFilter</value>
      <webElementGuid>0e293b35-8a6f-4532-aa75-dc4fd01123a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ef62ef2-8dcb-4990-9d2d-09ca360d71ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>67b3c258-4353-49a9-9b40-76274ae2850c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pagos y Recargas</value>
      <webElementGuid>0bb9f242-6f0d-4dd3-9c85-ba61044bec66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon7lblOptionTitle&quot;)</value>
      <webElementGuid>fa87332c-f3a6-4225-9128-c7a321536753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon7lblOptionTitle']</value>
      <webElementGuid>89df3c5b-d626-47c2-99aa-f7f18c3f7f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon7flxOptionInfo']/div/div</value>
      <webElementGuid>0b831631-e684-4cbb-b799-a1ebb270a4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[10]/following::div[8]</value>
      <webElementGuid>9c1124e6-2140-497e-a507-1030ea8153c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acceso y Seguridad'])[1]/following::div[10]</value>
      <webElementGuid>ad836326-448f-49ec-8019-3cba7975a6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[11]/preceding::div[1]</value>
      <webElementGuid>59d8266f-d293-489e-9bb3-9eadf9f159f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjetas'])[2]/preceding::div[3]</value>
      <webElementGuid>983766d3-1b82-4a04-b04c-590870ea04ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/div/div/div/div/div/div/div</value>
      <webElementGuid>14c11f89-dee2-48bd-b2a3-f7365e66c81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon7lblOptionTitle' and (text() = 'Pagos y Recargas' or . = 'Pagos y Recargas')]</value>
      <webElementGuid>6bb7f6e0-a36e-4a74-bf7d-d3971a4bf788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
