<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtSolicitudes</name>
   <tag></tag>
   <elementGuidId>30e72bc5-bede-4027-b04a-5e442ddbdec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon13lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon13lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46ffa7a7-28c3-41bf-ad14-2483a28488bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon13lblOptionTitle</value>
      <webElementGuid>6eb18a6e-ffb3-4ee7-8a76-70329fa5b9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>b3ad3dbc-85d0-4c69-82b2-c755f21f2a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmOperationsHomeBccl</value>
      <webElementGuid>1925d659-dc08-4310-baec-05660377a0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Filter_DropDownFilter</value>
      <webElementGuid>d5d02ebb-843a-412d-88a3-3390fc10ecd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c150d619-473a-4f1f-8dca-35d77583f6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>7a42f2d8-33f1-4aac-8cef-f4a8c6ae28bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solicitudes</value>
      <webElementGuid>47ee5267-0ec6-4ed0-bf02-6ad33675ea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon13lblOptionTitle&quot;)</value>
      <webElementGuid>09186815-a690-4565-a43f-d3f5c192fd84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon13lblOptionTitle']</value>
      <webElementGuid>62c400b7-fc82-4353-9c9c-ae9ee5818af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon13flxOptionInfo']/div/div</value>
      <webElementGuid>d401ebe1-06a5-45c1-b8c2-b75cd813a89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[16]/following::div[8]</value>
      <webElementGuid>ade61105-9bd0-439f-9367-105bb3de5c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recargas'])[1]/following::div[10]</value>
      <webElementGuid>bf30250c-93b6-4c75-9e20-0cb333ba75d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[17]/preceding::div[1]</value>
      <webElementGuid>494259b0-e2ad-4d79-9593-975031a09ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite disponible para transferir: $ 80.000,00'])[1]/preceding::div[3]</value>
      <webElementGuid>52485baf-516a-4e0c-88ef-ca59d60e5157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solicitudes']/parent::*</value>
      <webElementGuid>002454c0-e343-47c5-8f50-e898e7c76feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div/div/div/div/div</value>
      <webElementGuid>9be5adc9-d4f1-48ad-8ca4-75d66c529a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmOperationsHomeBccl_Filter_DropDownFilter_flxOptionCommon13lblOptionTitle' and (text() = 'Solicitudes' or . = 'Solicitudes')]</value>
      <webElementGuid>96eb180c-3148-44f9-99a6-b91aebba2e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
