<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTipoOperacionDetalle</name>
   <tag></tag>
   <elementGuidId>e3951a8c-aca6-431b-9c0e-5410cf18adc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclOperationDetails_lblTipoOperacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclOperationDetails_lblTipoOperacion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>946113ca-3775-4a2f-ad05-0a763c334a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclOperationDetails_lblTipoOperacion</value>
      <webElementGuid>29894f37-935f-4961-a97d-943dae272c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>ecd7b978-4c3c-4dab-bbbc-5e9ed83ed039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclOperationDetails</value>
      <webElementGuid>12301a9d-68a5-48e8-8d1d-240775013204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1466 cntmiddleleftalign disableSelection</value>
      <webElementGuid>dc22adb9-aae0-4830-8d8c-02231a2c85f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencia entre cuentas propias</value>
      <webElementGuid>4c4abb9b-cbc0-4f2a-af0d-ea0693963689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclOperationDetails_lblTipoOperacion&quot;)</value>
      <webElementGuid>c5a39e34-493e-4bf9-98f1-5d5b93c9ad53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclOperationDetails_lblTipoOperacion']</value>
      <webElementGuid>5bc2b14f-4426-45b3-b537-d01cc12c7a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclOperationDetails_flxOperationType']/div/div</value>
      <webElementGuid>9b02bd9e-7b24-4109-b8d3-4efd3354ab2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Operación'])[1]/following::div[5]</value>
      <webElementGuid>56001294-8560-4601-ba91-4e4ca42a1a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Adherente'])[1]/following::div[12]</value>
      <webElementGuid>68e2570d-38a6-47e6-99c7-4bcf2c1aaa92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Operación'])[1]/preceding::div[1]</value>
      <webElementGuid>f8238470-4aef-41c9-b18e-5a304ca67f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[1]/preceding::div[8]</value>
      <webElementGuid>c7935073-1048-4af0-8ba2-a8e4dbfe0777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transferencia entre cuentas propias']/parent::*</value>
      <webElementGuid>c0c5c99d-d7f0-4c67-84f9-765aa5d73a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>745f14cf-2861-439e-9548-3f66d1ecad1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclOperationDetails_lblTipoOperacion' and (text() = 'Transferencia entre cuentas propias' or . = 'Transferencia entre cuentas propias')]</value>
      <webElementGuid>c065351d-17f6-432b-8450-a7e1543ba56a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
