<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTipoOperacion</name>
   <tag></tag>
   <elementGuidId>cc36a636-be46-4b4e-a4e2-8d3cd04585d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxOperationsRow_lblOperationType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxOperationsRow_lblOperationType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb5c069b-4ce4-47ad-bf3a-44ac277ac30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxOperationsRow_lblOperationType</value>
      <webElementGuid>b5cee9fc-be1a-499c-9b0c-59e44825bc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>67573e4e-2a23-43ab-88b2-fed5db901b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxOperationsRow</value>
      <webElementGuid>013e7b32-9e17-4bd4-9f6c-765db5f7cd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segOperations</value>
      <webElementGuid>f633a6d2-745c-4236-88d5-38822ba2b193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>196CA9B8-F49F-451C-B902-E7502438D489</value>
      <webElementGuid>0fc45c32-77ca-4d3a-bfe4-fc2bba0890d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddleleftalign disableSelection</value>
      <webElementGuid>b615d183-f111-45a7-8fe4-b26be080c2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencia entre cuentas propias</value>
      <webElementGuid>49d6bd95-83b5-4c5f-a956-26968dfc5b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmOperationsHomeBccl_segOperations&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxOperationsRow_flxOperationsRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableCommonData&quot;]/div[@id=&quot;flxOperationsRow_lblOperationType&quot;]</value>
      <webElementGuid>3d0bbd27-0024-45a9-9c43-d59e91913979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxOperationsRow_lblOperationType']</value>
      <webElementGuid>21f89cdb-cbae-4ff7-9d7e-c59a93d90f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxOperationsRow_flxOperationsRow']/div[3]/div</value>
      <webElementGuid>06a6a3e6-d397-4e82-9f60-bebc864e2e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Importe'])[1]/following::div[16]</value>
      <webElementGuid>63f5c480-450a-40db-8196-991d518e8aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referencia'])[1]/following::div[21]</value>
      <webElementGuid>0c8bd2e6-ca9f-419f-9efe-fbc53baed4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia realizada'])[1]/preceding::div[1]</value>
      <webElementGuid>108ab0d7-2163-4578-914e-52d691ff7b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 001-065298/3'])[1]/preceding::div[9]</value>
      <webElementGuid>3743b2a7-2010-45ac-8fcd-9d24211816b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div[3]/div</value>
      <webElementGuid>d5b7adc9-1c8f-4bb8-b956-5ab9bd480048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxOperationsRow_lblOperationType' and (text() = 'Transferencia entre cuentas propias' or . = 'Transferencia entre cuentas propias')]</value>
      <webElementGuid>189a597a-1112-4e60-bbe1-59531167f19d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
