<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkLgnOlvidePass</name>
   <tag></tag>
   <elementGuidId>09fd5ffe-a3de-4f67-a156-dd3a97f2924b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmLogin_main_lblForgotPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmLogin_main_lblForgotPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>885c0d50-b2fe-43eb-a0bd-adb531ba6fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmLogin_main_lblForgotPassword</value>
      <webElementGuid>b00b8b6b-9d32-4c55-a79f-6c900cde7886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>75e6a4ac-9691-4f22-aa6b-6b4eb53c83f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmLogin</value>
      <webElementGuid>3bbff9cc-d8a7-47e8-999a-8e61be670596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>c98c7a3f-bc92-4b23-8b01-ee11db0371d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoReg14584F8C cntmiddlerightalign disableSelection</value>
      <webElementGuid>e09f148f-41b3-416d-933d-8986dd1f0da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Olvidé o bloqueé mi Clave</value>
      <webElementGuid>5e1a8905-2baf-4460-9416-4efa46de0aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin_main_lblForgotPassword&quot;)</value>
      <webElementGuid>14f6590e-96f2-4955-8b9b-29ac090d8eb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmLogin_main_lblForgotPassword']</value>
      <webElementGuid>715d103e-c31a-4a31-895c-6141b00125ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmLogin_main_flxForgotPassword']/div/div</value>
      <webElementGuid>fd102012-9d9e-4543-b05e-03eebd9db49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[6]/following::div[5]</value>
      <webElementGuid>36fb59e4-73a5-4fcc-abcb-819a0cfd9f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[10]</value>
      <webElementGuid>5041efb1-31b2-4968-adbb-d3e947a2349e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuario'])[1]/preceding::div[1]</value>
      <webElementGuid>e5b5ee03-6cae-4bbe-9ec5-6f938aaffc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[4]</value>
      <webElementGuid>bb2235fd-8763-493e-8e81-a04fcc532800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Olvidé o bloqueé mi Clave']/parent::*</value>
      <webElementGuid>02319ae3-0a42-4a61-8d37-c3c413c15315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>52ca8e9a-802f-491b-bd0a-537f9b1386b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmLogin_main_lblForgotPassword' and (text() = 'Olvidé o bloqueé mi Clave' or . = 'Olvidé o bloqueé mi Clave')]</value>
      <webElementGuid>71fe9550-b239-4a1b-ae84-9afaaacc7551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
