<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtRcpUsuarioCredicoop</name>
   <tag></tag>
   <elementGuidId>ab651b26-bf73-4372-9ae1-32d10ce47178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmLogin_RecuperarClave_InputUsername_tbxMasked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmLogin_RecuperarClave_InputUsername_tbxMasked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a06012e9-f4ef-49ec-9bd1-4d8689408a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmLogin_RecuperarClave_InputUsername_tbxMasked</value>
      <webElementGuid>a26adcfb-2660-4b1e-b4f4-a3b7bd002d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>9347acdb-dfda-4bb2-9bf1-e035594c4c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmLogin</value>
      <webElementGuid>5f32d7a0-1524-4cc7-97f0-ad20b830f551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>RecuperarClave_InputUsername</value>
      <webElementGuid>58829bf9-a2dc-4de8-b484-4a21ec90f78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknTbxInputMasked </value>
      <webElementGuid>792e181d-4e61-48ec-8f76-b3f5b8869061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>1542041f-72f9-4cc6-b6e8-cb5c7295eeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0da84c15-7091-45ba-9c52-4982e75eeca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>69fbb7f3-ac3e-4889-8def-7c6db6210d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef4d24ea-9bfe-42e0-988d-2ee9ccdc52ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>352e65b2-39c2-49f2-ab97-b0fd32cdf47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>5612464b-dbee-42db-a1e1-02b6eaf2e588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Usuario</value>
      <webElementGuid>b08bd1c2-939f-4592-a445-685a1070fdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>0d9c6de5-0a50-426c-b8fb-ed3c853defde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin_RecuperarClave_InputUsername_tbxMasked&quot;)</value>
      <webElementGuid>b1c75766-bb10-4284-9ec6-4150f423f955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmLogin_RecuperarClave_InputUsername_tbxMasked']</value>
      <webElementGuid>b8b59da7-a830-45c5-af1d-33ba94ca5c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmLogin_RecuperarClave_InputUsername_flxInput']/div/input</value>
      <webElementGuid>2cada3e4-e114-42c9-8a7c-7734bee0ee0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[4]/div/div/div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>be08aabc-3cd6-4464-923c-067865463d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmLogin_RecuperarClave_InputUsername_tbxMasked' and @type = 'text' and @placeholder = 'Usuario']</value>
      <webElementGuid>a9f483f2-d106-4614-996d-7ff3eb7f8dd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
