<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrfCalendarioFechaEnvio</name>
   <tag></tag>
   <elementGuidId>29f31208-7bfc-418f-bd02-9ce5e27f23ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='calendarDate_img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendarDate_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>16872bee-4e7d-47f1-a2f9-61932a420bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendarDate_img</value>
      <webElementGuid>3e508a2d-dbeb-4e0f-b55b-e81021e789a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>76760862-95c2-4c8f-913c-9dbf211149be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/calendar-regular.svg</value>
      <webElementGuid>f6989dd7-e55d-4c94-82cc-36ff8e1f59a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xalign</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>d30a2561-9532-4079-9ed4-363ab740d56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>$KW.Calendar.setCalElementStyle(this,false)</value>
      <webElementGuid>c0ab4ed4-593b-411c-873d-28fef39795b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>765f0bfa-d5a6-4442-82a1-9956278867b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Date</value>
      <webElementGuid>7a703cfa-853d-499a-9c1e-f3ef3cc7a0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5eaf4b9a-48b0-41dc-9dea-ff47eaa7b264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDate_img&quot;)</value>
      <webElementGuid>6d78bfe8-7cca-4d74-ae2b-9ea0635c6d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='calendarDate_img']</value>
      <webElementGuid>24217943-ea6b-45e6-80f3-504a558c7c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_Date_calendarDate']/img</value>
      <webElementGuid>635270d8-83b6-4f5e-9b61-34f0c68a628e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Calendar']</value>
      <webElementGuid>ce518d2e-477b-4684-80b1-6accd98c68ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>99eda6df-e666-4ddd-8e45-c83a867f46fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'calendarDate_img' and @type = 'image' and @src = 'desktopweb/images/calendar-regular.svg' and @alt = 'Calendar']</value>
      <webElementGuid>86839fac-d037-4200-8391-4e54017fa85d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
