<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnComprarDolares</name>
   <tag></tag>
   <elementGuidId>695d7404-a66c-45a3-9a56-37326e912541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderCompra_btnWithLoader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderCompra_btnWithLoader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ef587fe-19b5-4de4-b3e1-e36ad8c5d66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>0fff1134-514f-48cd-ab68-229750825e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderCompra_btnWithLoader-hint</value>
      <webElementGuid>a174114e-3ce9-4c68-83f6-5f0b3cd2b68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderCompra_btnWithLoader</value>
      <webElementGuid>fac9fd9c-8cc3-4c07-b9ff-5e9e39ce3a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>bb70f2c5-a046-4350-a9dd-ddaf5d69deef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>fe5d1b94-cf72-4284-a602-60de3bfd11a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CotizacionDolar_ButtonWithLoaderCompra</value>
      <webElementGuid>06f7f7a7-0af3-4adf-8ee8-1870d97fe87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14413b60-64f5-4516-a48e-88d0821de9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknBtnPrimary</value>
      <webElementGuid>e1b15857-0d43-4603-b031-a945e9ab98ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Comprar</value>
      <webElementGuid>b02a229a-3291-4a43-8600-1918c4238b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>1f2f8d2e-2ad6-413e-a2b7-8d4fd1273f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8bacfa1e-8d71-492d-b0e9-4e166e9c8e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderCompra_btnWithLoader&quot;)</value>
      <webElementGuid>41feeb05-2844-42da-8f1a-8a4109319f5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderCompra_btnWithLoader']</value>
      <webElementGuid>34468166-4b62-4355-805a-fd80ec036adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderCompra']/div/input</value>
      <webElementGuid>c22a087e-8e8e-4340-b053-83bbf2fcd51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>31d12978-f095-465e-9d0c-693fef8c2a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderCompra_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>5f4014c6-19ac-4d32-a865-6a2b097980ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
