<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnVenderDolares</name>
   <tag></tag>
   <elementGuidId>1275f3e6-8e30-44bc-b696-369965c94b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderVenta_btnWithLoader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderVenta_btnWithLoader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e83f8b01-4e80-4f04-b059-6cc6342fd872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>ce1a5283-9e26-4e04-87b5-14d2f53f6014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderVenta_btnWithLoader-hint</value>
      <webElementGuid>cfa898d0-46f1-4007-9704-9bcbf47c32e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderVenta_btnWithLoader</value>
      <webElementGuid>179cc629-9c14-4a12-a89b-1708dd82c457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>b125b045-345a-4eb5-bf50-1cd3307119b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>07971ff4-684e-4be0-a394-f51308cb5654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CotizacionDolar_ButtonWithLoaderVenta</value>
      <webElementGuid>11afe771-3d81-45f3-ae10-0d3047a42c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d4b002b-448c-493f-acb0-b97a9c2b6f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknBtnPrimary</value>
      <webElementGuid>0e0643a5-1a8f-4a5d-aa17-e69580ed1d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Vender</value>
      <webElementGuid>fe114a7b-9d60-434f-948c-584253cf6ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>4c583817-a400-481a-8379-15961a0c8621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>324775c8-614d-4443-ba52-265233c5b79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderVenta_btnWithLoader&quot;)</value>
      <webElementGuid>8d93eccb-ddb8-46b6-9073-eecf0d9873fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderVenta_btnWithLoader']</value>
      <webElementGuid>305b0256-1063-4d69-9c5d-8a958fb363d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderVenta']/div/input</value>
      <webElementGuid>16892e77-5b1a-4d4c-b1eb-e954bda84fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>0566aab9-bf1b-4cf7-bd9a-f828e103d908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmInvestmentsHomeBccl_CotizacionDolar_ButtonWithLoaderVenta_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>2e6269af-d55e-4342-906f-a581b6210769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
