<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblComprobanteVentaDolares</name>
   <tag></tag>
   <elementGuidId>74455526-acef-4c27-99b6-3cf776d7d9cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_lblVoucherTitle5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_ForeignCurrency_lblVoucherTitle5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da25c716-109d-4017-a2e9-a7cf97be0152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_ForeignCurrency_lblVoucherTitle5</value>
      <webElementGuid>a33a7630-a7c6-41f9-993c-56147b2cc8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>49e6f6a6-7acf-4d06-bb56-b8204c48b4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>e284b1ed-c633-4bae-b2fe-bef13b753262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ForeignCurrency</value>
      <webElementGuid>8086c32c-0c38-436e-b5a8-3b309d177f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> CopyslLabel0c15440b1b90941 cntmiddleleftalign disableSelection</value>
      <webElementGuid>48180884-aa27-4bfc-b030-fce131bc3ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Comprobante de Venta de Dólares</value>
      <webElementGuid>7896fc39-5be1-42b3-8b64-00d575507887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_ForeignCurrency_lblVoucherTitle5&quot;)</value>
      <webElementGuid>17427cb8-8669-4a68-9e8f-7887c3e6a36a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_lblVoucherTitle5']</value>
      <webElementGuid>803588a3-0444-4990-825c-6f8b3620aeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_flxVoucherTableData5']/div/div</value>
      <webElementGuid>40aa5c77-bd54-40c6-b610-564e1aa7d22a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venta de Dólares'])[5]/following::div[11]</value>
      <webElementGuid>f7636350-e90a-4364-a85c-58008b9092b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[11]/following::div[16]</value>
      <webElementGuid>56340d35-1174-40ce-ab19-3feb0e8de807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de operación'])[1]/preceding::div[1]</value>
      <webElementGuid>60b4a9a2-df14-4d66-af69-5768aa38c1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Núm. de operación'])[1]/preceding::div[8]</value>
      <webElementGuid>ebed051d-045c-49da-a3f8-9b7815e20198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Comprobante de Venta de Dólares']/parent::*</value>
      <webElementGuid>74a12c9b-10d5-4736-beca-89367292b05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>af09f920-f8d5-4f8a-9586-7ac6263fb421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_ForeignCurrency_lblVoucherTitle5' and (text() = 'Comprobante de Venta de Dólares' or . = 'Comprobante de Venta de Dólares')]</value>
      <webElementGuid>838ef64b-501c-4a4d-8978-7d508b8db036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
