<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCompraVentaDolares</name>
   <tag></tag>
   <elementGuidId>e7b814a0-d4ef-4bad-8257-b86c48fc675c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_CotizacionDolar_lblTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_lblTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb28cd18-bbc6-45d4-b702-71a9874a0de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CotizacionDolar_lblTitle</value>
      <webElementGuid>a120c684-c01c-462a-8e2f-a09b48c701b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>1bdd6885-ea08-4e8a-b829-e4c90fda7db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>0315bb68-c9ac-4531-90a1-a9790b3c374d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CotizacionDolar</value>
      <webElementGuid>a480a0da-961b-42df-a7bb-2baf567d684c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCotizacionDolar cntmiddleleftalign disableSelection</value>
      <webElementGuid>a0b87479-a8cc-4cb3-9f28-7fbde06d9205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compra Venta de Dólares</value>
      <webElementGuid>4c862c1a-f4da-4956-82b5-a90a49625d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_CotizacionDolar_lblTitle&quot;)</value>
      <webElementGuid>cfc81994-6a67-489c-8e24-cb0c3036f780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_lblTitle']</value>
      <webElementGuid>ad611d8c-577b-4f09-b6d7-44a8b4d0c3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_flxTitleContainer']/div/div</value>
      <webElementGuid>fd0efeac-3075-4515-8622-375b2abd6f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[5]</value>
      <webElementGuid>48cd1749-9df9-4b67-ac51-3155fb03dc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[6]/following::div[11]</value>
      <webElementGuid>d2a2580a-fd9e-4479-b8b2-99d68ee53ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver movimientos de compra/venta'])[1]/preceding::div[1]</value>
      <webElementGuid>3a69e38b-4362-4fca-9b85-8b3526d37363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización de Referencia'])[1]/preceding::div[13]</value>
      <webElementGuid>08bbe913-43a2-44b8-b9fc-85d1570af605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compra Venta de Dólares']/parent::*</value>
      <webElementGuid>3b410e05-c6ad-4e76-b1ab-c7ff03de9b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>381196f5-03d2-425f-aeed-542023243530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_CotizacionDolar_lblTitle' and (text() = 'Compra Venta de Dólares' or . = 'Compra Venta de Dólares')]</value>
      <webElementGuid>b5256087-ddb6-4b06-827e-4f93118f4441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
