<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblInvCuentaDebito</name>
   <tag></tag>
   <elementGuidId>a03d7468-be4f-468e-a465-62d500050891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_lblDebitAccount5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_ForeignCurrency_lblDebitAccount5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e48f4746-b567-4576-9847-48eafe7dd322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_ForeignCurrency_lblDebitAccount5</value>
      <webElementGuid>2811d5f4-8a67-4a4f-8160-ff1485551c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>11487019-91e2-416a-b55a-bd61129be6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>c9dc3f06-f2ab-433d-81be-d543b40eb46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ForeignCurrency</value>
      <webElementGuid>dd5c192b-740b-4a79-ad0c-6f9977617443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblPanelProductRowData cntmiddleleftalign disableSelection</value>
      <webElementGuid>6b49d15f-0576-452f-ae62-a16e612269c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cuenta de débito</value>
      <webElementGuid>fd339931-82ad-45f8-b132-0677617fd2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_ForeignCurrency_lblDebitAccount5&quot;)</value>
      <webElementGuid>a8ba8f8c-9616-45ef-ab2e-78c666eb0c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_lblDebitAccount5']</value>
      <webElementGuid>9018e5ab-3b4f-4c5c-a8ef-e271d7a821c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_flxDebitAccountContainer5']/div/div</value>
      <webElementGuid>5b684bdf-b130-456b-a611-7f1d6f4e90e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venta'])[3]/following::div[5]</value>
      <webElementGuid>831cd48d-de5e-433f-a4ae-b623c5b7a824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de operación'])[1]/following::div[7]</value>
      <webElementGuid>9b245ae1-9e5a-4f5f-a074-f53a19a94cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 119-011835/9'])[5]/preceding::div[1]</value>
      <webElementGuid>295088cc-1c34-4d01-8737-c5e00c71c63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto de venta'])[1]/preceding::div[3]</value>
      <webElementGuid>a406b155-1ea0-4f15-b404-ce003955863a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[6]/div/div/div/div</value>
      <webElementGuid>196e712b-2fd7-484f-a564-7491d9317f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_ForeignCurrency_lblDebitAccount5' and (text() = 'Cuenta de débito' or . = 'Cuenta de débito')]</value>
      <webElementGuid>3550300a-914d-4794-8009-b3a60c3b4f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
