<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblVentaDolares</name>
   <tag></tag>
   <elementGuidId>016f0b01-ffa4-4748-829f-c885a9aee2b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_ForeignCurrency_lblTitle1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_lblTitle1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a67784d-c0ff-4c01-951d-292ddb740385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_ForeignCurrency_lblTitle1</value>
      <webElementGuid>b9f466a5-114c-40f8-8f26-61ffb81b6408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>1fe89133-ae06-447b-a39f-fc481b34ef5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>80b0698a-42b3-4fe2-96d7-04016b1a5ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ForeignCurrency</value>
      <webElementGuid>27eb1b35-41b5-4c55-9c54-3521637146d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknNewBeneficiaryHeaderTitle cntmiddleleftalign disableSelection</value>
      <webElementGuid>740888cc-3496-4f6b-b093-f56307f4b2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Venta de Dólares</value>
      <webElementGuid>4bd68efe-4877-4d87-a067-e143abfc1a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_ForeignCurrency_lblTitle1&quot;)</value>
      <webElementGuid>38879f05-2290-4706-8ee3-443fe9c61de8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_lblTitle1']</value>
      <webElementGuid>9e85885d-1f1d-472b-8384-f7ba11b61bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_flxHeader1']/div/div</value>
      <webElementGuid>6104d40d-eeec-431e-a63c-bf3c47b1e916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[7]/following::div[5]</value>
      <webElementGuid>fe0b5564-cd43-4425-abed-308d5d9d92d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardando'])[1]/following::div[34]</value>
      <webElementGuid>697a358d-e6db-4cfb-8572-e456d35382b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresá los siguientes datos'])[1]/preceding::div[1]</value>
      <webElementGuid>6137c984-fe59-40e7-b27f-3c7d3fc26243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿De dónde debitar?'])[1]/preceding::div[3]</value>
      <webElementGuid>49bc8696-9b36-41cc-a360-9fd89403b718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Venta de Dólares']/parent::*</value>
      <webElementGuid>54bc04b9-f5a1-494b-b467-b4b84cd47146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>377cb704-a970-467c-9ba0-cf48fd1826ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_ForeignCurrency_lblTitle1' and (text() = 'Venta de Dólares' or . = 'Venta de Dólares')]</value>
      <webElementGuid>6ea43ca7-d680-4006-b3f8-9682c8d1a6ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
