<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuInvPFTipo</name>
   <tag></tag>
   <elementGuidId>3e8f6e8c-5161-44d1-b21f-b2e9e60912bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmSimulateFixedTerm_DropDownPlazoFijo_lblDropDownIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmSimulateFixedTerm_DropDownPlazoFijo_lblDropDownIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e31a54bd-9ef5-4bd6-b975-0045433d0d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmSimulateFixedTerm_DropDownPlazoFijo_lblDropDownIcon</value>
      <webElementGuid>19aecb3a-3db9-4791-abc5-3f9aac3fb634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9de65936-2dbc-46ee-8d8e-15e22f9bdb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmSimulateFixedTerm</value>
      <webElementGuid>e654e062-d48e-4419-9ba7-c2c3dd29bb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DropDownPlazoFijo</value>
      <webElementGuid>3f70499e-21c1-40d1-acfd-23fc70a92e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddlecenteralign disableSelection sknLblDropDownChevronAccounts</value>
      <webElementGuid>4131ce86-f588-4b61-a733-e6a2a3b64919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d68fe995-6273-4908-b4c7-80d692a7bf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6c68a92d-2df8-4ef5-9ea7-4dab27ddf58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSimulateFixedTerm_DropDownPlazoFijo_lblDropDownIcon&quot;)</value>
      <webElementGuid>007f7d7b-d38a-461f-8312-a961d991298e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmSimulateFixedTerm_DropDownPlazoFijo_lblDropDownIcon']</value>
      <webElementGuid>94efded0-3aff-4129-ba01-b5c23a184e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmSimulateFixedTerm_DropDownPlazoFijo_flxOption']/div[2]/div</value>
      <webElementGuid>69afc2d9-293d-4bb6-86eb-33fec9b372da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccionar'])[1]/following::div[2]</value>
      <webElementGuid>6cb2b991-a7b6-42e9-af4c-3f445201ca71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 1.000,00'])[1]/following::div[4]</value>
      <webElementGuid>7838d5d2-a986-4c03-a98a-f8a41a7f6984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plazo mínimo:'])[2]/preceding::div[10]</value>
      <webElementGuid>77636bdc-9a01-4233-b886-ff25deb311ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>0ded0422-8350-4cc4-ab38-bd4e32eba28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmSimulateFixedTerm_DropDownPlazoFijo_lblDropDownIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>eb8efb71-3d2f-46d1-a73d-f9b850991f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
