<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvTasa3</name>
   <tag></tag>
   <elementGuidId>cbf967fc-5a63-457c-a29f-44d507816e90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmFixedTermRatesTables_collapsableCard-30-1683488945394_lblHeaderTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmFixedTermRatesTables_collapsableCard-30-1683488945394_lblHeaderTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9eb8c3ee-4c16-4230-9c00-ff28e8db64b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables_collapsableCard-30-1683488945394_lblHeaderTitle</value>
      <webElementGuid>b0a974cb-9c61-49b9-a58b-946d4c748cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9062cb55-fb60-43e5-80d7-8e683de65d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables</value>
      <webElementGuid>088eac8f-c476-4f30-b376-64bbd44847c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>collapsableCard-30-1683488945394</value>
      <webElementGuid>ab31a166-8c8c-494b-8538-1bc8a66f8f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCardTitleLG cntmiddleleftalign disableSelection</value>
      <webElementGuid>d88e230a-f647-4a66-b986-b269c89e71e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesos Intransferible  -  Precancelable - BPI - C. Movil y  BEE</value>
      <webElementGuid>b5a6d40d-859a-421b-9198-1e9348f1bfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmFixedTermRatesTables_collapsableCard-30-1683488945394_lblHeaderTitle&quot;)</value>
      <webElementGuid>0def7171-8dda-48e9-84a1-e745e01120e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-30-1683488945394_lblHeaderTitle']</value>
      <webElementGuid>6c45d767-048b-49bc-bd2b-fde2a6fe4f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-30-1683488945394_flxHeader']/div/div</value>
      <webElementGuid>732c9f44-2652-4eec-9607-a6bea56f2a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TNA 90'])[2]/following::div[63]</value>
      <webElementGuid>081dfb9f-e9a9-4719-aa47-d773b853ec4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TNA 60'])[2]/following::div[68]</value>
      <webElementGuid>ff7e7617-da17-47fa-bde2-17433bc89d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[10]/preceding::div[1]</value>
      <webElementGuid>69525362-99c4-4eb9-b164-42ef50538462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto hasta ($)'])[3]/preceding::div[6]</value>
      <webElementGuid>e9abdb62-a43c-4bc9-954c-8c1045ffec1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div[2]/div/div/div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>06fcd6b3-2205-4376-923c-d705d82160be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmFixedTermRatesTables_collapsableCard-30-1683488945394_lblHeaderTitle' and (text() = 'Pesos Intransferible  -  Precancelable - BPI - C. Movil y  BEE' or . = 'Pesos Intransferible  -  Precancelable - BPI - C. Movil y  BEE')]</value>
      <webElementGuid>7a05ff97-6a99-4d41-9cc6-1667fb7b735f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
