<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvTasa8</name>
   <tag></tag>
   <elementGuidId>bb5ddac3-7e8a-46e8-a6b5-4c1277696c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmFixedTermRatesTables_collapsableCard-108-1683488945651_lblHeaderTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmFixedTermRatesTables_collapsableCard-108-1683488945651_lblHeaderTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50e8d0a6-7d9c-4aa8-8b7f-be3c2edf2c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables_collapsableCard-108-1683488945651_lblHeaderTitle</value>
      <webElementGuid>99604fdc-5546-4068-bdd6-5bcdb221cd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>23bd2b55-cae2-4988-bd33-a2805ff311ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables</value>
      <webElementGuid>8e724737-4e70-4b28-b9ad-5e70e6e775d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>collapsableCard-108-1683488945651</value>
      <webElementGuid>7503bcdc-1e40-4df5-bc13-4a5fbb8cd7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCardTitleLG cntmiddleleftalign disableSelection</value>
      <webElementGuid>68c54515-e568-464e-ba1e-09785ba1c556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesos Intransferible - COM A6871  - Ajus. por UVA - Precancelable -  BPI y C. Mo</value>
      <webElementGuid>d09da0dc-eedb-478f-919a-ff2f99fcbebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmFixedTermRatesTables_collapsableCard-108-1683488945651_lblHeaderTitle&quot;)</value>
      <webElementGuid>d7826d29-1821-457c-9d65-25cabe95145c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-108-1683488945651_lblHeaderTitle']</value>
      <webElementGuid>756e336e-c2a5-4c86-8510-78b1276b84f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-108-1683488945651_flxHeader']/div/div</value>
      <webElementGuid>882d9d1f-8c6e-4cb6-b88b-5b626806c670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TNA 180'])[2]/following::div[63]</value>
      <webElementGuid>c7bd6b87-1c42-4f79-9381-7e44f8805184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TNA 120'])[1]/following::div[68]</value>
      <webElementGuid>0dce6686-0266-45c0-8254-315fb883a520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[15]/preceding::div[1]</value>
      <webElementGuid>9c1b3acc-b7e1-4a39-a4e3-1c23d850e412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto hasta ($)'])[8]/preceding::div[6]</value>
      <webElementGuid>e19402a9-346c-4641-9003-7af4d7060e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[8]/div/div/div/div/div/div/div</value>
      <webElementGuid>9254d06b-dfdf-4db3-a381-65977d7a68f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmFixedTermRatesTables_collapsableCard-108-1683488945651_lblHeaderTitle' and (text() = 'Pesos Intransferible - COM A6871  - Ajus. por UVA - Precancelable -  BPI y C. Mo' or . = 'Pesos Intransferible - COM A6871  - Ajus. por UVA - Precancelable -  BPI y C. Mo')]</value>
      <webElementGuid>cc1c0526-b4e3-4891-957c-e9ce8278916b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
