<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvConsultarTasasPlazoFijo</name>
   <tag></tag>
   <elementGuidId>5aeebe06-5005-4abc-ae99-242ed10f47b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_CFloatingMenu_lblFixedTermRates</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_CFloatingMenu_lblFixedTermRates']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19035a75-07e4-4000-9bc4-db0b6b36c9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CFloatingMenu_lblFixedTermRates</value>
      <webElementGuid>e00de1e0-3488-4660-b244-c894a651979c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>2378d121-af92-4258-aa65-e769a345ae9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>5feab915-f2d9-4ec3-a146-af31811e9853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CFloatingMenu</value>
      <webElementGuid>5832d00c-df18-4c49-8f4e-6361b6cc89ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>cce5d1d3-f0d0-40d6-80ff-6297701c4dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consultar tasas de plazo fijo</value>
      <webElementGuid>4a34bac8-ea74-48b7-921f-1441cb1da062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_CFloatingMenu_lblFixedTermRates&quot;)</value>
      <webElementGuid>3de3a84d-629c-41e0-a7fa-4de33c71f5f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CFloatingMenu_lblFixedTermRates']</value>
      <webElementGuid>7d9d9326-486a-46ab-9eaf-a8ed30bf4902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CFloatingMenu_flxFixedTermRates']/div/div</value>
      <webElementGuid>872770b6-4bd5-4c6c-8f6f-c244fda88351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[7]/following::div[8]</value>
      <webElementGuid>261b4128-780e-4ee9-8fee-ef38f3636c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[35]/following::div[32]</value>
      <webElementGuid>767366ad-f6b5-419f-b557-f1df7a0c9f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retención de ganancias de plazo fijo'])[1]/preceding::div[1]</value>
      <webElementGuid>cf44f6e9-ace6-421e-b8ff-de3d8413b4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Para colocación a Plazo'])[1]/preceding::div[6]</value>
      <webElementGuid>e5d61cc7-afa5-46b6-bbc6-9a80457afb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consultar tasas de plazo fijo']/parent::*</value>
      <webElementGuid>644bb844-4600-4175-9171-ea8be6066813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>4a3ac4ae-26dc-488f-9e06-0469da5f74b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_CFloatingMenu_lblFixedTermRates' and (text() = 'Consultar tasas de plazo fijo' or . = 'Consultar tasas de plazo fijo')]</value>
      <webElementGuid>adc63f66-3da6-4bc7-9e6c-9e4defac30de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
