<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvTasa7</name>
   <tag></tag>
   <elementGuidId>24b137d0-a63b-4316-b82b-082aba57d8dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmFixedTermRatesTables_collapsableCard-98-1683488945590_lblHeaderTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmFixedTermRatesTables_collapsableCard-98-1683488945590_lblHeaderTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>741be9ab-6579-4f3c-8902-2678ccb5696b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables_collapsableCard-98-1683488945590_lblHeaderTitle</value>
      <webElementGuid>d3b59ebf-f131-4d8d-a982-7e8393b46fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>91d35081-903a-4efd-baa6-dd62ed55e19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables</value>
      <webElementGuid>def9566c-7f5b-4bc6-a00f-d6b133edef55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>collapsableCard-98-1683488945590</value>
      <webElementGuid>1a8a24d5-d85e-47d5-9212-d1d68d6889e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCardTitleLG cntmiddleleftalign disableSelection</value>
      <webElementGuid>bd53256a-3f88-4f72-892b-d323d1bb09d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesos Intransferible - Ajustable  por indice UVA - BPI y C. Movil</value>
      <webElementGuid>1f989c2b-4260-4d96-91ad-4ff2a8a5f6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmFixedTermRatesTables_collapsableCard-98-1683488945590_lblHeaderTitle&quot;)</value>
      <webElementGuid>0f7acc9b-19a7-470e-be28-481fe9e4863a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-98-1683488945590_lblHeaderTitle']</value>
      <webElementGuid>6a3b8342-58d9-4292-a781-9034b3883add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-98-1683488945590_flxHeader']/div/div</value>
      <webElementGuid>32b7e59c-398c-4b4a-8c84-0b0b30bd4d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasta 999 días'])[2]/following::div[123]</value>
      <webElementGuid>fa7495bc-cb1d-4dec-bc33-39ef45cb45da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto hasta ($)'])[6]/following::div[128]</value>
      <webElementGuid>9e5e7772-0af2-44f5-a78c-28c6faf36471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[14]/preceding::div[1]</value>
      <webElementGuid>7e84b5d9-68c9-4cb4-9e7f-5f3732000fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto hasta ($)'])[7]/preceding::div[6]</value>
      <webElementGuid>afb4775a-fead-4e67-86db-85a5d94378c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/div/div/div/div/div/div/div</value>
      <webElementGuid>7fa07014-69ee-441c-9751-3a30876a3837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmFixedTermRatesTables_collapsableCard-98-1683488945590_lblHeaderTitle' and (text() = 'Pesos Intransferible - Ajustable  por indice UVA - BPI y C. Movil' or . = 'Pesos Intransferible - Ajustable  por indice UVA - BPI y C. Movil')]</value>
      <webElementGuid>4b81e335-a993-4c3c-9b28-d3fb9a080c4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
