<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvTasa5</name>
   <tag></tag>
   <elementGuidId>75766b0d-5f20-475e-af80-cc79b3416cda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmFixedTermRatesTables_collapsableCard-32-1683488945482_lblHeaderTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmFixedTermRatesTables_collapsableCard-32-1683488945482_lblHeaderTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c305990f-59cb-499c-86bf-90a159e06f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables_collapsableCard-32-1683488945482_lblHeaderTitle</value>
      <webElementGuid>5618b6b5-f36c-45d6-9b20-0b3985c15baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f9925fce-1904-4f67-8ad2-8e5ccbe4d7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables</value>
      <webElementGuid>dbe54b6a-437c-4429-92a3-0ffdf8a316ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>collapsableCard-32-1683488945482</value>
      <webElementGuid>6db3e46c-c9a5-4900-9f69-faef8de2d399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCardTitleLG cntmiddleleftalign disableSelection</value>
      <webElementGuid>fb7e4095-c36b-4556-b309-24ce69c8c8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesos Intransferible - Tasa  Variable Encuesta BCRA - BPI - C.  Movil y BEE</value>
      <webElementGuid>93acee4f-772b-4580-be4e-98da944de9c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmFixedTermRatesTables_collapsableCard-32-1683488945482_lblHeaderTitle&quot;)</value>
      <webElementGuid>0a1ee398-5c3d-42ca-8735-020427edfd1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-32-1683488945482_lblHeaderTitle']</value>
      <webElementGuid>aed8912a-ba68-4cee-bc23-af122ec9cf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-32-1683488945482_flxHeader']/div/div</value>
      <webElementGuid>01fee82d-8f84-4ce4-b4f5-5bf301dce77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TNA 90'])[3]/following::div[74]</value>
      <webElementGuid>7d34fa27-5732-4d69-bc07-8b321613c48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TNA 60'])[3]/following::div[79]</value>
      <webElementGuid>16cf92e9-703c-489d-aeb4-3d1a28ff333a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[12]/preceding::div[1]</value>
      <webElementGuid>4da6146e-250d-40a1-8bb1-bd444c543176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto hasta ($)'])[5]/preceding::div[6]</value>
      <webElementGuid>ec390c91-89b4-4f4e-9c85-191028a08dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]/div/div/div/div/div/div/div</value>
      <webElementGuid>f517390f-43dc-4673-b484-591a92ff7cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmFixedTermRatesTables_collapsableCard-32-1683488945482_lblHeaderTitle' and (text() = 'Pesos Intransferible - Tasa  Variable Encuesta BCRA - BPI - C.  Movil y BEE' or . = 'Pesos Intransferible - Tasa  Variable Encuesta BCRA - BPI - C.  Movil y BEE')]</value>
      <webElementGuid>9a197195-46df-46ee-b5ec-7e913216fb7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
