<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvCuentaCrdtoCA</name>
   <tag></tag>
   <elementGuidId>87cc114e-9196-4bd3-bcdc-edb8c0d2d589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_lblCreditAccountData2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_ForeignCurrency_lblCreditAccountData2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b183732e-9e94-4572-8353-39b6591e4ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_ForeignCurrency_lblCreditAccountData2</value>
      <webElementGuid>f26eaf61-d074-40bd-a9a5-67f34454ea82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>328fdce9-b40b-41f5-b773-52b36f3ef314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>79b67eef-80db-44fb-9379-b5ddf673333d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ForeignCurrency</value>
      <webElementGuid>23e09218-c0b0-4aaf-a422-7111d8f65a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblPanelProductRowData cntmiddlerightalign disableSelection</value>
      <webElementGuid>803e4788-0663-49cf-acb9-4f121df49e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA $ 119-011835/9</value>
      <webElementGuid>1040df26-e04d-48b8-bfec-ff51778a4e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_ForeignCurrency_lblCreditAccountData2&quot;)</value>
      <webElementGuid>df0db183-6ee5-4726-83cc-e2103460ec01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_lblCreditAccountData2']</value>
      <webElementGuid>4c3c55d1-716a-4e5c-8d68-caa9cc30dfae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_flxCreditAccountContainer2']/div[2]/div</value>
      <webElementGuid>d829e8e1-36f3-4dd1-89b9-89e4cb3a8c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta de crédito'])[1]/following::div[2]</value>
      <webElementGuid>bf238c72-94ba-4e2d-bfb2-7006cc4a0e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto a Acreditar $ 183,51'])[1]/following::div[7]</value>
      <webElementGuid>7bd0a505-7f91-4177-98c2-17bd00ac4ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización'])[4]/preceding::div[1]</value>
      <webElementGuid>d96a4f48-2f82-403c-928e-6a26bb8220cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 183,51'])[2]/preceding::div[3]</value>
      <webElementGuid>c03e1487-ca1b-4bdf-bfde-e67763739efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>6290e16f-2428-4f08-af9d-4d6f2a7dab94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_ForeignCurrency_lblCreditAccountData2' and (text() = 'CA $ 119-011835/9' or . = 'CA $ 119-011835/9')]</value>
      <webElementGuid>8f6dc4ed-dccf-4bf3-988e-90fab9b40fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
