<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtIngresoMonto</name>
   <tag></tag>
   <elementGuidId>9fefdbcd-03ba-4445-bd64-8696291ce2c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_ForeignCurrency_ForeignCurrencyAmountToggle_tbxAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmInvestmentsHomeBccl_ForeignCurrency_ForeignCurrencyAmountToggle_tbxAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca01046d-b201-48a6-b916-aa3989dc8b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_ForeignCurrency_ForeignCurrencyAmountToggle_tbxAmount</value>
      <webElementGuid>f409806d-a942-4c03-b240-815a2147fb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>5a3588e5-902c-46b5-b874-2abd6c32ed47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>8cd64ad2-0e7f-4af7-b2aa-9ebe223c1dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ForeignCurrency_ForeignCurrencyAmountToggle</value>
      <webElementGuid>76dc5dd1-5749-4624-bc7c-03bde13f1a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>$0,00</value>
      <webElementGuid>5c6af1be-f8da-47de-840e-b59382833a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknTxtForeignCurrencyTbxAmount</value>
      <webElementGuid>36eb9916-51b6-470d-916e-6aa6dbefbde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>3c93c395-c818-4dae-91fc-183e0e15ee47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>17af52c4-9009-48c1-8009-990cdeec440a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9f5f044a-b70a-4a13-8509-4f2f1f241b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17e12b2d-5446-490d-a9f8-704c8a6218b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>dd4265c1-d828-4b01-b9e9-49fd8e53f340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>c3c830db-72f2-48ed-9be9-df63f8e21f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>U$S 0,00</value>
      <webElementGuid>0389f03d-aafb-48b0-9da4-38f2bd471627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_ForeignCurrency_ForeignCurrencyAmountToggle_tbxAmount&quot;)</value>
      <webElementGuid>dbae3d28-f5b5-451d-a769-ccf33dc41ce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmInvestmentsHomeBccl_ForeignCurrency_ForeignCurrencyAmountToggle_tbxAmount']</value>
      <webElementGuid>58e4c6b2-263e-4713-a604-706201775fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_ForeignCurrency_ForeignCurrencyAmountToggle_flxInputContainer']/div/input</value>
      <webElementGuid>cbb4f847-0db7-4be9-9654-a646e76c288a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>fc6bd4d4-1b62-49bf-b20d-71e3dd814faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmInvestmentsHomeBccl_ForeignCurrency_ForeignCurrencyAmountToggle_tbxAmount' and @type = 'text' and @placeholder = 'U$S 0,00']</value>
      <webElementGuid>8a7e2a48-ebe9-4942-a2ab-8d242f4bc585</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
