<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvMontoPFDetalle</name>
   <tag></tag>
   <elementGuidId>87b349d4-2490-4a07-a9c1-a07d73ba138d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_DetallePlazoFijo_lblMontoAReembolsarValue1683491896493']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_DetallePlazoFijo_lblMontoAReembolsarValue1683491896493</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6bcb8de-b05b-448d-8fba-6804e100ef0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_DetallePlazoFijo_lblMontoAReembolsarValue1683491896493</value>
      <webElementGuid>f20d0c9d-2a88-4fe0-b513-e263b23009a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9029b1ce-72bc-4c84-a07d-e216fc1ff534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>813566eb-a1da-48f1-b087-81004cec7bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DetallePlazoFijo</value>
      <webElementGuid>a3e53a42-361a-4335-9338-8e58562f18e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoReg14414042  disableSelection</value>
      <webElementGuid>31dd85a7-41d5-4977-b66f-5e576249d226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 1.060,12</value>
      <webElementGuid>960bf16e-1a25-4197-8656-8a37370ae9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_DetallePlazoFijo_lblMontoAReembolsarValue1683491896493&quot;)</value>
      <webElementGuid>a636c67d-1dad-485c-8581-dca6c57f03e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_DetallePlazoFijo_lblMontoAReembolsarValue1683491896493']</value>
      <webElementGuid>fa17af2a-d019-490f-814d-b0546044c79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_DetallePlazoFijo_flxMontoAReembolsar1683491896493']/div[2]/div</value>
      <webElementGuid>e94d6cae-ad6e-4de7-a944-8cb6b7f59209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto a reembolsar'])[2]/following::div[2]</value>
      <webElementGuid>e345dc54-ebc4-41b3-bdf0-290ecc528656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha vencimiento'])[1]/following::div[9]</value>
      <webElementGuid>316c3968-723d-4d9f-bbde-15b4067e7d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interés'])[1]/preceding::div[1]</value>
      <webElementGuid>ad2c1841-92a4-4aa3-9fb8-da0c5d95f991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 60,12'])[1]/preceding::div[3]</value>
      <webElementGuid>70a82625-cfa5-4f8f-ae0c-3aee3fdf63ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div/div/div[2]/div</value>
      <webElementGuid>6c0358c8-b509-442f-b7fe-4b9bfd589a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_DetallePlazoFijo_lblMontoAReembolsarValue1683491896493' and (text() = '$ 1.060,12' or . = '$ 1.060,12')]</value>
      <webElementGuid>10bcda0c-b64e-4dc5-91e7-2c426fe5bcc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
