<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvPFFechaVencimSimulacion</name>
   <tag></tag>
   <elementGuidId>8525a59c-cd58-4f05-a7a3-5deda600fe11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmSimulateFixedTerm_SimulateResults_lblFechaVencimiento']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmSimulateFixedTerm_SimulateResults_lblFechaVencimiento</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48993f67-f0d3-4fea-912b-1a9aa5ba2b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmSimulateFixedTerm_SimulateResults_lblFechaVencimiento</value>
      <webElementGuid>223842f3-4d1a-42ad-bdc2-917a6380539f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>3b1b8d88-0727-4aae-b16d-69ee04374963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmSimulateFixedTerm</value>
      <webElementGuid>b25131c1-6e23-44ae-84e3-a5adc4e647d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>SimulateResults</value>
      <webElementGuid>a6e279fd-2768-466f-a1f2-38aebadc5e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1466 cntmiddleleftalign disableSelection</value>
      <webElementGuid>1c478470-76c5-4893-8180-fc2bf442e634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22 Feb 2023</value>
      <webElementGuid>811d21dc-ccff-4a72-b72c-15df63d26550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSimulateFixedTerm_SimulateResults_lblFechaVencimiento&quot;)</value>
      <webElementGuid>d9897b53-cec0-4535-89eb-71082e50fc80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmSimulateFixedTerm_SimulateResults_lblFechaVencimiento']</value>
      <webElementGuid>507e88e2-e79f-491f-b20c-60961dde7b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmSimulateFixedTerm_SimulateResults_flxRow8']/div[2]/div</value>
      <webElementGuid>169f0bc2-d146-4a29-82cb-ecad120ed211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de vencimiento'])[1]/following::div[2]</value>
      <webElementGuid>51abfcdc-4aef-41aa-8eb5-eb28570ff63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de emisión'])[1]/following::div[9]</value>
      <webElementGuid>af200936-66be-415b-bb23-79dc9a75be80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Períodos'])[1]/preceding::div[1]</value>
      <webElementGuid>a6aaa06d-45e9-4b5c-97d5-2633a646ec9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T.N.A./Tasa fija adicional(*)'])[1]/preceding::div[8]</value>
      <webElementGuid>44c45b6e-1448-4d34-bdc7-d2463c056c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='22 Feb 2023']/parent::*</value>
      <webElementGuid>44e3824d-cb99-4396-b3fc-05a9d6ca371c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[5]/div/div/div[2]/div</value>
      <webElementGuid>bb40453e-f13c-45c6-bb62-9bbf11ac1cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmSimulateFixedTerm_SimulateResults_lblFechaVencimiento' and (text() = '22 Feb 2023' or . = '22 Feb 2023')]</value>
      <webElementGuid>ed0d6b4a-7ceb-4409-976b-2cc2aa5560a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
