<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvTasa4</name>
   <tag></tag>
   <elementGuidId>a8ae8d25-640b-4761-b72d-09e8750e57d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmFixedTermRatesTables_collapsableCard-31-1683488945439_lblHeaderTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmFixedTermRatesTables_collapsableCard-31-1683488945439_lblHeaderTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7346da0d-62c8-4c38-88ec-e4f4f5d061ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables_collapsableCard-31-1683488945439_lblHeaderTitle</value>
      <webElementGuid>a911aa3a-129a-4df9-b2bb-e1378a1f55b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>b3172ca4-bf14-413c-a2a5-97d3eb49077b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmFixedTermRatesTables</value>
      <webElementGuid>401ff05f-3bc5-4479-a675-0db3dd6aba3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>collapsableCard-31-1683488945439</value>
      <webElementGuid>0ab61ddd-8245-4e55-960a-691f9641415c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCardTitleLG cntmiddleleftalign disableSelection</value>
      <webElementGuid>169a0338-78e6-4070-aa7d-083eb4ebd782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pesos Intransferible - Pago  Periodico de Intereses - BPI - C.  Movil y BEE</value>
      <webElementGuid>18dd93f2-be81-4616-a6da-1fc8f160a56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmFixedTermRatesTables_collapsableCard-31-1683488945439_lblHeaderTitle&quot;)</value>
      <webElementGuid>4e0933a5-4d1b-4bd6-987a-b85f76a55ddd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-31-1683488945439_lblHeaderTitle']</value>
      <webElementGuid>b77b0318-7c41-4a96-ab33-c580c6914312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmFixedTermRatesTables_collapsableCard-31-1683488945439_flxHeader']/div/div</value>
      <webElementGuid>001c4421-1792-4d3d-af38-1cd2f908f29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasa'])[1]/following::div[75]</value>
      <webElementGuid>2613532d-fb0d-4180-ad76-64f6e7ca5eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plazo hasta'])[1]/following::div[80]</value>
      <webElementGuid>906ef653-7190-4d15-a0b6-ea2561996c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[11]/preceding::div[1]</value>
      <webElementGuid>1263fa54-2984-4ac3-9103-5f86dcbd56ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto hasta ($)'])[4]/preceding::div[6]</value>
      <webElementGuid>496012f9-6a8d-414f-b0f0-a6f1804f823b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div[2]/div/div/div[4]/div/div/div/div/div/div/div</value>
      <webElementGuid>5587b051-a19c-41b4-937e-efb6c73a1a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmFixedTermRatesTables_collapsableCard-31-1683488945439_lblHeaderTitle' and (text() = 'Pesos Intransferible - Pago  Periodico de Intereses - BPI - C.  Movil y BEE' or . = 'Pesos Intransferible - Pago  Periodico de Intereses - BPI - C.  Movil y BEE')]</value>
      <webElementGuid>c9bc65e0-b57e-401b-9096-891d58a4ee78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
