<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvFechaVencimientoPFListado</name>
   <tag></tag>
   <elementGuidId>2cebaa95-836e-4375-9db3-d7aeb07755d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxFixedTermRow_lblFixedTermExpirationDate'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0be958ac-c540-4f06-bea6-21df5dc9dc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxFixedTermRow_lblFixedTermExpirationDate</value>
      <webElementGuid>3b01868a-8df6-4809-9c64-14146310576f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>a6409c95-42d5-44d8-a900-c8699ad87a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxFixedTermRow</value>
      <webElementGuid>91da35bf-b345-48c3-a73c-817da42cf89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segFixedTerm</value>
      <webElementGuid>ab2cb794-0e86-4d8c-9368-1a0bd5d0170c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>B908648C-1BE3-4CAB-80C7-59C17E1B16D4</value>
      <webElementGuid>dfbd3e14-9274-4176-8caa-d41d644f93f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableDate cntmiddlecenteralign disableSelection</value>
      <webElementGuid>54baab85-9e73-49d4-bb3a-fa0b90edf7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22 Feb 2023</value>
      <webElementGuid>ef77887f-5c53-4196-a10c-7612f0f26885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_FixedTerm_segFixedTerm&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxFixedTermRow_flxFixedTermRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxFixedTermRow_flxFixedTermRowInner&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableDate&quot;]/div[@id=&quot;flxFixedTermRow_lblFixedTermExpirationDate&quot;]</value>
      <webElementGuid>3c2fa471-aedf-4583-afb1-2c13451767f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxFixedTermRow_lblFixedTermExpirationDate'])[2]</value>
      <webElementGuid>24c97189-87cd-4bc0-b7de-cc1e54704a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxFixedTermRow_flxFixedTermRowInner']/div[3]/div)[2]</value>
      <webElementGuid>148a0097-d248-4077-89a3-2ffdf487eda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plazo Fijo'])[1]/following::div[4]</value>
      <webElementGuid>ab979069-657c-412d-9e72-c047a964bbd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 1.060,12'])[1]/preceding::div[1]</value>
      <webElementGuid>c9963f47-7a84-43f9-9c55-efdece2ce46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba marula'])[1]/preceding::div[3]</value>
      <webElementGuid>1cedef8b-e7fb-4031-b267-b18ca152835a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='22 Feb 2023']/parent::*</value>
      <webElementGuid>634c8389-54d8-4160-89b2-f849cccacccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/div/div[3]/div</value>
      <webElementGuid>d0fdfd17-e135-444d-9096-b976ef3e0871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxFixedTermRow_lblFixedTermExpirationDate' and (text() = '22 Feb 2023' or . = '22 Feb 2023')]</value>
      <webElementGuid>a7230cc4-6d19-4cf1-b5e7-c0000425f855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
