<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvPFDiasSimulado</name>
   <tag></tag>
   <elementGuidId>f88dabb0-d830-49da-b7b5-a5df58cc89d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmSimulateFixedTerm_SimulateResults_lblTerm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmSimulateFixedTerm_SimulateResults_lblTerm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3335e2fd-af2e-4205-8a2d-eb91eb746e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmSimulateFixedTerm_SimulateResults_lblTerm</value>
      <webElementGuid>7ab276df-c882-4259-9602-6a09a1afef5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0918d693-aae0-4ec7-a6ed-45e40f56adf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmSimulateFixedTerm</value>
      <webElementGuid>0ee40057-cff1-4f2b-bf19-0a3eb16c4b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>SimulateResults</value>
      <webElementGuid>88b06b19-84ee-4c73-aafa-9fbfd5f9448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1466 cntmiddleleftalign disableSelection</value>
      <webElementGuid>569dba44-2ee1-4d5f-a121-b4049dbe6745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>30 días</value>
      <webElementGuid>f0cd30cb-8cb5-4c3e-9af7-3ab03ee0186c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSimulateFixedTerm_SimulateResults_lblTerm&quot;)</value>
      <webElementGuid>d3c7cef0-684b-4226-bfb0-18c5168f8e6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmSimulateFixedTerm_SimulateResults_lblTerm']</value>
      <webElementGuid>72052ca0-d644-4d99-9d7c-405757921554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmSimulateFixedTerm_SimulateResults_flxRow3']/div[2]/div</value>
      <webElementGuid>779f0268-dec4-4d87-985d-ea536f55f407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plazo'])[1]/following::div[2]</value>
      <webElementGuid>fbfda535-e8ff-400f-8a41-07e8133eb3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de emisión'])[1]/preceding::div[1]</value>
      <webElementGuid>d519ceda-03e1-4ab7-8ec2-2ed35dea9319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de vencimiento'])[1]/preceding::div[8]</value>
      <webElementGuid>20754920-4fac-486b-8b97-79e669c8de2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>b8fa1329-4a3f-4081-9c61-cada0aacae4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmSimulateFixedTerm_SimulateResults_lblTerm' and (text() = '30 días' or . = '30 días')]</value>
      <webElementGuid>a47b7e98-4d22-4351-9f60-49ae712e83f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
