<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNombrePlazoFijoDetalle</name>
   <tag></tag>
   <elementGuidId>4df0644e-21da-40da-809b-7334a6e796e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_DetallePlazoFijo_EditableLabelNameFixedTerm_lblEditableLabel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_DetallePlazoFijo_EditableLabelNameFixedTerm_lblEditableLabel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9f42726-3049-4010-862c-29ddb473b9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_DetallePlazoFijo_EditableLabelNameFixedTerm_lblEditableLabel</value>
      <webElementGuid>215726c9-0dc0-49f4-8b83-531f550a3fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9a40672b-728b-407e-9db1-81ff2c0a59c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>554264ae-9fd1-4012-a87f-0a3e205e48d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DetallePlazoFijo_EditableLabelNameFixedTerm</value>
      <webElementGuid>59e0653a-e661-4f77-a34b-3d9498374592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold14ff cntmiddleleftalign disableSelection</value>
      <webElementGuid>2e1d5e4f-01f9-423d-b475-4a73a947513a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plazo Fijo</value>
      <webElementGuid>de1d8ffa-6b07-4e4d-a3d0-2c38a41b1b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_DetallePlazoFijo_EditableLabelNameFixedTerm_lblEditableLabel&quot;)</value>
      <webElementGuid>c4a97e0c-6bbd-4c6e-a0d6-31205dabe514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_DetallePlazoFijo_EditableLabelNameFixedTerm_lblEditableLabel']</value>
      <webElementGuid>e26c25a3-8b04-4836-b96e-68fb3c9b8233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_DetallePlazoFijo_EditableLabelNameFixedTerm_flxLabel']/div/div</value>
      <webElementGuid>6e43d59c-cf97-4a81-a371-7aed8458ee72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[19]/following::div[8]</value>
      <webElementGuid>e51d5b79-fcec-40a7-9a0d-3cfddc2b59a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[19]</value>
      <webElementGuid>d66b37b6-fc53-449f-98b8-210a9c970131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>163003db-65d1-4155-920d-0b7fafb1c8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[7]</value>
      <webElementGuid>73c372dd-6255-469a-9bc7-b15f50f905ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>926b88bc-c1fd-4b1d-9895-b49e0f6cda6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_DetallePlazoFijo_EditableLabelNameFixedTerm_lblEditableLabel' and (text() = 'Plazo Fijo' or . = 'Plazo Fijo')]</value>
      <webElementGuid>67de347d-565c-4b3b-bbf0-7893c765ec58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
