<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnConfirmarTrxOtrosBancos</name>
   <tag></tag>
   <elementGuidId>b38a3b1e-e750-4a63-ad5f-3a9c30d9129d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_ConfirmTransfer_btnConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclConfirmTransfer_ConfirmTransfer_btnConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0fd54ea-03aa-4e64-bc85-105ad39454f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_ConfirmTransfer_btnConfirm</value>
      <webElementGuid>17d31e04-cf0b-41dc-9545-d8075ab5e231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>fa7f3cef-8825-41d2-97b5-907efbd88f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>d2d79b29-edc4-44f9-8029-5f8f0df07648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConfirmTransfer</value>
      <webElementGuid>3f766153-ca94-4970-aaf0-66299b6bfc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca426b27-5ef2-4283-ab54-db6fbc3d127e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>29c26158-6011-4c47-8bb7-e97b6c0078a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>7b90a4b2-0fed-4746-9be7-e017a46aae11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>53893cc0-abf2-4e56-b4d5-bc7c64b3d8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_ConfirmTransfer_btnConfirm&quot;)</value>
      <webElementGuid>ee3f91f6-6e34-4264-b18b-58b87e219897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclConfirmTransfer_ConfirmTransfer_btnConfirm']</value>
      <webElementGuid>91eb3a79-7e44-4aca-99fa-3e2de347fd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_ConfirmTransfer_flxContainerButtons']/div[2]/input</value>
      <webElementGuid>a329eee1-b1da-4cc6-9e83-380d4257a379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>ea95319a-c991-4dd6-b90a-0e91cd37b50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclConfirmTransfer_ConfirmTransfer_btnConfirm' and @type = 'button']</value>
      <webElementGuid>e13a6089-b511-4e60-8ae7-da8d4fc1d075</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
