<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnContinuarAlias</name>
   <tag></tag>
   <elementGuidId>eb9e2110-6160-4c48-857b-649ae7fb5626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_NewBeneficiary_btnContinuar_btnWithLoader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_btnContinuar_btnWithLoader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>496e1574-709d-4b96-a350-a6eccd8c02ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>f5ea1d96-a0ec-45db-a1d6-bdcc3765fcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_NewBeneficiary_btnContinuar_btnWithLoader-hint</value>
      <webElementGuid>617ac8a3-fb2b-402f-bfab-80012b28d9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_NewBeneficiary_btnContinuar_btnWithLoader</value>
      <webElementGuid>de54e956-e0ec-45dd-8009-4dec2f4cfb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>953f771d-b43e-4047-bca7-31d3a4b4e550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>0ac4ce21-4861-417f-be43-7dd1fe934300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>NewBeneficiary_btnContinuar</value>
      <webElementGuid>ff6840ab-51b3-46e1-abd1-ed664024a1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e88afa70-979d-45e0-b81c-7d4cc344bb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>8bc5061a-be9b-41c3-99c5-1301e0a525db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>9e87f0eb-4658-4469-a41c-c0c8ebb304c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>6d3c1273-c721-4918-aa35-e503935f36d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_NewBeneficiary_btnContinuar_btnWithLoader&quot;)</value>
      <webElementGuid>cefc1251-b4dd-450e-a4ef-70b8659bc82f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_btnContinuar_btnWithLoader']</value>
      <webElementGuid>beb0090e-f25f-4e4e-bebf-47be7a1e86eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_btnContinuar']/div/input</value>
      <webElementGuid>b2671019-fef1-4f1e-aacf-52b2b7fb7677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>48b77e5c-50fc-4f18-8dbb-2a7b1473b3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclBeneficiaryAgenda_NewBeneficiary_btnContinuar_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>fc5659c2-12c8-4556-9069-37bc219ead7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
