<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTrxJudicialVerComprobanteExito</name>
   <tag></tag>
   <elementGuidId>cbda1c42-ac96-48fb-8563-389863c752a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclConfirmTransfer_TransferMessage_ButtonSecondaryWithLoader_btnWithLoader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_TransferMessage_ButtonSecondaryWithLoader_btnWithLoader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7799243-1b8f-4586-a3a9-8ab02449345a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>6967416a-f642-45c6-8360-1fbe584ba44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_TransferMessage_ButtonSecondaryWithLoader_btnWithLoader-hint</value>
      <webElementGuid>bb5ed5d8-7f43-45b6-9845-5a997b540a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_TransferMessage_ButtonSecondaryWithLoader_btnWithLoader</value>
      <webElementGuid>89f95fe5-236a-40d2-a121-426ea8df60d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>d7bbfeaf-1e23-4784-a203-d27be47bf00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>59728f9e-9595-473b-ab3b-e9386592dc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferMessage_ButtonSecondaryWithLoader</value>
      <webElementGuid>8f592ab3-d418-45ef-8b9a-62493eaebe0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a274cfe-e078-46ab-abeb-21ebf1c9ceb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnSecondaryLoader disableSelection</value>
      <webElementGuid>dc4e2284-d614-409a-b79e-a58972dd4d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ver comprobante</value>
      <webElementGuid>bc9cd085-154e-4c23-a053-974de1e4cade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnSecondaryLoader</value>
      <webElementGuid>02821a94-3e98-4386-90c2-34bd0116c97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_TransferMessage_ButtonSecondaryWithLoader_btnWithLoader&quot;)</value>
      <webElementGuid>0e0f07b6-b541-4223-ba9f-8adbce2de335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclConfirmTransfer_TransferMessage_ButtonSecondaryWithLoader_btnWithLoader']</value>
      <webElementGuid>08188e50-7dcc-449b-8b3e-26286f93f083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_ButtonSecondaryWithLoader']/div/input</value>
      <webElementGuid>b27085c8-574e-4492-9d80-0f8e58c2778f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/input</value>
      <webElementGuid>aaa77ed0-151d-4ad6-a4ac-fc0730f555bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclConfirmTransfer_TransferMessage_ButtonSecondaryWithLoader_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>a775c79b-3cc4-49fe-abc8-7aedc51ec7d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
