<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTrxEliminar</name>
   <tag></tag>
   <elementGuidId>fa93bb40-3850-4dfe-bd0f-13a1d47cc2cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclTransfers_DeleteSentTransfer_btnContinue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclTransfers_DeleteSentTransfer_btnContinue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07b99e26-8024-4c88-940c-fbc1f0104476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclTransfers_DeleteSentTransfer_btnContinue</value>
      <webElementGuid>365a2915-62e8-4474-8e42-41531d2d5000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>9d508aa3-0f5e-4c98-8692-c5bd7abca558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>b8b47aad-de08-452d-bd92-6d400bf8163e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DeleteSentTransfer</value>
      <webElementGuid>04800df8-8807-461b-9606-46b87fdfdab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>035afe2e-9037-469a-bf2f-5a9d8fd7c9cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimaryBold disableSelection</value>
      <webElementGuid>411aa85f-245d-44b8-912d-b3a7a433e4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Eliminar Operación</value>
      <webElementGuid>9f0cfbde-66a9-448f-9edf-9000e752f0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimaryBold</value>
      <webElementGuid>84557975-cb00-400b-8906-d0db3d54ca21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_DeleteSentTransfer_btnContinue&quot;)</value>
      <webElementGuid>f4718fa2-6258-4e69-8519-cae3344e475f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclTransfers_DeleteSentTransfer_btnContinue']</value>
      <webElementGuid>f466c54a-d32d-4979-83aa-3404dc9261e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_DeleteSentTransfer_flxButtonsStep1']/div[2]/input</value>
      <webElementGuid>10edcc1d-8ebd-4fe1-aa88-7d5f8c9ab209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[4]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>8c9e4693-d208-436d-b350-2c26b7053f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclTransfers_DeleteSentTransfer_btnContinue' and @type = 'button']</value>
      <webElementGuid>dee5e677-37c6-41dc-b45f-f1a1ffc2cb6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
