<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTrxJudicialVolverTrxComprobante</name>
   <tag></tag>
   <elementGuidId>02d04211-ec65-4ed7-89e2-af1582b1ec50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclConfirmTransfer_Receipt_btnBack']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_Receipt_btnBack</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c674b94-1a0a-4540-8711-4f7f15abdee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_Receipt_btnBack</value>
      <webElementGuid>57c51cae-5a47-499b-8eb1-1e470c57b963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>2b424f54-31d8-4545-8f8e-6877155c765e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>c9559c9c-5f7b-4e3a-83a1-985a0ddd53f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Receipt</value>
      <webElementGuid>cac7bc92-0814-4349-8709-cd200e74e250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04794c56-a51d-47da-aaaa-0052eb27bcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>5336fd02-c14e-418f-86bf-4a265b48d6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Volver a transferencias</value>
      <webElementGuid>50d94b04-e986-4fd5-998b-05f489a70860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>0a86643f-eb23-49cf-8a57-b6b551c328b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_Receipt_btnBack&quot;)</value>
      <webElementGuid>c338a43f-17d9-43ec-9118-0484f286035f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclConfirmTransfer_Receipt_btnBack']</value>
      <webElementGuid>bf7a610c-fa2e-4eb6-9a6d-f4fa321612bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_Receipt_flxButtonsContainer']/div[2]/input</value>
      <webElementGuid>6f08e167-f36b-4014-9c60-df10e72593f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>60144877-011d-47cb-8a64-897ae255808b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclConfirmTransfer_Receipt_btnBack' and @type = 'button']</value>
      <webElementGuid>278b6bc0-4f27-4b85-8358-6cca4654c3ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
