<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxDiaPosdatada</name>
   <tag></tag>
   <elementGuidId>848cf697-6ccb-4c3b-8c95-0b78e0780947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-kony-w-c-cell-25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-kony-w-c-cell-25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5b499fb-2c1d-4fbf-afcf-bb4cf2a90038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>cda9353a-e335-4bbb-a8f5-04480f4d00f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferHistory_DateFilter</value>
      <webElementGuid>d1306c70-e8d9-408a-a5df-83dc87d3cdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>a1d1d6c2-ede2-4013-9d00-a99858be1c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-k-w-c-weekday-3 -kony-w-c-day- sknCalendar</value>
      <webElementGuid>59b436de-b4ba-4a39-84f7-beccb9ab3593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-kony-w-c-cell-25</value>
      <webElementGuid>32280043-f47f-4265-9410-948260802243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmBcclTransfers_TransferHistory_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>a6c8c7d6-b29e-4b7c-a3f6-a6d0060fdbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weekday</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3c4e3e7b-8fb5-4614-a16d-98da465f7549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-hold-day</name>
      <type>Main</type>
      <value>17,05,2023</value>
      <webElementGuid>b595a9be-dea3-4cb4-8fc7-b28bc1abd7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-date-retrieve</name>
      <type>Main</type>
      <value>17,05,2023</value>
      <webElementGuid>45e0e620-cb1e-4861-8f8e-e50dabde3a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>04a41897-3a4e-448f-8d68-be67cdc0b8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value> 17th May 2023</value>
      <webElementGuid>945ba9a7-bfb1-40c9-bb31-a5e6bf077d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>138ac15d-c938-40ee-9c88-58e14a57cea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-kony-w-c-cell-25&quot;)</value>
      <webElementGuid>9c83a7d5-53c7-44b6-a8b3-f8f06beb41dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='-kony-w-c-cell-25']</value>
      <webElementGuid>7ce1f5ea-d58e-4360-bbd8-bf0e065ad976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-05-2023']/div[2]/div[3]/div/div[4]</value>
      <webElementGuid>5100908e-1487-4d9a-8dc6-9f5ea4dfda96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sáb'])[1]/following::div[25]</value>
      <webElementGuid>3b827948-e6a4-4007-9ddd-cb68008299b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vie'])[1]/following::div[26]</value>
      <webElementGuid>1d73cc10-11fc-40f1-80c8-6700df632137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[33]</value>
      <webElementGuid>0dfdbfdb-70d3-40d8-bc96-791e1a0d5590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[35]</value>
      <webElementGuid>8fe79551-149a-4f1c-ace3-428f9f92bc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='17']/parent::*</value>
      <webElementGuid>f34bfbad-79af-4528-a43a-f7f2b8b6e0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]</value>
      <webElementGuid>d5e84a66-4645-4d2a-bef0-abb1f0e178ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '-kony-w-c-cell-25' and (text() = '17' or . = '17')]</value>
      <webElementGuid>a1baf4d8-a39b-4a2f-9755-d6f54664bf50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
