<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxEliminar</name>
   <tag></tag>
   <elementGuidId>d049fbcf-3749-479a-aae0-094e5a6f2bb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxSentRow_lblTrashIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxSentRow_lblTrashIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>494f0f02-2923-49f8-a1d2-efce6463c7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxSentRow_lblTrashIcon</value>
      <webElementGuid>7022b8ae-1411-40c3-9604-6d8a426152af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>8edda155-16a0-478e-bdaf-0561a2d9df2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxSentRow</value>
      <webElementGuid>4568cc74-3be4-48af-bcd7-73187669d7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segSent</value>
      <webElementGuid>0d0cba19-9969-4d09-b67e-cf15b02a089f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>18A673F1-6EA7-4CFC-B6EC-0215A69E70A5</value>
      <webElementGuid>1f80c5d9-fd5b-4e52-95c4-c3cf293bf030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTrashIcon cntmiddlecenteralign disableSelection</value>
      <webElementGuid>081b4298-ebb8-43dd-8691-52b2c73fc82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2a4d98be-6d22-464b-b200-157ddfce598e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flxSentRow_lblTrashIcon&quot;)</value>
      <webElementGuid>3beb2e5a-76be-44eb-aebf-5d0cc95e68eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxSentRow_lblTrashIcon']</value>
      <webElementGuid>5d030e0f-34a9-4d81-a7b0-6f27b60c7999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxSentRow_flxTrashIcon']/div/div</value>
      <webElementGuid>bda4da30-8d60-4b0a-9940-ae407c7d7fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[5]</value>
      <webElementGuid>3622322a-2d2b-4657-bc45-1d183710741e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 1,00'])[1]/following::div[16]</value>
      <webElementGuid>14e7ff2e-cbad-45a2-b626-6b2a7770ec24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultados por página'])[2]/preceding::div[1]</value>
      <webElementGuid>9990e01e-5f6a-4d16-a16e-eb00831cb5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[5]/preceding::div[5]</value>
      <webElementGuid>7a817ad8-7f9d-4a31-a57a-b11ac24bfa06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>419a9201-de3e-45d6-8480-253289207f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>f67ec1d9-a10f-4aed-8812-5a8c268fd210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxSentRow_lblTrashIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>7ed15d53-5dbf-420e-93db-d174f7606185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
