<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxProgramadasEliminar</name>
   <tag></tag>
   <elementGuidId>2c77e011-4c28-473f-97db-f2c758637e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxPostdatedRow_lblTrashIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxPostdatedRow_lblTrashIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7f97085-2716-4836-bf44-a739807d1bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxPostdatedRow_lblTrashIcon</value>
      <webElementGuid>146859d3-6d4d-44e8-ba37-7c219d1f26d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>24406385-3354-40fd-8069-d0eebd15e251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxPostdatedRow</value>
      <webElementGuid>f0e4bc90-7d99-480e-b11d-e14aedcb19c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segPostdated</value>
      <webElementGuid>b42d553e-5f1e-4eaa-9b91-b99ce9d49021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>A6450D8E-F6CF-48E3-B8D6-521D6E0CC101</value>
      <webElementGuid>15cbca54-33d2-4ee7-abf4-d40477a94e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTrashIcon cntmiddlecenteralign disableSelection</value>
      <webElementGuid>461a306a-c87f-4ecd-8d79-7c0e40cc8330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>18a2563d-9c8d-4abb-a83b-c6cb1a21f253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_TransferHistory_segPostdated&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxPostdatedRow_flxPostdatedRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxPostdatedRow_flxTrashIcon&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTrashIcon&quot;]/div[@id=&quot;flxPostdatedRow_lblTrashIcon&quot;]</value>
      <webElementGuid>a58212b8-1f65-41ab-b181-d67f2641ebb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxPostdatedRow_lblTrashIcon']</value>
      <webElementGuid>97129245-6af8-425e-abc9-56a126a3e449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxPostdatedRow_flxTrashIcon']/div/div</value>
      <webElementGuid>17f3778c-e181-40ed-8482-7144fc5a82f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 0,50'])[1]/following::div[5]</value>
      <webElementGuid>c5b7b003-aa68-4e3f-98e2-b91a2e4959b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cristinaaa Arjones'])[2]/following::div[14]</value>
      <webElementGuid>25f64dbe-5ba2-4745-80b5-b7679b5cd9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia Judicial'])[2]/preceding::div[6]</value>
      <webElementGuid>bc80ed36-d9a0-46b8-a8c6-a1ddf0708b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 119-011835/9'])[1]/preceding::div[8]</value>
      <webElementGuid>a22fc759-02e0-4661-82aa-29e69e31fbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>ed4550a6-5c30-4381-86ac-7a1af924dca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[7]/div/div/div/div</value>
      <webElementGuid>21f88ce1-1b18-4637-916b-cc2054329f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxPostdatedRow_lblTrashIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>c15555b6-df60-4e9d-becb-58c7657d0df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
