<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrxSeleccionTitularidadFormulario</name>
   <tag></tag>
   <elementGuidId>35550c68-cbed-45d4-8030-aac939ea6d0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_DropDownOwnership_lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_DropDownOwnership_lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b0704e8-9d37-47a4-9ab4-1eaaad2b5b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_DropDownOwnership_lblOptionTitle</value>
      <webElementGuid>47ad186c-2771-425f-a27a-1c6e9bc56910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>4352a450-6b2e-4d07-8b48-cf4a8d5a86a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>8fc21bf2-938f-45a3-8308-eaed8135f085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DropDownOwnership</value>
      <webElementGuid>54feaee8-8d4b-4223-8071-bafbd4d7f349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDownDisabled cntmiddleleftalign</value>
      <webElementGuid>5b0fe520-7267-40ac-88be-8da62c132676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccioná una opción</value>
      <webElementGuid>52edbbf6-7403-42e9-8a17-8a5de97f5071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_DropDownOwnership_lblOptionTitle&quot;)</value>
      <webElementGuid>05730b9f-d510-4885-84e2-7d5d673c3fe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_DropDownOwnership_lblOptionTitle']</value>
      <webElementGuid>dd7c9cbd-2271-4b9c-8789-35fc3d8007f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_DropDownOwnership_flxOptionInfo']/div/div</value>
      <webElementGuid>3baa87a3-78e8-4d44-89a5-b607add7a870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titularidad de la cuenta'])[1]/following::div[11]</value>
      <webElementGuid>8d67fa1a-76fd-4adb-9f00-a6b2dc92e65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[16]</value>
      <webElementGuid>ab1ec900-b6bc-402d-8ff2-92d40a1b46c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[7]/preceding::div[1]</value>
      <webElementGuid>b5952e0f-6ee8-483f-b640-e70b257f9c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccioná una opción'])[2]/preceding::div[3]</value>
      <webElementGuid>edeb22fd-cb00-4a26-a646-1d8a416e240e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Seleccioná una opción']/parent::*</value>
      <webElementGuid>8e21e18a-8843-4bd1-8038-fbcee4040064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>5d51613f-f588-4cad-89fa-24279e9deda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_DropDownOwnership_lblOptionTitle' and (text() = 'Seleccioná una opción' or . = 'Seleccioná una opción')]</value>
      <webElementGuid>c1757b9b-bdd3-45b7-8a91-5efe43b54489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
