<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrxAgendaBeneficiariosTitulo</name>
   <tag></tag>
   <elementGuidId>8210375c-4472-448b-a9c0-52981a950dd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_lblBeneficiaryAgendaTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_lblBeneficiaryAgendaTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>536bbf7e-37ee-41a6-9c4c-8013f763a804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_lblBeneficiaryAgendaTitle</value>
      <webElementGuid>f31f6f06-ba42-40e5-91a1-798c6ff5f84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>c5606840-c03f-4255-8094-9df210f36e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>dc158cd9-aa8e-4544-a707-1fe69cdc3e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSectionTitle cntmiddleleftalign disableSelection</value>
      <webElementGuid>1026bbc2-2053-4c99-b73d-b00c074262e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agenda de beneficiarios</value>
      <webElementGuid>4cfed5a7-0ced-4eac-9ad0-4df20fff61ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_lblBeneficiaryAgendaTitle&quot;)</value>
      <webElementGuid>1c687f9a-23ce-46b2-bad9-47a27b9b7620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_lblBeneficiaryAgendaTitle']</value>
      <webElementGuid>3d8d30ca-e042-4cca-a75c-bf24fb867d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_flxLeftContainer']/div[2]/div</value>
      <webElementGuid>ea8f8326-fd5a-4bb9-8f66-5da6c19e546c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[2]</value>
      <webElementGuid>a6671953-d42f-4751-90d6-58c5638080ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis cuentas'])[1]/following::div[39]</value>
      <webElementGuid>0125f847-d444-4d6c-8ee4-a91a10fce616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>b5981524-a3b0-4811-b597-116bc025ff24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[6]</value>
      <webElementGuid>c395fc29-6c93-4048-bfd8-98cc6fa0ab3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agenda de beneficiarios']/parent::*</value>
      <webElementGuid>6f2b5201-59a6-49a4-806f-8e19ba6ae229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>1b9888a9-6dae-4998-8708-a90cd860f703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_lblBeneficiaryAgendaTitle' and (text() = 'Agenda de beneficiarios' or . = 'Agenda de beneficiarios')]</value>
      <webElementGuid>029d0bfc-f393-425d-8745-53d9785c9a7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
