<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrfAgendaBenfCBUSinResultado</name>
   <tag></tag>
   <elementGuidId>6263118f-e25d-47ff-92dd-cbe958268c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer&quot;)[count(. | //*[@id = 'frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer' and (text() = 'La búsqueda no obtuvo resultados.No se encontraron beneficiarios para el/los criterio/s solicitado/s.' or . = 'La búsqueda no obtuvo resultados.No se encontraron beneficiarios para el/los criterio/s solicitado/s.')]) = count(//*[@id = 'frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer' and (text() = 'La búsqueda no obtuvo resultados.No se encontraron beneficiarios para el/los criterio/s solicitado/s.' or . = 'La búsqueda no obtuvo resultados.No se encontraron beneficiarios para el/los criterio/s solicitado/s.')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f19f639-5249-43ef-8687-d948f8024050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>24424092-f406-431c-83d9-a4f94a73b539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer</value>
      <webElementGuid>e01521fc-85c2-486c-8573-199846f03559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>19ce38ad-2ed2-43f2-b91c-ee510d287c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>8690f2f4-ad86-4663-ae7d-b95f6561e5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>NoResultsSearch</value>
      <webElementGuid>f472d9b0-f7b7-4639-bd11-60438562953a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>La búsqueda no obtuvo resultados.No se encontraron beneficiarios para el/los criterio/s solicitado/s.</value>
      <webElementGuid>85b017d6-8800-4765-b737-38d0dddfe443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer&quot;)</value>
      <webElementGuid>a296da2d-fb4c-4dcf-a778-c8f57300576c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer']</value>
      <webElementGuid>ec2aff0c-a112-4a42-9c9d-19b946bc7198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[246]</value>
      <webElementGuid>78e428f9-3603-4cd9-a046-942d8e69df60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[3]/following::div[10]</value>
      <webElementGuid>79ce5c01-0c7b-4774-956e-18f91b8154b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No existen beneficiarios dados de alta.'])[1]/following::div[12]</value>
      <webElementGuid>91910ccb-186c-4415-be10-6870703d8aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[6]/div/div/div[2]/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>ef989642-e799-4257-a864-e9db2cc59f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_NoResultsSearch_flxMessageContainer' and (text() = 'La búsqueda no obtuvo resultados.No se encontraron beneficiarios para el/los criterio/s solicitado/s.' or . = 'La búsqueda no obtuvo resultados.No se encontraron beneficiarios para el/los criterio/s solicitado/s.')]</value>
      <webElementGuid>7dc336e8-228f-41bf-98ed-ff8b8d8d1a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
