<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkTrfCuentaBenefTercerosPesos</name>
   <tag></tag>
   <elementGuidId>d1a1ea4b-a110-403f-a163-9680486528e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclBeneficiaryAgenda_segBeneficiaries&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiariesRow&quot;]/div[@class=&quot;kcell middlecenteralignsknFlxCursorPointer&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiaryNameCbu&quot;]/div[@class=&quot;kcell middlecenteralignsknLblCbuBeneficiary&quot;]/div[@id=&quot;flxBeneficiariesRow_lblCbu&quot;][count(. | //*[@id = 'flxBeneficiariesRow_lblCbu' and @kcontainerid = 'segBeneficiaries' and @class = ' sknLblCbuBeneficiary cntmiddleleftalign disableSelection' and (text() = 'CBU/CVU 19101196-55111901183599' or . = 'CBU/CVU 19101196-55111901183599')]) = count(//*[@id = 'flxBeneficiariesRow_lblCbu' and @kcontainerid = 'segBeneficiaries' and @class = ' sknLblCbuBeneficiary cntmiddleleftalign disableSelection' and (text() = 'CBU/CVU 19101196-55111901183599' or . = 'CBU/CVU 19101196-55111901183599')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxBeneficiariesRow_lblCbu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxBeneficiariesRow_lblCbu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>42367789-c53d-4304-88ac-11a0ee2728a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxBeneficiariesRow_lblCbu</value>
      <webElementGuid>4ce90888-5f5b-4231-a2bd-574acf2c132a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>5ed1d2ec-092a-4287-8e36-91720fc33329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxBeneficiariesRow</value>
      <webElementGuid>97b0f0df-1e42-4568-9ce4-e1d2d91a172d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segBeneficiaries</value>
      <webElementGuid>bb91fcc9-5e63-4f7d-a02a-f9de564e4d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>D51CE5E4-F632-4103-A207-13C120E41833</value>
      <webElementGuid>74fbeacb-2ee3-45df-99cc-30853c97fa95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCbuBeneficiary cntmiddleleftalign disableSelection</value>
      <webElementGuid>20506213-a2a0-452e-97cb-ea8012656bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CBU/CVU 19101196-55111901183599</value>
      <webElementGuid>decd6860-d3ab-4e9b-83af-284c9370fdf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_segBeneficiaries&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiariesRow&quot;]/div[@class=&quot;kcell middlecenteralignsknFlxCursorPointer&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiaryNameCbu&quot;]/div[@class=&quot;kcell middlecenteralignsknLblCbuBeneficiary&quot;]/div[@id=&quot;flxBeneficiariesRow_lblCbu&quot;]</value>
      <webElementGuid>828573b3-da37-44e8-87bd-0a342c467ca6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxBeneficiariesRow_lblCbu']</value>
      <webElementGuid>c142975c-3276-4e19-93b5-2f9253247fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxBeneficiariesRow_flxBeneficiaryNameCbu']/div[2]/div</value>
      <webElementGuid>48a4da7b-71ab-468b-8530-caea4d259763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDIE AGUSTIN  ENRICO'])[1]/following::div[2]</value>
      <webElementGuid>57e6df47-ac93-426a-89d8-3e8f681d13fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alias'])[1]/following::div[14]</value>
      <webElementGuid>fa760fe8-1756-4b60-8952-ff6217048110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>cb793ed3-8b3f-4457-a77f-7e471d8a193b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Propia'])[1]/preceding::div[9]</value>
      <webElementGuid>ab3adfb9-53df-482d-80aa-71d78d91e7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CBU/CVU 19101196-55111901183599']/parent::*</value>
      <webElementGuid>fa77b958-11d6-4350-bb3a-068e68e64e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>36a22e00-c253-41b5-8892-2aabe86e3457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxBeneficiariesRow_lblCbu' and (text() = 'CBU/CVU 19101196-55111901183599' or . = 'CBU/CVU 19101196-55111901183599')]</value>
      <webElementGuid>62085e3e-5f63-49b1-87b8-60f78712f67b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
