<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkTrxIniciarTrxBenefDolar</name>
   <tag></tag>
   <elementGuidId>3b8f0f1e-3c1b-4139-84df-4afadfb1311b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_TransferButton_lblButtonAction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_TransferButton_lblButtonAction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab908468-88f1-4159-b396-626e8ddc8f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_TransferButton_lblButtonAction</value>
      <webElementGuid>6218f70a-76c4-475b-9019-b0ee8122fef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>746e3a59-26c1-44dc-bf97-fb105f7b325a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>8cd0eda1-7422-4166-bdb7-aec71e1597d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBeneficiary_BeneficiaryDetails_TransferButton</value>
      <webElementGuid>9ebcccf0-5427-45af-b86f-db8090410452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblButton cntmiddleleftalign disableSelection</value>
      <webElementGuid>fe88b9e2-fe44-4719-8234-b7c337ce7d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iniciar Transferencia</value>
      <webElementGuid>49806fdf-0490-4168-bbdc-1d167040b82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_TransferButton_lblButtonAction&quot;)</value>
      <webElementGuid>33d91c64-38d5-4c7c-90d7-e6f28b4b7526</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_TransferButton_lblButtonAction']</value>
      <webElementGuid>393d0d30-e021-4121-a3fc-efd3ecc5bb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_TransferButton']/div[3]/div</value>
      <webElementGuid>0d6f9502-aaa7-4b10-8ff3-537d11b2e7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[42]/following::div[2]</value>
      <webElementGuid>4c1e0006-0b90-4378-a83f-021ff8325630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[6]/following::div[4]</value>
      <webElementGuid>ee571b4b-7d2b-4e82-9de7-d52f2ee2e42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>5075b8de-4570-4bed-b7d6-bd0482b3ddf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[6]/preceding::div[10]</value>
      <webElementGuid>e991ff07-0817-4740-b4e2-48968ddc0711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div[3]/div</value>
      <webElementGuid>d342e6c2-184b-4f7f-af05-53b3d36139de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_PanelBeneficiary_BeneficiaryDetails_TransferButton_lblButtonAction' and (text() = 'Iniciar Transferencia' or . = 'Iniciar Transferencia')]</value>
      <webElementGuid>559a133f-32ff-45c7-a2cc-5d7b86496ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
