<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkTrxSolapaProgramadas</name>
   <tag></tag>
   <elementGuidId>1ef9f90d-6b90-4af4-8427-992dd9bc5290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclTransfers_CustomNav_btnOptionThree']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclTransfers_CustomNav_btnOptionThree</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33c0f249-3322-4e09-9acb-8d0ddd8edac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclTransfers_CustomNav_btnOptionThree</value>
      <webElementGuid>00d9a002-4a23-4b70-a684-b0765c0ec7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>baad9228-fd05-4e44-a0cc-30ce5e2e0cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>5c86c5b9-9c31-417d-ac3a-7bf06fe29196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CustomNav</value>
      <webElementGuid>dc50a718-81c6-4e11-9ff8-93a485f27441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>219c61e2-83b7-4f3f-a875-dd7e4152fe76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f0e9ffd-c4d4-45c3-bd78-e5422ee6acb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknBtnInactiveNav</value>
      <webElementGuid>f9c21d33-f962-480e-a168-b6c1919a43b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Programadas</value>
      <webElementGuid>e3f73d7a-f00e-4dd4-a976-12765fb31a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnDisableNav</value>
      <webElementGuid>a95dd9fe-e0f0-438d-8bdb-51fc1372e69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_CustomNav_btnOptionThree&quot;)</value>
      <webElementGuid>7d565272-6547-43c0-8352-759bd61cb03d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclTransfers_CustomNav_btnOptionThree']</value>
      <webElementGuid>c27846aa-0faf-4d82-a1ed-042f47eb867b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_CustomNav_flxNavOptionThree']/div/input</value>
      <webElementGuid>fb9b281c-fd2a-4727-ae96-d64c9e83d25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>6d9c9ed0-0a65-4249-ae0c-e6106686a3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclTransfers_CustomNav_btnOptionThree' and @type = 'button']</value>
      <webElementGuid>79790298-dea7-40d9-af13-e58e2bdf11ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
