<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkTrfCuentaPropiaPesos</name>
   <tag></tag>
   <elementGuidId>a285425a-1f09-458d-99f2-732f7ea7fa44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxMisCuentasCredicoopRow_lblAccountDetail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxMisCuentasCredicoopRow_lblAccountDetail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57e775cc-36e1-4a54-9712-3b43f2b46486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_lblAccountDetail</value>
      <webElementGuid>450c2ab3-8224-479a-bc9a-5aa0191e319d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>3601c3ee-b3e1-46ce-8f88-6554fcad1197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>d78d18e7-9855-4f26-a1b1-f6feb1176b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>da646f8a-7989-403f-b86d-08dcaa70576f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>79DD52E8-D923-420C-9BB1-5EDD897FDDF2</value>
      <webElementGuid>8e37808d-cf0d-444b-b1eb-1083df522902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountDetailDashboard cntmiddleleftalign disableSelection</value>
      <webElementGuid>7eb76cb3-0e1d-48d6-94bb-a1d3f68620bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA $ 119-011835/9</value>
      <webElementGuid>3cef9081-33c0-49aa-bfe2-ab5906c89133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxAccountContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblAccountDetailDashboard&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountDetail&quot;]</value>
      <webElementGuid>1e8b1887-bffa-4d04-8ef9-e4a05f9d19dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxMisCuentasCredicoopRow_lblAccountDetail']</value>
      <webElementGuid>871ee605-6c98-4eb5-8fc1-a01890840a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxMisCuentasCredicoopRow_flxAccountContainer']/div[2]/div</value>
      <webElementGuid>07945396-6794-417e-9ad1-ad807f14374f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro sueldo prueba $'])[1]/following::div[2]</value>
      <webElementGuid>c35d1047-0ebb-44a5-a3ac-f0b021bd9d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[11]/following::div[24]</value>
      <webElementGuid>2f1e8acf-75c1-457c-8a0a-8b5e5d079381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENRICO EDIE A OR OTRO'])[1]/preceding::div[1]</value>
      <webElementGuid>044fe540-138b-444a-9e1b-ebed31cd7988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[5]/preceding::div[3]</value>
      <webElementGuid>70e71d2a-19e2-4c46-8dd4-dfe2384066fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA $ 119-011835/9']/parent::*</value>
      <webElementGuid>35336e21-29f6-40f1-8b44-24abb0b50d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>84d6bb10-7585-44bb-8553-88f18aa4353f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_lblAccountDetail' and (text() = 'CA $ 119-011835/9' or . = 'CA $ 119-011835/9')]</value>
      <webElementGuid>62fc9ded-2f76-46cd-9f48-6ed201270776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
