<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkTrxAgendaBeneficiarios</name>
   <tag></tag>
   <elementGuidId>4b5779e1-6e90-4257-be30-29c1df0ad538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclTransfers_flxLinkAgenda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclTransfers_flxLinkAgenda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d5ac049-e4a4-4439-8199-6d6c223ed0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  sknFlxCursorPointer </value>
      <webElementGuid>b0e5b6af-2f3d-4394-a518-dadfb19a8376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclTransfers_flxLinkAgenda</value>
      <webElementGuid>d1138d05-1ed0-4ff7-bc9f-1be117811083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>baf5c4d9-28dd-4bde-8653-cfd1ec459eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>b77fb068-064e-4378-aa53-974acf1ac323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ir a agenda de beneficiarios</value>
      <webElementGuid>c81fc7f7-4971-472d-b96a-9a8721ec0504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_flxLinkAgenda&quot;)</value>
      <webElementGuid>b4f4b681-bc2f-47c5-8e4d-0c941327aa9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_flxLinkAgenda']</value>
      <webElementGuid>29ef3df1-a7a3-4d90-a0c0-447fd9aef429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[237]</value>
      <webElementGuid>a560982b-27cd-4b6b-8354-b24b25d1b7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BENEFICIARIOS DESTACADOS'])[1]/following::div[3]</value>
      <webElementGuid>f6b272dd-b070-4b9e-b215-a989a8301c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/following::div[16]</value>
      <webElementGuid>1bc6a881-4516-411d-a431-6bdc123d798e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[29]/preceding::div[3]</value>
      <webElementGuid>0dfc6606-ca25-4e17-ac46-19c96a6e503b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>76845d8c-2c34-418e-8090-b762c1180e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclTransfers_flxLinkAgenda' and (text() = 'Ir a agenda de beneficiarios' or . = 'Ir a agenda de beneficiarios')]</value>
      <webElementGuid>feb4bf20-0eb8-49a9-a68f-d31464c88dfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
