<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuDesplegableTrxOtrosBancos</name>
   <tag></tag>
   <elementGuidId>5050f86f-3807-4307-92e0-a02912bb4843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclBeneficiaryAgenda_segBeneficiaries&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiariesRow&quot;]/div[@class=&quot;kcell middlecenteralignskncursor&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxSubMenuContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblSubMenuDashboard&quot;]/div[@id=&quot;flxBeneficiariesRow_lblSubMenuIcon&quot;][count(. | //*[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and @kuid = '525A18BF-C3EA-44BD-9F17-B4B439075B00' and @class = ' sknLblSubMenuDashboard cntmiddlecenteralign disableSelection' and (text() = '' or . = '')]) = count(//*[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and @kuid = '525A18BF-C3EA-44BD-9F17-B4B439075B00' and @class = ' sknLblSubMenuDashboard cntmiddlecenteralign disableSelection' and (text() = '' or . = '')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxBeneficiariesRow_lblSubMenuIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxBeneficiariesRow_lblSubMenuIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8bc91f8d-6085-46db-80a7-d01d9e1d942d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxBeneficiariesRow_lblSubMenuIcon</value>
      <webElementGuid>f4a2e36f-2077-4107-ac72-5f5dcbaf416b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>57b60e97-4ed0-46f7-8e30-bd0837f3c980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxBeneficiariesRow</value>
      <webElementGuid>79ce7b42-b7bf-4e63-b812-694fe4cb22cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segBeneficiaries</value>
      <webElementGuid>5e81b586-9bf6-4cc3-909a-8066278e2ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>525A18BF-C3EA-44BD-9F17-B4B439075B00</value>
      <webElementGuid>bed6e952-4663-46b1-a549-1ac1cf6f928f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSubMenuDashboard cntmiddlecenteralign disableSelection</value>
      <webElementGuid>0c56c4da-a4c4-4e20-b5e0-166e543cb30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>18a81c1c-fecf-4f85-af29-83c8d4eaa3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_segBeneficiaries&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiariesRow&quot;]/div[@class=&quot;kcell middlecenteralignskncursor&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxSubMenuContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblSubMenuDashboard&quot;]/div[@id=&quot;flxBeneficiariesRow_lblSubMenuIcon&quot;]</value>
      <webElementGuid>9f5bbe17-6217-497a-8c7f-d05f78f45411</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxBeneficiariesRow_lblSubMenuIcon']</value>
      <webElementGuid>6adaf08e-7097-4953-a163-e2892c6d702f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxBeneficiariesRow_flxSubMenuContainer']/div/div</value>
      <webElementGuid>6c24b0f4-19e3-42fb-aa63-ab5898ff6744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/following::div[5]</value>
      <webElementGuid>47565df7-ff84-40cd-9c76-9917c694e33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BBvA Banco Francés S.A.'])[1]/following::div[13]</value>
      <webElementGuid>315df387-fcc3-455b-a3f4-fff01c99aa18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANNETTA    LUCIANA EL'])[1]/preceding::div[1]</value>
      <webElementGuid>bb3cf33f-e7da-4302-abb2-697a36101120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU/CVU 01700992-44000057880134'])[1]/preceding::div[3]</value>
      <webElementGuid>f16ea1bf-f1ff-4115-92c4-c962690f6535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[6]/div/div/div/div</value>
      <webElementGuid>2c7756c4-3243-4b0a-9572-c500c1f6a842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>3875e184-10ae-4364-a442-f30c2f7c5c4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
