<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuDesplegableJudicialPesos</name>
   <tag></tag>
   <elementGuidId>0fc6fa4e-9e31-4e57-ba94-c9b1ee8907c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclBeneficiaryAgenda_segBeneficiaries&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiariesRow&quot;]/div[@class=&quot;kcell middlecenteralignskncursor&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxSubMenuContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblSubMenuDashboard&quot;]/div[@id=&quot;flxBeneficiariesRow_lblSubMenuIcon&quot;][count(. | //*[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and @kuid = '7453088F-E7F7-4BF3-915E-4AF50715823D' and @class = ' sknLblSubMenuDashboard cntmiddlecenteralign disableSelection' and (text() = '' or . = '')]) = count(//*[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and @kuid = '7453088F-E7F7-4BF3-915E-4AF50715823D' and @class = ' sknLblSubMenuDashboard cntmiddlecenteralign disableSelection' and (text() = '' or . = '')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxBeneficiariesRow_lblSubMenuIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxBeneficiariesRow_lblSubMenuIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5d44b15f-b51c-481b-8a82-9902ed8e7dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxBeneficiariesRow_lblSubMenuIcon</value>
      <webElementGuid>f2d3ba51-4c75-47ee-bbb5-55c514e246d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>ab6aa8aa-f040-495d-86da-a6e7b6ee8ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxBeneficiariesRow</value>
      <webElementGuid>2008012a-d695-476d-91eb-1f58d4266a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segBeneficiaries</value>
      <webElementGuid>8211c85e-25a7-4d5a-b1b4-3b98d27d1b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>7453088F-E7F7-4BF3-915E-4AF50715823D</value>
      <webElementGuid>5eb0dfa2-a5d8-46ab-a13b-2fa137f698fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSubMenuDashboard cntmiddlecenteralign disableSelection</value>
      <webElementGuid>202651f6-9b53-41a0-86f1-360ff8ee8bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>595a8d2f-5b04-480c-a36b-7a28f6a52f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_segBeneficiaries&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiariesRow&quot;]/div[@class=&quot;kcell middlecenteralignskncursor&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxSubMenuContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblSubMenuDashboard&quot;]/div[@id=&quot;flxBeneficiariesRow_lblSubMenuIcon&quot;]</value>
      <webElementGuid>359554e5-4d08-4488-9d45-b840292282f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxBeneficiariesRow_lblSubMenuIcon']</value>
      <webElementGuid>cf808674-ebdd-40ab-9160-be300620871a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxBeneficiariesRow_flxSubMenuContainer']/div/div</value>
      <webElementGuid>ed64c89b-5f93-4403-8142-ea16723dfeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/following::div[5]</value>
      <webElementGuid>742df0b6-8a56-4e74-820c-73b674e30e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banco Hipotecario S.A.'])[1]/following::div[13]</value>
      <webElementGuid>e8aba9be-a6fa-4907-b0f6-4c567104ed46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOMBCORTO'])[1]/preceding::div[1]</value>
      <webElementGuid>546fa128-9d7e-4d30-8060-11fd87ce36a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU/CVU 19100018-55200103198738'])[1]/preceding::div[3]</value>
      <webElementGuid>2d4ac812-3830-4954-a743-744535e1a830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[6]/div/div/div/div</value>
      <webElementGuid>78b16e42-c8f7-42a7-bbf3-037a174b0f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>63bb0a4c-8c30-4680-b1ac-ac448ba72086</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
