<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuTrxBenfFavoritoCtaDolar</name>
   <tag></tag>
   <elementGuidId>6d7536b3-40db-49f6-a284-8ca90f582156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_lblFloatingMenuIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_lblFloatingMenuIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ec00e23-6e0d-4163-97bc-2d61921494e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_lblFloatingMenuIcon</value>
      <webElementGuid>604728d2-62bd-4dc4-864c-3fbf49626206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>7d070b48-5b26-4b19-8a9e-62ff7cd63b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>1304862a-4e1a-42bb-a8fa-919a4ac9a23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary</value>
      <webElementGuid>a3fe935a-6422-4197-bd65-2947fff763de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSubMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>e06ba5ba-472c-46ab-88f2-4eeed98e3d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c64f9e5f-682f-4ecf-919a-dd4aa687c9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_lblFloatingMenuIcon&quot;)</value>
      <webElementGuid>bec8eaf9-950b-4858-b9e2-9f02ff337990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_lblFloatingMenuIcon']</value>
      <webElementGuid>f458d06f-3f05-40c2-9ae6-991d2c900a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary']/div/div</value>
      <webElementGuid>53a3dff7-dabe-42cb-a715-1edf290bea06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[8]</value>
      <webElementGuid>fa481810-b4aa-4304-9be0-42548d6ad5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU 01700992-44000057880134'])[1]/following::div[16]</value>
      <webElementGuid>392949c7-16bb-4db9-b879-c76cff8c6938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver detalle'])[3]/preceding::div[1]</value>
      <webElementGuid>562d7a5b-b127-48bf-9d93-cb68302c1912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva transferencia'])[3]/preceding::div[6]</value>
      <webElementGuid>2a47f673-f306-4395-bedb-2785550d1df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>5e4307a3-85c6-4af8-90fe-5d617428f93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_lblFloatingMenuIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>498c6b3d-4775-48c4-8768-bda4cb453eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
