<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuTrxTercerosCredicoop</name>
   <tag></tag>
   <elementGuidId>7bbd43c2-db52-49f0-9577-0fa49bc8872e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxBeneficiariesRow_lblSubMenuIcon'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclBeneficiaryAgenda_segBeneficiaries&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiariesRow&quot;]/div[@class=&quot;kcell middlecenteralignskncursor&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxSubMenuContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblSubMenuDashboard&quot;]/div[@id=&quot;flxBeneficiariesRow_lblSubMenuIcon&quot;][count(. | //*[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and @kuid = '8A170ECB-C803-4497-944A-5D63406BBA25' and @class = ' sknLblSubMenuDashboard cntmiddlecenteralign disableSelection' and (text() = '' or . = '')]) = count(//*[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and @kuid = '8A170ECB-C803-4497-944A-5D63406BBA25' and @class = ' sknLblSubMenuDashboard cntmiddlecenteralign disableSelection' and (text() = '' or . = '')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0cad9f74-7a0b-410d-b1f1-df69c49e7161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxBeneficiariesRow_lblSubMenuIcon</value>
      <webElementGuid>78d216ff-bea1-434e-a635-3ee535ebf22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>151648ec-9d76-4d7f-90ee-2e9ed9e4905c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxBeneficiariesRow</value>
      <webElementGuid>6e985b9e-c9f1-4244-94eb-8de1d98a5447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segBeneficiaries</value>
      <webElementGuid>c7d103d0-3de4-4c4e-95ba-c9d1ba014559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>8A170ECB-C803-4497-944A-5D63406BBA25</value>
      <webElementGuid>b34e6f5c-1aa1-4e1c-bd79-c162229d27c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSubMenuDashboard cntmiddlecenteralign disableSelection</value>
      <webElementGuid>ec388af8-4778-4bf9-9825-745240c11bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9dedadae-f321-4d3a-bafe-2b7dc1d4ee41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_segBeneficiaries&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxBeneficiariesRow&quot;]/div[@class=&quot;kcell middlecenteralignskncursor&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxBeneficiariesRow_flxSubMenuContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblSubMenuDashboard&quot;]/div[@id=&quot;flxBeneficiariesRow_lblSubMenuIcon&quot;]</value>
      <webElementGuid>8c1ff833-41c9-413b-af98-0d98f08bff91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxBeneficiariesRow_lblSubMenuIcon'])[3]</value>
      <webElementGuid>2b4fa1c7-4452-45a3-a7a0-7f5c77888397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxBeneficiariesRow_flxSubMenuContainer']/div/div)[3]</value>
      <webElementGuid>16bec39d-3140-42a2-910b-480c54e95158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S'])[2]/following::div[5]</value>
      <webElementGuid>d96f2f0e-8858-417f-bedf-c3ae134701ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banco Credicoop Cooperativo Limitado'])[1]/following::div[13]</value>
      <webElementGuid>e8ef048b-0759-46b9-9a93-637808d97b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARACI SALVADOR RAMON'])[1]/preceding::div[1]</value>
      <webElementGuid>36c06ed3-4591-4a19-8164-84a5b345df51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU/CVU 07200496-88000019230654'])[1]/preceding::div[3]</value>
      <webElementGuid>fde1ee9b-e21e-4f10-ae2d-2622638444d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[6]/div/div/div/div</value>
      <webElementGuid>8262b00b-d69c-4442-9435-43f48b5f36f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxBeneficiariesRow_lblSubMenuIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>164f6db8-801f-4b72-8666-758ae767c92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
