<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuTrxCuentaDebito</name>
   <tag></tag>
   <elementGuidId>a65efa4e-4522-459f-999f-f759ca019483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_DropDownAccounts_lblDropDownIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_DropDownAccounts_lblDropDownIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5263ec8-a361-41a5-a7e0-2ba05dab8f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_DropDownAccounts_lblDropDownIcon</value>
      <webElementGuid>b60d6714-1857-4714-96fc-682dae6d06ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>dec0dcfb-31ed-409b-a6c9-4526fe129e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>55c90263-98e5-4938-824c-d35fb7551069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DropDownAccounts</value>
      <webElementGuid>2497fed9-5c67-4f13-b9fd-a61e20fa772c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblDropDownChevronAccounts cntmiddlecenteralign disableSelection</value>
      <webElementGuid>ca539319-532b-4afc-8bea-ef8a0fa6636a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9c8466da-d78b-4635-b7fa-aa34a3aaabc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_DropDownAccounts_lblDropDownIcon&quot;)</value>
      <webElementGuid>42260173-9901-46e8-b1a3-87bd7f470edd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_DropDownAccounts_lblDropDownIcon']</value>
      <webElementGuid>93b3b9dd-6da3-4c76-ad6f-b933029ca2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_DropDownAccounts_flxOption']/div[2]/div</value>
      <webElementGuid>dd2190cc-ec5f-46d0-9573-f19bcd50eb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 113,15'])[1]/following::div[2]</value>
      <webElementGuid>0e04dc18-3926-4509-bc7b-aa1852498ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[3]/following::div[4]</value>
      <webElementGuid>79c899d0-0c3f-4ac0-bc43-d25e2a7088ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SZIR MARIA ALEJAN...'])[2]/preceding::div[1]</value>
      <webElementGuid>b0471a4c-345f-4c7a-a7c9-8c5499b80664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[3]</value>
      <webElementGuid>f6f3a7aa-6b7e-4764-aba4-e4220f438627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>4a89a4d0-c401-42fa-a6f1-99d3c9cf5dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_DropDownAccounts_lblDropDownIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>431392ec-2c90-438b-a08a-b9cd86811d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
