<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBypassConfirmacion</name>
   <tag></tag>
   <elementGuidId>a3d1a8db-d0fe-47b3-95b0-60d6ccc32523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclTransfers_DeleteSentTransfer_SecondFactor_InputMasked_tbxMasked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclTransfers_DeleteSentTransfer_SecondFactor_InputMasked_tbxMasked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>435000b2-98b2-46dc-97d8-3eeb7b14703b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclTransfers_DeleteSentTransfer_SecondFactor_InputMasked_tbxMasked</value>
      <webElementGuid>d8febd97-67a0-4c4e-8ebd-b8e7e67a1629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>1470fc12-2852-4d63-a7ef-c6518a3967f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>8a4a8236-bdf0-4247-af62-8525796a3df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DeleteSentTransfer_SecondFactor_InputMasked</value>
      <webElementGuid>a7c40655-b633-4750-b102-de07a14ef4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknTbxInputMasked</value>
      <webElementGuid>9babddd2-b40b-410f-b6af-3e945a676892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8534ca01-3f19-464f-951e-86445cbcd972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2860f3a4-93ec-4d92-b42f-06fe050336f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f81ecb30-c49a-4fd4-bf21-5d8df4943c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>903c7a55-c87c-43cb-b5ea-39f9e27099e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>cf83f9a3-0819-49d5-8420-d7de07ec9243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>802c137e-7aa1-4070-a47e-081f78293bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contraseña</value>
      <webElementGuid>4e099054-6996-43dc-a2f7-ee08163ac1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>1b2a48ba-b6c7-4d0f-ae42-ee2655ee3c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_DeleteSentTransfer_SecondFactor_InputMasked_tbxMasked&quot;)</value>
      <webElementGuid>4e651db5-da5f-48b4-9eec-44b178f97624</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclTransfers_DeleteSentTransfer_SecondFactor_InputMasked_tbxMasked']</value>
      <webElementGuid>fe3e45eb-006c-4d67-950d-f5c62344e75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_DeleteSentTransfer_SecondFactor_InputMasked_flxInput']/div/input</value>
      <webElementGuid>4c4cbc86-3ec0-4c14-9b92-f74b7aa26a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/div/div/div/div[4]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>daf8379a-ba62-4653-8f0e-8e7794150061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclTransfers_DeleteSentTransfer_SecondFactor_InputMasked_tbxMasked' and @type = 'text' and @placeholder = 'Contraseña']</value>
      <webElementGuid>a0936e71-cabb-4320-acb7-7570c8b1a4fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
