<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtMontoPesos</name>
   <tag></tag>
   <elementGuidId>4c5a52e6-ed12-4298-8280-d575b8a3f1dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclCreateTransfer_AmountInput_tbxAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_AmountInput_tbxAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15e7b23e-17ef-4718-aa54-27a1d8e9693f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_AmountInput_tbxAmount</value>
      <webElementGuid>b511251c-3e99-4d4f-9311-56ad1e4d579f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>ecd262f5-e9a8-473b-a01f-3c9e4bf2890f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>bac9da4f-0a0e-4a20-aa66-e13b8410dc99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AmountInput</value>
      <webElementGuid>66b4798c-0bc8-4a56-841e-4b51767f3d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknTbxAutonumeric</value>
      <webElementGuid>fbbb1c82-d5d7-47a4-b02a-640a365e5a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7ca0bb5a-527c-40f7-b957-db719fc2c130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1f636da6-8aaf-4f78-aea8-a4e5e082564b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>10185234-e0b1-4949-9f34-b589b90ff07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb8f5957-5b45-4c86-a8b4-760245bfa8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>9e758975-580f-4d45-9a6b-7f4a8a464e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>d8fc8375-cbab-4177-8722-6a70ba584aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_AmountInput_tbxAmount&quot;)</value>
      <webElementGuid>7d330c99-7707-4651-81aa-147f05014ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclCreateTransfer_AmountInput_tbxAmount']</value>
      <webElementGuid>016ec5da-986b-4239-be2a-0183f4ba3aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_flxInputContainer']/div/input</value>
      <webElementGuid>b7adf878-3871-4d26-bb15-1f84b8526abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>d840ba8f-b2c5-4fec-85ba-a2193a23602c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclCreateTransfer_AmountInput_tbxAmount' and @type = 'text']</value>
      <webElementGuid>6edc809e-5b36-4de5-93fa-1315f9788db9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
