<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNuevaTransferenciaOtrosBancos</name>
   <tag></tag>
   <elementGuidId>5602ede2-b193-4486-b44d-59a819179c8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxnewTransfer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxnewTransfer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a04d2eb-e9e9-43a5-9826-7628fd05c753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100 sknFlxOptionFloatMenuOnHover</value>
      <webElementGuid>c41d4c58-94c3-4c9f-8029-bf5823ecbd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxnewTransfer</value>
      <webElementGuid>df13e0e3-6acf-4ded-a7b0-27895ce2954c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>c7291629-de52-4dfe-a40d-92b075cd994e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>085bacfa-a5f6-441c-9c92-3f955124647a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>flxBeneficiariesRowFloatingMenu</value>
      <webElementGuid>1ff97d12-f4a8-4bff-aaf3-b124d25a391a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseenter</name>
      <type>Main</type>
      <value>$KI.HoverEvent.executeHoverEvent(event, this)</value>
      <webElementGuid>78b82501-89c9-4657-874f-c0a316a61b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>$KI.HoverEvent.executeHoverEvent(event, this)</value>
      <webElementGuid>f00c530e-7fb9-4340-93ee-410d3e9afc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>$KI.HoverEvent.executeHoverEvent(event, this)</value>
      <webElementGuid>36c6b117-b3dd-4740-adc5-386e9bcb5d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva transferencia</value>
      <webElementGuid>77304424-7716-4ffb-ba3a-2142ba16a185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxnewTransfer&quot;)</value>
      <webElementGuid>fe9ee1fa-7620-4567-8bfe-72c6e1f27dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxnewTransfer']</value>
      <webElementGuid>e825f652-10f8-4c62-bae5-da8dd31ecd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[727]</value>
      <webElementGuid>b6f43a46-a0c7-4fa6-aaee-1907d49d8307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver detalle'])[1]/following::div[3]</value>
      <webElementGuid>9ec7d5c9-e524-4ea9-a40d-610f3bafe2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[14]/following::div[11]</value>
      <webElementGuid>3b9a5cae-7b4b-49f1-852b-30c14fd4c8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[3]/preceding::div[3]</value>
      <webElementGuid>38cdf872-e66d-4ee7-9964-46f06537b010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>88648200-4b71-4be3-b528-b64f3e5291b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxnewTransfer' and (text() = 'Nueva transferencia' or . = 'Nueva transferencia')]</value>
      <webElementGuid>c2964bfa-1b5b-4d93-8676-cbc1339a6370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
