<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxCuentaDebito</name>
   <tag></tag>
   <elementGuidId>7412016d-8c0d-4a47-b319-a067fe0908c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer' and (text() = 'Label$ 10.078.953,56' or . = 'Label$ 10.078.953,56')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b27b278e-5275-4532-9210-092143a06b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>5796e912-9301-497f-894f-bd33d191667b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer</value>
      <webElementGuid>49af927a-d83c-4d17-80f6-2f69a2ada8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>cc009873-0b1b-4e21-8099-d9fc4900dfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>7ed6d71a-5eea-4973-a989-5cb2fef182e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DropDownAccounts</value>
      <webElementGuid>6e55b1a7-e9f4-449c-9626-956823107d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Label$ 10.078.953,56</value>
      <webElementGuid>159fa18e-0033-4910-a5cb-8866c6b8faaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer&quot;)</value>
      <webElementGuid>8e9c62e6-e1e3-4989-9b6a-0f45ef243c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer']</value>
      <webElementGuid>8b37931b-0561-4a07-bb54-6222a3794260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[271]</value>
      <webElementGuid>4f0efed2-2eae-4c31-a024-f09049531fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 056-515055/0'])[1]/following::div[3]</value>
      <webElementGuid>7b2d9798-f083-483d-97f2-098c800bf0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[8]/following::div[5]</value>
      <webElementGuid>b4e583a5-9aed-433e-b4f7-778998a0a3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>97027025-387e-49dd-a053-60c32555fd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer' and (text() = 'Label$ 10.078.953,56' or . = 'Label$ 10.078.953,56')]</value>
      <webElementGuid>d0f020d5-9dbc-4370-a6af-415a2e20527b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
