<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxProgramadasConfirmMonto</name>
   <tag></tag>
   <elementGuidId>c54c0213-199b-4585-88fe-d77f7fbadeea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_ConfirmTransfer_lblRightAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_ConfirmTransfer_lblRightAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c479a380-7d16-4754-abdd-94b7ecc487b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_ConfirmTransfer_lblRightAmount</value>
      <webElementGuid>e4e66dd7-7463-433f-ae97-257b896f72c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>303b1302-fe65-4baa-89d2-e3654b78e79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>7fa178fe-0504-4c5a-a471-6fbe4712984f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConfirmTransfer</value>
      <webElementGuid>6d0cbb4c-4e9e-4c8c-bfc6-358e44ba17a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblConfirmTransfervalue cntmiddlerightalign disableSelection</value>
      <webElementGuid>790fa9dd-dba1-4aeb-979f-e6aced588dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 0,50</value>
      <webElementGuid>18dd5bd2-367c-4de7-a3aa-0a0722184336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_ConfirmTransfer_lblRightAmount&quot;)</value>
      <webElementGuid>a8964836-a098-4862-9ca6-643cb0264ac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_ConfirmTransfer_lblRightAmount']</value>
      <webElementGuid>f04c2c62-0dbf-47b4-9627-fcb8908ca06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_ConfirmTransfer_flxRightAmount']/div/div</value>
      <webElementGuid>8431911d-c1b3-49bd-aecc-4ae2e72e6a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[1]/following::div[5]</value>
      <webElementGuid>f20898fe-64bd-466e-a70b-387797de661d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar Transferencia'])[1]/following::div[16]</value>
      <webElementGuid>8c02b80b-6198-4882-bfad-81f68aa2a581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Origen'])[1]/preceding::div[1]</value>
      <webElementGuid>6928889d-b8cb-4b9d-a7bf-ab026c5b7a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro sueldo prueba $'])[1]/preceding::div[6]</value>
      <webElementGuid>0f549859-1458-4cf2-b205-d00d22bb07c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 0,50']/parent::*</value>
      <webElementGuid>9918b5f8-f90a-4bee-88fe-05c4d1a46be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>d29d9d76-8b32-4953-bed5-20232e984ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_ConfirmTransfer_lblRightAmount' and (text() = '$ 0,50' or . = '$ 0,50')]</value>
      <webElementGuid>0e5b9cf6-4c8e-49c5-83e4-5bc66e4e1f40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
