<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMontoExitoTercerosDolar</name>
   <tag></tag>
   <elementGuidId>5c92af10-9149-483b-bdaf-57d4b0e04b5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9b9e5c3d-f1ff-4635-84ea-3afcf0a7f4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess</value>
      <webElementGuid>3f792888-7f7a-4688-8a48-0e19f5650cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>d7486bad-4d59-47f6-8981-62d497febc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>728b480e-4f12-4d08-81dc-72f323da43f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferMessage</value>
      <webElementGuid>80e64ca6-8947-491b-af0d-d77cb217e819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSuccessTransferAmount cntmiddlerightalign disableSelection</value>
      <webElementGuid>04638a2b-eff9-4abd-bca2-66cd8d53c47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>U$S 0,10</value>
      <webElementGuid>56400232-a6f8-4532-8581-60c9e132198c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess&quot;)</value>
      <webElementGuid>3b35010f-d557-4f8d-8dcc-b422a01e8d70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess']</value>
      <webElementGuid>83037639-6145-4243-a0db-f6a4a1a6eb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_flxFirstRowSuccess']/div[3]/div</value>
      <webElementGuid>61d610c6-41d6-4ad2-8304-403b1810ad4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dolardebin2'])[1]/following::div[2]</value>
      <webElementGuid>59f4711d-9b1b-4e95-a270-b62d21427b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOMBCORTO'])[3]/following::div[4]</value>
      <webElementGuid>1ce0a71b-9077-4e44-8224-a54195e52843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Operación'])[1]/preceding::div[1]</value>
      <webElementGuid>e27a9384-9891-4a91-8c71-43d8bbb1a112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargando'])[1]/preceding::div[9]</value>
      <webElementGuid>343ee18e-237c-46d4-b7d0-c62acbd821ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[3]/div</value>
      <webElementGuid>4384a91d-15b0-4b6a-b14c-ccd0e604d115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess' and (text() = 'U$S 0,10' or . = 'U$S 0,10')]</value>
      <webElementGuid>9066fd4a-9aa9-43f8-b67f-365a90c9b9de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
