<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxNuevaTransferenciaDolar</name>
   <tag></tag>
   <elementGuidId>5c8a8d18-94f6-4c0a-81ad-32ce7b591c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer2MenuBeneficiary_lblnewTransfer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer2MenuBeneficiary_lblnewTransfer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ecda987-baa0-48a0-ad3b-204afd255d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer2MenuBeneficiary_lblnewTransfer</value>
      <webElementGuid>982f6a23-fe6b-4083-b166-f3c30c914fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e2d1e81a-9012-4038-9a50-dd3e8472540f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>338cc57f-84ea-4c1f-a504-a110c0a3af30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>OutstandingBeneficiary_flxBeneficiaryDataContainer2MenuBeneficiary</value>
      <webElementGuid>9e3f25f5-d8fe-4fb1-be51-841354f96721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>a0fb19c8-2b1e-4a3d-adf5-e4dc7c86a534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva transferencia</value>
      <webElementGuid>d37fcdb7-4b8e-4cac-9096-7183d9626fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer2MenuBeneficiary_lblnewTransfer&quot;)</value>
      <webElementGuid>d0e59d60-892d-44e0-8435-8d623c5d006c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer2MenuBeneficiary_lblnewTransfer']</value>
      <webElementGuid>0db3b959-6eb7-4208-ab40-d11119d6c50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer2MenuBeneficiary_flxnewTransfer']/div/div</value>
      <webElementGuid>636b4d98-ad41-4623-a565-5c50ac065110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver detalle'])[2]/following::div[5]</value>
      <webElementGuid>f1e05c2c-1278-4364-a730-3c9e4e4d4c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[13]</value>
      <webElementGuid>660b17f8-bf08-45c3-88f9-d6b199bd69c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[2]/preceding::div[1]</value>
      <webElementGuid>e2f68b3d-9b5f-405a-96c8-61e8fb0b5ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[6]/preceding::div[6]</value>
      <webElementGuid>26b643fa-11dc-496f-9d0d-2d529daecbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>81753fb7-887e-4520-905b-2e49c466d5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer2MenuBeneficiary_lblnewTransfer' and (text() = 'Nueva transferencia' or . = 'Nueva transferencia')]</value>
      <webElementGuid>c5c1407e-51b1-46d9-8f6b-a9387b8d1cd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
