<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxCuentaDebito</name>
   <tag></tag>
   <elementGuidId>7412016d-8c0d-4a47-b319-a067fe0908c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71011c12-77c1-444c-b32e-d4b35ab4db08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>36fcb0af-ab72-4bff-9056-fadb22b0064e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer</value>
      <webElementGuid>4b1e0b73-ec70-4758-9727-717c0f614cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>f5caf67b-069d-44ec-b318-767cb71326ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>29dae126-2b27-4063-91ab-a681012ffe0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DropDownAccounts</value>
      <webElementGuid>bf88f2a3-b67a-426b-8e28-3bf73bff328c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Label$ 10.078.953,56</value>
      <webElementGuid>b2293033-98e5-47c3-9ee1-c27343b5bbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer&quot;)</value>
      <webElementGuid>362c43cd-8784-4944-ba05-7bb29bbf652b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer']</value>
      <webElementGuid>4f79b2c9-eb7c-4054-bd8c-9217a82f4718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[271]</value>
      <webElementGuid>ab31424e-dea5-47a0-8d3d-70f441edb52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 056-515055/0'])[1]/following::div[3]</value>
      <webElementGuid>e615192d-2370-4570-acde-a2f59a6625c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[8]/following::div[5]</value>
      <webElementGuid>4cfece5a-21c7-4bba-ad1f-8c2a567075ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>ec08935e-8d65-4099-8e5e-b33c54dcda44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_DropDownAccounts_flxOption7flxAmountCointainer' and (text() = 'Label$ 10.078.953,56' or . = 'Label$ 10.078.953,56')]</value>
      <webElementGuid>2928ed46-f92d-4e2e-87b3-3705fa7bac67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
