<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMontoSuperaSaldo</name>
   <tag></tag>
   <elementGuidId>5cb99b0a-9b09-461f-8415-d6603c88f8db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_AmountInput_lblValidationErrorMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_AmountInput_lblValidationErrorMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0809fa80-5cd0-4909-975f-5d20049a3293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_AmountInput_lblValidationErrorMessage</value>
      <webElementGuid>36caa8ff-fe59-448a-a86f-e86c848f5051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>daf57443-aa3f-4c9f-94b4-cff7f5f90acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>80fb87f4-46b1-40a4-8e5a-328b02f7d9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AmountInput</value>
      <webElementGuid>a8ea3dee-feca-4123-a17f-f5191984bcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddleleftalign disableSelection sknLblValidationErrorMessage</value>
      <webElementGuid>88daee37-7861-4c70-9b93-44fc08b9018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El monto supera el saldo de tu cuenta, ingresá otro valor.</value>
      <webElementGuid>5e7921a3-e938-416f-b5fd-c1213f5aabcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_AmountInput_lblValidationErrorMessage&quot;)</value>
      <webElementGuid>e5cae719-bafc-465e-8176-c3945f18ec7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_lblValidationErrorMessage']</value>
      <webElementGuid>994c18d2-03a9-402b-b2d8-da2e3ccabd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_flxValidationError']/div[2]/div</value>
      <webElementGuid>b19f0e0f-a3b8-4941-af7f-a69eab64a302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[2]</value>
      <webElementGuid>5e0fa981-d6d0-4c5d-b671-8cdfcf9462a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite disponible para transferir: $ 60.000,00'])[1]/following::div[7]</value>
      <webElementGuid>cd7d5ee7-a031-4ce0-894b-7cf8a6aa16ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>6501ad4b-5353-40d4-a325-04d038edf9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='El monto supera el saldo de tu cuenta, ingresá otro valor.']/parent::*</value>
      <webElementGuid>c73043d1-5f51-404b-9c58-64280aa3a38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/div/div[4]/div/div/div[2]/div</value>
      <webElementGuid>d1a84d29-2c5e-44dc-b531-712e5e43ec7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_AmountInput_lblValidationErrorMessage' and (text() = 'El monto supera el saldo de tu cuenta, ingresá otro valor.' or . = 'El monto supera el saldo de tu cuenta, ingresá otro valor.')]</value>
      <webElementGuid>4638b5ac-a32e-47aa-acb1-a189d90f3284</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
