<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxProgramadasSolapaBeneficiarioDolar</name>
   <tag></tag>
   <elementGuidId>50c9fb08-a06c-4bec-8a02-70e52bf91d8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxPostdatedRow_lblPostdatedOwner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c7b39c7-7da2-42a6-84cd-63cfe5b377a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxPostdatedRow_lblPostdatedOwner</value>
      <webElementGuid>cd864b5b-c63c-443c-a803-401b5c838e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>2b4c66f9-2ccb-49a9-8946-5164569283fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxPostdatedRow</value>
      <webElementGuid>544655cd-1633-4f6d-b404-4b1a487749f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segPostdated</value>
      <webElementGuid>16bdba1f-1212-4f02-bb86-8316f8c47833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>D6A9628E-9D63-4337-956A-EEB0908103E8</value>
      <webElementGuid>0892ea6f-42e2-4828-a2f1-79a87efa5a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddleleftalign disableSelection</value>
      <webElementGuid>2d8439b2-e88d-4891-8577-c5a2d86f2e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annetta Luciana Dolar</value>
      <webElementGuid>85617169-ee0c-4654-bde2-4966a8fcdb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_TransferHistory_segPostdated&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxPostdatedRow_flxPostdatedRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxPostdatedRow_flxPostdatedBeneficiary&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxPostdatedRow_lblPostdatedOwner&quot;]</value>
      <webElementGuid>c00ea7f5-cb12-4d8d-8157-648ee453cb1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxPostdatedRow_lblPostdatedOwner']</value>
      <webElementGuid>9e626a5a-fb29-4288-85ff-f6e15761da50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxPostdatedRow_flxPostdatedBeneficiary']/div/div</value>
      <webElementGuid>94cefbe2-853b-44df-b2f6-0714fcc46917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 119-011835/9'])[1]/following::div[5]</value>
      <webElementGuid>e00a0a6b-562d-48ce-b786-8e51181a45a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencia Judicial'])[1]/following::div[10]</value>
      <webElementGuid>11e9c7ff-55d0-49f8-9eb0-739bbafb263c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S 0,50'])[1]/preceding::div[5]</value>
      <webElementGuid>f187ce2c-9e5e-4a9a-9c91-09077baa2783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[10]</value>
      <webElementGuid>75fd45ff-5e36-4c42-b5e3-ca75d22434ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Annetta Luciana Dolar']/parent::*</value>
      <webElementGuid>548e19fc-d033-4a89-ae57-d6f1535e67b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>34148ad3-f40a-4ad0-9edf-6825ebd22231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxPostdatedRow_lblPostdatedOwner' and (text() = 'Annetta Luciana Dolar' or . = 'Annetta Luciana Dolar')]</value>
      <webElementGuid>f078afaf-a5ef-4def-a46c-b37d276b121a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
