<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrfMontoFormulario</name>
   <tag></tag>
   <elementGuidId>4de65a49-781e-48a1-a89a-692dd6e138b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclCreateTransfer_AmountInput_tbxAmount&quot;)[count(. | //*[@id = 'frmBcclCreateTransfer_AmountInput_tbxAmount' and @type = 'text' and @onfocus = '$KW.TextField.onfocusEventHandler(arguments[0],this)']) = count(//*[@id = 'frmBcclCreateTransfer_AmountInput_tbxAmount' and @type = 'text' and @onfocus = '$KW.TextField.onfocusEventHandler(arguments[0],this)'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclCreateTransfer_AmountInput_tbxAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_AmountInput_tbxAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54cc543a-95a2-4340-a94d-103dd402ddcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_AmountInput_tbxAmount</value>
      <webElementGuid>535cfd60-01d1-4275-ad99-dcb34227e77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>a2cd5c63-4fc0-4d57-b358-bab0ac6309e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>0464f1f7-68a3-4e0a-accf-0c53366c5e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AmountInput</value>
      <webElementGuid>9e74a41b-a2f4-437d-911a-7a9191c89c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknTbxAutonumeric</value>
      <webElementGuid>9f421be5-0287-49c9-b2af-4c7d50e9d4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>c8a4efe5-587e-4836-8eda-de2da08c7d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7061dbca-abec-4d78-ae4c-2ce1db811064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7a8f59e-fd86-4746-92b6-3de4357b61b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4907b4a-91c2-4338-80a7-607c05a0b9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>07d8270c-72b3-4c23-8a6d-0f4297e97afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>43a0396f-e47e-48c4-8198-fc641f7b5b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_AmountInput_tbxAmount&quot;)</value>
      <webElementGuid>7505e28a-0a50-48bc-8825-0a4f8a6d2f37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclCreateTransfer_AmountInput_tbxAmount']</value>
      <webElementGuid>8aee5ac2-b8e4-497e-a11b-0c0666a1c230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_flxInputContainer']/div/input</value>
      <webElementGuid>411ba39d-8912-4042-a8ea-1bfc4058591a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>01137977-82b4-4c89-8f6a-ef447babe085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclCreateTransfer_AmountInput_tbxAmount' and @type = 'text']</value>
      <webElementGuid>b0de89b8-eeda-43a1-ad50-6dba1acd2b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
