<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMensajeSinResultado</name>
   <tag></tag>
   <elementGuidId>096748ce-1771-4857-acc0-0252b8c720dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclTransfers_customhamburger_TRANSFERlblAccounts']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclTransfers_customhamburger_TRANSFERlblAccounts</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'frmBcclTransfers_customhamburger_TRANSFERlblAccounts' and (text() = 'Transferencias' or . = 'Transferencias')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60df5225-4a83-489f-8a11-44ea1e9cbcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Accounts </value>
      <webElementGuid>25a1e733-e823-48ff-95de-077690032583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f099ab3e-15af-4947-b264-73dbadc0db58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclTransfers_customhamburger_TRANSFERlblAccounts</value>
      <webElementGuid>785dffc4-c69f-4595-8286-865a22ce1972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>c468f523-aa84-4eb8-8db5-0fd8b9744490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>c7b82b3d-9769-4e70-b2f8-028dcd7e7f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>customhamburger</value>
      <webElementGuid>862dc957-162b-4450-965c-16340725d427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddleleftalign disableSelection sknLblItemMenuSelected</value>
      <webElementGuid>debd5a4f-ad36-4f33-9f28-fcdd1c887937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>baac0a65-bd98-472f-a9b1-695b81531087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencias</value>
      <webElementGuid>a6d817fa-9bda-4ae7-8660-83b6676f5088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_customhamburger_TRANSFERlblAccounts&quot;)</value>
      <webElementGuid>8087ae99-3f99-421c-a380-7c1ea2614f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_customhamburger_TRANSFERlblAccounts']</value>
      <webElementGuid>96e12c33-82ba-40be-8f5a-43df8705afd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_customhamburger_TRANSFERflxAccountsMenu']/div[3]/div</value>
      <webElementGuid>bb241dd8-db0a-4bd2-8906-220bc9f8dc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuentas'])[1]/following::div[17]</value>
      <webElementGuid>d2996323-8fa5-45fd-9caf-5abeea92c855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[1]/following::div[34]</value>
      <webElementGuid>4f921279-e728-41e0-a004-4c9d22e259d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagos y Recargas'])[1]/preceding::div[13]</value>
      <webElementGuid>fa1e0883-3bf7-4ad1-ba9d-f8b2e1afb2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[22]</value>
      <webElementGuid>fa7cd2d7-6629-4063-8d1d-150fe8de6c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transferencias']/parent::*</value>
      <webElementGuid>2432d94f-803e-4c14-ac48-87b78662e0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div</value>
      <webElementGuid>94498ce3-b534-445c-8839-15c52aa57fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclTransfers_customhamburger_TRANSFERlblAccounts' and (text() = 'Transferencias' or . = 'Transferencias')]</value>
      <webElementGuid>32a6a083-3627-4c07-8657-f85891430cc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
