<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxNuevaTransferenciaCredicoop</name>
   <tag></tag>
   <elementGuidId>4d7c75ea-fb1d-4b4d-8724-6139b2870165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9882c55b-9478-4f18-866b-72049a7ae963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer</value>
      <webElementGuid>d6489c91-7ebd-4e32-b084-e8623d10afe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>48b16ad5-7cb3-4e37-9285-c58945f9f552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>ca83ab6d-db66-48d0-8f04-46e1770f0ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>flxBeneficiariesRowFloatingMenu</value>
      <webElementGuid>511a8168-2b56-48c2-8acd-744651cb97c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>169c0072-2014-4438-ad2c-7f7c1abd00f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva transferencia</value>
      <webElementGuid>7a667898-8f3c-4e9b-ad4b-c0f264ffe703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer&quot;)</value>
      <webElementGuid>694ba4e5-9060-44f0-a703-0573f8268a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer']</value>
      <webElementGuid>272921b1-3a4d-42ca-9105-07938f66908a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxnewTransfer']/div/div</value>
      <webElementGuid>e86ce34d-0453-437e-83d5-7ce638e5318e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver detalle'])[1]/following::div[5]</value>
      <webElementGuid>89ed4cc5-fcac-4e41-81c6-f783ad492136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[14]/following::div[13]</value>
      <webElementGuid>ef0254ab-a5cb-47c5-9b40-29bb860689fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[3]/preceding::div[1]</value>
      <webElementGuid>efb8ae67-eb6b-49be-bb54-48f5b3007d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[7]/preceding::div[6]</value>
      <webElementGuid>54f991be-2628-4405-be6d-5684a9ec6cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nueva transferencia']/parent::*</value>
      <webElementGuid>4af916f6-6446-449a-ac7e-71cd90272f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>6239027c-5ea9-4589-a81a-b8e3ad944769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer' and (text() = 'Nueva transferencia' or . = 'Nueva transferencia')]</value>
      <webElementGuid>da4307f1-fda3-40c1-9142-9b0c64668ca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
