<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxTransferenciaExitosa</name>
   <tag></tag>
   <elementGuidId>b82faa55-9dfa-4534-9a83-ddd360da5dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_lblTitleSuccess']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_TransferMessage_lblTitleSuccess</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f20c229b-50f2-43d7-9268-0a51158b983f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_TransferMessage_lblTitleSuccess</value>
      <webElementGuid>df297096-ad2f-45b7-97a6-7d80c7d58ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>6e5d326d-e5b5-4014-a4d2-6aad62f04c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>770fc3a9-a0f6-4f54-b70e-7328a88ee88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferMessage</value>
      <webElementGuid>311af460-35e7-44ae-a1cc-1620d4cf8bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSuccessTransferTitle cntmiddlecenteralign disableSelection</value>
      <webElementGuid>67c3f992-0413-4dd1-914c-b1c06238bd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transferencia realizada con éxito</value>
      <webElementGuid>a0257852-884f-4758-8974-d88e2db42e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_TransferMessage_lblTitleSuccess&quot;)</value>
      <webElementGuid>5620d6a9-44f4-4924-91aa-55059e4e0a68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_lblTitleSuccess']</value>
      <webElementGuid>518f88f1-93f1-4e92-b4fd-3b05919a65b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_flxTitle']/div[2]/div</value>
      <webElementGuid>b82ca300-ac3a-4960-977a-262d6cac5ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[5]/following::div[15]</value>
      <webElementGuid>c66ab2b6-04aa-4781-8a9d-153ebd33f08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autorizando'])[1]/following::div[24]</value>
      <webElementGuid>908a7dd2-ee6c-46d6-8001-c4e590a314a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cristinaaa Arjones'])[2]/preceding::div[1]</value>
      <webElementGuid>a762e76a-f2f7-45d6-9aa6-19e4d0ba00aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transferencia realizada con éxito']/parent::*</value>
      <webElementGuid>f925336f-9947-422a-90cf-995b368f7f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>ffcb1e79-8cd6-45d8-b9a2-c545352da410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_TransferMessage_lblTitleSuccess' and (text() = 'Transferencia realizada con éxito' or . = 'Transferencia realizada con éxito')]</value>
      <webElementGuid>5bb078b9-cf99-4ef5-bbf6-adafbe1fd5e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
