<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxBenfFavoritoNuevaTrx</name>
   <tag></tag>
   <elementGuidId>48cd6cd6-2665-41b9-9da6-f63924ca50bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_flxnewTransfer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_flxnewTransfer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>177de076-4164-4162-a389-22e53eab511a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100 sknFlxOptionFloatMenuOnHover</value>
      <webElementGuid>696befe1-6305-4f78-b10f-99d126994a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_flxnewTransfer</value>
      <webElementGuid>fbfa1e0f-1aa0-4a4c-80c9-ded5896a6eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>fe22f6d4-ccb5-47f1-8ab2-e3a0bc1d16d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>2b2be80a-f9bc-455a-8c25-ff26ffc87608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary</value>
      <webElementGuid>7da25f72-bfc4-46c7-b2cf-7099d2436ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseenter</name>
      <type>Main</type>
      <value>$KI.HoverEvent.executeHoverEvent(event, this)</value>
      <webElementGuid>0859149d-fdc6-43cc-a358-f418d1b4bc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmousemove</name>
      <type>Main</type>
      <value>$KI.HoverEvent.executeHoverEvent(event, this)</value>
      <webElementGuid>1c3afa0e-cddd-48c0-984d-a792ec300068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>$KI.HoverEvent.executeHoverEvent(event, this)</value>
      <webElementGuid>f4f4b336-7551-4226-8e44-23fabe157689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva transferencia</value>
      <webElementGuid>0d3e1ad4-cd79-4939-b407-e42b1e77dbbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_flxnewTransfer&quot;)</value>
      <webElementGuid>00df6347-962f-46d0-baff-a6be3d7e858d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_flxnewTransfer']</value>
      <webElementGuid>43e4a550-5824-4438-b5a3-40084121bd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[286]</value>
      <webElementGuid>053f41a4-6dc1-4582-8ca3-1ed3ac2382b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver detalle'])[3]/following::div[3]</value>
      <webElementGuid>60bc9895-e719-4ecb-8294-8705acb9f93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/following::div[11]</value>
      <webElementGuid>e4f39686-aa93-4106-98d9-37874a9fee94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[3]/preceding::div[3]</value>
      <webElementGuid>4d879906-cdda-4ee8-8f49-62ee10181abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>e4471003-8584-4a66-8e22-d329164c6596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclTransfers_OutstandingBeneficiary_flxBeneficiaryDataContainer3MenuBeneficiary_flxnewTransfer' and (text() = 'Nueva transferencia' or . = 'Nueva transferencia')]</value>
      <webElementGuid>5d8aa528-9f13-4d81-9ddc-ee02d05b064b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
