<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxProgramadasSolapaFecha</name>
   <tag></tag>
   <elementGuidId>b999500a-24e2-411f-857d-a75794f61d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxPostdatedRow_lblPostdatedSendDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxPostdatedRow_lblPostdatedSendDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1e13ba9-908f-480e-9006-8cfca1fe140d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxPostdatedRow_lblPostdatedSendDate</value>
      <webElementGuid>890c409d-005a-4967-86de-ec2336d29a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>185f0ca2-a097-4919-8db5-80e0a3a42f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxPostdatedRow</value>
      <webElementGuid>118e74c1-f4bc-4cba-8b9e-68ce66ff3ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segPostdated</value>
      <webElementGuid>f9024b2b-f7c9-49c9-a6c4-5b0d09128633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>B467F0CF-4244-4526-A7EF-FEC01D8AE3A3</value>
      <webElementGuid>c1d94a81-60c1-49c9-a538-c81d7c5c3661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cnttopleftalign disableSelection</value>
      <webElementGuid>88912736-596c-4bf1-afe3-a1d8f914d274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13 Jul 2023</value>
      <webElementGuid>5d174f9c-33c5-4c65-a3da-29306fc0490d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_TransferHistory_segPostdated&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxPostdatedRow_flxPostdatedRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableCommonData&quot;]/div[@id=&quot;flxPostdatedRow_lblPostdatedSendDate&quot;]</value>
      <webElementGuid>352f6591-93f1-4d01-99bc-a7d1ee9274d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxPostdatedRow_lblPostdatedSendDate']</value>
      <webElementGuid>b71d158d-2ca0-4384-9063-68cf439ce06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxPostdatedRow_flxPostdatedRow']/div[5]/div</value>
      <webElementGuid>34709b46-6eb6-4a9c-960c-f64b35115f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cristinaaa Arjones'])[2]/following::div[4]</value>
      <webElementGuid>17dbdf4a-7bdc-4d46-9db8-f08c25fc91d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 119-011835/9'])[1]/following::div[9]</value>
      <webElementGuid>b49675b3-53b1-43b0-9270-4e2777caf3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 1,00'])[1]/preceding::div[1]</value>
      <webElementGuid>48cc1368-34e9-421a-9524-a44e7a1d177d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[6]</value>
      <webElementGuid>9ad46b72-c955-4831-8f73-18657307b67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='13 Jul 2023']/parent::*</value>
      <webElementGuid>f8035141-63e6-405d-9b6a-06f241e25200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[5]/div</value>
      <webElementGuid>6667be8b-00d3-4952-a263-e6d9de6b0cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxPostdatedRow_lblPostdatedSendDate' and (text() = '13 Jul 2023' or . = '13 Jul 2023')]</value>
      <webElementGuid>4fa780c1-8463-4442-aa0c-b20a4632aa0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
