<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMontoOtrosBncosComprbnte</name>
   <tag></tag>
   <elementGuidId>e8dc3280-3e51-4eb3-a6a4-f9b4807ea275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_Receipt_lblAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_Receipt_lblAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc9a4378-e6f1-4c04-ac2c-f75bbf1df798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_Receipt_lblAmount</value>
      <webElementGuid>e3fe33f4-6407-4025-b108-04496c3f3403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>fcdeb6eb-f676-4739-96ca-5a32f208ffc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>bf689f6d-446e-4497-8976-110505cf8076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Receipt</value>
      <webElementGuid>4880eadc-2b97-4863-9a37-d5a40fa6a038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblConfirmTransfervalue1433 cntmiddlerightalign disableSelection</value>
      <webElementGuid>806ee9bc-50b4-457c-a855-a09cbc5c36aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 1,00</value>
      <webElementGuid>9673a10b-0cd6-4fa5-af8e-f25eeaad91f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_Receipt_lblAmount&quot;)</value>
      <webElementGuid>208adb28-d389-4967-a15d-d8c3910586e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_Receipt_lblAmount']</value>
      <webElementGuid>7616e955-c30d-44f2-afd8-a9c491f13da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_Receipt_flxAmountRow']/div[2]/div</value>
      <webElementGuid>86194ab9-9d10-47ea-89ef-ddb0f4a62036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[3]/following::div[2]</value>
      <webElementGuid>f7269e19-b547-4bd8-9d3a-3cd07e27e24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de emisión'])[1]/following::div[9]</value>
      <webElementGuid>c6e9b39c-d5ce-4464-b1c8-193392ada4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Origen'])[3]/preceding::div[1]</value>
      <webElementGuid>0d75be95-eb39-4ab8-a9bb-20c0c0ff6ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APELLIDO NOMBRE'])[2]/preceding::div[3]</value>
      <webElementGuid>a308d02e-b991-40a9-a7de-2b62689b805e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>b7cf1987-bf2c-4a0a-ba9e-95ea7360a0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_Receipt_lblAmount' and (text() = '$ 1,00' or . = '$ 1,00')]</value>
      <webElementGuid>81b8fa4b-18b3-4d59-9642-77adb305b2d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
