<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMontoSuperaLimite</name>
   <tag></tag>
   <elementGuidId>3581735f-f585-4478-a34e-8a3184faf5e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb691d3b-d707-4480-a59a-70cb0b42209e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip</value>
      <webElementGuid>ad7d23a2-7798-4337-a9c9-5bd550dbb3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>RichText</value>
      <webElementGuid>e98f9546-e8d9-4098-85c3-8733f1eb62e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>04183068-6b01-4690-96e7-a9b7cca64e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AmountInput</value>
      <webElementGuid>cbaef815-24be-4ee9-a09b-abe3c64dd114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknRtxValidationError </value>
      <webElementGuid>ed3d5372-b3c6-484b-8e90-80c6741580c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El monto ingresado supera tu límite disponible para realizar esta transferencia. </value>
      <webElementGuid>84da8e10-1204-41ee-8085-71eb6adb470c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip&quot;)</value>
      <webElementGuid>11e0dc9a-29e4-46ae-9697-415802d5b08e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip']</value>
      <webElementGuid>2f9a30d2-c5c8-4ee6-a8b4-b6d013ed4ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_flxValidationError']/div[3]/div</value>
      <webElementGuid>883bf29f-d98b-4eea-9809-c15f3c7c49e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El monto ingresado supera tu límite disponible para realizar esta transferencia.'])[1]/following::div[2]</value>
      <webElementGuid>367a6336-0ab3-4f2a-98bb-a21ae6da980f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[4]</value>
      <webElementGuid>7e366601-e6bc-484f-ad0a-c50e18a0f35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titularidad de la cuenta'])[1]/preceding::div[1]</value>
      <webElementGuid>353a5138-5bc1-4202-a2b5-5f2dfd17073c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/div/div[4]/div/div/div[3]/div</value>
      <webElementGuid>5d560147-1672-4c31-b6b6-19e53350c531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip' and (text() = 'El monto ingresado supera tu límite disponible para realizar esta transferencia. ' or . = 'El monto ingresado supera tu límite disponible para realizar esta transferencia. ')]</value>
      <webElementGuid>5dfbecc3-a0b0-42a1-83f2-9e75b28b2c54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
