<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxNuevaTransferenciaTercerosDolar</name>
   <tag></tag>
   <elementGuidId>c5f7f1ec-806c-45d3-9252-c0c56b7031a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>85faca73-7e71-42a4-91f2-0e9f10924648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer</value>
      <webElementGuid>e435b39b-7a65-46d1-94fc-8d83c5f15f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>669c3a5a-029f-4183-a1e3-7ae48e76b871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>6ad09bc3-2f89-4164-8ee6-a6fae295aacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>flxBeneficiariesRowFloatingMenu</value>
      <webElementGuid>8be10e0b-9af8-4d7b-9643-56651d625b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>9d2ca1eb-67d7-4c95-8dd5-6fa9580c1083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva transferencia</value>
      <webElementGuid>a562e68d-d589-43ff-9057-9148579a8854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer&quot;)</value>
      <webElementGuid>b15ef513-11ed-4afd-99bb-59cea09eacf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer']</value>
      <webElementGuid>95b07df7-d75e-466b-8e33-5662c0c4e720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_flxnewTransfer']/div/div</value>
      <webElementGuid>376a87ef-1217-4c79-a640-53578d1ae7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver detalle'])[1]/following::div[5]</value>
      <webElementGuid>6012fa43-84b5-4a17-8d73-b149789f8e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[14]/following::div[13]</value>
      <webElementGuid>0a5a883d-78fb-4141-9d85-275bc6e94261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[3]/preceding::div[1]</value>
      <webElementGuid>ddae75f6-2007-461b-a5f4-cc3b488a7ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[7]/preceding::div[6]</value>
      <webElementGuid>7580d674-638b-43bf-9d84-51f0be3581f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nueva transferencia']/parent::*</value>
      <webElementGuid>58cb5934-46ae-4774-8b17-541f75f17254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>28be25e2-f309-460a-9520-8f35df003e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_flxBeneficiariesRowFloatingMenu_lblnewTransfer' and (text() = 'Nueva transferencia' or . = 'Nueva transferencia')]</value>
      <webElementGuid>88c5a269-a804-43de-b3a8-286fff21cced</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
