<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxProgramadasConfirmFecha</name>
   <tag></tag>
   <elementGuidId>f1ff3ab2-fcf8-4152-95b4-4ebbf565dace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_ConfirmTransfer_lblRightSentDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_ConfirmTransfer_lblRightSentDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4772ba83-0372-4a2f-bfe2-3c314f246c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_ConfirmTransfer_lblRightSentDate</value>
      <webElementGuid>398de8b3-ba08-4b9e-84b4-1933f540292e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>825f4e80-9e99-4935-bd92-f625e0ec603d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>5c97e890-eb26-4b72-bb8e-eb8d777e8078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConfirmTransfer</value>
      <webElementGuid>79537c67-b3e5-4b93-9cfa-d386fec83c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddlerightalign disableSelection</value>
      <webElementGuid>90cc80c9-3ca9-421b-8167-f185feb9cc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>03 Jul 2023</value>
      <webElementGuid>6acfdf78-db9a-4e6e-a460-afcd7de10cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_ConfirmTransfer_lblRightSentDate&quot;)</value>
      <webElementGuid>68bdb85a-7972-4be5-bc02-1b5e04ba36bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_ConfirmTransfer_lblRightSentDate']</value>
      <webElementGuid>f4d7e97f-734e-4ded-9bc0-6b382663a834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_ConfirmTransfer_flxRightSentDate']/div/div</value>
      <webElementGuid>47f135c6-b247-4ea8-a909-dde92fdaf064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de envío'])[1]/following::div[5]</value>
      <webElementGuid>b7caa1a5-f2c3-4bff-9729-358b8f0ebba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuit/Cuil'])[1]/following::div[33]</value>
      <webElementGuid>871977de-939f-4e1d-8a99-335b4b521b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[1]/preceding::div[1]</value>
      <webElementGuid>0da67e37-0812-4e85-81fe-8ed337580193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Judicial'])[1]/preceding::div[3]</value>
      <webElementGuid>855beb9f-c545-459c-8942-6c8d7fbacdc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='03 Jul 2023']/parent::*</value>
      <webElementGuid>036f9fd0-6ce2-4144-923a-da5dcd539d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>c3d4f71e-dc5f-4c45-bb88-922eaaf2765a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_ConfirmTransfer_lblRightSentDate' and (text() = '03 Jul 2023' or . = '03 Jul 2023')]</value>
      <webElementGuid>b230858e-4e0b-499c-9887-327eee55bc4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
