<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrfSaldoInicialCuentaPesos</name>
   <tag></tag>
   <elementGuidId>e6ca33e6-f819-42c3-be66-fa92d9b63bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>((//div[@id='flxAccountDashboardRow_flxAmountCointainer']/div/div)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'flxAccountDashboardRow_lblAccountAmount' and (text() = '$ 23,21' or . = '$ 23,21')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3276b19b-548d-497c-82d6-5bf10da2e9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountDashboardRow_lblAccountAmount</value>
      <webElementGuid>d66775ce-b14d-4d1c-9e85-d29e683a005b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f0c5b978-fe86-418d-851a-8d985c5263c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountDashboardRow</value>
      <webElementGuid>5cb6f7ab-b306-4c85-bb96-5423eae408b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segProduct</value>
      <webElementGuid>c8bd2862-df28-4f77-906b-e3ab4af87ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>6A2E74FF-905E-43ED-A18D-FA4B6D2ABEED</value>
      <webElementGuid>f15cd729-58a5-4205-8f2b-c0ed39741a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountAmountDashboard cnttopleftalign disableSelection</value>
      <webElementGuid>a37e8bc1-e2fd-4f94-8735-2fecede3a211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 23,21</value>
      <webElementGuid>cf6083ef-d4ca-420e-88bf-4d60c5778f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsLanding_AccountContainer_segProduct&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountDashboardRow_flxAccountDashboardRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountDashboardRow_flxAmountCointainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblAccountAmountDashboard&quot;]/div[@id=&quot;flxAccountDashboardRow_lblAccountAmount&quot;]</value>
      <webElementGuid>3cdfbbc5-552b-4b7e-8a1f-099c47cdfb7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountDashboardRow_lblAccountAmount'])[2]</value>
      <webElementGuid>24253fed-7bd0-4447-bc45-5c7e38f7e036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountDashboardRow_flxAmountCointainer']/div/div)[2]</value>
      <webElementGuid>e576f09c-b0cf-42ed-859b-3708c21194cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 060-006575/5'])[1]/following::div[5]</value>
      <webElementGuid>542511b4-0adf-4860-887c-7228baa33a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[7]</value>
      <webElementGuid>e2904817-048a-43a6-bc6a-d0bbe979fab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>c92b5ec8-b4f7-4805-9365-1c2859c820ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro U$S 1'])[1]/preceding::div[6]</value>
      <webElementGuid>bbdc9598-366e-49e7-a751-bc17de301621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 23,21']/parent::*</value>
      <webElementGuid>f2bbffe9-0e0c-4635-92d6-9f24878d54f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/ul/li[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>2d9692bc-774b-4cc4-81ae-6047bfb426b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountDashboardRow_lblAccountAmount' and (text() = '$ 23,21' or . = '$ 23,21')]</value>
      <webElementGuid>8041e045-d231-4677-8a4c-6de49aa96e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
