<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnBuscarHistorialPago</name>
   <tag></tag>
   <elementGuidId>8c4778b0-a6d1-48f3-9f80-ab2a4a1abf7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmPaymentsHistoryBccl_btnSearchFilterDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPaymentsHistoryBccl_btnSearchFilterDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b79f66da-0883-41cb-898b-13a55fa75c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl_btnSearchFilterDate</value>
      <webElementGuid>b0ecff97-9180-47c1-9380-e3b206059026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>b7fdbf82-1efc-45df-9f09-1f92e673f425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl</value>
      <webElementGuid>3172f9d3-349c-4de9-87bd-9b14f89789bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbd3fb8a-8aeb-4dfc-acab-07c815248e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>f1e04ff9-6045-488f-84e3-115e6c3b754c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>ca4d2699-4090-47c2-be48-fab13f8dbf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>2a9ab720-3d4c-4e2d-924c-6bf69d9aedfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPaymentsHistoryBccl_btnSearchFilterDate&quot;)</value>
      <webElementGuid>2c7001f0-261d-4ec0-82cb-0e6f39983953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPaymentsHistoryBccl_btnSearchFilterDate']</value>
      <webElementGuid>3d686bd8-749d-4991-8af4-0991de068d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_flxContainerButtonsFilterDate']/div/input</value>
      <webElementGuid>0f1e5281-0c42-44a6-8f79-4ff4f642b36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>b751896a-b711-4c31-912c-f02e584086dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPaymentsHistoryBccl_btnSearchFilterDate' and @type = 'button']</value>
      <webElementGuid>2c09e9a7-9172-48bb-9ec6-371853ef24ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
