<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnConfirmarEliminarServicio</name>
   <tag></tag>
   <elementGuidId>d4259b24-a7a9-4684-a692-ced606c66ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_ConfirmPopup_btnConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclServicesPay_ConfirmPopup_btnConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5962e850-1a9b-4cf0-ae30-cb9ea10ab3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_ConfirmPopup_btnConfirm</value>
      <webElementGuid>18e4ee35-286a-4e62-9cdf-ced3066fd694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>457d814e-6185-4ed1-aa78-0d553c48aec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>2fa6b3fd-2d7e-4382-bf39-72995b5baac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConfirmPopup</value>
      <webElementGuid>5f68907c-bd1b-4b74-a6ff-29e88b99bc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2e5973c-436d-4854-8a2a-bd9f513d7cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>905cf8ba-c6fc-4916-8f9e-40ee66ab46d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sí</value>
      <webElementGuid>44b7e093-c0ee-47e0-b0f7-11627d78a16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>65966526-d220-4d88-8855-39fa48930431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_ConfirmPopup_btnConfirm&quot;)</value>
      <webElementGuid>6a288d71-6f80-4862-b6c7-92029d574fc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclServicesPay_ConfirmPopup_btnConfirm']</value>
      <webElementGuid>8ae98c19-03a5-4f6b-ad94-e3fbfb9df2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_ConfirmPopup_flxConfirmPopup']/div[7]/input</value>
      <webElementGuid>e7898dc4-073d-4e88-bab3-24248efa4b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/div[7]/input</value>
      <webElementGuid>86a4f30c-d903-48de-955a-0bd44585efbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclServicesPay_ConfirmPopup_btnConfirm' and @type = 'button']</value>
      <webElementGuid>040394ea-85e8-47df-9f90-72a8d9a96d61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
