<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnConfirmarByPass</name>
   <tag></tag>
   <elementGuidId>5351e767-6fa1-456f-9449-eaaf5b7ea920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclServicesPay_PanelBillPay_SecondFactor_ButtonConfirm_btnWithLoader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_PanelBillPay_SecondFactor_ButtonConfirm_btnWithLoader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b477670-8861-46d1-ba43-bbe6891042cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>0bb89cc1-327a-484d-95a1-f5a1cc5f2c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmBcclServicesPay_PanelBillPay_SecondFactor_ButtonConfirm_btnWithLoader-hint</value>
      <webElementGuid>2a363612-884f-4f93-b9b3-072cb27d3521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_PanelBillPay_SecondFactor_ButtonConfirm_btnWithLoader</value>
      <webElementGuid>023e320b-5e8d-41b4-8073-b6bd7c7a14ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>64877b80-7787-4416-b071-6a0d01129666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>f7668989-7bd0-4ce7-8a1b-f0503c923e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBillPay_SecondFactor_ButtonConfirm</value>
      <webElementGuid>b93e76d2-3726-4da7-8bb3-c1c45b563b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0d51ca10-bdf6-4e6f-8e77-02e55c62f118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>0eb06c0d-6d1e-493d-9755-14cc63e4f169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>cca1cc30-9ec4-4d1f-bf5c-6b1cbf6394c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>9a4f934d-ec60-4aa8-9099-b1a5ec92f333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelBillPay_SecondFactor_ButtonConfirm_btnWithLoader&quot;)</value>
      <webElementGuid>6dc6c6f0-d485-4c36-84eb-d1480728be56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclServicesPay_PanelBillPay_SecondFactor_ButtonConfirm_btnWithLoader']</value>
      <webElementGuid>e2a50161-8a2b-4c14-a3a5-6ceb52469d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_SecondFactor_ButtonConfirm']/div/input</value>
      <webElementGuid>98ce78c7-348a-40e6-8450-ee0c32f72270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>f051cc95-12d0-425a-bc6c-2574da5453cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclServicesPay_PanelBillPay_SecondFactor_ButtonConfirm_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>2a7d638d-8ebd-4fed-8f48-7f794a5bc472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
