<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPYRConfirmarByPassPago</name>
   <tag></tag>
   <elementGuidId>83daafdb-419e-4863-b5b1-57e217328c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SecondFactor_ButtonConfirm_btnWithLoader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_AddEntePanel_AddEnte_SecondFactor_ButtonConfirm_btnWithLoader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>685abd7c-8c02-48b7-8107-1eb91e11d8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>697d5d61-63a1-4205-a45c-1aff4d393728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmBcclServicesPay_AddEntePanel_AddEnte_SecondFactor_ButtonConfirm_btnWithLoader-hint</value>
      <webElementGuid>a1c99d1a-0507-443c-bd12-953c78b26bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_AddEntePanel_AddEnte_SecondFactor_ButtonConfirm_btnWithLoader</value>
      <webElementGuid>d1509c26-ed5e-4c26-b0bc-13e136cb9a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>5030d7df-194a-4314-92b8-1c18c94fe7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>fb1e69a0-40fe-4ff2-9e1c-596dd64273da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AddEntePanel_AddEnte_SecondFactor_ButtonConfirm</value>
      <webElementGuid>897819a6-a060-4f6b-92e2-20c805116fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7eae0e1f-9329-47c4-ae14-babca3b26b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>e77b5dd0-e6de-4178-9fee-8344d5e0bf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>fc0bdbfe-a1f6-4411-b400-1023a7889757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>c56bc3b0-8180-4dfc-9344-fa6eefafdbfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_AddEntePanel_AddEnte_SecondFactor_ButtonConfirm_btnWithLoader&quot;)</value>
      <webElementGuid>da030e68-5a7f-436e-acd2-76a84805500f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SecondFactor_ButtonConfirm_btnWithLoader']</value>
      <webElementGuid>a9d38f50-1912-45e8-b651-466b31b29b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SecondFactor_ButtonConfirm']/div/input</value>
      <webElementGuid>d31719f6-af7c-45d3-b519-738785007ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>84ecc9fb-b07f-43d2-b28e-e193044faa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclServicesPay_AddEntePanel_AddEnte_SecondFactor_ButtonConfirm_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>950580c9-6a5b-4a0e-9a8f-227279a6db6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
