<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnPYRConfirmarPagoServicio</name>
   <tag></tag>
   <elementGuidId>73608d2b-bd1e-4ff5-83bc-5850df03ce19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclServicesPay_AddEntePanel_AddEnte_btnConfirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_AddEntePanel_AddEnte_btnConfirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>440ff68e-7976-4e48-a061-7ccc53c71ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_AddEntePanel_AddEnte_btnConfirm</value>
      <webElementGuid>167996bc-10c5-45a7-96f3-407dbf89730a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>e4199550-3842-43a5-9d1c-f61a4b767a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>bdcbe00b-6050-492d-9167-c1319137971e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AddEntePanel_AddEnte</value>
      <webElementGuid>e609d57e-8f9a-4e6a-8c52-8ed8cb7466e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8cf39011-bd05-4a93-9397-ee64398129b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknBtnPrimary</value>
      <webElementGuid>554f4be0-1d89-4f3d-83a7-2edb1af45442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar pago</value>
      <webElementGuid>9e9ec728-5227-470d-869b-b198221c82ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimaryBold</value>
      <webElementGuid>752433dd-bb81-45a8-8582-804c185823b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>90d28c70-de22-4c7b-939a-77117f8222fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_AddEntePanel_AddEnte_btnConfirm&quot;)</value>
      <webElementGuid>c2bec099-709a-4da8-af26-10d8d78384d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclServicesPay_AddEntePanel_AddEnte_btnConfirm']</value>
      <webElementGuid>b5b8b74e-f97b-4e1b-90ee-d21fae7f9a56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_flxButtonsContainer']/div[2]/input</value>
      <webElementGuid>ae631755-caca-4faa-9084-c30bfe581741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>f5338c24-ecdb-4b36-8d23-aab175aa6ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclServicesPay_AddEntePanel_AddEnte_btnConfirm' and @type = 'button']</value>
      <webElementGuid>94bdc2b7-f57b-4654-9edc-d228b4b3bab2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
