<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoPYRCalendarioDiaDesdeHistorialPagos</name>
   <tag></tag>
   <elementGuidId>f6cab2fc-e54d-40a8-a38b-f915175dca98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-kony-w-c-cell-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#-kony-w-c-cell-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9a7c61c-d922-490f-ac4c-681beee7eb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>cc77d28b-0ff5-4c81-adfe-7b2c6a80bcf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DateFilter</value>
      <webElementGuid>727468e0-843c-4457-a5cf-5e9e5e35e3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>ad172dcf-0dbc-41e3-b576-cd7167f5197e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-k-w-c-weekday-1 -kony-w-c-day- sknCalendarSelected</value>
      <webElementGuid>8a9e91dd-322c-476d-bd94-31aa206c233c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-kony-w-c-cell-16</value>
      <webElementGuid>7cac01d9-4086-412a-92d3-92bb8cf3416c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>dfd1382a-cefd-44d9-9f5b-7ffd7b9adfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weekday</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>914f8e2f-a44b-4c18-936a-e45e1ab75922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-hold-day</name>
      <type>Main</type>
      <value>3,1,2022</value>
      <webElementGuid>759b8e15-1e16-4f87-b6e4-d9006b65192e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-date-retrieve</name>
      <type>Main</type>
      <value>3,1,2022</value>
      <webElementGuid>27cc78a0-8d5b-4b5e-b109-c24cda3a90ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7fcb8a2b-4034-4888-b992-7291e0ed7b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value> 3rd January 2022</value>
      <webElementGuid>8ec0f75e-7dcc-4d2e-9137-6ba72a0da0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>14654ea0-11d6-41cb-9d5a-4aa9b8b12e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-kony-w-c-cell-16&quot;)</value>
      <webElementGuid>e8e6270e-321f-406a-bed0-c66b3a6d554f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='-kony-w-c-cell-16']</value>
      <webElementGuid>826dcc08-ee13-4972-9c68-457f1f6061b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-1-2022']/div[2]/div[2]/div/div[2]</value>
      <webElementGuid>9de0f1f4-b46f-4f69-a639-0ec6a83b925f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sáb'])[1]/following::div[14]</value>
      <webElementGuid>ef8e2a38-8f3f-4666-861f-b58fe1f65346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vie'])[1]/following::div[15]</value>
      <webElementGuid>0677cc1d-5a07-4075-9ef3-2ce446d0b9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[44]</value>
      <webElementGuid>06bff646-7625-41c9-bea7-7b259b17e2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[46]</value>
      <webElementGuid>4dd33273-1d42-4af8-90bf-e7b70919d209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3']/parent::*</value>
      <webElementGuid>42b6b9d9-7682-48f4-8cd3-73c8e4846d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]</value>
      <webElementGuid>82d9aac2-736b-45dc-b785-015beb3cc3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '-kony-w-c-cell-16' and (text() = '3' or . = '3')]</value>
      <webElementGuid>245a5264-a105-4592-9d7a-d5d553a683dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
