<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoPYRBorrarServicio</name>
   <tag></tag>
   <elementGuidId>4050def0-50d2-498f-8c58-0e92a198e040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxServicesPayRow_lblTrash'])[27]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'flxServicesPayRow_lblTrash' and (text() = '' or . = '')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d98b80df-8041-4fcc-b6f5-4531898c9e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxServicesPayRow_lblTrash</value>
      <webElementGuid>3678d577-9a91-4809-ab84-e13195b7f580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>59cde59a-2269-4bc9-904b-17cbc480cba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxServicesPayRow</value>
      <webElementGuid>17bdbdc3-85a2-4055-985e-1d8c10709491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segServices</value>
      <webElementGuid>61e8ed7d-6905-47e1-a431-36fe5d258fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>5BE41FC4-9B6C-4108-9AF8-D9779A007E9B</value>
      <webElementGuid>f1f69368-d2f6-41ab-8090-efc93c6ceb53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblFALight14666666 cntmiddlerightalign disableSelection</value>
      <webElementGuid>7e215ad1-a1f0-4c8b-ae4e-9e3794880a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a18fd7df-4e0d-408c-a330-2c8e30995956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelServices_ServicesPay_segServices&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxMainContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxIconsContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxTrashContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblFALight14666666&quot;]/div[@id=&quot;flxServicesPayRow_lblTrash&quot;]</value>
      <webElementGuid>aa66b9b8-a494-4c1e-a39f-bfa61666391b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxServicesPayRow_lblTrash'])[27]</value>
      <webElementGuid>73aab57c-9246-4696-9d29-adac19de4843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxServicesPayRow_flxTrashContainer']/div/div)[27]</value>
      <webElementGuid>db8297e2-3990-46e4-8197-576e97c2850e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[27]/following::div[5]</value>
      <webElementGuid>9c76d3a2-83c2-41d7-9af7-77d363c1614a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrogas Antiguo'])[2]/following::div[18]</value>
      <webElementGuid>5010b78b-4a56-4ae6-affd-f9058433b304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrogas Antiguo'])[3]/preceding::div[8]</value>
      <webElementGuid>ce2675d4-60c4-40e5-873c-89c4cfe108a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrogas Antiguo 517'])[1]/preceding::div[10]</value>
      <webElementGuid>3ac9a263-e0d1-48f2-9217-560c16b0685e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[27]/div/div/div/div/div/div[3]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>79ac35f2-67da-405c-906d-6cdbd77ff6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxServicesPayRow_lblTrash' and (text() = '' or . = '')]</value>
      <webElementGuid>94fa197e-1ae1-4cc2-a1e2-1be98c8bb3af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
