<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoPYRCalendarioFechaDesdeHitorialPagos</name>
   <tag></tag>
   <elementGuidId>9b00eb0f-2721-4283-92a2-836b60c22392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='calendarDateFilterFrom_img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendarDateFilterFrom_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e394eadf-b1da-44e7-9d56-8f1e91b1fc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendarDateFilterFrom_img</value>
      <webElementGuid>45a13519-7916-4244-b5db-920b4f2dfca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ac7f64c6-58b1-4182-9cbb-f05d52351cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/calendar-regular.svg</value>
      <webElementGuid>825c7f4f-3330-4068-a90b-718945aa0720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xalign</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>970be87c-6209-4848-891f-ee820a772f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>$KW.Calendar.setCalElementStyle(this,false)</value>
      <webElementGuid>beb759f6-6f5c-4a0e-b1f2-f6ed24b10307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>cc493299-6e70-4221-95f0-f38476cac1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DateFilter</value>
      <webElementGuid>828253de-42dd-45ae-9aa5-21413397ec5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d9e2725-0fd1-44ff-bb3d-3456bd5bc522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDateFilterFrom_img&quot;)</value>
      <webElementGuid>a9ab32a7-28e4-451e-b66f-5871914a4686</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='calendarDateFilterFrom_img']</value>
      <webElementGuid>3d5e579f-5e2e-48be-8e3a-60acd48506b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_DateFilter_calendarDateFilterFrom']/img</value>
      <webElementGuid>6c9aa8ce-ea22-451e-8929-7200d04ed9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Calendar']</value>
      <webElementGuid>e5bae5a2-44d9-4f73-8fe0-5fdfd17e1fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>d83bf6ee-a6c3-426a-b854-c873fe4e531e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'calendarDateFilterFrom_img' and @type = 'image' and @src = 'desktopweb/images/calendar-regular.svg' and @alt = 'Calendar']</value>
      <webElementGuid>6f9cea82-c83c-46dd-bf71-452c928b0295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
