<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblConceptoDetalle</name>
   <tag></tag>
   <elementGuidId>2d273c39-d010-4e6d-bf23-6445c49c39b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_PanelBillPay_lblConceptData']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_PanelBillPay_lblConceptData</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>378273b5-70d4-4bc2-b6c3-a9545ca31ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_PanelBillPay_lblConceptData</value>
      <webElementGuid>e318681b-e5d9-4a4d-ab6c-768b5d579de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>1d96da69-f8bb-4402-9b25-3f4c321ccc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>45efdc8e-e064-45b9-8cd6-cb7f8288f0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBillPay</value>
      <webElementGuid>cc678b1c-ef0b-4f96-9a8c-e51f57db46c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1433 cntmiddlerightalign disableSelection</value>
      <webElementGuid>cab5060d-2592-4259-a28b-680efd152511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cuota</value>
      <webElementGuid>220a9005-6868-4da8-b451-6eabf17c9c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelBillPay_lblConceptData&quot;)</value>
      <webElementGuid>ea09406d-1186-42ba-9f84-4c29a387b6a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_lblConceptData']</value>
      <webElementGuid>2a03e0ad-28d7-4a86-b874-bf768306beb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_flxConceptContainer']/div[2]/div</value>
      <webElementGuid>ada0d8be-e86f-4932-9f1f-531834154453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[6]/following::div[2]</value>
      <webElementGuid>2643904b-c56a-4315-8f3b-207549c6d195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[139]/following::div[7]</value>
      <webElementGuid>d233ed45-1492-4cd1-9913-cad79ded9a6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moneda de pago'])[2]/preceding::div[1]</value>
      <webElementGuid>c00d5b39-f5eb-4b58-8153-2820d1c116dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[4]/preceding::div[15]</value>
      <webElementGuid>589f779e-23ce-41b4-b0a4-652605546a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div/div/div/div/div/div[5]/div/div/div[2]/div</value>
      <webElementGuid>db96cd01-5265-4e75-b789-33db5c605431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_PanelBillPay_lblConceptData' and (text() = 'Cuota' or . = 'Cuota')]</value>
      <webElementGuid>42cc3cf7-a047-4f28-a1cc-cfa00fafff87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
