<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblIdentificadorDetalle</name>
   <tag></tag>
   <elementGuidId>928d87f3-4965-4755-84d4-e5bb274e7a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_PanelBillPay_lblBillData']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_PanelBillPay_lblBillData</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d286e04d-94e4-45a7-82d2-1d2d7258ee13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_PanelBillPay_lblBillData</value>
      <webElementGuid>e449c043-77d5-485f-9e41-7a2e3c5c8212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>fb277cfa-3a92-4ca7-8da8-2e3498b41ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>b9e3aa27-2347-4bee-a48b-a1a740287dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBillPay</value>
      <webElementGuid>797d9e9c-b01c-4d00-8d39-74240e679db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1433 cntmiddlerightalign disableSelection</value>
      <webElementGuid>49dc9145-9ed6-47ba-8384-3002ff5a0896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0474921</value>
      <webElementGuid>5e65561a-a8dd-4a9e-a546-98979f3f676e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelBillPay_lblBillData&quot;)</value>
      <webElementGuid>36a46b2b-5ed3-4101-a1dd-c8588d21cf96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_lblBillData']</value>
      <webElementGuid>85fa0be8-5cc8-4172-8d44-7f1c43f52c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_flxBillContainer']/div[2]/div</value>
      <webElementGuid>66bcabe7-d3fb-4281-b0c4-d5562f5ac65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cód. de identificación'])[7]/following::div[2]</value>
      <webElementGuid>3ecbbd82-39cc-404d-863b-fdcfb237e79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[138]/following::div[7]</value>
      <webElementGuid>9c2cb361-f43f-41d5-b516-faf4bf60618e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vencimiento'])[7]/preceding::div[1]</value>
      <webElementGuid>4ec4384a-fcd1-4921-a545-cda43f148e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[139]/preceding::div[3]</value>
      <webElementGuid>e8753f18-83ce-474f-b718-5a74cbe8f829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div/div/div/div/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>82684997-3cbf-4cdf-ba2f-a24fa500fab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_PanelBillPay_lblBillData' and (text() = '0474921' or . = '0474921')]</value>
      <webElementGuid>83da4281-82ef-4e35-90ee-50b075f41eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
