<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPYRSinPagosRealizados</name>
   <tag></tag>
   <elementGuidId>c8f8582e-153e-4000-931f-9f30a399af12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmPaymentsHistoryBccl_NoResults_lblNoResultsTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmPaymentsHistoryBccl_NoResults_lblNoResultsTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c1442af-e359-4d03-858b-98877f597e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl_NoResults_lblNoResultsTitle</value>
      <webElementGuid>bfaf79c8-3921-470d-b3c8-5d79e63dc1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f79f8fc0-3a69-437e-b51c-039c65837ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl</value>
      <webElementGuid>6048e8c1-e9d0-4f16-aca1-a0f35175ae7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>NoResults</value>
      <webElementGuid>14cf5323-63b2-443d-a797-579f27cfc531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblNotificationMessageEmptyTable cntmiddleleftalign disableSelection</value>
      <webElementGuid>c280a169-c45d-465f-a410-6f9d6ec58851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No se encontraron pagos realizados.</value>
      <webElementGuid>935549ab-33e5-43ba-85f4-433abfcfb17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPaymentsHistoryBccl_NoResults_lblNoResultsTitle&quot;)</value>
      <webElementGuid>72a86f2a-4ca0-47bb-ad50-b707c8df29fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_NoResults_lblNoResultsTitle']</value>
      <webElementGuid>96cbf1bc-97cd-4f1b-8cb2-c7b981a11757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_NoResults_flxMessageContainer']/div/div</value>
      <webElementGuid>80347d2e-181f-4215-ae1b-7e17afc553ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[12]</value>
      <webElementGuid>1a236a19-9f08-45df-bdcb-4db0dcabc808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[19]</value>
      <webElementGuid>afbd3a70-e947-4437-af66-fa48599cb748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[298]/preceding::div[4]</value>
      <webElementGuid>421699be-4f23-4fc1-9feb-05725689aeee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credicoop Digital'])[1]/preceding::div[23]</value>
      <webElementGuid>d10f7822-3f7e-4b52-a551-8050b265a4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No se encontraron pagos realizados.']/parent::*</value>
      <webElementGuid>fdb535f9-b1fa-4521-8793-adecf8fb041c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>55f674eb-fea2-4c13-bfce-ba199acde8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmPaymentsHistoryBccl_NoResults_lblNoResultsTitle' and (text() = 'No se encontraron pagos realizados.' or . = 'No se encontraron pagos realizados.')]</value>
      <webElementGuid>44a12161-bbd6-4cfd-8b2b-1a24d2ea4c70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
