<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPYRMontoErroneo</name>
   <tag></tag>
   <elementGuidId>00f8087e-bb02-414d-905d-7e93f538f8f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_PanelBillPay_AmountInput_lblValidationErrorMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_PanelBillPay_AmountInput_lblValidationErrorMessage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2068c0f-e4ea-4104-9b2a-703ff89ba705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_PanelBillPay_AmountInput_lblValidationErrorMessage</value>
      <webElementGuid>ffffe526-e1be-4ac2-b139-2f5cd6f6a4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>cf37f047-c62b-4ef5-8b48-218c4ff12086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>b33213fe-4585-42d3-bc7f-cb320ba24245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBillPay_AmountInput</value>
      <webElementGuid>5d41d99d-c595-4e95-98fc-a6dc2833c248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddleleftalign disableSelection sknLblValidationWarningMessage</value>
      <webElementGuid>1e20fe0e-2858-492d-bbff-c7ac37fdc021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El monto supera el saldo de tu cuenta</value>
      <webElementGuid>2069989a-8e0b-46ab-b98b-cec57367ed25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelBillPay_AmountInput_lblValidationErrorMessage&quot;)</value>
      <webElementGuid>1b4f9306-9ed3-437d-9d7c-1725fc01d649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_AmountInput_lblValidationErrorMessage']</value>
      <webElementGuid>04ba40ee-d979-4eb6-aef4-9816d933c85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_AmountInput_flxValidationError']/div[2]/div</value>
      <webElementGuid>11ec6634-d1ab-4a2e-a4ad-9d0487752061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[8]/following::div[2]</value>
      <webElementGuid>d06e2411-184a-4f71-8858-dda9c94be295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite disponible para transferir: $ 80.000,00'])[4]/following::div[7]</value>
      <webElementGuid>3eadf307-0685-4b62-82a9-c410633f3c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/preceding::div[1]</value>
      <webElementGuid>970f1f19-8c32-41be-b5be-6d2e8c967919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='El monto supera el saldo de tu cuenta']/parent::*</value>
      <webElementGuid>f0c402bd-3821-4384-9b59-fb28c486c6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div/div/div/div[4]/div/div/div[2]/div</value>
      <webElementGuid>aeabf8c0-609a-40a7-a78e-029858bc2a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_PanelBillPay_AmountInput_lblValidationErrorMessage' and (text() = 'El monto supera el saldo de tu cuenta' or . = 'El monto supera el saldo de tu cuenta')]</value>
      <webElementGuid>2b8c5f9a-884f-4fae-b7a5-ca8e682d365a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
