<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPYRServicioLista</name>
   <tag></tag>
   <elementGuidId>f0ae98d1-7bc9-4bc6-8062-553449b3acf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxCardPaymentsAndOtherMaturities_lblTaxService'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c673e525-8628-4e34-92ef-4f900fdcd2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCardPaymentsAndOtherMaturities_lblTaxService</value>
      <webElementGuid>8b976949-d7ad-4bf1-bbd5-8b32a6c87033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>fff4039b-28a2-40b0-acda-4d74daa2e6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCardPaymentsAndOtherMaturities</value>
      <webElementGuid>365c39a4-5a45-4f24-8edd-b1ffd895589c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segCardPaymentsAndOtherMaturities</value>
      <webElementGuid>ec398eed-2066-4c0e-a8af-fc3c041ed702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>CE159F46-EC1E-48CE-A84E-B973C627BABE</value>
      <webElementGuid>ad9800da-1580-4ec0-b931-9d2a6b10082f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberDataAssociatedService cntbottomleftalign disableSelection</value>
      <webElementGuid>ad9adaa8-3994-4a6e-a502-ff7b234e3a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iplan Networks</value>
      <webElementGuid>135005e6-e340-40c9-a397-7dd6b2e2035d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_CardPaymentsAndOtherMaturities_segCardPaymentsAndOtherMaturities&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardPaymentsAndOtherMaturities_flxCardPaymentsAndOtherMaturities&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardPaymentsAndOtherMaturities_flxAssociatedServicesRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardPaymentsAndOtherMaturities_flxServiceDescription&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardPaymentsAndOtherMaturities_flxLblServiceInfo&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberDataAssociatedService&quot;]/div[@id=&quot;flxCardPaymentsAndOtherMaturities_lblTaxService&quot;]</value>
      <webElementGuid>85bb2f44-b5f2-42ad-9c67-c12889e475fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxCardPaymentsAndOtherMaturities_lblTaxService'])[6]</value>
      <webElementGuid>fdaf511c-c7a5-4dee-9ddb-c14697f60d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxCardPaymentsAndOtherMaturities_flxLblServiceInfo']/div/div)[11]</value>
      <webElementGuid>e74cffca-d287-4a76-a781-f7c49d338e1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagar'])[5]/following::div[22]</value>
      <webElementGuid>f6da7b05-45a1-4ca1-bdd1-1eaa35f0339a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[10]/following::div[27]</value>
      <webElementGuid>60c1e13b-f271-40b8-9e98-bb659f31c8bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iplan Networks'])[2]/preceding::div[1]</value>
      <webElementGuid>86d42813-c96e-42d2-9908-9661e7d3e1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuota'])[3]/preceding::div[5]</value>
      <webElementGuid>e2285eeb-072d-4389-9057-4acb34a99330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Iplan Networks']/parent::*</value>
      <webElementGuid>07e9770a-27be-4583-816a-04e374a22151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>214af23d-95c8-4e0e-a29f-611aec9e9918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCardPaymentsAndOtherMaturities_lblTaxService' and (text() = 'Iplan Networks' or . = 'Iplan Networks')]</value>
      <webElementGuid>736825f9-f674-435e-88d3-b6e3893352fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
