<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPYRListaHistorialNroOperacin</name>
   <tag></tag>
   <elementGuidId>b416ec79-17cd-4321-9379-4d741950d437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmPaymentsHistoryBccl_lblNumOp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmPaymentsHistoryBccl_lblNumOp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a6cd183c-a5a0-4fb1-a513-75f6c96500a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl_lblNumOp</value>
      <webElementGuid>0bbc2ad1-4b3c-422e-994b-5505f4bdb978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>da325a5a-0392-4d15-ab52-a55ee22a17d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl</value>
      <webElementGuid>e2d34d97-3b90-4981-aaa9-6aa0cb6fbd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableTitle3 cntmiddleleftalign disableSelection</value>
      <webElementGuid>815c6a4a-3240-4499-b3f6-ba567126dbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Núm. de operación</value>
      <webElementGuid>7879c1dd-8526-44a2-8acc-7687bf52323c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPaymentsHistoryBccl_lblNumOp&quot;)</value>
      <webElementGuid>af71d49a-b6cc-43cd-9953-af81abe4b748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_lblNumOp']</value>
      <webElementGuid>5b743673-fd42-4b47-bea6-7c9756548628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_flxContainerNumOp']/div/div</value>
      <webElementGuid>272b13a5-3fcc-4809-a2e8-6c6b9ddbf210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anotación personal'])[2]/following::div[5]</value>
      <webElementGuid>c9ea4493-1f55-45f8-9dbb-8dd42c8b37e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio'])[1]/following::div[10]</value>
      <webElementGuid>4ef1c085-5c26-4a99-8119-017e6edb5a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Origen'])[1]/preceding::div[1]</value>
      <webElementGuid>385e0288-6a0f-4a44-a4b0-c6096fc289bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Importe'])[1]/preceding::div[6]</value>
      <webElementGuid>1c0abd05-6541-42bd-8b54-caf5eab7c10b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Núm. de operación']/parent::*</value>
      <webElementGuid>015af499-3006-44a7-acdc-25ab214b932a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>ee06c6da-6281-427d-94f9-508178cd7115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmPaymentsHistoryBccl_lblNumOp' and (text() = 'Núm. de operación' or . = 'Núm. de operación')]</value>
      <webElementGuid>bcbea9f9-3291-439b-8ae9-7f316b5378c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
