<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPYRListaHistorialServicio</name>
   <tag></tag>
   <elementGuidId>e1ef7271-d17b-4b12-bdf6-7e3619b30ea0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmPaymentsHistoryBccl_lblServicio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmPaymentsHistoryBccl_lblServicio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>606d6340-a21b-47f1-8ee0-c83a3677f2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl_lblServicio</value>
      <webElementGuid>f8f3093a-d329-4006-8100-d878ecb10486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>7fb3d8b7-a2e6-488f-bf14-6fca1cce929f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl</value>
      <webElementGuid>dcc9af49-7669-4783-bedc-6c039d97a6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableTitle3 cntmiddleleftalign disableSelection</value>
      <webElementGuid>94267cae-5ace-410e-bd91-e83b3035584f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Servicio</value>
      <webElementGuid>65abdca9-6aa4-4cc4-b506-75a697ae5419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPaymentsHistoryBccl_lblServicio&quot;)</value>
      <webElementGuid>6c42891d-41b7-4c49-a1c0-a59d0991fc08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_lblServicio']</value>
      <webElementGuid>5b65b1d2-8395-48f1-bd20-2d9d33507fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_flxContainerServicio']/div/div</value>
      <webElementGuid>9b3b71bd-e023-431c-af73-cfa5662fe95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha'])[2]/following::div[5]</value>
      <webElementGuid>136cf319-42e3-408d-adf7-e94837d2b51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[5]/following::div[22]</value>
      <webElementGuid>16f3f2d2-f158-4282-bd1d-de0a4a488324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anotación personal'])[2]/preceding::div[1]</value>
      <webElementGuid>56e93c3b-1111-4de9-a3fe-39a63a3486c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Núm. de operación'])[1]/preceding::div[6]</value>
      <webElementGuid>73f8267d-f0f4-4a88-9a6a-a6449b6c0aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Servicio']/parent::*</value>
      <webElementGuid>b75a4505-735e-4864-8a91-c5027883374c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>8634f0ae-89f6-45cb-96a9-b3b73289377f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmPaymentsHistoryBccl_lblServicio' and (text() = 'Servicio' or . = 'Servicio')]</value>
      <webElementGuid>eb2868ef-ddc0-4902-8333-147b4bd7d031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
