<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPYRListaHistorialFecha</name>
   <tag></tag>
   <elementGuidId>c866868d-9dd0-4341-b099-f2808391f226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmPaymentsHistoryBccl_lblFecha</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmPaymentsHistoryBccl_lblFecha&quot;)[count(. | //*[@id = 'frmPaymentsHistoryBccl_lblFecha' and @kformname = 'frmPaymentsHistoryBccl' and @class = ' sknLblTableTitle3 cntmiddleleftalign disableSelection' and (text() = 'Fecha' or . = 'Fecha')]) = count(//*[@id = 'frmPaymentsHistoryBccl_lblFecha' and @kformname = 'frmPaymentsHistoryBccl' and @class = ' sknLblTableTitle3 cntmiddleleftalign disableSelection' and (text() = 'Fecha' or . = 'Fecha')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmPaymentsHistoryBccl_lblFecha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>087c4ffa-89d9-4df3-abbb-8113f4a0fa76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl_lblFecha</value>
      <webElementGuid>aee76c70-5b52-4d8c-a012-2c24144904f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>06e60fb9-f7dc-49cb-b257-4238a021c613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl</value>
      <webElementGuid>e71accf3-6670-4251-98e9-b3d7c9b3538a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableTitle3 cntmiddleleftalign disableSelection</value>
      <webElementGuid>9b2cac19-4119-4a83-bc9e-fe4b69cb07b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha</value>
      <webElementGuid>cfac1858-d17a-4e08-841e-697538d1ae10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPaymentsHistoryBccl_lblFecha&quot;)</value>
      <webElementGuid>60914f6b-db4f-45b5-bc19-fd19aa519c68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_lblFecha']</value>
      <webElementGuid>0ab0865f-1728-4b2b-ab0e-de26b3338e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_flxContainerFecha']/div/div</value>
      <webElementGuid>0b7adf5f-5b5c-4e30-a63f-d69ac3244338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[5]/following::div[17]</value>
      <webElementGuid>0a58834b-4d14-401b-8e4c-942377b39fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[19]</value>
      <webElementGuid>338c9afe-a63e-4992-ab78-280b1d04e1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio'])[1]/preceding::div[1]</value>
      <webElementGuid>dae8c42b-f41c-4dd5-8237-4edae703e315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anotación personal'])[2]/preceding::div[6]</value>
      <webElementGuid>ed88bf0b-e1b2-4283-a54d-b118f9d1a164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>eb6f21e8-4e30-4833-946b-5883a98be41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmPaymentsHistoryBccl_lblFecha' and (text() = 'Fecha' or . = 'Fecha')]</value>
      <webElementGuid>97c0d852-59e5-4377-8474-0cc113748294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
