<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPYRHistorialPagos</name>
   <tag></tag>
   <elementGuidId>195f81c2-8faf-4274-aa21-dfc01cfcddd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmPaymentsHistoryBccl_lblHistoryTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmPaymentsHistoryBccl_lblHistoryTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0560de6b-6c22-4f9a-9862-ed3499b33872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl_lblHistoryTitle</value>
      <webElementGuid>f90d49dd-f7d9-4b91-9705-0077d0adb7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>1bc7bbb3-b9db-49d6-b539-d97e5394e131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl</value>
      <webElementGuid>fb7ed1a8-f1ad-4667-b0b4-180684f99080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTitleSection cntmiddleleftalign disableSelection</value>
      <webElementGuid>8bd895d0-bd23-4995-9358-80b1d44a3988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Historial de pagos</value>
      <webElementGuid>aed35114-81ea-4bf8-8c75-015020d9ead1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPaymentsHistoryBccl_lblHistoryTitle&quot;)</value>
      <webElementGuid>bb041303-280c-4d4d-a02b-6c993aff9bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_lblHistoryTitle']</value>
      <webElementGuid>865691be-20e3-4f57-9418-f03731febce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmPaymentsHistoryBccl_flxLeftContainer']/div[2]/div</value>
      <webElementGuid>eb94c1fc-bae5-4d7b-8e1a-e63d89c0cb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[2]</value>
      <webElementGuid>6cfa4f0a-d62e-45ea-a006-e34a41030b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis cuentas'])[1]/following::div[39]</value>
      <webElementGuid>12b0fc87-719f-4faa-b701-ac19853ccf03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>fedc9a56-8311-4d70-ae1e-bc9fc0d6be09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis operaciones'])[2]/preceding::div[6]</value>
      <webElementGuid>93c92685-7af6-4df0-b7e9-345090f0a24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Historial de pagos']/parent::*</value>
      <webElementGuid>b8738e79-1fce-47cf-a3eb-649dfa0c050f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>795f843d-fd94-4781-a5dd-9039dec2b5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmPaymentsHistoryBccl_lblHistoryTitle' and (text() = 'Historial de pagos' or . = 'Historial de pagos')]</value>
      <webElementGuid>f506322d-7840-4622-812e-39c300f81b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
