<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkBajaDbitoAutomtico</name>
   <tag></tag>
   <elementGuidId>a222d5e5-44b4-4bed-8a59-7c2a53f0f28b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_CFloatingMenu_lblbajaDebito']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_CFloatingMenu_lblbajaDebito</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a21ce6f4-72ab-43d7-a579-56889a0b6f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_CFloatingMenu_lblbajaDebito</value>
      <webElementGuid>b2aa8c95-b1fb-4d10-b7c3-136eb33e67b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>5ef16d57-d8b4-43f9-a95e-3a93452941d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>7d4a8b3d-f684-4348-adbe-d71491838d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CFloatingMenu</value>
      <webElementGuid>d58c8094-6af3-4700-97cd-8cacfe67d0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>67477f87-5a51-4f3d-8e57-6b381cfa0cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baja de un débito automático</value>
      <webElementGuid>556faff2-1d8c-4c37-bb7b-2bef024bcfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_CFloatingMenu_lblbajaDebito&quot;)</value>
      <webElementGuid>55b65fa7-87d6-4879-94df-9d72e67fe0bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_CFloatingMenu_lblbajaDebito']</value>
      <webElementGuid>0855acf9-ab4e-4323-b193-854fc20b2d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_CFloatingMenu_flxbajaDebito']/div/div</value>
      <webElementGuid>eeaf0fbd-0b4b-4fa5-ba8f-85d70a872534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alta a un débito automático'])[1]/following::div[5]</value>
      <webElementGuid>c43b36e8-1f7c-4421-aefa-bae81f2ec751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite transitorio para operaciones'])[1]/following::div[10]</value>
      <webElementGuid>0eb308c9-ab67-43ae-b79e-bc6896cddfb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[3]</value>
      <webElementGuid>a92f2315-5f10-4a0e-868b-ff3950bfa48f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[5]</value>
      <webElementGuid>f18fcf83-20fd-4c75-b990-336ca9fa28bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Baja de un débito automático']/parent::*</value>
      <webElementGuid>56cf8085-281a-4cfe-aaf6-8881796bfe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div[5]/div/div/div/div</value>
      <webElementGuid>35016299-67d8-4bcb-a659-65841157dfa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_CFloatingMenu_lblbajaDebito' and (text() = 'Baja de un débito automático' or . = 'Baja de un débito automático')]</value>
      <webElementGuid>ecb34749-e5f7-4526-8c91-b206e26d77c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
