<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkMetrogas</name>
   <tag></tag>
   <elementGuidId>a453a43f-1433-4f37-a878-fee1549a53a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxTableRow_9894864606579744_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='flxTableRow_9894864606579744_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bb8b1b6e-594b-4389-88d8-2b95d859c752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxTableRow_9894864606579744_0</value>
      <webElementGuid>4826644c-61c8-4a9f-bd84-c0b1a5c667da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknLblLatoReg1466</value>
      <webElementGuid>a7f3bb5b-2586-4d90-ac2b-4acd291f6e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Metrogas Antiguo</value>
      <webElementGuid>4fcbcd35-cdc1-4f7b-9667-31caa2b0b5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flxTableRow_9894864606579744_0&quot;)</value>
      <webElementGuid>3b257f9d-80bd-49cd-a5eb-ec75c3f8bb66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='flxTableRow_9894864606579744_0']</value>
      <webElementGuid>146c7366-4774-4925-9bb8-d72664f63b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxTableRow_46975721938686127_0']/span</value>
      <webElementGuid>39d3b52a-15cb-45f6-9448-bb303a5b4277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::span[1]</value>
      <webElementGuid>7671b11a-5a88-4904-8bf8-0ebc34edecf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[2]/following::span[1]</value>
      <webElementGuid>c360f7a4-4049-4bdb-9def-ae173eaa1408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La búsqueda no obtuvo resultados.'])[2]/preceding::span[2]</value>
      <webElementGuid>2eb56787-d170-406b-a452-2cf6788544bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontraron categorías o rubros para el criterio solicitado.'])[1]/preceding::span[2]</value>
      <webElementGuid>f8db1686-a201-4c35-8691-d5c3484df7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Metrogas Antiguo']/parent::*</value>
      <webElementGuid>96e279e6-39f5-4429-b458-ecc1f813cfaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>a666580e-d3b0-4430-baed-d85a1d4a1c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'flxTableRow_9894864606579744_0' and (text() = 'Metrogas Antiguo' or . = 'Metrogas Antiguo')]</value>
      <webElementGuid>259b69f0-3790-4f33-a536-854f2d7e96fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
