<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkPYREcowifi</name>
   <tag></tag>
   <elementGuidId>f3337ad4-005b-4bb5-a08a-cfe422744a5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='flxTableRow_26841478937622967_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxTableRow_26841478937622967_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1dffccc-c220-41ca-a7cd-d1f572a64d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxTableRow_26841478937622967_2</value>
      <webElementGuid>1fd2ef68-d4db-405a-9674-f91b069f88d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknLblLatoReg1466</value>
      <webElementGuid>49ac441f-c68f-4734-a1c7-91e00d6273ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ECOWIFI</value>
      <webElementGuid>328d000e-6e14-4a4f-bfa2-9529a664b335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flxTableRow_26841478937622967_2&quot;)</value>
      <webElementGuid>5b47eafd-6b2d-41b0-a7c9-35fe1750ba9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='flxTableRow_26841478937622967_2']</value>
      <webElementGuid>600cbc0f-c5d8-4164-b9b7-8b5b5417ef95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxTableRow_7565127626185536_2']/span</value>
      <webElementGuid>768e523f-41b8-421f-9f17-e266ed03bf08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ecom Chaco'])[1]/following::span[1]</value>
      <webElementGuid>0555d959-4a19-4553-9d97-81b18a537e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canal 3 Fortin Mulitas - Internet y Telecomunic'])[1]/following::span[2]</value>
      <webElementGuid>53b7d1d5-67ba-40bc-a962-8029a52f2d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telecom Ex Fibercorp'])[1]/preceding::span[1]</value>
      <webElementGuid>72f95e09-2733-47f5-a8f6-6c7ab7c6fff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telecom L Distancia'])[1]/preceding::span[2]</value>
      <webElementGuid>d9d0f451-8f42-4283-8289-7cccc51d1439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ECOWIFI']/parent::*</value>
      <webElementGuid>4fb5766d-0f07-4cae-a893-3d2a8008f82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>477abbbb-cf37-49d4-9787-e44337787c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'flxTableRow_26841478937622967_2' and (text() = 'ECOWIFI' or . = 'ECOWIFI')]</value>
      <webElementGuid>33cbd435-68ec-465e-b803-f8d1993c4b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
