<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkPYRIplanNetworks2</name>
   <tag></tag>
   <elementGuidId>bc463f04-73c4-449b-851f-4f1b83cc3c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxTableRow_14981492699145168_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;flxTableRow_14981492699145168_0&quot;)[count(. | //*[@id = 'flxTableRow_14981492699145168_0' and @class = 'sknLblLatoReg1466' and (text() = 'Iplan Networks' or . = 'Iplan Networks')]) = count(//*[@id = 'flxTableRow_14981492699145168_0' and @class = 'sknLblLatoReg1466' and (text() = 'Iplan Networks' or . = 'Iplan Networks')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='flxTableRow_14981492699145168_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d167b20-f6d9-49d3-8105-6faf968a7c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxTableRow_14981492699145168_0</value>
      <webElementGuid>86c1c4f8-5e76-4439-8dcc-b23d15710aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknLblLatoReg1466</value>
      <webElementGuid>db4349ed-8a24-4179-aa4e-7835d9f0eeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iplan Networks</value>
      <webElementGuid>035f1520-f5bd-4a26-96da-2944e85ee98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flxTableRow_14981492699145168_0&quot;)</value>
      <webElementGuid>07314f85-c645-402a-8c4e-c03c1f57c036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='flxTableRow_14981492699145168_0']</value>
      <webElementGuid>c945cfb9-b09b-4ca2-b70d-a921acd83e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxTableRow_4017344697928986_0']/span</value>
      <webElementGuid>27255aed-28c2-4318-85a9-ea13c70460f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::span[1]</value>
      <webElementGuid>db4bac50-a5a7-43a9-9b55-9c7a0115f687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buscar'])[2]/following::span[1]</value>
      <webElementGuid>5c390a95-4b02-483f-a52d-0d34d2d79b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La búsqueda no obtuvo resultados.'])[2]/preceding::span[2]</value>
      <webElementGuid>7671de24-1484-415e-9183-08d53902dc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se encontraron categorías o rubros para el criterio solicitado.'])[1]/preceding::span[2]</value>
      <webElementGuid>8d60a166-9262-4fc7-8e81-d8bd41846687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Iplan Networks']/parent::*</value>
      <webElementGuid>af55c537-bd41-4837-84e8-5c66a2dc1b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>eb01bac5-3b05-4dd9-83eb-c755e59b2b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'flxTableRow_14981492699145168_0' and (text() = 'Iplan Networks' or . = 'Iplan Networks')]</value>
      <webElementGuid>c14ce68b-5075-41d6-9053-ccafceedeafe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
