<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkPYRAltaDbitoAutomtico</name>
   <tag></tag>
   <elementGuidId>e0e96bc2-8477-4b07-b52e-2cde89527027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_CFloatingMenu_lblaltaDebito']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_CFloatingMenu_lblaltaDebito</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58fdf812-8748-49fd-b6fc-11815ba5b515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_CFloatingMenu_lblaltaDebito</value>
      <webElementGuid>83c56478-067d-40e5-9e27-c569c06dfed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>bb3d6dc6-9a4f-4dd3-8fbe-d1dd2d00fb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>fe1d9623-94a4-4d17-8138-e61b8c853d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CFloatingMenu</value>
      <webElementGuid>3bc0053e-e37e-4a02-b5bf-3822a68248e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>b8120f9f-c602-42ff-9fcc-3408f5f9b86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alta a un débito automático</value>
      <webElementGuid>1e0d797e-4039-4323-a9f4-11fa0438acd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_CFloatingMenu_lblaltaDebito&quot;)</value>
      <webElementGuid>9a8ed18f-061b-4e1e-9687-229423911fcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_CFloatingMenu_lblaltaDebito']</value>
      <webElementGuid>95fbe95f-3332-4962-b20f-673a19dd0710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_CFloatingMenu_flxaltaDebito']/div/div</value>
      <webElementGuid>1d92b243-384e-4308-bfa7-96bfe1bba1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite transitorio para operaciones'])[1]/following::div[5]</value>
      <webElementGuid>46ea012a-dc2e-4f88-ab92-9b85c73e8c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver historial de pagos'])[1]/following::div[10]</value>
      <webElementGuid>7feec752-fe4c-41b0-9c74-86f5de72e73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baja de un débito automático'])[1]/preceding::div[1]</value>
      <webElementGuid>529bdb12-bd97-494d-8c47-2cdc1cd72e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[8]</value>
      <webElementGuid>e72421a4-91b4-4757-b882-a96de4f07fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alta a un débito automático']/parent::*</value>
      <webElementGuid>4a46322d-cd0e-41e1-8296-5630a9588d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>e93c7c20-7f7c-4213-9989-cfc02ecf63a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_CFloatingMenu_lblaltaDebito' and (text() = 'Alta a un débito automático' or . = 'Alta a un débito automático')]</value>
      <webElementGuid>a1792150-3ada-4dad-a365-5c5878bd7f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
