<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkVerServiciosAdheridos</name>
   <tag></tag>
   <elementGuidId>0fc5de4b-f2c4-49c1-9180-9298e013b6a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_CFloatingMenu_lblgetEntes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_CFloatingMenu_lblgetEntes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b71d08eb-ca0a-48fc-9292-c064515d3ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_CFloatingMenu_lblgetEntes</value>
      <webElementGuid>16281e10-98db-4e9d-ab7d-0b3554d01df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>b45a5f6d-e7c9-45f7-b848-ab1b61bdb2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>f94d89c6-367f-4a2d-84b6-62406f646931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CFloatingMenu</value>
      <webElementGuid>5e98aba5-cde7-4cbc-97dd-0f9c7d9c43e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>718bae4f-f2ee-4f74-aeb5-31aec0d58e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver servicios adheridos</value>
      <webElementGuid>e7ba1673-f44f-45ee-a1f8-33500ef33309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_CFloatingMenu_lblgetEntes&quot;)</value>
      <webElementGuid>47c4682f-9787-48d4-83cd-67a3341bc1c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_CFloatingMenu_lblgetEntes']</value>
      <webElementGuid>b5f1661a-003e-4a68-b11e-79ab8fd1df40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_CFloatingMenu_flxgetEntes']/div/div</value>
      <webElementGuid>bd467e43-ee56-4717-8e9b-8e5abb1d9da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[31]/following::div[8]</value>
      <webElementGuid>367bd390-fc92-4037-b3fd-61722d43e639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[20]</value>
      <webElementGuid>914ee125-a739-4148-8860-98b84c12aa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver historial de pagos'])[1]/preceding::div[1]</value>
      <webElementGuid>9af3919a-efe4-42d3-a461-df921206782d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite transitorio para operaciones'])[1]/preceding::div[6]</value>
      <webElementGuid>dcaedd88-c6dc-4ef3-96fd-19266383508e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ver servicios adheridos']/parent::*</value>
      <webElementGuid>3ce38cae-ae87-4aef-aa90-c837cd08e61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>8f3f3425-a43c-49c1-ba8b-5454bd5217d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_CFloatingMenu_lblgetEntes' and (text() = 'Ver servicios adheridos' or . = 'Ver servicios adheridos')]</value>
      <webElementGuid>7e2f0ce2-67ac-4b6c-81bb-b642e51b9d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
