<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtConceptoServicio</name>
   <tag></tag>
   <elementGuidId>23b3b419-6c98-4334-96ae-5aac0bf3f58c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_lblConceptData']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_AddEntePanel_AddEnte_lblConceptData</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>661faee7-9d1c-4ef9-96a1-a0821059588a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_AddEntePanel_AddEnte_lblConceptData</value>
      <webElementGuid>3084acb1-45d9-46c6-8805-4ff5d7ed1372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>3ef470a9-69a0-4666-883e-030e6df2af07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>8c87e085-a45c-47b3-8ce4-877362500c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AddEntePanel_AddEnte</value>
      <webElementGuid>774bcffc-1ef3-4d4a-8831-8ea7e4c81b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1433 cntmiddlerightalign disableSelection</value>
      <webElementGuid>139f4efa-28dc-41bf-9a72-ddbbcf587298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INTERNET</value>
      <webElementGuid>a5277c12-878f-4073-9fa7-afe797d66a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_AddEntePanel_AddEnte_lblConceptData&quot;)</value>
      <webElementGuid>88362489-776f-4e66-b512-36a326cbdb62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_lblConceptData']</value>
      <webElementGuid>fb4f2d56-1554-4080-99e3-a70fdf9cb4d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_flxConceptData']/div/div</value>
      <webElementGuid>9acd6ee9-b5d4-4e92-b632-9284c7863c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vencimiento'])[3]/following::div[10]</value>
      <webElementGuid>6972bf57-c5a8-4ee3-97ba-c8aa7ea04d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[35]/following::div[15]</value>
      <webElementGuid>f62c9d77-7bd9-4020-891e-f5a86f10438c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[2]/preceding::div[1]</value>
      <webElementGuid>c641fbf5-564a-4396-af3c-b39ddc1b5635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[36]/preceding::div[3]</value>
      <webElementGuid>455d4c6a-9175-44de-a5f4-4f1ecf7b3ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INTERNET']/parent::*</value>
      <webElementGuid>93c0718b-300b-4714-86a6-812ea8ee404b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[4]/div/div/div/div/div/div/div</value>
      <webElementGuid>e206bc0f-f571-4893-b49b-6610e8a42326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_AddEntePanel_AddEnte_lblConceptData' and (text() = 'INTERNET' or . = 'INTERNET')]</value>
      <webElementGuid>5faff333-d517-4283-ae1b-cc8e3083fd30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
