<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCodigoServicio</name>
   <tag></tag>
   <elementGuidId>6956937c-99fe-4dd8-956f-e8fcfdaae57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxServicesPayRow_lblCodigoPago'])[29]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99bfe2c4-639a-4e3a-832e-c8f88b5d86b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxServicesPayRow_lblCodigoPago</value>
      <webElementGuid>55e3448b-c4f7-4795-8e91-51c0ed6de352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>5633b117-2e00-454e-a4c9-5fe7d1d406fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxServicesPayRow</value>
      <webElementGuid>962a9abe-2c57-4d88-8e56-c9b51787ccb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segServices</value>
      <webElementGuid>3a6bf18d-2a3d-4e61-9539-06bd2d2bea8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>252B1BBE-7019-4620-97FF-B6C43D2911C1</value>
      <webElementGuid>c49e864c-762f-463f-916f-9f022665671f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableCellSM cntmiddleleftalign disableSelection</value>
      <webElementGuid>29bdc493-c303-469d-a175-2e03124c237e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>54444444888</value>
      <webElementGuid>1f2da07f-331c-4100-add9-7a581d7dd7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelServices_ServicesPay_segServices&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxMainContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayContainer&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxCodigoPago&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTableCellSM&quot;]/div[@id=&quot;flxServicesPayRow_lblCodigoPago&quot;]</value>
      <webElementGuid>25810b93-02bd-43ce-b8ea-e932f493562e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxServicesPayRow_lblCodigoPago'])[29]</value>
      <webElementGuid>1f8a6e6d-016d-4473-8fc9-b7929db1bfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxServicesPayRow_flxCodigoPago']/div/div)[29]</value>
      <webElementGuid>16f36de6-2755-4bc2-99b1-8787cefce5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prueba 888'])[1]/following::div[5]</value>
      <webElementGuid>f81f72d3-69b6-4e6d-8fba-4aeb2afd8154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrogas Antiguo'])[3]/following::div[7]</value>
      <webElementGuid>f5ed4e46-d79f-4a05-bea2-45a625f4e8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[29]/preceding::div[1]</value>
      <webElementGuid>82796410-72b0-467b-8a39-8427a23d7ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[29]/preceding::div[6]</value>
      <webElementGuid>e83d5225-6400-43a8-b037-0562fef827e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='54444444888']/parent::*</value>
      <webElementGuid>9b6ae8ce-9779-483f-bc23-998600b39fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>f14c8f3b-31b9-4587-b6b0-0521db12d2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxServicesPayRow_lblCodigoPago' and (text() = '54444444888' or . = '54444444888')]</value>
      <webElementGuid>2f1e5eb6-0009-4210-9d01-b695e694b0eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
