<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPYRNombreServicio</name>
   <tag></tag>
   <elementGuidId>c3130255-cb90-44e7-9a0d-8b56b1d2cd0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxServicesPayRow_lblName'])[30]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97410a20-d094-4217-bd27-d1af9b358d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxServicesPayRow_lblName</value>
      <webElementGuid>1af57380-2d24-4a61-8746-ccfcf6ca260b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>c5358c2c-4609-4376-9ce1-4612a42b043a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxServicesPayRow</value>
      <webElementGuid>ca333701-71fa-4f2b-96ee-2231dd17ef68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segServices</value>
      <webElementGuid>f0d4b896-6568-4155-b76b-b6d24c9f0754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>E7C2EA47-B28D-4689-B13B-4603127417A0</value>
      <webElementGuid>aeb34992-4a35-442f-9776-403f032f796f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableCellDataLarge cntmiddleleftalign disableSelection</value>
      <webElementGuid>c5f9d1ff-cde8-4b21-90e7-254854ae4b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Metrogas Antiguo</value>
      <webElementGuid>b27c559c-98f7-43fd-bb9e-ee5c753a61da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelServices_ServicesPay_segServices&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxMainContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTableCellDataLarge&quot;]/div[@id=&quot;flxServicesPayRow_lblName&quot;]</value>
      <webElementGuid>e9e796ec-537e-4a09-b755-402d7aab9f1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxServicesPayRow_lblName'])[30]</value>
      <webElementGuid>d85e1adf-9eca-4818-9957-bdc90a131918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxServicesPayRow_flxServicesPayContainer']/div/div)[88]</value>
      <webElementGuid>a4415d96-ebdd-4b78-965b-d66f4227ed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[29]/following::div[17]</value>
      <webElementGuid>8372ad38-deb8-442e-8ffc-fecd90dfb2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[29]/following::div[22]</value>
      <webElementGuid>d28101d2-3814-49c7-ad74-c46f2a253198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrogas Antiguo 517'])[1]/preceding::div[1]</value>
      <webElementGuid>1cc78339-5d47-4148-8a76-f260e0336dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[30]/preceding::div[8]</value>
      <webElementGuid>31b1375e-5ad0-43d0-af14-36810ca65b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[30]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>81ab0ae0-3b6a-4d0a-a2c9-129d82cd3bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxServicesPayRow_lblName' and (text() = 'Metrogas Antiguo' or . = 'Metrogas Antiguo')]</value>
      <webElementGuid>a46d57ca-4694-46ac-9480-62ae46710425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
