<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPYRVisaArgentina</name>
   <tag></tag>
   <elementGuidId>d0b37f8a-a7e9-4339-be78-e2f44dadf1fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxOptionCommon51']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxOptionCommon51</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;flxOptionCommon51&quot;)[count(. | //*[@id = 'flxOptionCommon51' and @class = 'sknFlxDropDownOptionCommon sknFlxDropDownOptionCommonHover' and (text() = 'Visa Argentina' or . = 'Visa Argentina')]) = count(//*[@id = 'flxOptionCommon51' and @class = 'sknFlxDropDownOptionCommon sknFlxDropDownOptionCommonHover' and (text() = 'Visa Argentina' or . = 'Visa Argentina')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a4aee5ce-83a1-4287-8b5c-d3fc333422b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxOptionCommon51</value>
      <webElementGuid>beed43e4-4c45-4702-a06c-24622986f573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknFlxDropDownOptionCommon sknFlxDropDownOptionCommonHover</value>
      <webElementGuid>81831004-456a-4496-ac82-174ccea81156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visa Argentina</value>
      <webElementGuid>ed3ab151-559c-493f-bec8-9aac2ecebe18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flxOptionCommon51&quot;)</value>
      <webElementGuid>b1ef3457-f180-4e74-8614-adb79a2d25b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxOptionCommon51']</value>
      <webElementGuid>d7b63f7e-db72-43fe-9036-b06085747c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxOptionsContainer']/div[17]</value>
      <webElementGuid>279dd288-1751-4837-905b-1f6fa43dc780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Universidad Arg. John F. Kennedy'])[1]/following::div[1]</value>
      <webElementGuid>7d5aa976-eb83-45e2-837b-d981c800cfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tierra del Fuego - Dirección Provincial de Energía'])[1]/following::div[3]</value>
      <webElementGuid>e5d0bc68-5651-467a-a0c4-e5f554a72c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[7]</value>
      <webElementGuid>0ae066fb-2025-430e-955d-9f159b4df0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[17]</value>
      <webElementGuid>9ba2a9fd-dfbc-49cf-897f-fd1976e3e360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxOptionCommon51' and (text() = 'Visa Argentina' or . = 'Visa Argentina')]</value>
      <webElementGuid>7a52b782-d38f-48a4-871a-40d9e6c3b15e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
