<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPYRMsjeServicioAdherido</name>
   <tag></tag>
   <elementGuidId>fdf40f69-1a19-4976-a1c8-2a4138c496d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_lblSuccessMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_AddEntePanel_AddEnte_lblSuccessMessage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df4784a4-6514-4dc4-8cb3-54cb0951ee43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_AddEntePanel_AddEnte_lblSuccessMessage</value>
      <webElementGuid>20285fd4-2968-4b7c-a9c4-22fb68275cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>c10ff236-59ab-483a-bc74-cc1833f2aa7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>a3a32a08-47b1-4356-962d-46e23412f51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AddEntePanel_AddEnte</value>
      <webElementGuid>770efe29-161f-4667-9056-cd2cd036060b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoBold1433 cntmiddleleftalign disableSelection</value>
      <webElementGuid>e6f2eba2-0096-432e-bc5f-13386cb2a849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡SERVICIO ADHERIDO!</value>
      <webElementGuid>190488cf-54a8-425a-bc2e-8a35d0dc5cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_AddEntePanel_AddEnte_lblSuccessMessage&quot;)</value>
      <webElementGuid>f8fd3be1-bc22-4486-b38f-5857f55e8718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_lblSuccessMessage']</value>
      <webElementGuid>ecd006a3-66c7-4171-bbbf-b0bdab577bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_flxSuccessHeader']/div[2]/div</value>
      <webElementGuid>bcad9e89-03c3-4104-9797-c51053d9e7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/following::div[2]</value>
      <webElementGuid>221a64d0-39d2-4ae1-bf26-46488ffe28e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autorizando'])[1]/following::div[20]</value>
      <webElementGuid>00ee9ac1-d4c0-4d93-b4e6-3944910ef3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrogas Antiguo'])[4]/preceding::div[1]</value>
      <webElementGuid>bc3bcc89-eac0-4423-8869-4178da5fc305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenés vencimientos pendientes para este servicio.'])[1]/preceding::div[12]</value>
      <webElementGuid>3df14e9e-99f6-4a79-b52d-5146f71d6971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡SERVICIO ADHERIDO!']/parent::*</value>
      <webElementGuid>8dd1d7c1-d7f5-4dc8-bf4f-c624d55b3020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>5f132feb-b9f8-40ac-bddc-3e9e45e68ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_AddEntePanel_AddEnte_lblSuccessMessage' and (text() = '¡SERVICIO ADHERIDO!' or . = '¡SERVICIO ADHERIDO!')]</value>
      <webElementGuid>a4f17b58-4184-434a-8070-c8f0f71aeec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
