<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPYRInternetTelecomunicaciones</name>
   <tag></tag>
   <elementGuidId>aa8d059f-c0d3-4a4b-aaed-7fb1b0ca6fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon36lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon36lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc3ea1aa-0ca8-4874-ab60-6a0c390174d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon36lblOptionTitle</value>
      <webElementGuid>4d3efe5d-da78-413e-9e95-141b8ec5bd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>143f6561-e2f8-47e3-b0cc-3c7565247593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>15d4c502-d413-4756-96e9-859f3b2a41f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AddEntePanel_AddEnte_SearchRubros</value>
      <webElementGuid>32698748-0ce3-4586-ac17-471f17dcbf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>86e42055-f1ae-480c-820c-0d77fc5d6e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Internet y Telecomunicaciones</value>
      <webElementGuid>a46f692e-2d08-4f5b-8e13-5cb5ed9af5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon36lblOptionTitle&quot;)</value>
      <webElementGuid>eb6988a1-63a8-424d-8c21-dc4ce1637771</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon36lblOptionTitle']</value>
      <webElementGuid>cf215e75-a403-467a-a3f0-cece5c2337dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon36flxOptionInfo']/div/div</value>
      <webElementGuid>8f7379ab-e540-41d5-a504-682b3d419081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[33]/following::div[8]</value>
      <webElementGuid>521a3b8a-ab38-4bda-ad3b-8f95ef5f1502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aportes AFJP'])[1]/following::div[10]</value>
      <webElementGuid>fbee25ef-6995-499c-a27d-114d7fc600f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[34]/preceding::div[1]</value>
      <webElementGuid>89e62553-5290-4eb7-900d-5512e7f9480c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Planes de Ahorro'])[1]/preceding::div[3]</value>
      <webElementGuid>6fbc2a10-2ea6-4e3f-8e7e-d5d29d3a2886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Internet y Telecomunicaciones']/parent::*</value>
      <webElementGuid>773364ea-d626-42ca-b3c8-fc5b2e34b70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/div/div/div/div</value>
      <webElementGuid>2bdbc8f4-c922-493d-93f1-d1a03efa2406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon36lblOptionTitle' and (text() = 'Internet y Telecomunicaciones' or . = 'Internet y Telecomunicaciones')]</value>
      <webElementGuid>17425268-5aa9-4db2-8463-5a7cfc880c06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
