<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPagosFecha</name>
   <tag></tag>
   <elementGuidId>b77a18b1-0cf3-47f9-bc18-4282ef2a3fe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxHistoryPayments_lblFecha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxHistoryPayments_lblFecha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4cc7aa12-0418-49c0-ae2e-bd0c8b03e279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxHistoryPayments_lblFecha</value>
      <webElementGuid>aea9c6be-33b6-49d1-be46-322b115677ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>a544fe4f-81ad-4b71-9b1d-fa2d430340c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxHistoryPayments</value>
      <webElementGuid>7e13d94c-5da9-4164-b5ad-d1f58098644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>sgmHistoryPayments</value>
      <webElementGuid>93d97fbd-8e59-4bca-9776-72e3cde791cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>1219BE20-4348-431D-BE0B-752DDBCFBB30</value>
      <webElementGuid>1df333b0-0f9e-4cec-8ef2-ca57d5020ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoReg1466 cntmiddleleftalign disableSelection</value>
      <webElementGuid>7f55edad-314c-4f76-a237-f0c2cfbaf355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>03 May 2023</value>
      <webElementGuid>8e264198-2072-4664-817c-3b103a9398d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPaymentsHistoryBccl_sgmHistoryPayments&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxHistoryPayments_flxHistoryPayments&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxHistoryPayments_flxContainerFecha&quot;]/div[@class=&quot;kcell middlecenteralignsknLblLatoReg1466&quot;]/div[@id=&quot;flxHistoryPayments_lblFecha&quot;]</value>
      <webElementGuid>9275edf2-83ea-4201-a1ab-9eaf83d10e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxHistoryPayments_lblFecha']</value>
      <webElementGuid>b01c1f02-82e8-4e10-a301-0a5c0ceb7e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxHistoryPayments_flxContainerFecha']/div/div</value>
      <webElementGuid>b4682c91-5406-4cec-be57-745122fc50cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Importe'])[2]/following::div[12]</value>
      <webElementGuid>3aabbef5-101d-4bd8-9b79-2beee9c5828f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Origen'])[2]/following::div[17]</value>
      <webElementGuid>0dcdd8a1-ac7b-4eb0-9870-43f498b4bc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mercado Libre'])[2]/preceding::div[3]</value>
      <webElementGuid>ac9b882a-5f78-45bd-bec7-d9f2570aefe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mercado Libre Código'])[1]/preceding::div[8]</value>
      <webElementGuid>0cef0bcb-f738-4ac4-b6d8-c072c23954f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='03 May 2023']/parent::*</value>
      <webElementGuid>be86e3b5-c95d-4fc2-8789-9a1ee1eb8689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/ul/li/div/div/div/div/div/div/div</value>
      <webElementGuid>e2071154-de1e-4d23-9079-baf7bdf19dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxHistoryPayments_lblFecha' and (text() = '03 May 2023' or . = '03 May 2023')]</value>
      <webElementGuid>78eccdec-a03a-4b35-8a0c-ebca92f4cef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
