<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPYRCodigoServicio</name>
   <tag></tag>
   <elementGuidId>6956937c-99fe-4dd8-956f-e8fcfdaae57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxServicesPayRow_lblCodigoPago'])[29]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclServicesPay_PanelServices_ServicesPay_segServices&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxMainContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayContainer&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxCodigoPago&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTableCellSM&quot;]/div[@id=&quot;flxServicesPayRow_lblCodigoPago&quot;][count(. | //*[@id = 'flxServicesPayRow_lblCodigoPago' and @kuid = '252B1BBE-7019-4620-97FF-B6C43D2911C1' and (text() = '54444444888' or . = '54444444888')]) = count(//*[@id = 'flxServicesPayRow_lblCodigoPago' and @kuid = '252B1BBE-7019-4620-97FF-B6C43D2911C1' and (text() = '54444444888' or . = '54444444888')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3e687ec3-ac27-4593-b3fd-ae0e12936d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxServicesPayRow_lblCodigoPago</value>
      <webElementGuid>63962c7e-0ebb-46b6-be49-a110dc531e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>1ae0ac6d-568a-4a8c-b285-75a8f0f491aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxServicesPayRow</value>
      <webElementGuid>48777a7a-81a1-4018-be80-23e4db7350ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segServices</value>
      <webElementGuid>db1a8b00-eb47-46c7-b1d5-e962e7321d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>252B1BBE-7019-4620-97FF-B6C43D2911C1</value>
      <webElementGuid>0a15b5fd-2f88-4665-937d-a7e54d3e8956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableCellSM cntmiddleleftalign disableSelection</value>
      <webElementGuid>4771fb7f-fe43-4ee8-a806-951dda08afa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>54444444888</value>
      <webElementGuid>556b5f5f-cbe7-4423-ba99-8286b6df34f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelServices_ServicesPay_segServices&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxMainContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxServicesPayContainer&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxServicesPayRow_flxCodigoPago&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTableCellSM&quot;]/div[@id=&quot;flxServicesPayRow_lblCodigoPago&quot;]</value>
      <webElementGuid>3f994379-4244-45db-85f5-7114afd93697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxServicesPayRow_lblCodigoPago'])[29]</value>
      <webElementGuid>3ef9a11c-c5fe-4035-8f5a-05fc1e061354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxServicesPayRow_flxCodigoPago']/div/div)[29]</value>
      <webElementGuid>668769af-1528-479c-9f76-ad52a645b498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prueba 888'])[1]/following::div[5]</value>
      <webElementGuid>79217105-cbe9-4001-bcf5-147a8fc870a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Metrogas Antiguo'])[3]/following::div[7]</value>
      <webElementGuid>68a31860-655a-4a91-884a-fa935519980d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[29]/preceding::div[1]</value>
      <webElementGuid>efc1ecab-1a32-4604-8596-c90340ba023a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[29]/preceding::div[6]</value>
      <webElementGuid>776db4a2-def9-4450-8f12-3a12faa249b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='54444444888']/parent::*</value>
      <webElementGuid>14a7b88f-2724-42b1-b513-05bfd2a291b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[29]/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>ad06f3a6-0d26-45e8-8959-797cdcfe3596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxServicesPayRow_lblCodigoPago' and (text() = '54444444888' or . = '54444444888')]</value>
      <webElementGuid>44c0c1a1-49eb-4980-b371-2b895461e4ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
