<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPYRTelefonia</name>
   <tag></tag>
   <elementGuidId>5e1e9130-18b5-47a4-a3ee-57507464600f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon3lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon3lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c5c66e74-bad9-4676-986c-4975e8011282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon3lblOptionTitle</value>
      <webElementGuid>e080b1c3-b394-404a-8ee3-0dbc4fde3af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>14195279-670d-482c-b39e-6f1edbc20c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>9677cb4b-555a-4f06-853f-75d5bc2e609c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AddEntePanel_AddEnte_SearchRubros</value>
      <webElementGuid>c85dd600-3072-4960-b188-82b74cd069b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>aa0f7707-441c-4b1b-a99a-1260bd896681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Telefonía</value>
      <webElementGuid>2336eba0-dade-45c8-bab8-ad1d588de3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon3lblOptionTitle&quot;)</value>
      <webElementGuid>19677b34-caf7-4df1-a31f-a5f1ebd4adb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon3lblOptionTitle']</value>
      <webElementGuid>d5799641-ef0b-4091-ad57-d8ab9bb9ac22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon3flxOptionInfo']/div/div</value>
      <webElementGuid>e1ee3a4a-7142-4d52-a150-26ef24aa0d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[20]/following::div[8]</value>
      <webElementGuid>64e635f2-8239-4677-b81a-9c7a34bcb597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impuestos AFIP'])[1]/following::div[10]</value>
      <webElementGuid>25124356-0b39-44fd-bc0f-31e6f250a18f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[21]/preceding::div[1]</value>
      <webElementGuid>661c2e0c-704f-4ad5-bade-9d2555135ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Luz, Agua y Gas'])[1]/preceding::div[3]</value>
      <webElementGuid>05d66512-6f32-451c-960b-c95e4a5913a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Telefonía']/parent::*</value>
      <webElementGuid>5fe382e4-863d-44a1-b1cc-6478dfd1203c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>87e21ec2-fac2-4926-9fcc-b18bb82e97cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_AddEntePanel_AddEnte_SearchRubros_flxOptionCommon3lblOptionTitle' and (text() = 'Telefonía' or . = 'Telefonía')]</value>
      <webElementGuid>9dd0b79f-3c76-4b1d-b017-2116f41f9955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
