<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPYRCalendarioAnioDesdeHistorialPagos</name>
   <tag></tag>
   <elementGuidId>18239f6e-c154-4d03-8595-b6285f5d2d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendarDateFilterFrom-k-w-c-navigator-']/div[4]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>621a5c45-d1e5-45df-b25a-a497838cc29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>1f523441-3cbe-4940-813c-05f78d1cff46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5c413b35-c6c6-4970-9c0e-397cf4525431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>47efba85-e066-444b-a05f-b8b3cfe54c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-w-c-navigator-year</value>
      <webElementGuid>b8b6e41a-1ae3-418c-90d3-19667c5db778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-hold</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>08c0ef15-70fa-482c-b360-df0cef71d525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>[object HTMLDivElement]</value>
      <webElementGuid>0a60b233-77d5-4b09-8f09-67daabba3a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>3d6dcab9-0f25-49ba-ab68-0df1e1baeae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmPaymentsHistoryBccl</value>
      <webElementGuid>b790d32b-6635-4121-9024-cc2838de04b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DateFilter</value>
      <webElementGuid>a975bfa0-d27e-448a-b8ae-64b3b7584c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>e9c037a6-70bd-44db-9e14-60555fb9ddb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDateFilterFrom-k-w-c-navigator-&quot;)/div[@class=&quot;-kony-w-c-navigator-table&quot;]/div[2]/div[@class=&quot;-kony-w-c-navigator-year&quot;]</value>
      <webElementGuid>7e47b72a-17d8-47ca-a52e-779d05c54e30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendarDateFilterFrom-k-w-c-navigator-']/div[4]/div[2]/div[2]</value>
      <webElementGuid>0bae535c-5a41-44b7-a735-91fc4225f248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dic'])[1]/following::div[14]</value>
      <webElementGuid>7d0170b0-9500-48a9-ad6b-3f88796a8af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov'])[1]/following::div[15]</value>
      <webElementGuid>6ee02536-f683-4fa1-a7c9-1457a92b7a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[14]</value>
      <webElementGuid>cbef5352-4db5-4283-9a2a-0b9e60abd0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[16]</value>
      <webElementGuid>9e353322-94bc-489c-a02c-5af7376f050c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2022']/parent::*</value>
      <webElementGuid>8449489a-ef1f-49a0-bfd3-fb2593dc4d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]</value>
      <webElementGuid>f58c1476-7732-4b37-9a87-a319a3219c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2022' or . = '2022')]</value>
      <webElementGuid>cdda24ad-32dd-427e-9243-8550297a0f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
