<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtSinServiciosAdheridosPorVncer</name>
   <tag></tag>
   <elementGuidId>67145d2a-2243-4610-919c-57fe55b121b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_PanelServices_ServicesPay_NoResults_lblNoResultsTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_PanelServices_ServicesPay_NoResults_lblNoResultsTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5598ff2b-bf76-4283-8a0b-3319c363c637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_PanelServices_ServicesPay_NoResults_lblNoResultsTitle</value>
      <webElementGuid>5cdd5c28-6693-4a3c-839f-2eba1981dbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>fb0cb74e-3bda-4aa8-9e52-624f9f17523c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>ba65b8bc-05d0-47b2-8f06-e765e777c80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelServices_ServicesPay_NoResults</value>
      <webElementGuid>201fcbe1-9f99-4878-bb2e-a04db479857a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblNotificationMessageEmptyTable cntmiddleleftalign disableSelection</value>
      <webElementGuid>02f929b3-6068-49df-82be-5717701f79e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No tenés servicios adheridos próximos a vencer.</value>
      <webElementGuid>12c6d4e9-0e25-417f-b3cc-5fa57cba9cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelServices_ServicesPay_NoResults_lblNoResultsTitle&quot;)</value>
      <webElementGuid>ec2d9e9e-aa5e-40e4-a85b-9a8b3b13857f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelServices_ServicesPay_NoResults_lblNoResultsTitle']</value>
      <webElementGuid>9974c151-0363-4901-8716-b218136ab7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelServices_ServicesPay_NoResults_flxMessageContainer']/div/div</value>
      <webElementGuid>7b58103f-3ba2-47c9-bb5e-df061765a2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[25]/following::div[16]</value>
      <webElementGuid>aa60b271-43c5-47f3-b89b-19b830513dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[24]/following::div[18]</value>
      <webElementGuid>746ab159-4a93-4ba9-b97d-5fd6c45b88c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MC'])[1]/preceding::div[14]</value>
      <webElementGuid>acdf900b-9851-4cda-b61b-8b7ecd14565c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[26]/preceding::div[22]</value>
      <webElementGuid>005fed9b-64d9-4baa-b36d-5a0c081f3624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No tenés servicios adheridos próximos a vencer.']/parent::*</value>
      <webElementGuid>7ae718c7-f82d-4fda-bf26-8ab0f1f091df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>75134a6f-6eb8-4299-90ab-db0005128153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_PanelServices_ServicesPay_NoResults_lblNoResultsTitle' and (text() = 'No tenés servicios adheridos próximos a vencer.' or . = 'No tenés servicios adheridos próximos a vencer.')]</value>
      <webElementGuid>6b49201f-025a-4a79-9161-500974257361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
