<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtSaldoCta</name>
   <tag></tag>
   <elementGuidId>598adfc3-3988-46d1-a905-0a1e740b4fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclServicesPay_PanelBillPay_DropDownAccounts_lblAccountAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclServicesPay_PanelBillPay_DropDownAccounts_lblAccountAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e3bc18c5-560a-450f-b064-fe19e1eed8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclServicesPay_PanelBillPay_DropDownAccounts_lblAccountAmount</value>
      <webElementGuid>e697779e-3bff-45ab-a5b7-244142329c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e4164f44-712f-4803-84ad-5c92abfa7f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclServicesPay</value>
      <webElementGuid>c01f672d-11bd-4010-86c2-86bc0d7b092c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>PanelBillPay_DropDownAccounts</value>
      <webElementGuid>1ba0df47-1823-4fd6-afbc-0d08d822a397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountAmountDropdown cntmiddleleftalign disableSelection</value>
      <webElementGuid>9ac03518-dddf-4a21-b07a-927412592c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 116,15</value>
      <webElementGuid>50a3076b-6760-4ffb-a7b2-b19c9390b41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclServicesPay_PanelBillPay_DropDownAccounts_lblAccountAmount&quot;)</value>
      <webElementGuid>0320e3b7-8d3f-4468-81f5-ce606e0d6c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_DropDownAccounts_lblAccountAmount']</value>
      <webElementGuid>a0f0882b-c438-4cde-b612-bbf4f86fe5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclServicesPay_PanelBillPay_DropDownAccounts_flxAmountCointainer']/div[2]/div</value>
      <webElementGuid>c60ad48f-845d-4896-a66a-f0580e72b202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo'])[2]/following::div[2]</value>
      <webElementGuid>f1be5a9b-2cbb-4fae-8e98-69fec47b2cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 001-065307/8'])[1]/following::div[7]</value>
      <webElementGuid>684083b5-43ce-4aab-bdea-f20f50646bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[21]/preceding::div[1]</value>
      <webElementGuid>8659c24a-5fd8-4364-ab01-54c4c3787a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SZIR MARIA ALEJAN...'])[2]/preceding::div[3]</value>
      <webElementGuid>8aad92e8-f3c5-4a14-aa3e-a309c3358887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 116,15']/parent::*</value>
      <webElementGuid>6a84feec-cc83-44cb-94af-8e2b2c61ee6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[4]/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>94c290b0-a225-4942-9ad9-3198ee9b3839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclServicesPay_PanelBillPay_DropDownAccounts_lblAccountAmount' and (text() = '$ 116,15' or . = '$ 116,15')]</value>
      <webElementGuid>b9ae9bad-877e-42bc-8fd3-7fa684a38ae0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
