<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTrxContinuarFormulario</name>
   <tag></tag>
   <elementGuidId>b9db6ca7-fc6b-42d5-9cdb-8c982fe8d826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclCreateTransfer_btnContinue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_btnContinue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c7449ff-d358-4ada-9444-bb60a59003ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_btnContinue</value>
      <webElementGuid>68306057-d447-47ba-8aa5-bf21aeb25425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>45d3934f-b425-4ef1-8b1a-b0cb03c43278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>d1b97117-cfd4-422e-8b8f-b5150491bb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>53a77873-2bce-4b21-ae5f-e83feaeb6141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimaryBold disableSelection</value>
      <webElementGuid>2165792b-1702-4639-89a8-d78aa691d565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>9d4f5bfd-bebe-4e13-8dca-5da23d44a81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimaryBold</value>
      <webElementGuid>32945b95-5c8a-41c3-a772-25f87e703954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_btnContinue&quot;)</value>
      <webElementGuid>627c96df-e0bc-4944-8b83-5d98fd42718c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclCreateTransfer_btnContinue']</value>
      <webElementGuid>fa1ff328-f255-4cc7-99ca-8b56fd26d27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_flxButtons']/div/input</value>
      <webElementGuid>26f56877-ee9a-4895-833f-5f55419bae9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/input</value>
      <webElementGuid>f6e6404d-7182-4ae2-9741-294dfb437cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclCreateTransfer_btnContinue' and @type = 'button']</value>
      <webElementGuid>bd542eac-9294-4ba0-8d53-c81c0ce2ca8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
