<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrfCuentaDolres</name>
   <tag></tag>
   <elementGuidId>bdf1a2e6-c892-4f69-be71-762d688138ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxMisCuentasCredicoopRow_lblAccountCurrency'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kcell.middlecenteralignsknFlxBadgeUSD > #flexcontainer_wrapper > #flxMisCuentasCredicoopRow_flxBadgeContainer > div.kcell.middlecenteralignsknLblBadgeAccounts > #flxMisCuentasCredicoopRow_lblAccountCurrency</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c8eba009-959c-44f5-b57c-94136063dbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_lblAccountCurrency</value>
      <webElementGuid>94343a81-a2b3-4c99-bc6f-ff34ef3ca868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>27e01803-c3e6-4793-a00c-5ad120c49bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>dcf4caa4-a897-4973-83a9-f48bf089541c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>e633c3ed-f43a-4c98-b7cc-28e48b268502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>CA2EA197-205A-4046-A577-41299D3B3BFD</value>
      <webElementGuid>fcc20ad1-a0f3-49fb-89bd-e698ef81bdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblBadgeAccounts cntmiddlecenteralign disableSelection</value>
      <webElementGuid>1693fc99-63c9-4ff7-891a-173e49fa79f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>U$S</value>
      <webElementGuid>eec3f75f-14d8-4085-a368-37a45793aed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxCurrencyContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknFlxBadgeUSD&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxBadgeContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblBadgeAccounts&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountCurrency&quot;]</value>
      <webElementGuid>8f7e7624-7974-4512-b06c-5ac4fe18bd47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_lblAccountCurrency'])[11]</value>
      <webElementGuid>08178541-715c-49a3-a5d0-ea69a8b889e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_flxBadgeContainer']/div/div)[11]</value>
      <webElementGuid>4972eff3-5f07-4409-89de-4587c49b0c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE-1 24400086749'])[1]/following::div[8]</value>
      <webElementGuid>1a5c820f-ed0a-4ea4-8b59-2758908313ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 440-008674/9'])[1]/following::div[10]</value>
      <webElementGuid>cec0c64b-1939-4121-99c7-e590e2eb599e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[22]/preceding::div[1]</value>
      <webElementGuid>3d6aa7c7-d803-4833-825b-e6b00e6e7974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S 134.690,48'])[1]/preceding::div[6]</value>
      <webElementGuid>cf071d5e-5bc1-4923-b931-7977bc8ed343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>cbd856f5-9cb0-4025-ad05-ac472d2a9146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = 'U$S' or . = 'U$S')]</value>
      <webElementGuid>bec3dcc4-c8f3-4a31-bb30-e0ffb1547376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
