<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxMonedaPesos</name>
   <tag></tag>
   <elementGuidId>f6c81f4b-35ad-455a-a3f9-454af5053b1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = '$' or . = '$')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxMisCuentasCredicoopRow_lblAccountCurrency</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxCurrencyContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknFlxBadgeARS&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxBadgeContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblBadgeAccounts&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountCurrency&quot;][count(. | //*[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = '$' or . = '$')]) = count(//*[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = '$' or . = '$')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8d5c6a2-7f8d-4ac0-93da-567aa63fe919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_lblAccountCurrency</value>
      <webElementGuid>a7730023-066f-4ef3-8b40-65b0c0b0ed35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>4694dfdd-183b-4430-9bda-5ae89ef27bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>c2d18199-a781-4825-8a11-6f5e0403f757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>afed095d-df51-4efa-b91d-e9c5b7b31e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>BB797CFA-6995-49E1-96B3-FC75C2D0CBEA</value>
      <webElementGuid>3618d41b-e0ef-422d-a425-30163c06479e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblBadgeAccounts cntmiddlecenteralign disableSelection</value>
      <webElementGuid>d9bb18f9-4871-4580-b2e0-f140b497c3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$</value>
      <webElementGuid>5e350624-d4b6-407d-9386-8b046375f0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxCurrencyContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknFlxBadgeARS&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxBadgeContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblBadgeAccounts&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountCurrency&quot;]</value>
      <webElementGuid>ecb95c4f-1336-49a2-9bf7-15024dcce058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxMisCuentasCredicoopRow_lblAccountCurrency']</value>
      <webElementGuid>f4b0a559-d898-4c6c-afde-2ed623bedf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxMisCuentasCredicoopRow_flxBadgeContainer']/div/div</value>
      <webElementGuid>9e19dba9-055c-425e-8b7c-83d7336dfc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE-1 11190118359'])[1]/following::div[8]</value>
      <webElementGuid>45975b20-6130-45cb-8995-c070fc859375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 119-011835/9'])[1]/following::div[10]</value>
      <webElementGuid>2200f489-282f-4215-93ba-6ee4f7fba47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[12]/preceding::div[1]</value>
      <webElementGuid>bd204096-a2c8-4085-9514-d09fab03d8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 79.998.285,47'])[1]/preceding::div[6]</value>
      <webElementGuid>e14bc849-c3bb-4d96-b7e5-02f089d92ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>959d32e9-f057-41c8-b79f-2a3e40c3827d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = '$' or . = '$')]</value>
      <webElementGuid>3117eaac-48f0-4870-8742-d40b8b80d8ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
