<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxMonedaFormDolares</name>
   <tag></tag>
   <elementGuidId>8ab05778-aedb-43aa-9c48-f7efc9bdc6da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_AmountInput_flxCurrencyContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_AmountInput_flxCurrencyContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ae0108d-e4fe-4e65-aa92-41576f5fac2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>2574e0f0-d074-4eb5-9728-4086b0068f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_AmountInput_flxCurrencyContainer</value>
      <webElementGuid>70fad2da-c102-4638-9821-0de50b7e8a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>89077c99-3fe2-4ee1-b3cb-6f6bd90ec858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>ba67cfc8-57ca-419e-bf4d-b0cc1cbe4136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AmountInput</value>
      <webElementGuid>f11e1404-fdba-4039-a767-ec41caa12b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>U$S</value>
      <webElementGuid>7ff767a6-a6c7-439b-b48b-d5a36ab2710c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_AmountInput_flxCurrencyContainer&quot;)</value>
      <webElementGuid>671e22f8-7e03-40cc-8f39-6f80e4f74420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_flxCurrencyContainer']</value>
      <webElementGuid>106aab35-9155-4a3f-8373-88a7f9c2a1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[260]</value>
      <webElementGuid>00dc4f2e-5655-4c56-afc0-c9d78b5f758a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='obligatorio'])[1]/following::div[7]</value>
      <webElementGuid>095c5676-35b9-4acc-a76b-fa3e1a322792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[9]</value>
      <webElementGuid>fc1a3601-9789-4d06-8ff8-e5a5b0de822a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite disponible para transferir: U$S 252.000,00'])[1]/preceding::div[3]</value>
      <webElementGuid>a10cc01d-bb1d-45e6-9770-ec7e19ac23d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>b79cfdcc-b0ae-463f-91ef-05dc9aa1f446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_AmountInput_flxCurrencyContainer' and (text() = 'U$S' or . = 'U$S')]</value>
      <webElementGuid>800b5592-477e-460b-be28-9c4ec5f0f91f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
