<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxMonedaDolares</name>
   <tag></tag>
   <elementGuidId>6cca04f3-4e41-45da-a67d-c1d55dc1bcd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxCurrencyContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknFlxBadgeUSD&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxBadgeContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblBadgeAccounts&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountCurrency&quot;][count(. | //*[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = 'U$S' or . = 'U$S')]) = count(//*[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = 'U$S' or . = 'U$S')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kcell.middlecenteralignsknFlxBadgeUSD > #flexcontainer_wrapper > #flxMisCuentasCredicoopRow_flxBadgeContainer > div.kcell.middlecenteralignsknLblBadgeAccounts > #flxMisCuentasCredicoopRow_lblAccountCurrency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f2b8320-7ea3-4497-bf45-db266af4ca1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_lblAccountCurrency</value>
      <webElementGuid>e8ad0f90-7f83-4db3-ab8d-f17bc7ba3247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>2dbe56ed-9119-458c-af9e-f010862311a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>c98e3a5b-63fb-4721-be0b-aa93d6ad7a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>37bd290e-2ae9-4386-abf7-be55d451596d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>0EBA1855-9F65-409A-9F10-DB66D0EB2100</value>
      <webElementGuid>832aa29d-f5da-4ed6-b57d-13edc5513bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblBadgeAccounts cntmiddlecenteralign disableSelection</value>
      <webElementGuid>d4bb9db2-8ec1-48c0-a7b7-7de0fd424d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>U$S</value>
      <webElementGuid>e8024f5f-ee12-46c4-b47c-a5c466bb8adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxCurrencyContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknFlxBadgeUSD&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxBadgeContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblBadgeAccounts&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountCurrency&quot;]</value>
      <webElementGuid>0cdced69-1ecc-4c86-8995-fbe28a2a9e63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_lblAccountCurrency'])[2]</value>
      <webElementGuid>4c790bf8-75c2-4ff5-8253-6690f9e63324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_flxBadgeContainer']/div/div)[2]</value>
      <webElementGuid>934cce41-81d9-49f8-9f95-5b1e7f3a066e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE-1 21190118359'])[1]/following::div[8]</value>
      <webElementGuid>bc05b5ec-7b09-4211-9dad-8bffd2927645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 119-011835/9'])[1]/following::div[10]</value>
      <webElementGuid>97f53a4d-397d-4a2d-8d24-2ec3027e7737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[13]/preceding::div[1]</value>
      <webElementGuid>55ed2768-7991-4710-ab60-e6ae6473a11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S 2.999.899,28'])[1]/preceding::div[6]</value>
      <webElementGuid>78814ced-68e4-40dc-bfc0-3218aafdbf78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>fc233b97-1d9c-410b-8bb8-cb7def687952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = 'U$S' or . = 'U$S')]</value>
      <webElementGuid>d78d2bf0-0e63-4890-812f-57e34959e406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
