<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxListaMonedaDolar</name>
   <tag></tag>
   <elementGuidId>7014e384-ec3f-4b63-87b5-91a10bd14417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxMisCuentasCredicoopRow_flxBadgeContainer']/div/div)[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.kcell.middlecenteralignsknFlxBadgeUSD > #flexcontainer_wrapper > #flxMisCuentasCredicoopRow_flxBadgeContainer > div.kcell.middlecenteralignsknLblBadgeAccounts > #flxMisCuentasCredicoopRow_lblAccountCurrency</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c6a133d-4b36-41aa-bc13-5c8b393a32db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_lblAccountCurrency</value>
      <webElementGuid>e07a1bb4-64c4-4f51-9b83-ee771172b87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0d1fa62f-f6ad-4e68-aa12-ea0987ac0adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>d78d0e01-2d58-43cf-bee5-664e2c80950a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>d0e1f2db-7f96-4128-971d-2d4ccb23088b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>95252B35-ADB2-4472-B8FC-747886CAD9DA</value>
      <webElementGuid>63a7c174-0bde-4028-a3d9-00ac0ca77b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblBadgeAccounts cntmiddlecenteralign disableSelection</value>
      <webElementGuid>8256d4b3-ac66-4989-85a9-d79447e52077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>U$S</value>
      <webElementGuid>d086cc44-95c5-461d-858b-c31add78a67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxCurrencyContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknFlxBadgeUSD&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxBadgeContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblBadgeAccounts&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountCurrency&quot;]</value>
      <webElementGuid>dddb0001-fa2d-421c-b167-e2cf9e534c9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_lblAccountCurrency'])[11]</value>
      <webElementGuid>e947de94-ae0e-45b1-86ce-8f5b52aa0ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_flxBadgeContainer']/div/div)[11]</value>
      <webElementGuid>73d25e1b-904d-4499-beba-4661ed494c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE-1 24400086749'])[1]/following::div[8]</value>
      <webElementGuid>3f454af0-0cd8-44e9-b72b-98015ff6cf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 440-008674/9'])[1]/following::div[10]</value>
      <webElementGuid>84167438-d90c-40b5-a16d-520f681c2d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[22]/preceding::div[1]</value>
      <webElementGuid>64936807-7ef4-45ca-874e-4e7b9f10e21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S 134.690,48'])[1]/preceding::div[6]</value>
      <webElementGuid>ab2f5308-da1b-474e-a9ac-f89478bbe950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>834e7b10-8975-4089-b520-7e75774807be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_lblAccountCurrency' and (text() = 'U$S' or . = 'U$S')]</value>
      <webElementGuid>2c95e940-5e4b-4036-af0b-84cdb2a64531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
