<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblDenominacionConfirm</name>
   <tag></tag>
   <elementGuidId>ed4dd93e-4f51-4827-b3e5-cef48e5c9cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightDenomination</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightDenomination']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>260dfaa1-da3e-4d3f-979a-bd7b8ef71362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightDenomination</value>
      <webElementGuid>1d601e94-ef4f-4e91-80c7-0a9713830b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>4f269062-eac1-48de-96ab-70abfd3aeba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>8bf22e8e-c0f4-420b-a60b-690f91c9f008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>OwnConfirmTransfer</value>
      <webElementGuid>8942224f-6ecb-4747-afef-9bdcd9dca686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddlerightalign disableSelection</value>
      <webElementGuid>c3603dac-d4b8-4175-b741-3754a310eeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TITLE-1 11190118359</value>
      <webElementGuid>ca70dcab-6ea0-40a1-a09a-588dc1860c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightDenomination&quot;)</value>
      <webElementGuid>6df3d9ff-5fe0-4cf7-9df5-8d624389ad07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightDenomination']</value>
      <webElementGuid>ef9fa738-89aa-451a-b379-fbcc8ae8f2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_OwnConfirmTransfer_flxRowThree']/div[2]/div</value>
      <webElementGuid>54b1898f-598d-4dcc-b2bc-90a380c430be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denominación'])[1]/following::div[2]</value>
      <webElementGuid>cd1b1035-20cb-44d3-a060-8c257abd213c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 119-011835/9'])[1]/following::div[7]</value>
      <webElementGuid>93e6e293-6d4f-4dbf-8db3-e3e0dbbfd51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de envío'])[2]/preceding::div[1]</value>
      <webElementGuid>6a94e3b6-7230-4111-8adf-81c17be82677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Correo electrónico'])[2]/preceding::div[14]</value>
      <webElementGuid>3c9320d3-dbe1-4661-8410-775fa6ec5bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TITLE-1 11190118359']/parent::*</value>
      <webElementGuid>9b2acd6c-d34f-4857-82aa-2ad768d6431f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div[4]/div/div/div[2]/div</value>
      <webElementGuid>4b487c2b-c5b0-4595-a688-c7c8800c033a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightDenomination' and (text() = 'TITLE-1 11190118359' or . = 'TITLE-1 11190118359')]</value>
      <webElementGuid>629643d1-3335-400e-8ee9-1845b4c9c53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
