<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblNumeroTrx</name>
   <tag></tag>
   <elementGuidId>d158a546-6605-4172-9e39-87fb4c91743d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountNumberSaved</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountNumberSaved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>228d70ba-2a73-449a-b66f-7a2a61a379c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountNumberSaved</value>
      <webElementGuid>072ed01e-2fcd-49c9-b674-73583c7b3246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>b11dfb30-5fc2-4331-ae1e-fb85f1e7ccc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>6f1cf524-2efb-4625-a086-af9501cff542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>BeneficiaryTransfer</value>
      <webElementGuid>67b656d0-7c82-4c1a-9292-6f299874d951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblBeneficiaryTransferDataSaved cntmiddlerightalign disableSelection</value>
      <webElementGuid>4c339534-5df0-4ee2-ad7d-5b47823a3a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA $ 119-011835/9</value>
      <webElementGuid>6cefaf4e-7aad-4000-98d4-a3078f6cbf83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountNumberSaved&quot;)</value>
      <webElementGuid>9497ba32-37ec-4a9f-8ded-11285d41976c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountNumberSaved']</value>
      <webElementGuid>70155191-ff99-4f78-a4d6-e80ff1e671f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_flxAccountNumberContainerDataSaved']/div[2]/div</value>
      <webElementGuid>a3b20888-1096-4941-b49b-4a230e777951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número'])[1]/following::div[2]</value>
      <webElementGuid>d620a784-dec6-45bb-ba26-6e1883c8416a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro sueldo ..'])[1]/following::div[7]</value>
      <webElementGuid>3e476c81-7f98-4b82-88ac-d601cc6dbc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denominación'])[1]/preceding::div[1]</value>
      <webElementGuid>4ff801d2-7c66-4ee0-bb4a-4407db503f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE-1 11190118359'])[1]/preceding::div[3]</value>
      <webElementGuid>7c61fb68-032c-4db0-be68-f6edfca4257a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA $ 119-011835/9']/parent::*</value>
      <webElementGuid>e569dd1b-708f-4bdc-b17d-96ac8c8eebbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>6f2fffed-0e76-49a2-9b39-f9cafa1174f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountNumberSaved' and (text() = 'CA $ 119-011835/9' or . = 'CA $ 119-011835/9')]</value>
      <webElementGuid>574baac8-6713-4241-be24-b9e8adc4e291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
