<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrxDenominacion</name>
   <tag></tag>
   <elementGuidId>15132b90-a86c-4681-862a-bf6eb90c64e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>660734ff-025f-4016-a8e1-3dad4b4be7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved</value>
      <webElementGuid>a798ac59-4a18-4227-bb11-7acaade86cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>6a54eaa2-f469-4555-9c05-137d20347ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>947cda67-737f-484d-af14-4756b8ac4bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>BeneficiaryTransfer</value>
      <webElementGuid>c1204ba4-bc57-4ca7-a427-8b97a18e3e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblBeneficiaryTransferDataSaved cntmiddlerightalign disableSelection</value>
      <webElementGuid>6009ae25-557e-4ea5-b78a-20d29f2ac2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TITLE-1 11190118359</value>
      <webElementGuid>0548083d-1053-45c7-827b-0e4dcab1d0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved&quot;)</value>
      <webElementGuid>5829b3be-40c5-4fb2-84f6-b4a2b5573be4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved']</value>
      <webElementGuid>a11b8c5f-36e6-44f7-a1e1-1bc2566db6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_flxAccountDenominationContainerDataSaved']/div[2]/div</value>
      <webElementGuid>fe70c94d-fd92-45a9-b140-8b013dc6232e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denominación'])[1]/following::div[2]</value>
      <webElementGuid>405959af-71e1-4205-a907-81f9ea3fd053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 119-011835/9'])[1]/following::div[7]</value>
      <webElementGuid>0fac8053-a3a6-4e70-a232-1cb7e5c7e744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de envío'])[1]/preceding::div[5]</value>
      <webElementGuid>885cc7ab-93b1-4b6a-afde-7a8184edbb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[1]/preceding::div[21]</value>
      <webElementGuid>3b5e42ca-71b1-41cd-b061-1a912106b0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TITLE-1 11190118359']/parent::*</value>
      <webElementGuid>24370793-829c-4a3f-86e9-771890305b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>32fdae1b-0039-4d04-ba17-5d27e946cedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved' and (text() = 'TITLE-1 11190118359' or . = 'TITLE-1 11190118359')]</value>
      <webElementGuid>eba103af-a298-45fb-ab51-2961c592f8ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
