<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrfMontoSuperaLimite</name>
   <tag></tag>
   <elementGuidId>46b612d6-6d1d-433a-b27c-37f15457fdf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>89cfadb5-11cf-4b0d-b556-3243cd687247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip</value>
      <webElementGuid>e207523e-dda0-4d77-b5fa-cc84b1694822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>RichText</value>
      <webElementGuid>4e88a18e-2b9f-4e7b-b5e0-6be484a86fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>f4e959fb-9ed3-4b44-bf99-bed8c129761b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AmountInput</value>
      <webElementGuid>39803c94-3d42-4326-b811-8e03c3aafee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknRtxValidationError </value>
      <webElementGuid>3fffa9b0-1dad-44d5-8f67-a2ec45051571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>El monto ingresado supera tu límite disponible para realizar esta transferencia. </value>
      <webElementGuid>298e961e-8ced-428c-a76d-57fd5fc8527d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip&quot;)</value>
      <webElementGuid>9e2483c5-8cc9-4bb4-9f23-2aa3438bafa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip']</value>
      <webElementGuid>d4fe5b38-1135-4240-905c-0c4d7d827363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_AmountInput_flxValidationError']/div[3]/div</value>
      <webElementGuid>0d043395-2dab-409d-8a15-6c870fdf0945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El monto ingresado supera tu límite disponible para realizar esta transferencia.'])[1]/following::div[2]</value>
      <webElementGuid>1990b1d8-83eb-4761-9ce0-92f52a4bcbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[4]</value>
      <webElementGuid>1a3fdd3e-18eb-4362-8f0b-e38d14b3b288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titularidad de la cuenta'])[1]/preceding::div[1]</value>
      <webElementGuid>36bad516-9c76-4efc-8784-d4b70d70cbc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div/div/div/div[4]/div/div/div[3]/div</value>
      <webElementGuid>20dd7ab0-663f-40d2-8ab7-85c25ec2a2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_AmountInput_rtxValidationErrorTooltip' and (text() = 'El monto ingresado supera tu límite disponible para realizar esta transferencia. ' or . = 'El monto ingresado supera tu límite disponible para realizar esta transferencia. ')]</value>
      <webElementGuid>bc9ce724-872b-466e-8c30-a800da2fa1d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
