<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LiTrxCtasPropiasCredicoop</name>
   <tag></tag>
   <elementGuidId>a7eae2a1-fff9-460d-b4e3-9139dc1f3f83</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[1]/form/div[3]/div/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div/ul</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxMisCuentasCredicoopRow_flxAccountContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>660a2269-7c1c-48ea-9ffc-431201e813ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>35f3bac4-63f2-43d9-8a0e-42f9b0d0bed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_flxAccountContainer</value>
      <webElementGuid>b3291bc8-59ca-492a-a298-14bd257b86a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>09beda71-4d73-491b-a85a-3e2aa9247122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>3dadd4c2-3989-4794-9c2b-1d166a897e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>8beab5ab-d91b-4e4e-a411-f8e60915a327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>6F4EF634-3A25-4803-94D5-4FC290724FBF</value>
      <webElementGuid>bfb6e624-5543-4828-a8a0-b245d4ccfab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Caja de Ahorro sueldo prueba $CA $ 119-011835/9TITLE-1 11190118359</value>
      <webElementGuid>ff75fa5c-5b0b-4fea-b475-658629320e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxAccountContainer&quot;]</value>
      <webElementGuid>e48787ad-1d7f-450e-b174-0d040fbf5a87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxMisCuentasCredicoopRow_flxAccountContainer']</value>
      <webElementGuid>1c47ea85-466a-42a8-a928-1808b2f36894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[336]</value>
      <webElementGuid>7fdbcaa1-9072-4101-b795-db89280d0194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[11]/following::div[20]</value>
      <webElementGuid>8ff6990a-0b17-416e-9675-1342693ea18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[27]</value>
      <webElementGuid>2d298849-7b3b-46ec-9b7b-a93eea505699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul</value>
      <webElementGuid>087610b2-2fad-4996-8173-ec80c50058b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_flxAccountContainer' and (text() = 'Caja de Ahorro sueldo prueba $CA $ 119-011835/9TITLE-1 11190118359' or . = 'Caja de Ahorro sueldo prueba $CA $ 119-011835/9TITLE-1 11190118359')]</value>
      <webElementGuid>230e2e42-3a46-4509-94b7-b019ad09dbae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
