<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMontoComprobDolar</name>
   <tag></tag>
   <elementGuidId>bd9c1ef3-296b-4d10-9ca8-708f00a20361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_Receipt_lblAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_Receipt_lblAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e21ed3ee-80f6-4e70-90cc-ab0030a918c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_Receipt_lblAmount</value>
      <webElementGuid>8025684e-f595-4ac2-9b88-dbc1b0e1129c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>ba4843e0-b254-473c-97c1-d5eae894faa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>74b7e38c-886e-4cb7-9cc6-f28ae8ae6f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Receipt</value>
      <webElementGuid>e6476713-b4da-4300-8005-6247391abb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblConfirmTransfervalue1433 cntmiddlerightalign disableSelection</value>
      <webElementGuid>77289a4e-4614-444e-93f6-90fd9791c808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>U$S 1,00</value>
      <webElementGuid>eeca2240-5d0b-45de-ad0d-74cad89f03ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_Receipt_lblAmount&quot;)</value>
      <webElementGuid>f34035d4-a5df-41a7-bb34-c7a73c4cb409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_Receipt_lblAmount']</value>
      <webElementGuid>49168f41-3608-4985-adf4-33a95889becb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_Receipt_flxAmountRow']/div[2]/div</value>
      <webElementGuid>da69f80e-cd9e-49a7-af64-79f11987c6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[3]/following::div[2]</value>
      <webElementGuid>b92ba288-66b1-4132-8d51-d0fea2b7b479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de emisión'])[1]/following::div[9]</value>
      <webElementGuid>bcf66949-89c2-4069-ac5e-2868e484f90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Origen'])[3]/preceding::div[1]</value>
      <webElementGuid>72131479-61bf-4ad4-83e9-0ffcc87ab7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro U$S 2'])[2]/preceding::div[3]</value>
      <webElementGuid>90ff86ac-ab10-429a-82fe-200b7657e3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>75e5e076-b326-4752-b899-a673c9b868d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_Receipt_lblAmount' and (text() = 'U$S 1,00' or . = 'U$S 1,00')]</value>
      <webElementGuid>b2ddb4b0-fb49-428f-aa19-f7e3803d7ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
