<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxListaNumeroCuentaDolar</name>
   <tag></tag>
   <elementGuidId>ea8eff12-4c7c-4386-b3f2-6419a38d2764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxMisCuentasCredicoopRow_flxAccountContainer']/div[2]/div)[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13e62117-feb0-4f17-9328-19a47af3d6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_lblAccountDetail</value>
      <webElementGuid>e9a35365-72a9-4e31-a3bd-41ea69acd053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>a3bbe83e-297f-49cd-b781-7cd197d91eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>0ec3260f-c24a-4eaf-8ace-72722f3a6ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>bd0aa5fb-256f-461b-94be-c501dc712efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>03D842E9-8D7A-42FE-9015-286534CEB250</value>
      <webElementGuid>6fa07cdb-312b-4193-b6fc-ad431eed120e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountDetailDashboard cntmiddleleftalign disableSelection</value>
      <webElementGuid>7c7b1775-b2f6-474e-b527-e802b4fc61b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA U$S 440-008674/9</value>
      <webElementGuid>ba85f4bb-843f-4d44-84b5-7c87291b3c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxAccountContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblAccountDetailDashboard&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountDetail&quot;]</value>
      <webElementGuid>13b37468-3b1f-4a6c-9624-7bf8c1f9e438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_lblAccountDetail'])[11]</value>
      <webElementGuid>7ddb3140-ead8-4163-b5c6-9d0e6d100bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_flxAccountContainer']/div[2]/div)[11]</value>
      <webElementGuid>38ebd754-e972-40a8-8ca5-0e8e59c7fadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro U$S 2'])[1]/following::div[2]</value>
      <webElementGuid>0558e6ce-1e7a-424b-81e7-06d0e4be985b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 28.349,77'])[1]/following::div[9]</value>
      <webElementGuid>0719e461-2354-42b5-abc4-8ba10a1c54c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE-1 24400086749'])[1]/preceding::div[1]</value>
      <webElementGuid>8f758fd0-e627-4837-9dc1-211a17116083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S'])[6]/preceding::div[3]</value>
      <webElementGuid>0f9b5918-4caa-414d-ba3a-06c5b3ea498a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA U$S 440-008674/9']/parent::*</value>
      <webElementGuid>6f2e97ab-e868-4b4a-8440-81b5abbdd765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>14a4d569-ae31-4cff-ba69-203dada75dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_lblAccountDetail' and (text() = 'CA U$S 440-008674/9' or . = 'CA U$S 440-008674/9')]</value>
      <webElementGuid>ac64e456-0211-49ee-b84d-32c542a07940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
