<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrfListaNombreCajaAhorroDolres</name>
   <tag></tag>
   <elementGuidId>19bf907f-5498-4c17-bb36-01dfdfd9eb58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxMisCuentasCredicoopRow_lblAccountTitle'])[11]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76b100b4-9de1-4ca2-93fa-03f0a4925a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_lblAccountTitle</value>
      <webElementGuid>329b975e-d6ff-4c7a-9a6e-4abeb2985d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>84ac4aff-7c93-499a-9e82-0c9161502981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>fe64240d-c468-4c47-9e0b-5ec49649d90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>f3559481-9b64-4bb1-b043-675b23a47a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>87482A78-BC40-4C41-BA58-4E80C561EFF6</value>
      <webElementGuid>0c4d4a73-a5b2-4809-9152-0017bd93d191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountTitleBcclAccounts cntmiddleleftalign disableSelection</value>
      <webElementGuid>4df0a585-6824-4d75-8817-d6a47b80225f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Caja de Ahorro U$S 2</value>
      <webElementGuid>0fc4959e-f5ad-4a92-9d3b-9c72a7781921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxAccountContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblAccountTitleBcclAccounts&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblAccountTitle&quot;]</value>
      <webElementGuid>66712523-9778-4ebc-b2ed-689794aaf56a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_lblAccountTitle'])[11]</value>
      <webElementGuid>acc81b8a-d63a-4d15-8d9d-f6be2238b412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_flxAccountContainer']/div/div)[31]</value>
      <webElementGuid>bf0c2d67-441d-4248-8cf9-0a5433ee18bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 28.349,77'])[1]/following::div[7]</value>
      <webElementGuid>64371c1b-ca81-46e5-b45d-aad9384e1e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[21]/following::div[9]</value>
      <webElementGuid>ab927802-23fb-4c2c-80ef-ec23f3a850b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 440-008674/9'])[1]/preceding::div[1]</value>
      <webElementGuid>e706c513-473f-48c7-9834-acdc32900181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TITLE-1 24400086749'])[1]/preceding::div[3]</value>
      <webElementGuid>af104b32-e25e-4578-ac14-dddf5fc62234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Caja de Ahorro U$S 2']/parent::*</value>
      <webElementGuid>a1c3e70d-2279-42ef-a7e1-54d89c6e3dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/div/div/div/div/div/div/div</value>
      <webElementGuid>7c3fbad6-7bee-4048-baac-ad3abf2251a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_lblAccountTitle' and (text() = 'Caja de Ahorro U$S 2' or . = 'Caja de Ahorro U$S 2')]</value>
      <webElementGuid>0db36244-339c-4560-9838-6403cf396013</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
