<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxNvoBenefNmeroCuenta</name>
   <tag></tag>
   <elementGuidId>345f5d8a-0f5a-400a-bbbf-05bc5dd5e599</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclBeneficiaryAgenda_NewBeneficiary_lblAccountNumberDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_lblAccountNumberDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8de9dce0-415e-4b8d-9a1f-a5ffffa7894c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda_NewBeneficiary_lblAccountNumberDesc</value>
      <webElementGuid>735aba21-9463-41d9-8211-3a12de3c2b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>176a4d15-be60-4367-bd3c-5a97c50ff856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclBeneficiaryAgenda</value>
      <webElementGuid>08a05122-ef0d-4d80-bef6-0753c5b1b013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>NewBeneficiary</value>
      <webElementGuid>4cd70d8e-d1b5-4af0-9b1f-af8423f649ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblNewBeneficiaryTitle cntmiddleleftalign disableSelection</value>
      <webElementGuid>2ba5aa9e-0a22-49eb-a14b-8eea08b936db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Número de cuenta (Sólo cuentas Credicoop)</value>
      <webElementGuid>da45c7ac-a999-4d0d-865a-4d2db7f1bedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclBeneficiaryAgenda_NewBeneficiary_lblAccountNumberDesc&quot;)</value>
      <webElementGuid>625769e2-7ec8-4751-af9b-4f5cfb42abac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_lblAccountNumberDesc']</value>
      <webElementGuid>b6505f4c-2455-47ae-b3a0-96dc67d5a3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclBeneficiaryAgenda_NewBeneficiary_flxAccountNumberContainer']/div/div</value>
      <webElementGuid>6dab3e21-3309-4a40-8be7-8e5c6c0b7a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[8]</value>
      <webElementGuid>af4ecba1-0cec-4ed4-aee8-51c2440c3b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alias'])[2]/following::div[10]</value>
      <webElementGuid>6af90b01-72c5-4082-b9ff-576bdbfac8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/preceding::div[1]</value>
      <webElementGuid>f87f921f-57ec-44a2-902e-71e48e925345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/preceding::div[6]</value>
      <webElementGuid>5fa488e7-8f98-4110-ac37-f26e5f845fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Número de cuenta (Sólo cuentas Credicoop)']/parent::*</value>
      <webElementGuid>4a2c2c7f-6dae-4cee-9717-7ceeb92c0b7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div/div/div[4]/div/div/div/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>1855492c-de93-4b1f-9003-6ac0e4ad21ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclBeneficiaryAgenda_NewBeneficiary_lblAccountNumberDesc' and (text() = 'Número de cuenta (Sólo cuentas Credicoop)' or . = 'Número de cuenta (Sólo cuentas Credicoop)')]</value>
      <webElementGuid>aad85e89-2185-44c3-beb2-c0ff82b26522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
