<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMontoConfirm</name>
   <tag></tag>
   <elementGuidId>0ee41a72-0528-41a6-a2d0-0729a0a2955b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2087a02-95c0-4a20-9255-e3c244909af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightAmount</value>
      <webElementGuid>d59a7450-4e76-4dcc-9373-cb07b83f5403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>295127b6-43fe-48f6-8bcd-88103b808ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>5db2784e-dd82-4ced-943f-d820cd84ccdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>OwnConfirmTransfer</value>
      <webElementGuid>ff17d2cf-59f2-4d83-bd8f-6e21de310e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblConfirmTransfervalue cntmiddlerightalign disableSelection</value>
      <webElementGuid>833a68ca-641a-4ccf-b1b3-b9a413894709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 1,00</value>
      <webElementGuid>da3e9afe-5362-4de9-9a13-0b9608ff5619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightAmount&quot;)</value>
      <webElementGuid>f3e509b0-0cbe-412c-8308-5555392de077</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightAmount']</value>
      <webElementGuid>2fc0270f-db5d-4e1c-abc1-b7d36f2a1024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_OwnConfirmTransfer_flxRightAmount']/div/div</value>
      <webElementGuid>58c6e3bf-4307-4860-8927-81a514aa0c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[2]/following::div[5]</value>
      <webElementGuid>67f782c7-fb44-4bec-953f-bdcf3a809f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar Transferencia'])[2]/following::div[16]</value>
      <webElementGuid>158751fb-b2ee-46bf-ae8b-aba66dfea789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Origen'])[2]/preceding::div[1]</value>
      <webElementGuid>b3590330-cb33-4ec0-a2da-982fc3d66899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENRICO EDIE AGUSTIN'])[1]/preceding::div[6]</value>
      <webElementGuid>e822d162-1fd7-4c1e-8f6f-b1febbd2a0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 1,00']/parent::*</value>
      <webElementGuid>a7e4cade-c55e-40a1-99be-68bc05bbbece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>9ccbb6f5-1cf3-4119-b9f6-b21c9c843fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_OwnConfirmTransfer_lblRightAmount' and (text() = '$ 1,00' or . = '$ 1,00')]</value>
      <webElementGuid>5a57aa6a-686a-48eb-bc24-bb559290b323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
