<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrfListaDnomCuentaDolares</name>
   <tag></tag>
   <elementGuidId>920167b7-dceb-413c-ba2d-160d79f4a1dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxMisCuentasCredicoopRow_lblDenominacionCuenta'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61e1ac2d-5a0b-47f1-95d1-693ea603b1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow_lblDenominacionCuenta</value>
      <webElementGuid>36c7003f-7685-41c1-b082-0882ae5879b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>b7f332a4-e60d-48de-9f3f-e5dd3b1b05a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxMisCuentasCredicoopRow</value>
      <webElementGuid>d2a330e7-2348-4ea9-b177-81dd39fec1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>e75da791-8403-48f4-80de-1ad635e72eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>BCD0E4F5-AA8F-4BDD-A6BD-29CBB2392CFD</value>
      <webElementGuid>9e36b451-24e0-495d-a0d6-f2e57ed89236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountDetailDashboard cntmiddleleftalign disableSelection</value>
      <webElementGuid>88436c42-1941-4772-b250-a70e9dc55a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TITLE-1 21190118359</value>
      <webElementGuid>99caff4f-f3ab-4cd8-8433-814c90cde237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmNewTransferBccl_segAccounts&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxMisCuentasCredicoopRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_flxAccountContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblAccountDetailDashboard&quot;]/div[@id=&quot;flxMisCuentasCredicoopRow_lblDenominacionCuenta&quot;]</value>
      <webElementGuid>74a3b8e0-5f4c-428c-8609-577306d971f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_lblDenominacionCuenta'])[2]</value>
      <webElementGuid>76e870f1-dc18-43c7-a809-a1d36ce5ec0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxMisCuentasCredicoopRow_flxAccountContainer']/div[3]/div)[2]</value>
      <webElementGuid>ead4cf9b-9796-4af0-933b-c9120a2877f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 119-011835/9'])[1]/following::div[2]</value>
      <webElementGuid>bbefff90-6d76-41d1-80b9-ed2a1fef27ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro en dólares'])[1]/following::div[4]</value>
      <webElementGuid>07d34323-2acb-4c1c-9485-f8de254817c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S'])[6]/preceding::div[1]</value>
      <webElementGuid>df815fd7-691f-446b-ae7d-ab340bc9b33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[13]/preceding::div[9]</value>
      <webElementGuid>f5f6fb7b-39b8-44ec-a750-e5753195eb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TITLE-1 21190118359']/parent::*</value>
      <webElementGuid>49c8213b-5840-4a99-8377-3c3ccca14c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/div/div[3]/div</value>
      <webElementGuid>55a64c88-7ab4-4375-8db9-21445ac37209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxMisCuentasCredicoopRow_lblDenominacionCuenta' and (text() = 'TITLE-1 21190118359' or . = 'TITLE-1 21190118359')]</value>
      <webElementGuid>7a0c3f38-fd5e-4174-9531-b13251a27b2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
