<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxNumOperacionComprobante</name>
   <tag></tag>
   <elementGuidId>cbda5123-5184-42b2-819a-dfa68d2abb0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_Receipt_lblOperationNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_Receipt_lblOperationNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bab7dcbf-844f-4da9-a053-c96b6fda18c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_Receipt_lblOperationNumber</value>
      <webElementGuid>a4f53d01-7075-448a-a1a6-c9d0f482a087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>8804710f-4a8c-4c05-bded-77d78877eb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>dbbc0845-ea77-49e9-a670-d352600b9e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Receipt</value>
      <webElementGuid>d03d9db2-f324-49f7-bc8a-37066ecef2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblConfirmTransfervalue cntmiddlerightalign disableSelection</value>
      <webElementGuid>87bd355c-e8a8-43aa-9dc6-5b643a0042ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7195</value>
      <webElementGuid>f7a003ff-ac16-49b3-a9b3-4ac8e70e0bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_Receipt_lblOperationNumber&quot;)</value>
      <webElementGuid>609623fb-2d6c-4793-a75b-3edb666da22c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_Receipt_lblOperationNumber']</value>
      <webElementGuid>e9ebdb75-1e09-4406-8ee0-bf2f94e16532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_Receipt_flxOperationNumberRow']/div[2]/div</value>
      <webElementGuid>4c4fb732-58d0-42c1-a133-6bff98c230d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Operación'])[3]/following::div[2]</value>
      <webElementGuid>76b837b9-7633-4f05-8eac-532c3c0003dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprobante de Transferencia'])[1]/following::div[10]</value>
      <webElementGuid>e1f46e34-4d33-4ea6-8516-fcd7eadf1488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de emisión'])[1]/preceding::div[1]</value>
      <webElementGuid>2cf2b823-e2ba-4989-a6fd-7856ab4a97e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[3]/preceding::div[8]</value>
      <webElementGuid>3ff491d2-541a-4d3d-b93a-03f9b1e7b41e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>a615711b-af8d-4cf8-aa57-355172b6dbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_Receipt_lblOperationNumber' and (text() = '7195' or . = '7195')]</value>
      <webElementGuid>1f4a2a0a-af0f-4007-a8df-8ca7f537e500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
