<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrfNuevaTransferenciaInicioCtaDolares</name>
   <tag></tag>
   <elementGuidId>f250d5b0-69b0-49d0-b2a0-37f754f2ec97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsLanding_flxAccountDashboardRowFloatingMenu_lblnewTransfer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsLanding_flxAccountDashboardRowFloatingMenu_lblnewTransfer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>838915bf-34c2-4d1d-8db8-c2d05a2f30bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsLanding_flxAccountDashboardRowFloatingMenu_lblnewTransfer</value>
      <webElementGuid>90bda082-16bb-4f97-8418-fdc451839bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>8adf37b8-d3dc-401f-b2aa-af05e8779107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsLanding</value>
      <webElementGuid>033bd0e3-d58d-4d03-a091-00a68247ca53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>flxAccountDashboardRowFloatingMenu</value>
      <webElementGuid>1f6b061b-f575-4dbb-9a59-6270476550f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>138d3164-c17d-4caa-b61b-9c0347256929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva transferencia</value>
      <webElementGuid>92635523-e6da-4873-ba6f-324f74136aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsLanding_flxAccountDashboardRowFloatingMenu_lblnewTransfer&quot;)</value>
      <webElementGuid>6e0e5ad5-ae96-4da2-9041-a6731a394e58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_flxAccountDashboardRowFloatingMenu_lblnewTransfer']</value>
      <webElementGuid>786317a9-2c72-4f3b-8d78-70a22abcf143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_flxAccountDashboardRowFloatingMenu_flxnewTransfer']/div/div</value>
      <webElementGuid>73c11da6-1ff7-4f27-b95c-d9a52fcea192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copiar el CBU'])[1]/following::div[5]</value>
      <webElementGuid>ce72fcd0-068b-41cc-8565-3efa72c2f11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultar Alias / CBU'])[1]/following::div[10]</value>
      <webElementGuid>71101e2b-8b20-47ef-9dcd-a1ac35ca4fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver resúmenes'])[1]/preceding::div[1]</value>
      <webElementGuid>bfc91c37-4f83-4697-9bad-237c705a5e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[8]</value>
      <webElementGuid>147bc78e-9472-4920-a2cd-5eb45d31a5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nueva transferencia']/parent::*</value>
      <webElementGuid>5b87fff6-6eac-46a4-99a3-d25e5f28d712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>8917853f-a67d-4247-8d07-bacc24da3d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsLanding_flxAccountDashboardRowFloatingMenu_lblnewTransfer' and (text() = 'Nueva transferencia' or . = 'Nueva transferencia')]</value>
      <webElementGuid>b87bdc80-9bf4-4c85-a224-1494211202c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
