<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMontoExitoDolar</name>
   <tag></tag>
   <elementGuidId>314aa006-a695-4915-8b4e-229c66e75197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc96a998-b5d2-4fa6-af0b-9c022e99af41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess</value>
      <webElementGuid>bfba34bb-682c-475d-9538-89f4e16bed8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9af9afb6-cc94-4952-9982-eed94a2f48af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclConfirmTransfer</value>
      <webElementGuid>3b37752a-b96f-4f51-9e87-df4e3080b4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferMessage</value>
      <webElementGuid>92bb7673-22b3-4af9-8b48-e09e4e286d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblSuccessTransferAmount cntmiddlerightalign disableSelection</value>
      <webElementGuid>0e755c03-c3bf-4c36-b248-2548bf24a94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>U$S 1,00</value>
      <webElementGuid>0ba01575-ddfd-4bb7-b9e9-d8c745050631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess&quot;)</value>
      <webElementGuid>73210a83-bc24-45ee-bcd1-705998f2c722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess']</value>
      <webElementGuid>0bc9a7cb-d3b4-4bcc-a59f-229eaba85960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclConfirmTransfer_TransferMessage_flxFirstRowSuccess']/div[3]/div</value>
      <webElementGuid>40d7f222-9827-4e3a-a7f4-57d2c3efb512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='viviendolasimulacion'])[2]/following::div[2]</value>
      <webElementGuid>bbb5c131-c6bb-463c-965b-03649f6e7135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SZIR MARIA ALEJANDRA'])[3]/following::div[4]</value>
      <webElementGuid>31d50e59-0922-47c5-b8da-5c459d0def1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Operación'])[1]/preceding::div[1]</value>
      <webElementGuid>6e34964a-24e1-41f6-be67-ee448adbb973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargando'])[1]/preceding::div[9]</value>
      <webElementGuid>e828d01e-f626-40f3-a3e5-83d090046624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[3]/div</value>
      <webElementGuid>51479992-b4e8-4358-8427-6730a8d1325f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclConfirmTransfer_TransferMessage_lblAmountRowSuccess' and (text() = 'U$S 1,00' or . = 'U$S 1,00')]</value>
      <webElementGuid>e4c3df79-9385-4e70-a86e-f435cee9222f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
