<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrfFormDenomCuentaDolar</name>
   <tag></tag>
   <elementGuidId>40f227b0-9233-4cb1-9d18-0c77613b44cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved&quot;)[count(. | //*[@id = 'frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved' and (text() = 'TITLE-1 24400086749' or . = 'TITLE-1 24400086749')]) = count(//*[@id = 'frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved' and (text() = 'TITLE-1 24400086749' or . = 'TITLE-1 24400086749')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6ac9154c-e4d9-4204-b3c4-40c3eed3ca1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved</value>
      <webElementGuid>cd57b122-4717-45b7-a158-841dbd34cc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>33e3bf38-4711-47aa-b9d1-4f67fc156ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCreateTransfer</value>
      <webElementGuid>de4061c1-9ab6-48f9-8a20-29d052c929e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>BeneficiaryTransfer</value>
      <webElementGuid>da31ea90-b003-48c5-a5c4-d1fd6677a8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblBeneficiaryTransferDataSaved cntmiddlerightalign disableSelection</value>
      <webElementGuid>cbab1640-2197-40d4-a970-d3ecb0db89d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TITLE-1 24400086749</value>
      <webElementGuid>4bc71e97-fef7-439f-9e77-ab93880f6dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved&quot;)</value>
      <webElementGuid>530130ee-ace3-4285-93be-40ebd14cd3f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved']</value>
      <webElementGuid>bb13cd01-32da-4818-9e9c-55a2da60d779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCreateTransfer_BeneficiaryTransfer_flxAccountDenominationContainerDataSaved']/div[2]/div</value>
      <webElementGuid>a11c4d41-0c45-4a0a-8d35-965b20e80eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denominación'])[1]/following::div[2]</value>
      <webElementGuid>53b2296a-4ce2-404c-b059-256825bbe260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 440-008674/9'])[1]/following::div[7]</value>
      <webElementGuid>bd7853cd-cbf2-4376-8e25-564efb5678fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de envío'])[1]/preceding::div[5]</value>
      <webElementGuid>462f9af9-1aca-4aa1-aee0-d8ad02ba4e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[1]/preceding::div[21]</value>
      <webElementGuid>fbcedf1e-3b57-45a6-8720-b7db0682b8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TITLE-1 24400086749']/parent::*</value>
      <webElementGuid>377dea07-78e3-4c68-b3f5-a428bd174a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>1002bcd4-ce4b-43a1-ae90-6e8069e26cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCreateTransfer_BeneficiaryTransfer_lblAccountDenominationSaved' and (text() = 'TITLE-1 24400086749' or . = 'TITLE-1 24400086749')]</value>
      <webElementGuid>92aed707-0b67-4518-8fd5-1f4743e4f683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
