<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTrjDebitoGuardarLimite</name>
   <tag></tag>
   <elementGuidId>0dc0dab5-c470-49da-8376-0603b1278e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclDebitCardLimits_ButtonWithLoader_btnWithLoader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclDebitCardLimits_ButtonWithLoader_btnWithLoader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07e8ff6d-a899-4af5-9a0d-567f7bb4ab27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>8ae6b818-14c3-49b2-ae2a-d0ea6741420f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmBcclDebitCardLimits_ButtonWithLoader_btnWithLoader-hint</value>
      <webElementGuid>b99536b2-fd61-4606-97be-82f3a797268b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclDebitCardLimits_ButtonWithLoader_btnWithLoader</value>
      <webElementGuid>f92db271-19b5-4f39-8eab-b5333aea8827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>386a664b-3927-4f50-8be4-499f5f562cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclDebitCardLimits</value>
      <webElementGuid>cc0c12d8-62fe-4f4e-862b-27bf5dd5dd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ButtonWithLoader</value>
      <webElementGuid>4a7a0fc4-1798-4db2-94eb-d020d1f68e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ab676b1-2a88-4c70-a7b2-e92ddebf9600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknBtnPrimary</value>
      <webElementGuid>c00ba138-cee8-4be3-99dd-4f9792cbcc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>0561f440-f7a1-4eea-904e-bf6626e0743e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>c664d6f0-f20e-4ce1-9f62-49a579b514c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad5e9021-d315-46ca-928c-c3aaba94e388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclDebitCardLimits_ButtonWithLoader_btnWithLoader&quot;)</value>
      <webElementGuid>e9b8c713-c89b-489f-91d4-cb05a73e5c97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclDebitCardLimits_ButtonWithLoader_btnWithLoader']</value>
      <webElementGuid>db5bf232-7002-46e7-b824-e281695d24e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclDebitCardLimits_ButtonWithLoader']/div/input</value>
      <webElementGuid>4aae4647-2987-4bee-bf90-81654f50c76f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>a17136dd-3e5b-42a9-8e6c-a34e0aef47d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclDebitCardLimits_ButtonWithLoader_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>25571215-d83b-4e62-9ebb-d400cabc64f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
