<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnTrjListaCuentaPrincipalGuardar</name>
   <tag></tag>
   <elementGuidId>94cb0bfd-39ea-44be-a913-289c880e75f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmBcclCardsHome_Panel_debitCardsPrimary_btnContinueStep1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardsHome_Panel_debitCardsPrimary_btnContinueStep1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af802ed2-26dd-4113-98c1-8aff301863f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardsHome_Panel_debitCardsPrimary_btnContinueStep1</value>
      <webElementGuid>f3834d86-66fe-4ebd-8ca3-918ca61bfc55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>02a50807-efb3-4192-afd0-afd964767ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardsHome</value>
      <webElementGuid>c66f6e61-ae96-41e7-8110-9086a8ba323b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Panel_debitCardsPrimary</value>
      <webElementGuid>b8cf50e5-d518-4605-8b8c-a19706be46bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66bfa37a-ffb5-4373-afb8-31d28d976170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>6f55b0c8-051f-4918-8a6e-3c1c92d4b320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>ae3d9701-9f5d-4a8a-a6df-7d83737138b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>17b441fa-1899-45a0-af52-7e34fa3692e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardsHome_Panel_debitCardsPrimary_btnContinueStep1&quot;)</value>
      <webElementGuid>d8c49682-b147-4090-98d8-9ca0c4ff8bd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmBcclCardsHome_Panel_debitCardsPrimary_btnContinueStep1']</value>
      <webElementGuid>1d10add0-431d-4b98-bfbb-892012c9811b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_Panel_debitCardsPrimary_flxButtons']/div[2]/input</value>
      <webElementGuid>bbce7778-45ff-4d6b-b23c-3738a77390e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>e62c148e-d368-4af9-a24d-334664be862d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmBcclCardsHome_Panel_debitCardsPrimary_btnContinueStep1' and @type = 'button']</value>
      <webElementGuid>618fabdf-2ef2-40eb-a30c-ba3caa36ba23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
