<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoCalendario</name>
   <tag></tag>
   <elementGuidId>418866e8-f851-4a25-9b92-d70a53965d12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendarDateFilterFrom_img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='calendarDateFilterFrom_img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dad7a9f4-34b3-4653-995e-216bcca3e05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendarDateFilterFrom_img</value>
      <webElementGuid>99b9972b-5c6a-4e20-bbff-3da11c6a9390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>523452a4-b881-4b7f-bdb5-caaa0517c284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/calendar-regular.svg</value>
      <webElementGuid>09db2407-2629-460c-a70e-a9d7301b9876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xalign</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>e64a9684-c9f1-463e-99a9-3c665f60d2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>$KW.Calendar.setCalElementStyle(this,false)</value>
      <webElementGuid>afaa75d5-ff2b-4221-aa17-f133e62760b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>4c67e05a-4869-4a08-95ce-7e0a8f8984db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DateFilter</value>
      <webElementGuid>839c4e00-bae5-4668-91e1-0b7d8b0a32d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3295bf95-14ce-4ce3-afa8-7b9f50c903ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDateFilterFrom_img&quot;)</value>
      <webElementGuid>f1b89a93-2e45-4197-8fec-68f26750a025</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='calendarDateFilterFrom_img']</value>
      <webElementGuid>802155ab-3c34-4844-b3b4-2828af799587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_DateFilter_calendarDateFilterFrom']/img</value>
      <webElementGuid>c15bc407-c520-4c63-b660-9b1f2e7aa454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Calendar']</value>
      <webElementGuid>b3db08fb-08bf-415c-997c-70ca7cb6b64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>7b9bb5e4-b452-458c-94ed-ba515f6becc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'calendarDateFilterFrom_img' and @type = 'image' and @src = 'desktopweb/images/calendar-regular.svg' and @alt = 'Calendar']</value>
      <webElementGuid>6a487e52-2adc-4b02-891e-362b49bfbdf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
