<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrjVisa</name>
   <tag></tag>
   <elementGuidId>534da28f-c4d7-48bc-92d3-74b2e9bf14ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxCardHomeRow_FlexGroup0c4de954607f848</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;flxCardHomeRow_FlexGroup0c4de954607f848&quot;)[count(. | //*[@id = 'flxCardHomeRow_FlexGroup0c4de954607f848' and @kcontainerid = 'segCards' and @kuid = '6D0367DE-A904-4DB8-9AB3-4C9EB585E3E3' and (text() = 'Visa Platinum0974' or . = 'Visa Platinum0974')]) = count(//*[@id = 'flxCardHomeRow_FlexGroup0c4de954607f848' and @kcontainerid = 'segCards' and @kuid = '6D0367DE-A904-4DB8-9AB3-4C9EB585E3E3' and (text() = 'Visa Platinum0974' or . = 'Visa Platinum0974')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxCardHomeRow_FlexGroup0c4de954607f848']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d9c41ae-b195-4532-954b-cbacf38c1fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>59119b01-f02b-4fbb-b5b0-185c1d6bd228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCardHomeRow_FlexGroup0c4de954607f848</value>
      <webElementGuid>912f6e1e-0e1f-48ca-bc39-cdd8a249dabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>38956f34-b0c3-4ea6-8bfc-c72ca2123cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCardHomeRow</value>
      <webElementGuid>7f07f39b-1f7e-4b58-93f4-291aaeb2282e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segCards</value>
      <webElementGuid>95e004fd-0b61-48a9-abf3-398b3c8eaf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>6D0367DE-A904-4DB8-9AB3-4C9EB585E3E3</value>
      <webElementGuid>3394b89f-2a5b-4649-a785-4aed50af78d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visa Platinum0974</value>
      <webElementGuid>e6c73a56-2248-4db6-a193-e18f6683497e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flxCardHomeRow_FlexGroup0c4de954607f848&quot;)</value>
      <webElementGuid>ba0cec9c-49ba-4fc0-b51b-dbabb385097a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxCardHomeRow_FlexGroup0c4de954607f848']</value>
      <webElementGuid>987b6a28-5d84-413a-bf99-c35bf75451b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[263]</value>
      <webElementGuid>0795786c-5f75-4215-a33a-9c45fe887d34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[2]/following::div[22]</value>
      <webElementGuid>78e80a58-4a8e-41f9-a79d-2d00041f347a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[24]</value>
      <webElementGuid>cb30ab4e-1d09-4528-934b-412dd1d4a1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrado'])[1]/preceding::div[6]</value>
      <webElementGuid>d420c4cc-18cc-4dcc-8481-624644a2fee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>e9dff197-a8de-4636-80e1-4e97216afef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCardHomeRow_FlexGroup0c4de954607f848' and (text() = 'Visa Platinum0974' or . = 'Visa Platinum0974')]</value>
      <webElementGuid>c9612ef9-d48e-40e3-b360-87bfddc18862</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
