<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblResumenes</name>
   <tag></tag>
   <elementGuidId>7fcb679a-1e82-4717-9b74-f929d876686c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2ac6a20-53b1-479c-bed0-66ee8a3765c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx3</value>
      <webElementGuid>49ccc86a-8734-4e15-ba94-d84bbc8a76ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>RichText</value>
      <webElementGuid>b02509de-05bc-4660-bb6d-35f33c174cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardDetails</value>
      <webElementGuid>ae67db90-536c-4c1a-914f-da69fa4314b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Tabs</value>
      <webElementGuid>71fa7381-8fb9-4172-b3a9-83be2d2810b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknRtxLatoReg1466 </value>
      <webElementGuid>4d66049e-414d-4d62-a23c-247795c10a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resúmenes</value>
      <webElementGuid>a2674ff1-5873-4fac-87fa-786d9350f90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx3&quot;)</value>
      <webElementGuid>d2429cac-2de3-499d-a1a3-68b724b764b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx3']</value>
      <webElementGuid>18314d04-415f-4d0c-b04c-bf9aaae69e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsFlx3']/div/div</value>
      <webElementGuid>c06d1c68-0405-44ac-b78d-97ded691189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendientes de Autorización'])[1]/following::div[5]</value>
      <webElementGuid>8fd9f70f-ddd6-4abf-94ed-18322b1350d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuotas Pendientes'])[1]/following::div[10]</value>
      <webElementGuid>afb1729c-37c6-437c-ae3b-c014ffc96eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consumos en Pesos'])[1]/preceding::div[11]</value>
      <webElementGuid>3e7d9c2e-bb4e-46ef-a6f0-f79e2f35580e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 10.823,33'])[1]/preceding::div[13]</value>
      <webElementGuid>0ea8f696-5bfc-46b0-91e2-3b6ce7b93981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resúmenes']/parent::*</value>
      <webElementGuid>18cf781b-71d6-4682-ae77-a65425995d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>38d1031c-24bd-41a9-9546-3012a61c7c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx3' and (text() = 'Resúmenes' or . = 'Resúmenes')]</value>
      <webElementGuid>d7a95630-6a74-458c-ad61-c5aa9788a278</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
