<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrjCuotasPendientesAutorizacn</name>
   <tag></tag>
   <elementGuidId>1832dead-3d31-46b7-95e2-bf839f253b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02ca6492-c227-4b17-8ca0-744d7d14dec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx2</value>
      <webElementGuid>03ccd969-ca87-439d-8af0-862b00ed8478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>RichText</value>
      <webElementGuid>876083e7-4731-457b-ba6b-bb6b436c16bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardDetails</value>
      <webElementGuid>8316e816-6f32-4a3f-badb-f03eba60067b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Tabs</value>
      <webElementGuid>235f1aaa-3e2d-4ec1-a6a1-accbfd16fb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknRtxLatoReg1466 </value>
      <webElementGuid>8c20759d-7369-4d9d-8095-a675c010f36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pendientes de Autorización</value>
      <webElementGuid>499f77e4-af97-4245-b3ac-a4863040eb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx2&quot;)</value>
      <webElementGuid>6be13fca-96b0-46c3-b611-e50f07c6d3d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx2']</value>
      <webElementGuid>035c517a-43c4-484b-86ef-21b5a43c5550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsFlx2']/div/div</value>
      <webElementGuid>a6e98510-f880-454b-b8ae-5c660c403068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuotas Pendientes'])[1]/following::div[5]</value>
      <webElementGuid>8d2b58f3-6bc3-415d-b15d-06050bfd13dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Últimos Movimientos'])[1]/following::div[10]</value>
      <webElementGuid>5e939e31-dc67-40d7-bce8-2d3bfab3cd6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resúmenes'])[1]/preceding::div[1]</value>
      <webElementGuid>76d39afe-d170-4b42-9619-2d7cd50a47fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consumos en Pesos'])[1]/preceding::div[16]</value>
      <webElementGuid>d64f8dff-a39b-42b8-83c9-f8ba74202bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pendientes de Autorización']/parent::*</value>
      <webElementGuid>48ae7065-e4b9-4129-a8d2-d24c258bc4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>e412dfaf-a3fe-454c-a246-a1b7b68ef068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx2' and (text() = 'Pendientes de Autorización' or . = 'Pendientes de Autorización')]</value>
      <webElementGuid>c6c1c0fc-65f6-45eb-9cbd-b967e6bc006f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
