<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrjDebitoDisponibleExtraccin</name>
   <tag></tag>
   <elementGuidId>034db902-0657-4697-81f5-aa7f37c613e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardsHome_DebitCards_lblHeaderTitleDisponibleExtraccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardsHome_DebitCards_lblHeaderTitleDisponibleExtraccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>996d1187-a3f1-4fa0-9ea7-b44b82d98bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardsHome_DebitCards_lblHeaderTitleDisponibleExtraccion</value>
      <webElementGuid>ed6bad5d-e081-45e1-a070-ee14387467ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9ea0eda4-ac4c-4ec0-8361-da9cd05dc994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardsHome</value>
      <webElementGuid>55669671-a8e9-49d6-a54e-9726e81247fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebitCards</value>
      <webElementGuid>e74cbf8b-0600-4b1a-a653-86363a45c078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTransactionTableHeader cntmiddlerightalign disableSelection</value>
      <webElementGuid>a7db4bd0-537b-4738-8c80-4a11c7d770ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disponible para extracción</value>
      <webElementGuid>04fa186c-2ea3-4b24-b820-738afa83995a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardsHome_DebitCards_lblHeaderTitleDisponibleExtraccion&quot;)</value>
      <webElementGuid>9345865c-d67e-4eb0-bcce-3b3b8bc7996b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_DebitCards_lblHeaderTitleDisponibleExtraccion']</value>
      <webElementGuid>86050cf9-9a90-4afa-9bb2-17e6e33e2df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_DebitCards_flxTableHeaderContainer']/div[4]/div</value>
      <webElementGuid>38011f27-031f-45f3-8875-f8d2560b3b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite de extracción'])[1]/following::div[2]</value>
      <webElementGuid>bde78716-0cc7-406b-baf4-53d526c078d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número'])[1]/following::div[4]</value>
      <webElementGuid>7cdc76b2-67f7-4723-b029-1738d7204f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite de compra'])[1]/preceding::div[1]</value>
      <webElementGuid>cc73892a-885a-4fa9-811a-41a69cbe7f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilitada para compra'])[1]/preceding::div[3]</value>
      <webElementGuid>81de211f-ad16-4826-94ee-b0ad62b0b0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disponible para extracción']/parent::*</value>
      <webElementGuid>73b5482c-a22d-40bb-8821-4c1df9d102c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[4]/div</value>
      <webElementGuid>4fa7ef20-0fa3-4059-b1c2-3b9a53fd8c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardsHome_DebitCards_lblHeaderTitleDisponibleExtraccion' and (text() = 'Disponible para extracción' or . = 'Disponible para extracción')]</value>
      <webElementGuid>08acf9fb-2273-4a9f-a41c-4d952495d7a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
