<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrjDebitoLimiteExtraccin</name>
   <tag></tag>
   <elementGuidId>7fd4b7fe-823c-4644-8173-75ad4a349ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardsHome_DebitCards_lblHeaderTitleLimiteExtraccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardsHome_DebitCards_lblHeaderTitleLimiteExtraccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c78b9d65-6fe9-419d-80be-1b19b41e696b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardsHome_DebitCards_lblHeaderTitleLimiteExtraccion</value>
      <webElementGuid>9d267d62-4d21-4c93-ab35-034b5eb557ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>35eae17e-3925-4b9c-baf8-2f9e81d2fbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardsHome</value>
      <webElementGuid>3b4a3078-d748-4b23-8cc3-dde285f6ee42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebitCards</value>
      <webElementGuid>25cb0e83-8269-4f7b-928e-28d1a98768da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTransactionTableHeader cntmiddlerightalign disableSelection</value>
      <webElementGuid>c9a50e44-c4f6-402b-b29a-8b9d2691b0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Límite de extracción</value>
      <webElementGuid>1443c899-47de-4270-9a4f-358031284f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardsHome_DebitCards_lblHeaderTitleLimiteExtraccion&quot;)</value>
      <webElementGuid>8e8de879-eb45-4a72-9f76-761faa2e297b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_DebitCards_lblHeaderTitleLimiteExtraccion']</value>
      <webElementGuid>f53e5bda-3de5-4dde-86d9-9d81708adff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_DebitCards_flxTableHeaderContainer']/div[3]/div</value>
      <webElementGuid>1ed836eb-7756-4f01-9a7d-0629878e03ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número'])[1]/following::div[2]</value>
      <webElementGuid>fd617100-e5ec-459a-8cfb-e51c4fb562c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjeta'])[1]/following::div[7]</value>
      <webElementGuid>8cb1267e-6d5f-4949-b41b-9285973b6dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disponible para extracción'])[1]/preceding::div[1]</value>
      <webElementGuid>ea144df4-ce98-4444-86fe-8686ed9b029b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite de compra'])[1]/preceding::div[3]</value>
      <webElementGuid>04e9286a-83ad-4a1f-9df3-360be2dbd23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Límite de extracción']/parent::*</value>
      <webElementGuid>36c4daa7-8e97-4580-9d32-f572090c3826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div[3]/div</value>
      <webElementGuid>6d342c42-7742-4c7d-9527-47cb67f3b681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardsHome_DebitCards_lblHeaderTitleLimiteExtraccion' and (text() = 'Límite de extracción' or . = 'Límite de extracción')]</value>
      <webElementGuid>b23670d6-63af-4158-bb30-c786831dab1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
