<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrjUltimosMovimientosVisa</name>
   <tag></tag>
   <elementGuidId>8fb44897-70b7-41db-9c03-a58de342c346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cab11c71-b50d-47c8-aa84-5d7f2af83caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx0</value>
      <webElementGuid>bee4f9de-3705-4ee1-8f47-c82cce8f867f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>RichText</value>
      <webElementGuid>84eaec4b-1742-4b35-9acd-47a4269537e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardDetails</value>
      <webElementGuid>cdcaf75c-533b-45a5-88f0-93eb34791575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Tabs</value>
      <webElementGuid>e98cb101-9388-4cb1-a922-6c174696e0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknRtxLatoBold1433 </value>
      <webElementGuid>7b6d6c06-de8a-42aa-9101-48ebda9d6c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Últimos Movimientos</value>
      <webElementGuid>70158873-a047-474d-ba6b-eacccab496f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx0&quot;)</value>
      <webElementGuid>4dc2fab0-ec6c-4733-b4b7-3a4e1842c11c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx0']</value>
      <webElementGuid>7c89dd78-6f6f-4bde-9817-0718b6561977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsFlx0']/div/div</value>
      <webElementGuid>64e0836b-4a9a-4951-b00a-5fcffbdc141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[4]/following::div[18]</value>
      <webElementGuid>a8d9d0a7-e62d-4064-845e-94a9c509b51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[3]/following::div[20]</value>
      <webElementGuid>89088c54-3fd4-4869-ad43-449798a77dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuotas Pendientes'])[1]/preceding::div[1]</value>
      <webElementGuid>6404652f-c99a-4324-9f74-0a6c2d313e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendientes de Autorización'])[1]/preceding::div[6]</value>
      <webElementGuid>b5d117b1-275c-4513-a02a-0b8555960d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Últimos Movimientos']/parent::*</value>
      <webElementGuid>fb83231e-c714-465b-9bf6-61660a254406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>065abac3-53c7-4be4-aeeb-bda686c02b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardDetails_Tabs_frmBcclCardDetailsTabsRtx0' and (text() = 'Últimos Movimientos' or . = 'Últimos Movimientos')]</value>
      <webElementGuid>3a444a79-baa2-4ea3-96b4-d09c60fd77d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
