<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrjTablaCuotasPendientesAutorizacn</name>
   <tag></tag>
   <elementGuidId>539c01c2-e558-4877-a805-2c78bc570e3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_flxResumenes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardDetails_flxResumenes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8df5104f-12f2-4e56-b9e6-aba6923fb658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>25be4e5d-4224-4184-a662-bb8fb230bc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_flxResumenes</value>
      <webElementGuid>ee7c4fe1-18ed-4b15-ae73-db37013dec5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>14865573-23c5-45a5-89fc-e53fd0b1b002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardDetails</value>
      <webElementGuid>7b57010e-4eee-4f34-94f9-2cb7d6e2e305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BuscarPeríodo-RichTextFecha de CierreFecha de VencimientoPago MínimoSaldo $Saldo U$DCierreVencimientoPago MínimoSaldo $Saldo U$DLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelResultados por página10102030501001001 - 10 de xLabel LabelLabelLabel</value>
      <webElementGuid>1db40387-5b03-4e1f-8f63-2f17f03772e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_flxResumenes&quot;)</value>
      <webElementGuid>4704966a-2fc5-4bfa-936b-5cb3cb60e070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_flxResumenes']</value>
      <webElementGuid>ae70e655-f448-4f6a-8f72-7613448f3250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[442]</value>
      <webElementGuid>2ee992f4-fca9-4319-9c9c-2b2bb819fb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESÚMENES'])[1]/following::div[3]</value>
      <webElementGuid>e24f6e12-25db-4c4d-afc1-975b949ee73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[8]</value>
      <webElementGuid>74cfd4d9-9a81-436d-a519-1dc90f1d4f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[5]/div/div</value>
      <webElementGuid>1f09927a-652a-44c1-bcca-9687ecd9efee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardDetails_flxResumenes' and (text() = 'BuscarPeríodo-RichTextFecha de CierreFecha de VencimientoPago MínimoSaldo $Saldo U$DCierreVencimientoPago MínimoSaldo $Saldo U$DLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelResultados por página10102030501001001 - 10 de xLabel LabelLabelLabel' or . = 'BuscarPeríodo-RichTextFecha de CierreFecha de VencimientoPago MínimoSaldo $Saldo U$DCierreVencimientoPago MínimoSaldo $Saldo U$DLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelResultados por página10102030501001001 - 10 de xLabel LabelLabelLabel')]</value>
      <webElementGuid>3e7f471b-540a-44fe-8c1b-9e2384bcf307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
