<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrjDebitoHabilitadaCompra</name>
   <tag></tag>
   <elementGuidId>1c250a86-6141-452d-8a18-afc37c7ebbde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardsHome_DebitCards_lblHabilitadaCompra</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardsHome_DebitCards_lblHabilitadaCompra']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d70780d3-c314-4f8b-9516-527dc1117f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardsHome_DebitCards_lblHabilitadaCompra</value>
      <webElementGuid>2a33125c-3b54-4481-865b-b09c3a7c6b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f6b350f2-6b64-4c6b-b847-61c36eda935d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardsHome</value>
      <webElementGuid>b8874023-2666-48f0-8339-47215a09b308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebitCards</value>
      <webElementGuid>f5020dd2-3534-4a11-b078-ff33d80a56ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTransactionTableHeader cntmiddlecenteralign disableSelection</value>
      <webElementGuid>f4b08a81-e06a-4804-b19f-a7c45ac24c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Habilitada para compra</value>
      <webElementGuid>decee0ca-f4aa-45df-84bf-9b7b6a8bf033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardsHome_DebitCards_lblHabilitadaCompra&quot;)</value>
      <webElementGuid>71d35dcc-ca97-49ed-9774-8dda4e404e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_DebitCards_lblHabilitadaCompra']</value>
      <webElementGuid>4e57d7e9-a264-4c6e-b8e4-c751948af186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_DebitCards_flxTableHeaderContainer']/div[6]/div</value>
      <webElementGuid>884b3a73-bef0-4743-86b0-8c7afff54112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite de compra'])[1]/following::div[2]</value>
      <webElementGuid>d04d4472-bcbf-430d-a372-2e47728d9502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disponible para extracción'])[1]/following::div[4]</value>
      <webElementGuid>6c71178d-7f57-4712-9046-ca83d69fc631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 40.000,00'])[1]/preceding::div[4]</value>
      <webElementGuid>9227cb31-4724-47f8-ae65-b229288825d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 40.000,00'])[2]/preceding::div[6]</value>
      <webElementGuid>40f8be69-998a-4cc2-9bfa-d4cc03f9cb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Habilitada para compra']/parent::*</value>
      <webElementGuid>170e75ec-9bd7-4567-aa46-feb2ce4dff68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[6]/div</value>
      <webElementGuid>38a81b6c-fb81-4baf-9451-659c24a5904e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardsHome_DebitCards_lblHabilitadaCompra' and (text() = 'Habilitada para compra' or . = 'Habilitada para compra')]</value>
      <webElementGuid>95360259-1a9e-4b33-9ab9-5f891d0c66f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
