<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radTrjListaCuentaPrincipal2</name>
   <tag></tag>
   <elementGuidId>7ff77779-1264-49d0-8192-f57fb36f9cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[3]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e73d7fe-6a44-4262-b1a5-85976782dd33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxSegDebitCardsPrimary_lblRadioAccount</value>
      <webElementGuid>624a6f5a-752b-49e0-baaf-ca38e0452f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>ceb02bf5-1f33-4ed9-83da-7a86d86e777f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxSegDebitCardsPrimary</value>
      <webElementGuid>0bd5924d-4680-427b-a6de-bc3ea1103fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segDebitCardsPrimary</value>
      <webElementGuid>885d9e49-3fd4-4d49-bee7-42db7e164de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>57CDF848-60BC-41BD-9DB0-4198C9E68AFC</value>
      <webElementGuid>6f719a58-1398-4a67-8dcb-e5561d1300e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblRadioSelectedDot cntmiddlecenteralign disableSelection</value>
      <webElementGuid>714ee9ef-9128-4681-b54d-d16d03eb6f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e93d9758-65ea-4f62-9db4-779c0835efc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardsHome_Panel_debitCardsPrimary_segDebitCardsPrimary&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_flxSegDebitCardsPrimary&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_flxContainerRbg&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_flxAccountLocal&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_flxLblRadioAccount&quot;]/div[@class=&quot;kcell middlecenteralignsknLblRadioSelectedDot&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_lblRadioAccount&quot;]</value>
      <webElementGuid>a1f90778-5b87-48a0-ae48-6106b41a8641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxSegDebitCardsPrimary_lblRadioAccount'])[3]</value>
      <webElementGuid>3062a282-cef1-44f2-a154-38111c59f1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxSegDebitCardsPrimary_flxLblRadioAccount']/div/div)[3]</value>
      <webElementGuid>0b2655eb-5274-409f-9f45-6252ade0636b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[6]/following::div[8]</value>
      <webElementGuid>e082877c-27a6-4b2b-9312-c9cd75001410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 004-009706/4'])[1]/following::div[19]</value>
      <webElementGuid>3569bf00-e1ce-4956-96f7-f92ad90c5ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SZIR MARIA ALEJANDRA'])[2]/preceding::div[1]</value>
      <webElementGuid>63c80300-db90-4d0b-a273-8baf4e696a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 001-065307/8'])[1]/preceding::div[3]</value>
      <webElementGuid>97e897ee-e583-45de-95fb-700cc3456d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>76db4fd0-37d7-4d3a-b62e-abd706ae99db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxSegDebitCardsPrimary_lblRadioAccount' and (text() = '' or . = '')]</value>
      <webElementGuid>ede95149-eef4-47ca-9246-824ab01034a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
