<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radTrjListaCuentaPrincipal</name>
   <tag></tag>
   <elementGuidId>68f7bd5a-5789-49f0-920b-18a0d679bf8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxSegDebitCardsPrimary_lblRadioAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae675a20-4112-42d4-805d-96dcb0b3963f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxSegDebitCardsPrimary_lblRadioAccount</value>
      <webElementGuid>6c0ae4b7-2688-4000-b1e0-bd42f5d5c86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>5cd20cf4-0ef7-42c5-8c2f-8ec4ec893c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxSegDebitCardsPrimary</value>
      <webElementGuid>f853908d-de66-4021-9f70-eade384ad730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segDebitCardsPrimary</value>
      <webElementGuid>c85c4f20-8911-4b5b-8d7a-01ab39be627b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>2CA97E44-CB71-4CB0-83C6-D04D102A0870</value>
      <webElementGuid>120099e6-f6fa-4ae9-ab6e-6b61e7295389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblRadioSelectedDot cntmiddlecenteralign disableSelection</value>
      <webElementGuid>5e4a59ee-158f-4384-bb9e-b064e7b835e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>af8886d3-afb2-488b-b936-a5913ed76f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardsHome_Panel_debitCardsPrimary_segDebitCardsPrimary&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_flxSegDebitCardsPrimary&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_flxContainerRbg&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_flxAccountLocal&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_flxLblRadioAccount&quot;]/div[@class=&quot;kcell middlecenteralignsknLblRadioSelectedDot&quot;]/div[@id=&quot;flxSegDebitCardsPrimary_lblRadioAccount&quot;]</value>
      <webElementGuid>d99b7e94-8a59-40e6-82db-e151fc975641</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxSegDebitCardsPrimary_lblRadioAccount']</value>
      <webElementGuid>933d7770-1cd7-473f-9b6e-3f1a04095beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxSegDebitCardsPrimary_flxLblRadioAccount']/div/div</value>
      <webElementGuid>6e5e0199-fbe2-44be-9de8-80d2a90a1caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[8]</value>
      <webElementGuid>224010ea-3d58-4336-a194-8161e18b5c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 001-065350/4'])[1]/following::div[19]</value>
      <webElementGuid>93ad84fb-96a2-4ab1-bdcf-1f7607819dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APELLIDO NOMBRE'])[1]/preceding::div[1]</value>
      <webElementGuid>1497dbba-185a-473e-b379-429318c68ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 003-014379/5'])[1]/preceding::div[3]</value>
      <webElementGuid>023acf05-251c-4afe-9e6a-8709cb22698b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>23ab6fe8-9fcb-4358-bcc1-09914801e44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxSegDebitCardsPrimary_lblRadioAccount' and (text() = '' or . = '')]</value>
      <webElementGuid>eb687f55-7730-4955-8757-d7c380e59fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
