<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCPNombre</name>
   <tag></tag>
   <elementGuidId>1d97b6dd-42e7-4b17-8202-c484fdc2e72c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxCuotasCard_lblCuotasTitular</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxCuotasCard_lblCuotasTitular']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ec948d7-04d7-42ff-af65-e7684adfa16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCuotasCard_lblCuotasTitular</value>
      <webElementGuid>bbf511a3-327a-4c32-bd3f-caf0c8623709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>12c6d9ab-b101-4ef5-813f-ea9391879485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCuotasCard</value>
      <webElementGuid>43df09ee-1c5b-475a-a04a-aac74369dc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segCuotasPendientes</value>
      <webElementGuid>ef3e13a5-71a7-4047-9175-1ec7f755bdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>53F9BD19-4D1E-45EE-BD1C-66828CC0D0F7</value>
      <webElementGuid>36fe8344-f8be-43f1-90b2-812475c03fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCuotasDate cnttopleftalign disableSelection</value>
      <webElementGuid>8872137c-7801-4d3b-a2ea-2d4aa8d2dc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>— (0974)</value>
      <webElementGuid>9c42278e-5e4a-43ea-a57a-fed5ed692666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_CuotasPendientesTarjetasDeCredito_segCuotasPendientes&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCuotasCard_flxCuotasCard&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableCuotasDate&quot;]/div[@id=&quot;flxCuotasCard_lblCuotasTitular&quot;]</value>
      <webElementGuid>8093017e-813b-4a9d-b276-ee4e8c83e119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxCuotasCard_lblCuotasTitular']</value>
      <webElementGuid>1774f09e-b90c-40d1-9711-2e1b95aba57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxCuotasCard_flxCuotasCard']/div[3]/div</value>
      <webElementGuid>e0cb4ad3-fa45-40c2-af70-c35d6968b4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAYNAR1 SA'])[1]/following::div[2]</value>
      <webElementGuid>acdbab84-852a-4643-b93e-d71c87e282eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo Pendiente'])[1]/following::div[13]</value>
      <webElementGuid>c8fb8c9a-9ae7-46f3-a115-71570b3321fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/preceding::div[8]</value>
      <webElementGuid>1c4c2686-5ce4-45f6-8bec-af5424d891e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAYNAR2 SA'])[1]/preceding::div[20]</value>
      <webElementGuid>773223e9-cd9f-4ff0-9be2-9237d6b69978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='— (0974)']/parent::*</value>
      <webElementGuid>5b723c63-114e-48b6-979c-20c0c57a2f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/div/div/div[3]/div</value>
      <webElementGuid>ae7c894a-fe54-45b4-a040-1ac7728fefed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCuotasCard_lblCuotasTitular' and (text() = '— (0974)' or . = '— (0974)')]</value>
      <webElementGuid>5e96e45e-6740-4670-9371-9e9bc21cac82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
