<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDiaCalendario</name>
   <tag></tag>
   <elementGuidId>04efb9ff-fc72-4159-a137-71ae48bdddbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-kony-w-c-cell-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-kony-w-c-cell-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>645d043a-24c1-492a-b9a9-80d48f74e386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>81096024-81a0-4637-a72d-fe0e704bfdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DateFilter</value>
      <webElementGuid>63a49ae2-f0b7-423c-aa30-c41667846c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-k-w-c-weekday-1 -kony-w-c-day- sknCalendar</value>
      <webElementGuid>70253fe7-8803-4bfc-926d-aa87acfddfb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-kony-w-c-cell-9</value>
      <webElementGuid>1c56dd1a-612e-44f1-aa93-042f927c288f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Previous month</value>
      <webElementGuid>3de564ee-1021-4037-b387-c776ca9b6cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>1e43d28b-0576-49b5-82ab-277d8338cbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value> 2nd March 2020</value>
      <webElementGuid>0d57e753-7ec3-4ed2-a856-fde905e51ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0bb22b2-6abc-4ddb-bd29-3309fb5a3c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-date-retrieve</name>
      <type>Main</type>
      <value>2,3,2020</value>
      <webElementGuid>7e710670-bd91-4ae3-ace7-f91fc28f6245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>69a6c4b4-2cc0-4449-9922-d86aa760352d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>eb54c75c-c1f5-4dfa-949d-08f7a93c942a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weekday</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c7e4a1eb-da47-4f9f-ab1c-ec1f7dcc671f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-hold-day</name>
      <type>Main</type>
      <value>2,3,2020</value>
      <webElementGuid>12decedc-f7c0-47db-b8cd-659f092417e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cba22877-ecc7-4bf5-9fe1-70d863b3f8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-kony-w-c-cell-9&quot;)</value>
      <webElementGuid>7124aa3a-ae09-4c92-9207-5c9f22887c5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='-kony-w-c-cell-9']</value>
      <webElementGuid>c5401b08-23de-4184-81ce-198f31b44469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-3-2020']/div[2]/div/div/div[2]</value>
      <webElementGuid>a45ec99f-e316-4eca-b23e-320373b5506a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sáb'])[1]/following::div[5]</value>
      <webElementGuid>7e8f8a97-3397-4f60-ab59-7b00289964f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vie'])[1]/following::div[6]</value>
      <webElementGuid>dfb06cd5-6635-4be4-931f-48db089b6f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[53]</value>
      <webElementGuid>65798c9a-64cb-4545-a4c1-f61c8b915411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[55]</value>
      <webElementGuid>b2c18d75-223d-4c05-83a7-6eba1d3f87d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>81b1ace0-2beb-4105-ae41-bdbd542e8526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>66c4ef7b-f1ff-445c-acb6-dd1dc2ff2786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '-kony-w-c-cell-9' and @title = 'Previous month' and (text() = '2' or . = '2')]</value>
      <webElementGuid>b4a9b30d-6332-4fff-b30e-a2227cc76726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
