<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtFechaCierreValorRes</name>
   <tag></tag>
   <elementGuidId>a5e82764-b9c0-4861-9058-e3f0b31bf299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxCardsResumenes_lblCierre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxCardsResumenes_lblCierre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdb50cc5-0727-4876-a1da-a6b979eb7d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCardsResumenes_lblCierre</value>
      <webElementGuid>8d60e311-347b-4867-a30a-e6be18e33709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>a98e25cd-d4d7-45d0-8ce3-43bf9f12b6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCardsResumenes</value>
      <webElementGuid>ee5976a9-1110-4bd5-9a6c-4478819a529f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>sgmResumenes</value>
      <webElementGuid>782c5495-4a67-448a-afcd-630961ad5403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>E0787AC9-B1C5-470F-B154-C6EEA564CA10</value>
      <webElementGuid>206a34d2-ae9f-4424-b0bb-1058ef3714be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableCellPositivePrimary cntmiddleleftalign disableSelection</value>
      <webElementGuid>99a9768e-ff31-4b2c-bda5-f746d75366a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26 Nov 2020</value>
      <webElementGuid>f709cb83-d956-4347-81c1-6f393fe17c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_sgmResumenes&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardsResumenes_flxCardsResumenes&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardsResumenes_flxCierre&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTableCellPositivePrimary&quot;]/div[@id=&quot;flxCardsResumenes_lblCierre&quot;]</value>
      <webElementGuid>8f4ec16d-869e-4b5d-8a80-1f9373871650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxCardsResumenes_lblCierre']</value>
      <webElementGuid>c116bfa1-91a8-4ab6-bde6-f0444ab3166f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxCardsResumenes_flxCierre']/div/div</value>
      <webElementGuid>6eab2de2-bf84-40c8-a2cb-01f77fce7418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo U$D'])[2]/following::div[12]</value>
      <webElementGuid>b6b5fc23-35ed-4029-89a3-624c8b6bf7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo $'])[2]/following::div[14]</value>
      <webElementGuid>1695b04d-9f28-4781-9753-4cf92e799e2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[19]</value>
      <webElementGuid>199e68cd-6c62-4a9d-aece-43ab6ac742ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[24]</value>
      <webElementGuid>c5519978-9ca6-42ae-95c6-03d2efb934b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26 Nov 2020']/parent::*</value>
      <webElementGuid>a58164f2-c3b7-4c25-aacc-a04f2628e9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/ul/li/div/div/div/div/div/div/div</value>
      <webElementGuid>4325ccf2-7ccc-442b-ab12-13308a9f14d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCardsResumenes_lblCierre' and (text() = '26 Nov 2020' or . = '26 Nov 2020')]</value>
      <webElementGuid>a7f91c60-a9b2-4c8d-9c8b-4ba2a8d717cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
