<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtFechaCP</name>
   <tag></tag>
   <elementGuidId>054e9d4f-dece-484c-b445-7d46e488ec82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_flxResumenes</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmBcclCardDetails_flxResumenes&quot;)[count(. | //*[@id = 'frmBcclCardDetails_flxResumenes' and (text() = 'Fecha' or . = 'Fecha')]) = count(//*[@id = 'frmBcclCardDetails_flxResumenes' and (text() = 'Fecha' or . = 'Fecha')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardDetails_flxResumenes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>21126159-5399-4393-98a0-f3f656b994d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox </value>
      <webElementGuid>7c567abd-ab08-4a56-a224-b07310247259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_flxResumenes</value>
      <webElementGuid>67ac6ff6-6d9f-48cc-ace4-9d2f404f92a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>908330fb-7424-451e-b259-bb2d49d53690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardDetails</value>
      <webElementGuid>0b35d7d7-0f15-4479-b2c4-52e907b469e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha</value>
      <webElementGuid>dafde7e0-e925-4763-98cd-58aeec7270e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_flxResumenes&quot;)</value>
      <webElementGuid>a37f1649-df13-4cf6-9f54-bccf520d8c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_flxResumenes']</value>
      <webElementGuid>ca6b7b56-f05e-4c55-8e6d-e7d28a891bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[372]</value>
      <webElementGuid>171e64f4-d447-4626-81de-f3b23b5cc79d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESÚMENES'])[1]/following::div[3]</value>
      <webElementGuid>76a62f16-e586-496f-83a4-f37a557a983c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[8]</value>
      <webElementGuid>7ab71074-8a06-43e7-a5f0-6278d048aa58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[5]/div/div</value>
      <webElementGuid>9f20768f-f209-4c31-955d-cc00569f8d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardDetails_flxResumenes' and (text() = 'BuscarPeríodo-RichTextFecha de CierreFecha de VencimientoPago MínimoSaldo $Saldo U$DCierreVencimientoPago MínimoSaldo $Saldo U$DLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelResultados por página10102030501001001 - 10 de xLabel LabelLabelLabel' or . = 'BuscarPeríodo-RichTextFecha de CierreFecha de VencimientoPago MínimoSaldo $Saldo U$DCierreVencimientoPago MínimoSaldo $Saldo U$DLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelResultados por página10102030501001001 - 10 de xLabel LabelLabelLabel')]</value>
      <webElementGuid>76ac0ab9-d815-4422-88c8-5f7f4d1671a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
