<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNumeroVisaTarjeta</name>
   <tag></tag>
   <elementGuidId>1f76b7d1-c0b6-4c4d-a789-6ca477d264bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_ConsolidatedPosition_lblCardNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardDetails_ConsolidatedPosition_lblCardNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3022cc3b-e5b6-4a8e-81d8-3d50071308ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_ConsolidatedPosition_lblCardNumber</value>
      <webElementGuid>5c865b89-7c80-46a9-9c75-48e173442f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>6a0385c0-60a3-47e5-a513-cddc2d1b5070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardDetails</value>
      <webElementGuid>a5cd6a75-aa6d-40d3-bff1-9660a10469e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConsolidatedPosition</value>
      <webElementGuid>2ed857ee-45a1-4c4a-9d76-257aff099413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblMaskedCardNumber cntbottomleftalign disableSelection</value>
      <webElementGuid>19ac2c80-0dd5-4a0c-a81e-372a7bb8d20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>**** **** **** 0974</value>
      <webElementGuid>646a4fe0-6934-4142-b51b-2f157754c84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_ConsolidatedPosition_lblCardNumber&quot;)</value>
      <webElementGuid>e10cef48-6210-489b-b002-d5f1ab47531c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_ConsolidatedPosition_lblCardNumber']</value>
      <webElementGuid>b106ece5-d937-4088-833e-811ab1348e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_ConsolidatedPosition_flxCardNumber']/div[2]/div</value>
      <webElementGuid>f2e6d978-8819-42ea-b4ee-ed4465ce00ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de tarjeta'])[1]/following::div[2]</value>
      <webElementGuid>9d741c42-1f13-449f-b21c-4e6231783734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[39]</value>
      <webElementGuid>fb388cbd-bcc5-4921-914b-8b77e2c18826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de Cuenta Visa Platinum'])[1]/preceding::div[1]</value>
      <webElementGuid>e6651d48-50ad-4546-a9e9-c8bd7957d234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disponible Pesos'])[1]/preceding::div[8]</value>
      <webElementGuid>61dd7fb1-6c37-4c9f-b869-f27c618ba119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='**** **** **** 0974']/parent::*</value>
      <webElementGuid>de6abc2b-82d0-4d17-bc8e-41844b99a2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>0d442f1c-e2a0-4013-9654-aee468358b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardDetails_ConsolidatedPosition_lblCardNumber' and (text() = '**** **** **** 0974' or . = '**** **** **** 0974')]</value>
      <webElementGuid>4cc8fe0d-dd46-4413-bcf1-db01cf45796f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
