<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjMontoValorDolarMov</name>
   <tag></tag>
   <elementGuidId>e3bff36c-ba3d-4237-a28d-d1129a2dd912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxCardLastMovementsRow_lblMontoUSD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxCardLastMovementsRow_lblMontoUSD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c81202d6-d388-49bb-94a5-971e36fb86bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCardLastMovementsRow_lblMontoUSD</value>
      <webElementGuid>7f704f07-5f96-4e0e-af08-47fb74d63429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>29617ea6-c587-49bd-86a6-d5fda1596bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCardLastMovementsRow</value>
      <webElementGuid>f1971b58-40e6-4378-b02e-86209cc71d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segUltimosMovimientos</value>
      <webElementGuid>c988d8b6-98dc-4667-a437-7220d43368b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>4892C5ED-5823-41C1-8BCE-73F2FE399481</value>
      <webElementGuid>65d417bb-9a11-4f20-8553-9be3ccb6e4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoReg1466 cntmiddlerightalign disableSelection</value>
      <webElementGuid>5f939b07-8f13-423f-9cf4-a02072dba43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>55,90</value>
      <webElementGuid>13cf26bc-74cc-4be9-97d9-1f91fe30b327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_segUltimosMovimientos&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardLastMovementsRow_flxCardLastMovementsRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardLastMovementsRow_flxLblMontoUSD&quot;]/div[@class=&quot;kcell middlecenteralignsknLblLatoReg1466&quot;]/div[@id=&quot;flxCardLastMovementsRow_lblMontoUSD&quot;]</value>
      <webElementGuid>8c82f48b-d5fa-4d65-80c3-6dfd9f135e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxCardLastMovementsRow_lblMontoUSD']</value>
      <webElementGuid>391de637-2519-4c8e-9eba-85bd237a44f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxCardLastMovementsRow_flxLblMontoUSD']/div/div</value>
      <webElementGuid>3a68efa8-ff12-4063-a363-e2e0228f5de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony - Playstation store -'])[2]/following::div[10]</value>
      <webElementGuid>7ecd2bdc-dd70-42cb-a244-04e2cafbd610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony - Playstation store -'])[1]/following::div[15]</value>
      <webElementGuid>ba964eac-a791-44af-b77f-525f0b368cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultados por página'])[1]/preceding::div[1]</value>
      <webElementGuid>097420ea-8451-4804-ba0d-fa6365784ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/preceding::div[5]</value>
      <webElementGuid>ebfc0d0d-71a9-4e6d-a116-43b3e64ba169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='55,90']/parent::*</value>
      <webElementGuid>3b627a90-8657-426d-a127-b52f7dbd2308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[5]/div/div/div/div</value>
      <webElementGuid>5e47a9ae-5b3b-48fa-b45b-f01ef7117024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCardLastMovementsRow_lblMontoUSD' and (text() = '55,90' or . = '55,90')]</value>
      <webElementGuid>4625c210-d98f-4c1b-8b95-5db4ab1e79cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
