<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjCuotasPendAutorizacnNombreTarjeta</name>
   <tag></tag>
   <elementGuidId>643da21d-91e7-405d-92b4-48da279ef1ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_segPendientesAutorizacion > ul > li.seg2Normal > #flexcontainer_wrapper > #flxCardLastMovementsRow_flxCardLastMovementsRow > div.kcell.middlecenteralign > #flexcontainer_wrapper > #flxCardLastMovementsRow_flxLblNombre > div.kcell.middlecenteralignsknLblLatoReg1466 > #flxCardLastMovementsRow_lblNombre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxCardLastMovementsRow_lblNombre'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e9fbad0-36a0-4ca5-9c4f-fba9bd22b323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCardLastMovementsRow_lblNombre</value>
      <webElementGuid>38c2d87b-e6aa-4815-89af-2c75e8efe267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>20597f59-c056-4f7c-adff-381e94a3e292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCardLastMovementsRow</value>
      <webElementGuid>0f4fd45f-8db0-498d-a56e-3d02c20292af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segPendientesAutorizacion</value>
      <webElementGuid>ed564357-c61d-48d7-8d78-7d26f9bf30df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>AC796F35-E65D-4D26-994F-7CB222E31C3B</value>
      <webElementGuid>1c480d73-f9c9-4e18-85e1-b6c73b0a5193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoReg1466 cntmiddleleftalign disableSelection</value>
      <webElementGuid>731ce4c6-b225-4eaf-84c1-131139258ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sony - Playstation store - </value>
      <webElementGuid>28ce9ab2-bbe2-47b7-a68d-54e4a75d985c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_segPendientesAutorizacion&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardLastMovementsRow_flxCardLastMovementsRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardLastMovementsRow_flxLblNombre&quot;]/div[@class=&quot;kcell middlecenteralignsknLblLatoReg1466&quot;]/div[@id=&quot;flxCardLastMovementsRow_lblNombre&quot;]</value>
      <webElementGuid>f6e760fc-d8bd-4e71-891d-e0847941bf87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxCardLastMovementsRow_lblNombre'])[2]</value>
      <webElementGuid>f6267386-073b-47bb-a7d3-429424cc8465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxCardLastMovementsRow_flxLblNombre']/div/div)[2]</value>
      <webElementGuid>bc21779a-d8ba-4543-9e0d-1b30d08ce977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony - Playstation store -'])[3]/following::div[5]</value>
      <webElementGuid>4de46879-4798-46cc-a57e-8f0e5c194409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto U$S'])[2]/following::div[19]</value>
      <webElementGuid>4bcc2c23-15d9-4fdf-917c-c89b3c14c63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultados por página'])[3]/preceding::div[11]</value>
      <webElementGuid>2ccb3742-f926-41a7-bd05-6df4f637f472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[6]/preceding::div[15]</value>
      <webElementGuid>561cc6ee-0785-48de-af13-c7e9c74e20ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>11457413-6794-403f-ac7c-982163373ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCardLastMovementsRow_lblNombre' and (text() = 'Sony - Playstation store - ' or . = 'Sony - Playstation store - ')]</value>
      <webElementGuid>bd1bc727-d35f-43df-a0f2-909316fbd7ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
