<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjSinTarjetasDebito</name>
   <tag></tag>
   <elementGuidId>1302661b-076a-410b-8f9e-e0ae4acba1c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardsHome_DebitCards_NoResults_lblNoResultsTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardsHome_DebitCards_NoResults_lblNoResultsTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b918c1f6-5d24-4a97-a9fe-1fcea66cd6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardsHome_DebitCards_NoResults_lblNoResultsTitle</value>
      <webElementGuid>18665762-a4ef-42a6-91ac-1e6eb7d12f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e2506eda-114e-4a00-b306-7538f3618437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardsHome</value>
      <webElementGuid>e9e4e655-9795-4d8f-b1bc-a9d02957e196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebitCards_NoResults</value>
      <webElementGuid>838ccace-8dc8-4f74-b4cd-370438753437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblNotificationMessageEmptyTable cntmiddleleftalign disableSelection</value>
      <webElementGuid>81b05c87-bf90-4130-b0cf-bad5a54b8822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No tenés tarjetas de Débito.</value>
      <webElementGuid>ee193483-bfbc-4458-a8a0-70dba2a1bc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardsHome_DebitCards_NoResults_lblNoResultsTitle&quot;)</value>
      <webElementGuid>0f772811-340c-4fb3-8d59-57cd30fdc4d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_DebitCards_NoResults_lblNoResultsTitle']</value>
      <webElementGuid>16e35d07-4929-4c15-ad43-437942f53043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_DebitCards_NoResults_flxMessageContainer']/div/div</value>
      <webElementGuid>2e786905-8370-4efb-adad-c8f8ae6b974a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[37]/following::div[16]</value>
      <webElementGuid>b908b276-4365-4c1c-a988-ff16892896a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[36]/following::div[18]</value>
      <webElementGuid>176b58c4-1b96-4033-bff0-03d460c25e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarjetas Precargadas'])[1]/preceding::div[3]</value>
      <webElementGuid>419c1271-f075-4451-9b30-8a9c3acbcb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[8]</value>
      <webElementGuid>276b03ff-0e5e-48d4-affc-dc7853616dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No tenés tarjetas de Débito.']/parent::*</value>
      <webElementGuid>45b9fa60-9ac4-4f83-b849-36a16e3a9789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div[3]/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>c876da50-94f9-4d36-a9cf-513b69da9b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardsHome_DebitCards_NoResults_lblNoResultsTitle' and (text() = 'No tenés tarjetas de Débito.' or . = 'No tenés tarjetas de Débito.')]</value>
      <webElementGuid>2cc43cac-d75e-4333-bfc5-1971e1209a5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
