<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjCuotasPendientesCP</name>
   <tag></tag>
   <elementGuidId>5c19707c-5d85-4c5e-aa7d-9fa0583d5133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardDetails_flxResumenes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_flxResumenes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c1723858-441c-43e1-a5b7-faa635c13d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  slFbox</value>
      <webElementGuid>2b379c8a-afb5-4052-95e6-67711392549e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_flxResumenes</value>
      <webElementGuid>e8f4aac9-3f3a-44ef-ba9b-413b24ae5f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>c636e27b-133d-477b-8759-6ef05fe8b98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardDetails</value>
      <webElementGuid>47c5b0f6-2d31-463a-8b8e-e9e52a89e469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BuscarPeríodo-RichTextFecha de CierreFecha de VencimientoPago MínimoSaldo $Saldo U$DCierreVencimientoPago MínimoSaldo $Saldo U$DLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelResultados por página10102030501001001 - 10 de xLabel LabelLabelLabel</value>
      <webElementGuid>a36ae435-595c-497d-ab06-de412fb85234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_flxResumenes&quot;)</value>
      <webElementGuid>1387ac7d-61ec-432b-8780-b37159e15152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardDetails_flxResumenes']</value>
      <webElementGuid>7981988c-d2b0-42e7-bb97-5abc8e4dbb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[372]</value>
      <webElementGuid>0f72679b-bd1f-4457-bc34-cd0ed14ec156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESÚMENES'])[1]/following::div[3]</value>
      <webElementGuid>58ab7941-b1e4-4072-a889-a973e97461bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[8]</value>
      <webElementGuid>b69fff92-1e29-4ec9-bb16-1505ffed048d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[5]/div/div</value>
      <webElementGuid>720e932d-3b7d-46d3-9c8d-679e3ac4a739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardDetails_flxResumenes' and (text() = 'BuscarPeríodo-RichTextFecha de CierreFecha de VencimientoPago MínimoSaldo $Saldo U$DCierreVencimientoPago MínimoSaldo $Saldo U$DLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelResultados por página10102030501001001 - 10 de xLabel LabelLabelLabel' or . = 'BuscarPeríodo-RichTextFecha de CierreFecha de VencimientoPago MínimoSaldo $Saldo U$DCierreVencimientoPago MínimoSaldo $Saldo U$DLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelLabelResultados por página10102030501001001 - 10 de xLabel LabelLabelLabel')]</value>
      <webElementGuid>d3052b8a-d42a-4cd4-9082-16bacd54096e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
