<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjFechaVencValorRes</name>
   <tag></tag>
   <elementGuidId>dd32ee97-a7a3-49f8-b9a3-1240c264622e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxCardsResumenes_lblVencimiento']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxCardsResumenes_lblVencimiento</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>069f23b3-67c9-4630-87f1-de7dffe3f615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCardsResumenes_lblVencimiento</value>
      <webElementGuid>0b8b7cad-0a85-40a1-af8c-cc842eaa24f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>3ad8c913-4f5d-4307-b9c4-a35cf1c27b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCardsResumenes</value>
      <webElementGuid>2b986c90-a0ae-4c8a-9563-11414fbd9353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>sgmResumenes</value>
      <webElementGuid>afe4437d-6245-4f78-9bc1-9e774a70a2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>AB286AF5-D104-4D0F-B898-9DD0FDAFEA80</value>
      <webElementGuid>f269c3d6-c442-477f-b133-a598d48b4734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTableCellPositivePrimary cntmiddleleftalign disableSelection</value>
      <webElementGuid>fb996f46-e5e0-4384-8e2b-f094a065c2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>09 Dic 2020</value>
      <webElementGuid>24dabe93-0939-4378-ab58-4ae784d7da23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_sgmResumenes&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardsResumenes_flxCardsResumenes&quot;]/div[@class=&quot;kcell middlecenteralignslFbox&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardsResumenes_flxVencimiento&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTableCellPositivePrimary&quot;]/div[@id=&quot;flxCardsResumenes_lblVencimiento&quot;]</value>
      <webElementGuid>45a26e0a-919d-4354-8929-740ebe1e59eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxCardsResumenes_lblVencimiento']</value>
      <webElementGuid>5e7e5a34-e0c8-4a0b-a7ab-fd08b053441c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxCardsResumenes_flxVencimiento']/div/div</value>
      <webElementGuid>e81abc8f-7c6f-4433-ad67-69cc3efb1bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo U$D'])[2]/following::div[17]</value>
      <webElementGuid>e8254cfa-9ae4-49bb-8fe8-7a1060705230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo $'])[2]/following::div[19]</value>
      <webElementGuid>0430cbb5-6c89-46a0-b702-093175ec213d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[14]</value>
      <webElementGuid>50af67c2-00c3-4330-99fb-a7bec0a729c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[19]</value>
      <webElementGuid>29d2a3ba-695d-4fde-8ddb-40881353e484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='09 Dic 2020']/parent::*</value>
      <webElementGuid>654609f9-db86-4f07-9120-3136a86da7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/ul/li/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>9ca90980-bbb5-43a5-b85f-6c4583fa8895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCardsResumenes_lblVencimiento' and (text() = '09 Dic 2020' or . = '09 Dic 2020')]</value>
      <webElementGuid>2d94289d-cf09-42e3-b16f-84c987484792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
