<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjMes</name>
   <tag></tag>
   <elementGuidId>0ecf98f9-5a9b-4469-ad3c-2d0b0d180e63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-k-w-c-month-cmp-02-2023']/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.-kony-w-c-cell.-kony-w-c-yemo.-kony-w-c-yemo-skin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e9f4402a-5bbb-4e8f-8fa4-91e69430c385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>0ec02dc3-ddea-410e-a82f-0e272a9e7569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DateFilter</value>
      <webElementGuid>9be0adf8-b9a7-4ca3-acb4-6d31987bec7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>6eaf5f55-4c25-484f-b0d6-c8f6fd135e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-w-c-cell -kony-w-c-yemo  -kony-w-c-yemo-skin</value>
      <webElementGuid>2cc3e2e5-2521-43f4-a996-f4815b5db518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c661dc6f-9a45-434d-9d0d-a67d1c76b4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmBcclCardDetails_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>d1ace469-8751-4cdc-ade8-18ce371aed49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Febrero, 2023</value>
      <webElementGuid>59623a53-7287-4fcc-9d82-61a063d81208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-k-w-c-month-cmp-02-2023&quot;)/div[@class=&quot;-kony-w-c-topSection&quot;]/div[@class=&quot;-kony-w-c-table&quot;]/div[@class=&quot;-kony-w-c-row&quot;]/div[@class=&quot;-kony-w-c-cell -kony-w-c-yemo  -kony-w-c-yemo-skin&quot;]</value>
      <webElementGuid>89588616-cc32-4c0c-bdd4-13a65b4390b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-02-2023']/div/div/div/div[2]</value>
      <webElementGuid>64f6643c-8a48-4581-8ce4-ff46f32380fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[15]</value>
      <webElementGuid>5ccf7ee1-0d63-4eb0-9cd1-a810c022cbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar'])[1]/following::div[17]</value>
      <webElementGuid>72cb18c4-7923-4a6e-b2a0-686603628449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dom'])[1]/preceding::div[2]</value>
      <webElementGuid>1d825ea1-9559-4542-910f-986fb570e806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lun'])[1]/preceding::div[3]</value>
      <webElementGuid>24953b09-6cc2-4ec6-a1ad-99a6aeac13e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Febrero, 2023']/parent::*</value>
      <webElementGuid>0e9814c1-fa93-4949-bda4-4b360675a26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]</value>
      <webElementGuid>69de3b99-c812-4ca3-875f-bcfe2c9b8022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Febrero, 2023' or . = 'Febrero, 2023')]</value>
      <webElementGuid>c2a0519f-96a0-4838-95fd-f38d927b2e9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
