<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjCuotasPendAutorizacnMontoPesos</name>
   <tag></tag>
   <elementGuidId>ea158666-9009-4b65-834f-aee0d4a330f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardDetails_segPendientesAutorizacion > ul > li.seg2Normal > #flexcontainer_wrapper > #flxCardLastMovementsRow_flxCardLastMovementsRow > div.kcell.middlecenteralign > #flexcontainer_wrapper > #flxCardLastMovementsRow_flxlblMontoARS > div.kcell.middlecenteralignsknLblLatoReg1466 > #flxCardLastMovementsRow_lblMontoARS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxCardLastMovementsRow_lblMontoARS'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>261fa40c-93bb-400b-9aba-2c5f3d67eb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCardLastMovementsRow_lblMontoARS</value>
      <webElementGuid>59c48b64-a90f-45ee-9a89-a0c8af0213c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>2b006af3-0823-4bf1-8f3a-bfc6c6d64237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCardLastMovementsRow</value>
      <webElementGuid>35e541fa-1176-4014-8c60-8c184b3b9491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segPendientesAutorizacion</value>
      <webElementGuid>51cc0b15-e0b3-4661-aeab-8293a2aae23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>2E80AA6A-94C6-4C4D-83EB-45381653FE44</value>
      <webElementGuid>6b648860-9697-4c79-9773-c4b1d1eed67e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoReg1466 cntmiddlerightalign disableSelection</value>
      <webElementGuid>cf184f56-49c8-40bb-925b-872c292e46c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22.000,00</value>
      <webElementGuid>fc7262b2-04f6-4c39-98ef-7748fbeb5aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardDetails_segPendientesAutorizacion&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardLastMovementsRow_flxCardLastMovementsRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxCardLastMovementsRow_flxlblMontoARS&quot;]/div[@class=&quot;kcell middlecenteralignsknLblLatoReg1466&quot;]/div[@id=&quot;flxCardLastMovementsRow_lblMontoARS&quot;]</value>
      <webElementGuid>39f80845-4611-49a6-b3d4-7c8e1dea1e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxCardLastMovementsRow_lblMontoARS'])[2]</value>
      <webElementGuid>711d683f-52d8-4d99-b3bf-fa18e144a976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxCardLastMovementsRow_flxlblMontoARS']/div/div)[2]</value>
      <webElementGuid>49828718-f524-4cba-80dc-018f56f1827d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony - Playstation store -'])[4]/following::div[5]</value>
      <webElementGuid>f99989fb-3011-4b84-862f-a04ed2451a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony - Playstation store -'])[3]/following::div[10]</value>
      <webElementGuid>5a0ea242-60ce-471e-9c51-dda0e185796f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resultados por página'])[3]/preceding::div[6]</value>
      <webElementGuid>933b2ac4-b903-4c2f-994f-c645227f82d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[6]/preceding::div[10]</value>
      <webElementGuid>f998b9cf-4582-4e6b-8a12-0e17a796f1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/div/ul/li/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>3bcec600-240b-4cb3-903e-5ffcf9615e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCardLastMovementsRow_lblMontoARS' and (text() = '22.000,00' or . = '22.000,00')]</value>
      <webElementGuid>6adeffe3-94f4-4ef8-8f2b-69fd38a74697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
