<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjDebitoDisponibleExtraccn</name>
   <tag></tag>
   <elementGuidId>0f79d397-d7d0-43a4-9584-d4e5370dbc67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxCardDebitRow_lblDisponibleExtraccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxCardDebitRow_lblDisponibleExtraccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ec478f3-a3d6-4553-b1c0-b422a05acef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxCardDebitRow_lblDisponibleExtraccion</value>
      <webElementGuid>bc1d8a19-7ffd-4844-a227-5c90e2ba8a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>38185647-81dc-48b1-8b75-6df654dcabc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxCardDebitRow</value>
      <webElementGuid>1099a080-4fcb-4af2-92a0-3d59496d7d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segDebitCards</value>
      <webElementGuid>a1043d7c-6ce1-47c9-84bc-cf36ff50f745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>5289947B-33FB-469D-B435-6E23036CCC05</value>
      <webElementGuid>93204bde-e8b9-4d00-a6f6-98546780f0b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCardRow cntmiddlerightalign disableSelection</value>
      <webElementGuid>28c9dc1e-ddec-4d90-9b67-7e27d8660a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 40.000,00</value>
      <webElementGuid>737f58cb-c137-4a05-aed5-19f0fa668594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flxCardDebitRow_lblDisponibleExtraccion&quot;)</value>
      <webElementGuid>3aa8d741-373f-46bc-97b5-966fab3ed8d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxCardDebitRow_lblDisponibleExtraccion']</value>
      <webElementGuid>96b85e72-24c2-4f28-bd36-ea065c19ebfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxCardDebitRow_flxCardDebitRow']/div[4]/div</value>
      <webElementGuid>1b15bf86-708f-4185-a4b3-e2e74d1434ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 40.000,00'])[1]/following::div[2]</value>
      <webElementGuid>7ec3c4e3-890d-4009-9e1a-91b987d3ee0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilitada para compra'])[1]/following::div[14]</value>
      <webElementGuid>eee1c6e8-ce51-47de-8814-cc1bdfc586c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 60.000,00'])[1]/preceding::div[1]</value>
      <webElementGuid>a5a73788-8fc3-43fe-96e7-90dbba807ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::div[3]</value>
      <webElementGuid>d9fe3207-4eb0-4c95-9557-be20052e8d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[4]/div</value>
      <webElementGuid>469f8dda-f13a-4ec4-a00b-5980fcaec024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxCardDebitRow_lblDisponibleExtraccion' and (text() = '$ 40.000,00' or . = '$ 40.000,00')]</value>
      <webElementGuid>831ea2d9-d076-4503-b8dc-41cfaecd7239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
