<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrjDebitoModificarLimitesExtraccin</name>
   <tag></tag>
   <elementGuidId>c939d0a0-ce9b-4b27-8bda-b6a0e14534b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmBcclCardsHome_flxCardDebitRowFloatingMenu_lblmodifyLimit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmBcclCardsHome_flxCardDebitRowFloatingMenu_lblmodifyLimit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1e806b61-0b42-4e57-a890-dfa92f605b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmBcclCardsHome_flxCardDebitRowFloatingMenu_lblmodifyLimit</value>
      <webElementGuid>c395eb7f-e933-4f03-8696-43d396838a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>466724c9-186a-48b0-907e-da5672036592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclCardsHome</value>
      <webElementGuid>654629fa-2548-448d-b936-f84049596e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>flxCardDebitRowFloatingMenu</value>
      <webElementGuid>7b8a4dea-fa31-40ba-b1df-4749dd855349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>d97526be-cae3-4b44-9629-cef7c355f244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modificar límites de extracción y compra</value>
      <webElementGuid>6f856bab-7041-42f9-9631-347485c91491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclCardsHome_flxCardDebitRowFloatingMenu_lblmodifyLimit&quot;)</value>
      <webElementGuid>bf5856c5-e10e-49a6-88d4-52988b1ca9a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_flxCardDebitRowFloatingMenu_lblmodifyLimit']</value>
      <webElementGuid>e57fa031-356b-42f4-a86b-fc57da1ab094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmBcclCardsHome_flxCardDebitRowFloatingMenu_flxmodifyLimit']/div/div</value>
      <webElementGuid>60de0d2e-954e-4e83-95ca-aeafa7fb8a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modificar cuenta principal'])[1]/following::div[5]</value>
      <webElementGuid>4b0151df-2a68-4e0f-9c4b-1ba7865df902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[7]/following::div[13]</value>
      <webElementGuid>3fc04cca-ffe8-47f6-8383-b6bad37dca3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitar reposición'])[1]/preceding::div[1]</value>
      <webElementGuid>96163335-5ae3-4f7a-b8de-ef20a4ee447a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denunciar por robo o extravío'])[1]/preceding::div[6]</value>
      <webElementGuid>5245cb43-81c6-4d0e-aaf4-53bcae19fd31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modificar límites de extracción y compra']/parent::*</value>
      <webElementGuid>75911d94-1255-4869-8c2f-b00b6e726401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>a11db22b-f3d7-463b-babd-790ba89c52cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmBcclCardsHome_flxCardDebitRowFloatingMenu_lblmodifyLimit' and (text() = 'Modificar límites de extracción y compra' or . = 'Modificar límites de extracción y compra')]</value>
      <webElementGuid>6e60d33a-83c1-4f85-8c2f-7a49c338fa1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
