<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnAceptar</name>
   <tag></tag>
   <elementGuidId>d8a93d2a-a6f4-4f7b-b450-5844b8aef7eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_btnContinue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_btnContinue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db3b2396-0fb7-4e6f-948c-ce13cb180dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_btnContinue</value>
      <webElementGuid>8f33f813-e507-49d7-8574-ad503379646f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>cfa5c7cc-0c3a-4310-bae9-8f73e5f87f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl</value>
      <webElementGuid>310429a5-da7d-4c60-8b1a-adffddb0de79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AceptarDebinPanel_AceptarDebin</value>
      <webElementGuid>eff7dab7-4331-4b03-b267-f5f5f53495c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29f6909b-1b99-422e-8a41-1bd37fdf26fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimaryBold disableSelection</value>
      <webElementGuid>fd7b0bb3-16a0-4088-8850-9c96f9dfa742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>72b6a097-d668-4448-9209-6b74f2976882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimaryBold</value>
      <webElementGuid>a01c64b0-dc40-46aa-82b0-85aa65e72b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_btnContinue&quot;)</value>
      <webElementGuid>641c885d-fc29-45ab-9664-b06eb2824e8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_btnContinue']</value>
      <webElementGuid>5828a0a0-e931-4dc9-9c6e-6e3fe5588f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_flxButtonsStep1']/div[2]/input</value>
      <webElementGuid>5f39065d-278b-41b5-b59f-03d63e270324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div[2]/input</value>
      <webElementGuid>896d973f-cd8a-4185-bdc4-e0f130be97b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_btnContinue' and @type = 'button']</value>
      <webElementGuid>cf10d881-7c16-44f6-9e5e-f1e6560ea32b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
