<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnConfirmarFormulario</name>
   <tag></tag>
   <elementGuidId>85f2079c-a5fe-4a90-8d98-f490f3144b79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmConfirmDebinBccl_ConfirmDebin_btnConfirmDEBIN_btnWithLoader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmConfirmDebinBccl_ConfirmDebin_btnConfirmDEBIN_btnWithLoader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a65423e2-b266-4b47-8721-991f613aa9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>240afec1-f7ab-405f-a6c5-1c309cbade8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmConfirmDebinBccl_ConfirmDebin_btnConfirmDEBIN_btnWithLoader-hint</value>
      <webElementGuid>d7e5db33-d1cf-464c-9ae1-1aad04ee92bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmConfirmDebinBccl_ConfirmDebin_btnConfirmDEBIN_btnWithLoader</value>
      <webElementGuid>9eba7154-1523-42b9-b23d-d47314cb2c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>a0e05102-72f8-4190-8274-9b2e168d1ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmConfirmDebinBccl</value>
      <webElementGuid>156becef-7353-4361-b2aa-9360fa4755f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConfirmDebin_btnConfirmDEBIN</value>
      <webElementGuid>d0940cf4-7eef-4fe9-9179-052697a5ffa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6269f874-4071-4f98-bf35-751c6a3f3456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>d078307b-01b7-4de2-bab9-a5bf56ed343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>0c575c1e-9f9a-4ead-9536-0a5936813074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>490d851b-9875-419e-92a1-d370954c2cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfirmDebinBccl_ConfirmDebin_btnConfirmDEBIN_btnWithLoader&quot;)</value>
      <webElementGuid>6e9d72de-e50a-4cd5-b1cd-61079069cc1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmConfirmDebinBccl_ConfirmDebin_btnConfirmDEBIN_btnWithLoader']</value>
      <webElementGuid>7adcdfa3-0e0d-490c-91f4-87dbf56d0f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmConfirmDebinBccl_ConfirmDebin_btnConfirmDEBIN']/div/input</value>
      <webElementGuid>24aa7492-9ebd-4f80-9286-782f43f53d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>e2952370-4efa-49fb-84f5-e32e05c7f5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmConfirmDebinBccl_ConfirmDebin_btnConfirmDEBIN_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>51f1eff0-a14b-40f3-951c-f992cc126303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
