<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnAdherirDebinCuenta</name>
   <tag></tag>
   <elementGuidId>2ea3bf1d-fa27-4e45-9060-a96e526de294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmDebinAdhesionBccl_segAccountsToAdhere&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsDebinRow_flxAccountsDebinRow&quot;]/div[@class=&quot;kcell middlecenteralignsknBtnPrimary&quot;]/input[@id=&quot;flxAccountsDebinRow_btnAdhere&quot;][count(. | //*[@id = 'flxAccountsDebinRow_btnAdhere' and @kuid = '7ADC5C51-977D-4156-8FEB-507C1F996F32' and @type = 'button' and @value = 'Adherir']) = count(//*[@id = 'flxAccountsDebinRow_btnAdhere' and @kuid = '7ADC5C51-977D-4156-8FEB-507C1F996F32' and @type = 'button' and @value = 'Adherir'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxAccountsDebinRow_btnAdhere</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flxAccountsDebinRow_btnAdhere']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5393357c-c460-4aad-ba60-7759c4965ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsDebinRow_btnAdhere</value>
      <webElementGuid>1146cbc1-2f93-4a58-a55b-5b6b06455259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>e6fdf563-b37c-4e6a-bbe9-82fe52b38db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsDebinRow</value>
      <webElementGuid>6c2a99a1-aa4d-4389-8ffb-ca3e8be8b1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccountsToAdhere</value>
      <webElementGuid>728672a1-4534-47e5-9e19-523c1fa27597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>7ADC5C51-977D-4156-8FEB-507C1F996F32</value>
      <webElementGuid>65ade46e-a2d1-4090-9d0b-fef99e6d5ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9967eb75-3ce7-4f1e-9cec-9a645678d070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>48cdd3fe-52ff-469d-b04e-6ea78c23484b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Adherir</value>
      <webElementGuid>24399489-6a62-4417-9cc9-f45d163e0958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>f7d031ff-2f12-4ecf-b284-23eb38cfd6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinAdhesionBccl_segAccountsToAdhere&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsDebinRow_flxAccountsDebinRow&quot;]/div[@class=&quot;kcell middlecenteralignsknBtnPrimary&quot;]/input[@id=&quot;flxAccountsDebinRow_btnAdhere&quot;]</value>
      <webElementGuid>bdd9829e-227d-4dc7-8c8e-5f009f9a126e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flxAccountsDebinRow_btnAdhere']</value>
      <webElementGuid>af594af5-943d-40e6-b23b-3c7a8741ed42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountsDebinRow_flxAccountsDebinRow']/div[5]/input)[2]</value>
      <webElementGuid>cd4c9b09-c981-4d3e-af45-7d064baf1ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[5]/input</value>
      <webElementGuid>28e2bc21-94d9-4105-a922-7b1e5fef4fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'flxAccountsDebinRow_btnAdhere' and @type = 'button']</value>
      <webElementGuid>635123aa-bdaf-4b22-b90c-5d53991956ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
