<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnRechazarDebin</name>
   <tag></tag>
   <elementGuidId>70fc3909-9e87-49d5-8404-89ad15b6910c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flxDebinPaymentsReceivedsRow_btnReject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxDebinPaymentsReceivedsRow_btnReject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91f1745e-88fa-48e8-bd9c-a0e840d0711c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxDebinPaymentsReceivedsRow_btnReject</value>
      <webElementGuid>e6e7c232-cf8c-401a-bb83-346cd4462841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>ced87689-e5dd-4be1-a0ed-e6f51ed8ea21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxDebinPaymentsReceivedsRow</value>
      <webElementGuid>f79d65cf-98b4-4579-b0d8-d3224e76c5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segReceiveds</value>
      <webElementGuid>3e97bb04-1ae5-43d5-ad59-a4dda39c46f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>C5EA0574-BD07-4360-AFD1-4C1BC082A4FE</value>
      <webElementGuid>6fffd83c-dab3-4ed1-8e29-a87bbaaccea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d193dddd-4594-4813-98f7-eb7451e2f860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnCircleSecondary disableSelection</value>
      <webElementGuid>e15c8b15-1729-4f10-8bf4-b7591536f956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8e5fc41a-57a9-4112-85d6-e8568ce1bf78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnCircleSecondary</value>
      <webElementGuid>01dae8b5-3773-454b-b713-306a0255bc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinPaymentsHomeBccl_DebinReceiveds_segReceiveds&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinPaymentsReceivedsRow_flxDebinPaymentsReceivedsRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinPaymentsReceivedsRow_flxIconsContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknBtnCircleSecondary&quot;]/input[@id=&quot;flxDebinPaymentsReceivedsRow_btnReject&quot;]</value>
      <webElementGuid>deabdd8d-49ab-435f-96fa-4fbe8543f247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flxDebinPaymentsReceivedsRow_btnReject']</value>
      <webElementGuid>32fa1b73-f5fe-4dc5-9e5c-ea87aa06c313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxDebinPaymentsReceivedsRow_flxIconsContainer']/div/input</value>
      <webElementGuid>74ae0c64-2cc3-42a4-b82c-3bc4b01da3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>6c3e0f0e-6d18-4c8c-a56c-849792868596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'flxDebinPaymentsReceivedsRow_btnReject' and @type = 'button']</value>
      <webElementGuid>bdb6800a-a3c7-4131-ac7c-f70c52332679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
