<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnRechazar</name>
   <tag></tag>
   <elementGuidId>8d247180-2106-4b9d-ac63-1fdadeacf37e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmDebinPaymentsHomeBccl_RejectDebinPanel_RejectDebin_ButtonReject_btnWithLoader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinPaymentsHomeBccl_RejectDebinPanel_RejectDebin_ButtonReject_btnWithLoader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>490df6be-0aee-4d36-abe4-8f88a11a400a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>ffb9308b-c627-4a43-83b8-5e04776a8d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl_RejectDebinPanel_RejectDebin_ButtonReject_btnWithLoader-hint</value>
      <webElementGuid>8cf5cd54-c3c9-4c75-9e53-a5a432cd29d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl_RejectDebinPanel_RejectDebin_ButtonReject_btnWithLoader</value>
      <webElementGuid>3685a6a2-c18e-4683-98b7-4a5465d88028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>7e534444-3b14-4380-9ebf-7c1d33a2719c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl</value>
      <webElementGuid>fcc51721-f2bc-4e0f-915c-42a971a7ca5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>RejectDebinPanel_RejectDebin_ButtonReject</value>
      <webElementGuid>c9de7e4c-d9df-44f6-bd78-38689642c1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e38fe62d-1983-4870-8a19-09ec75dde5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknBtnPrimary</value>
      <webElementGuid>4dd4ef0b-5fc2-45a8-af7c-8c7dd85489ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rechazar</value>
      <webElementGuid>d91f9beb-2b9f-4c24-b969-626775e0c7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>1150f1dd-4c00-4762-84fd-9dc7bd53b577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25022898-3ef8-4746-aa8a-1a8a7c34d51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinPaymentsHomeBccl_RejectDebinPanel_RejectDebin_ButtonReject_btnWithLoader&quot;)</value>
      <webElementGuid>572a742b-ca1f-4bc4-81ab-a3a947653653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmDebinPaymentsHomeBccl_RejectDebinPanel_RejectDebin_ButtonReject_btnWithLoader']</value>
      <webElementGuid>1508e890-cf99-4f03-8ba5-487783135f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinPaymentsHomeBccl_RejectDebinPanel_RejectDebin_ButtonReject']/div/input</value>
      <webElementGuid>881558dd-6b02-4e14-a653-79a20f52cb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>7103886c-af23-4c82-8b4a-edd649486063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmDebinPaymentsHomeBccl_RejectDebinPanel_RejectDebin_ButtonReject_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>3baace1d-2f95-4c0a-bf16-40f77a50678f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
