<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnAdherirDebinCuenta</name>
   <tag></tag>
   <elementGuidId>2ea3bf1d-fa27-4e45-9060-a96e526de294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxAccountsDebinRow_btnAdhere</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flxAccountsDebinRow_btnAdhere']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmDebinAdhesionBccl_segAccountsToAdhere&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsDebinRow_flxAccountsDebinRow&quot;]/div[@class=&quot;kcell middlecenteralignsknBtnPrimary&quot;]/input[@id=&quot;flxAccountsDebinRow_btnAdhere&quot;][count(. | //*[@id = 'flxAccountsDebinRow_btnAdhere' and @kuid = '7ADC5C51-977D-4156-8FEB-507C1F996F32' and @type = 'button' and @value = 'Adherir']) = count(//*[@id = 'flxAccountsDebinRow_btnAdhere' and @kuid = '7ADC5C51-977D-4156-8FEB-507C1F996F32' and @type = 'button' and @value = 'Adherir'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80345548-bf62-4078-86ea-fe7a32606c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsDebinRow_btnAdhere</value>
      <webElementGuid>c6035dd8-fbf1-45f4-97a0-3bb31409b74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>767eeb2f-a90a-4ebf-b3dd-0f599feb0c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsDebinRow</value>
      <webElementGuid>7d1f82c2-1a80-45e1-9ce4-fb46c1293437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccountsToAdhere</value>
      <webElementGuid>4e9efc1e-1df9-4a9e-b407-f8bb2662cfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>7ADC5C51-977D-4156-8FEB-507C1F996F32</value>
      <webElementGuid>e7157f88-394e-4180-9bf1-66cc961a2dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6af902b5-6ca7-48bc-a42f-15559e149e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>d14a68bb-dabb-4e20-b73d-2a52e74c4b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Adherir</value>
      <webElementGuid>52910243-8998-470d-8e23-9d6055d7e68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>527fb208-94f2-458c-9273-daf1b6d82c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinAdhesionBccl_segAccountsToAdhere&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsDebinRow_flxAccountsDebinRow&quot;]/div[@class=&quot;kcell middlecenteralignsknBtnPrimary&quot;]/input[@id=&quot;flxAccountsDebinRow_btnAdhere&quot;]</value>
      <webElementGuid>7de40689-3d8d-4c68-8ad7-280b6223381f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flxAccountsDebinRow_btnAdhere']</value>
      <webElementGuid>cb2b5c75-b1a0-4828-97a9-2c8679a0d092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountsDebinRow_flxAccountsDebinRow']/div[5]/input)[2]</value>
      <webElementGuid>7d47ab43-2e51-427e-93ea-4068f92c85bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[5]/input</value>
      <webElementGuid>90b3ba79-f707-4e10-a4f2-f3b765063ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'flxAccountsDebinRow_btnAdhere' and @type = 'button']</value>
      <webElementGuid>b1dad901-9ea3-45ed-88a6-a917879f3ea1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
