<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnDesadherirCuenta</name>
   <tag></tag>
   <elementGuidId>2719b126-eea7-42ba-97a6-2b59e0535186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmDebinAdhesionBccl_segAccountsToAdhere&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsDebinRow_flxAccountsDebinRow&quot;]/div[@class=&quot;kcell middlecenteralignsknBtnSecondary&quot;]/input[@id=&quot;flxAccountsDebinRow_btnUnattach&quot;][count(. | //*[@id = 'flxAccountsDebinRow_btnUnattach' and @kuid = '1D284314-4264-40E1-A928-80B58CF22D52' and @type = 'button' and @value = 'Desadherir']) = count(//*[@id = 'flxAccountsDebinRow_btnUnattach' and @kuid = '1D284314-4264-40E1-A928-80B58CF22D52' and @type = 'button' and @value = 'Desadherir'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='flxAccountsDebinRow_btnUnattach'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dec46e9a-d3bd-42d8-a458-91fc90ef39b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsDebinRow_btnUnattach</value>
      <webElementGuid>0f5913e4-2e99-4c9d-88d1-19c8f3cc2b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>0d8b204e-07c4-47cb-b4f7-00eb5197c990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsDebinRow</value>
      <webElementGuid>a54d5b98-7cd1-4365-97fa-fea2e66fd551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccountsToAdhere</value>
      <webElementGuid>5c193972-e29f-470b-a46b-62a3afd70782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>1D284314-4264-40E1-A928-80B58CF22D52</value>
      <webElementGuid>19bb5fdd-ce58-4ca9-ab43-8f82cc738e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99480872-0458-4c80-a6e7-4d7cf6dbc6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnSecondary disableSelection</value>
      <webElementGuid>4fe26c21-837e-4058-9e0b-d639923c2162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Desadherir</value>
      <webElementGuid>30ccadb4-2ab0-4a05-bdd6-4c8cea0df98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnSecondary</value>
      <webElementGuid>bf322568-06cf-4179-aae7-8f83e5bd4492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinAdhesionBccl_segAccountsToAdhere&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsDebinRow_flxAccountsDebinRow&quot;]/div[@class=&quot;kcell middlecenteralignsknBtnSecondary&quot;]/input[@id=&quot;flxAccountsDebinRow_btnUnattach&quot;]</value>
      <webElementGuid>4c980e8a-64fa-4cf4-9ea0-04d0dde1822c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='flxAccountsDebinRow_btnUnattach'])[2]</value>
      <webElementGuid>678fc3cd-3630-40ad-a590-76d30f5f2762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountsDebinRow_flxAccountsDebinRow']/div[5]/input)[2]</value>
      <webElementGuid>8b822b35-b8f7-4001-be51-3cad43afb4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[5]/input</value>
      <webElementGuid>a2b81239-9206-43e2-bbb6-690819904a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'flxAccountsDebinRow_btnUnattach' and @type = 'button']</value>
      <webElementGuid>286e699f-133c-4e0c-99bb-0e3a1d0a37d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
