<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnConfirmarDesadherir</name>
   <tag></tag>
   <elementGuidId>8b720930-d751-475f-a8a8-fe2ea66ff8ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmDebinAdhesionBccl_ConfirmPopup_btnConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmDebinAdhesionBccl_ConfirmPopup_btnConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc0ff10b-1484-4310-9f5d-2fda02267e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinAdhesionBccl_ConfirmPopup_btnConfirm</value>
      <webElementGuid>ec41deba-c378-4967-9b4e-678299198d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>85e87a4b-ea55-4137-bd52-e2f99ea80e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinAdhesionBccl</value>
      <webElementGuid>4b79aee6-be38-48a0-ad4f-2de8ee07dbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConfirmPopup</value>
      <webElementGuid>a4d1e33d-9fbb-489f-ba00-473b23d80c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e6f8d23-192b-418c-9a1e-d226f8ec6358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>df9b5d6c-c1bf-4780-b1d6-56b350da278d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sí</value>
      <webElementGuid>59367081-c4f7-4afd-97ce-2e8f6b62405f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>84fb818f-6148-42af-ab6a-ac402f9d9736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinAdhesionBccl_ConfirmPopup_btnConfirm&quot;)</value>
      <webElementGuid>bc986546-2098-49d7-8cde-6433061063b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmDebinAdhesionBccl_ConfirmPopup_btnConfirm']</value>
      <webElementGuid>e31328d8-7423-41db-bfd5-809467993b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinAdhesionBccl_ConfirmPopup_flxConfirmPopup']/div[7]/input</value>
      <webElementGuid>bf3603ca-166f-4bda-b1f0-d2a33ca1f6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div[7]/input</value>
      <webElementGuid>3d10953f-396f-4d95-8b77-ebfcb194f1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmDebinAdhesionBccl_ConfirmPopup_btnConfirm' and @type = 'button']</value>
      <webElementGuid>b7f8c058-7f94-48ec-905e-4813e767209b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
