<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnConfirmarEliminar</name>
   <tag></tag>
   <elementGuidId>4ed6cd75-9338-422a-b912-c917d08a0cf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmDebinPaymentsHomeBccl_ConfirmPopup_btnConfirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinPaymentsHomeBccl_ConfirmPopup_btnConfirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b85938c-5b73-41aa-b0e9-a678a41113a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl_ConfirmPopup_btnConfirm</value>
      <webElementGuid>534cb403-091e-4bb5-9ada-996b9474666a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>e24466da-7aa5-4273-97fd-a9457ffcf56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl</value>
      <webElementGuid>2c245afd-2ec1-414f-aace-76163af2dab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConfirmPopup</value>
      <webElementGuid>c19909f2-2b54-48df-8b56-19a65a906f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>62ef08a1-f59d-4d8b-a81a-3d75935adca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>aca69a21-2463-4c51-bbf8-80cffa1c22cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>5c1f0b7c-7558-4d9f-b015-2c4fdc629d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>58af43f7-499c-4f28-a287-cd01e1d6f882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinPaymentsHomeBccl_ConfirmPopup_btnConfirm&quot;)</value>
      <webElementGuid>557dccaa-85f0-40ea-89d7-60f6ab69f7e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmDebinPaymentsHomeBccl_ConfirmPopup_btnConfirm']</value>
      <webElementGuid>34843c5b-5cd8-4e9e-a2b7-e935ec5c4b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinPaymentsHomeBccl_ConfirmPopup_flxConfirmPopup']/div[7]/input</value>
      <webElementGuid>6659dc98-b9bb-4fb5-a37f-845b37e86514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div[7]/input</value>
      <webElementGuid>84eea1f4-4469-42c2-ac3b-8f13e3ff5272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmDebinPaymentsHomeBccl_ConfirmPopup_btnConfirm' and @type = 'button']</value>
      <webElementGuid>5af86e8e-e455-4a15-ba30-20318c39b21e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
