<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnAceptarBasesCondiciones</name>
   <tag></tag>
   <elementGuidId>17df92d0-5d3c-42ef-bd86-215cd6732e40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmDebinAdhesionBccl_TermsAndConditions_btnContinue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinAdhesionBccl_TermsAndConditions_btnContinue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0219148-a169-46ce-972c-287f903d98b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinAdhesionBccl_TermsAndConditions_btnContinue</value>
      <webElementGuid>837c4c03-b918-4e3a-bb33-aab11e564098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>62120213-9d74-4d3b-b4e0-d5204b172114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinAdhesionBccl</value>
      <webElementGuid>e40d1ec4-3ba8-467c-afbe-87eb17e2491b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TermsAndConditions</value>
      <webElementGuid>953910bd-1b34-474e-af62-5bc855de2ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7432cb3b-125b-4c78-a0d4-f8d3485f1012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknBtnPrimary</value>
      <webElementGuid>c5edda36-94af-407f-a8d8-1cfab5041308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>ee6a6d2c-efa4-42a0-ab04-96202c1f7423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>d4810c42-6bbc-4086-ae2d-8c2613104c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>277401d0-7323-48bc-9aeb-5b395df2f4e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinAdhesionBccl_TermsAndConditions_btnContinue&quot;)</value>
      <webElementGuid>ba48dbc1-7efc-4ccd-9466-14588929c83a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmDebinAdhesionBccl_TermsAndConditions_btnContinue']</value>
      <webElementGuid>57bc3099-eecb-47ef-b0a9-3feda2a4aca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinAdhesionBccl_TermsAndConditions_flxButtonsContainer']/div[2]/input</value>
      <webElementGuid>03aa7a39-1e2f-4fff-8573-40943aa8c62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/input</value>
      <webElementGuid>7c4b0723-94ff-4eaf-8496-ffe83d607e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmDebinAdhesionBccl_TermsAndConditions_btnContinue' and @type = 'button']</value>
      <webElementGuid>53be28cb-0903-423e-b853-53c74d0e16c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
