<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnConfirmar</name>
   <tag></tag>
   <elementGuidId>17e6d212-ed83-49a1-b2b6-dfe3e1b8edba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm_btnWithLoader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm_btnWithLoader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dd6bc73-c057-4308-88e0-69445fc40a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>5452bb8a-a681-42dd-b108-beba4347e0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm_btnWithLoader-hint</value>
      <webElementGuid>ec10c259-aa1f-451a-95b9-bb10a2fa88d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm_btnWithLoader</value>
      <webElementGuid>5f0c6b27-105d-437b-a94d-9261a12436e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>64a0f740-74f8-4bc6-80ce-1526ba7e607c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl</value>
      <webElementGuid>c6d972fd-9bcc-44ee-a294-1aee6de70b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm</value>
      <webElementGuid>ebe7890f-fcc1-4682-9550-745c2e77bdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88ffe76e-59cb-4fb5-9cfb-a0fdabae6d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>71ec9efc-86f3-406d-ab67-3871cc4ebdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>0c77498e-565b-4332-9572-4670edea5100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>2db4ab05-0258-4947-ae79-d221bd2e1c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm_btnWithLoader&quot;)</value>
      <webElementGuid>5ca42589-ccae-4ffb-a703-146359d6fec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm_btnWithLoader']</value>
      <webElementGuid>7c7c9611-68cf-4b23-8a9a-8b847bd47e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm']/div/input</value>
      <webElementGuid>f6de9d68-a6f5-4975-a4e8-5d69f2dd9c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>9035c113-348f-4200-90a5-71d949f34c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmDebinPaymentsHomeBccl_AceptarDebinPanel_AceptarDebin_SecondFactor_ButtonConfirm_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>feac57bf-e4de-45ae-9551-6f580a5b561d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
