<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnContinuar</name>
   <tag></tag>
   <elementGuidId>b3cb46ee-dbc4-48d6-b1f8-f87bdefc3cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmAdhereDebin_CreateDebinForm_btnContinue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAdhereDebin_CreateDebinForm_btnContinue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b7bb378-d93e-4bd5-af3b-6d22e0ad8e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAdhereDebin_CreateDebinForm_btnContinue</value>
      <webElementGuid>b3c14a9e-f9c6-4fa4-a422-011d76b27f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>c75febe3-d0fb-415a-bb47-f34451536ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAdhereDebin</value>
      <webElementGuid>83900bf0-96ca-426c-8426-66952ce34084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CreateDebinForm</value>
      <webElementGuid>96e0ec26-d589-412a-84b1-ce6ae5e56ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d3ab2e7a-64da-4180-90ea-dea13a74e3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimaryBold disableSelection</value>
      <webElementGuid>79ba20a2-d4c3-4a0c-8cf8-c093f9c3142c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>b11405b1-8ed3-41b2-8f16-1f3acfb81e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimaryBold</value>
      <webElementGuid>4d8dea45-bee4-4dca-bf30-5c518da4c4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAdhereDebin_CreateDebinForm_btnContinue&quot;)</value>
      <webElementGuid>cfdab7b0-8596-4c79-b889-9b3a98626c92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmAdhereDebin_CreateDebinForm_btnContinue']</value>
      <webElementGuid>2ecb433a-19e5-423f-bcdf-ba88f44e1104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_CreateDebinForm_flxButtons']/div/input</value>
      <webElementGuid>d9001f2b-d71c-480a-9847-e8a204baace0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>430649fb-2132-4324-989d-057b1bc10f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmAdhereDebin_CreateDebinForm_btnContinue' and @type = 'button']</value>
      <webElementGuid>1aca90f7-5f47-47f1-b87a-f65c112e9dff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
