<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDbnDesadherirCuenta</name>
   <tag></tag>
   <elementGuidId>2719b126-eea7-42ba-97a6-2b59e0535186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='flxAccountsDebinRow_btnUnattach'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cc3fafb-5b0c-452b-8f70-32f0ae509d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsDebinRow_btnUnattach</value>
      <webElementGuid>ac69ad89-fd1e-4533-b665-5660eba76f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>6de3de0c-cb4c-4242-ba18-fd7a8d15556e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsDebinRow</value>
      <webElementGuid>41563060-9513-4962-8c22-6c3bb831dd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccountsToAdhere</value>
      <webElementGuid>a44898b9-f436-432e-9591-c87a21f6880d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>1D284314-4264-40E1-A928-80B58CF22D52</value>
      <webElementGuid>8235702b-7d40-4dd2-bd7c-5f402ccd555f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75319d51-3d2d-4649-8e8a-a8d1941fc15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnSecondary disableSelection</value>
      <webElementGuid>1c7eba43-cb3d-498a-bba5-c6b7acd58d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Desadherir</value>
      <webElementGuid>b9c50411-991c-4f44-b776-f2684fbf482b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnSecondary</value>
      <webElementGuid>d299e9b7-390c-4148-8f58-bcfb3581b21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinAdhesionBccl_segAccountsToAdhere&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsDebinRow_flxAccountsDebinRow&quot;]/div[@class=&quot;kcell middlecenteralignsknBtnSecondary&quot;]/input[@id=&quot;flxAccountsDebinRow_btnUnattach&quot;]</value>
      <webElementGuid>80dc1fa3-8444-4816-a701-f20bbcc499c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='flxAccountsDebinRow_btnUnattach'])[2]</value>
      <webElementGuid>424bbf8a-eaf2-48f3-a7ee-621e6bfdcb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountsDebinRow_flxAccountsDebinRow']/div[5]/input)[2]</value>
      <webElementGuid>eae5caf1-8e85-40c9-8766-168a2131c70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[5]/input</value>
      <webElementGuid>f1fc61de-3bbb-4bd8-ac98-a8edb5c1b276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'flxAccountsDebinRow_btnUnattach' and @type = 'button']</value>
      <webElementGuid>14492f6f-0150-428f-9555-ef17394142a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
