<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chbxDbnDolarFormulario</name>
   <tag></tag>
   <elementGuidId>475904a6-260d-4b7c-9468-b411ef5445e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAdhereDebin_CreateDebinForm_RadioButtonDolares_lblRadio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAdhereDebin_CreateDebinForm_RadioButtonDolares_lblRadio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b709e65d-f737-4094-9184-ac58d46298ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAdhereDebin_CreateDebinForm_RadioButtonDolares_lblRadio</value>
      <webElementGuid>1ae3bafe-fe0f-4307-83b8-65a5766a74ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>303ace25-7105-4aab-897f-fa5e4d34f870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAdhereDebin</value>
      <webElementGuid>f2822a96-17d3-49cc-9dab-655090c14d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CreateDebinForm_RadioButtonDolares</value>
      <webElementGuid>5131a07f-3520-48ce-8b44-75b29df99423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddlecenteralign disableSelection sknLblRadioSelectedDot</value>
      <webElementGuid>f8f874ca-c303-424c-ba24-801850527fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>767df1ae-50cb-40ae-b849-793dfefaf63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAdhereDebin_CreateDebinForm_RadioButtonDolares_lblRadio&quot;)</value>
      <webElementGuid>531b35e1-f35e-494c-bd0e-2016bd4d292d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_CreateDebinForm_RadioButtonDolares_lblRadio']</value>
      <webElementGuid>11fcf8b7-3741-40bc-88f9-8041427efb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_CreateDebinForm_RadioButtonDolares_flxRadioButton']/div/div</value>
      <webElementGuid>3c272270-898f-4085-bfcd-20e09ecfda85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesos'])[1]/following::div[11]</value>
      <webElementGuid>7be42f54-cc69-4a73-b55e-2e6cbeb7d2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[13]</value>
      <webElementGuid>3802029c-e30c-4b5d-833b-bc57c5269f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dólares'])[1]/preceding::div[1]</value>
      <webElementGuid>9f3dcd3f-1504-4595-81ff-d0ac4108bbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duración de la solicitud'])[1]/preceding::div[3]</value>
      <webElementGuid>06345329-2e69-427b-9b9b-d7a0af39a10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>b45803aa-fb2d-4555-b5db-4fadf4037154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAdhereDebin_CreateDebinForm_RadioButtonDolares_lblRadio' and (text() = '' or . = '')]</value>
      <webElementGuid>2dadb347-0fc2-446a-8300-a584b08e1795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
