<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoDbnCalendarioMesSiguienteDesde</name>
   <tag></tag>
   <elementGuidId>89ed98e1-c6c9-491e-a2d3-d8992c0e375a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-k-w-c-month-cmp-05-2023']/div/div/div/div[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.-kony-w-c-next-nav-right-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>39738bc6-7805-43fc-a03b-0c6ecad16c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>9115aec7-f62b-4e39-b124-aef3d023c603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-w-c-next-nav-right-link</value>
      <webElementGuid>53531742-e2c5-47da-9543-70522ba3530e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Next Month</value>
      <webElementGuid>34cea2d4-b5e1-49bc-9bd2-d8b8c5f02a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/right-arrow.png</value>
      <webElementGuid>dcdc8765-a2b9-4e29-adab-c2bf3d1b6e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinStatusFilters_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>213826e4-4ce4-4c5d-a555-00010a7208b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-k-w-c-month-cmp-05-2023&quot;)/div[@class=&quot;-kony-w-c-topSection&quot;]/div[@class=&quot;-kony-w-c-table&quot;]/div[@class=&quot;-kony-w-c-row&quot;]/div[@class=&quot;-kony-w-c-cell -kony-w-c-next-nav&quot;]/img[@class=&quot;-kony-w-c-next-nav-right-link&quot;]</value>
      <webElementGuid>7249bb33-ec7a-4330-b184-bb238d132499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-05-2023']/div/div/div/div[3]/img</value>
      <webElementGuid>c5a5711a-6a80-47ba-83e0-1ec3d4637296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Next Month']</value>
      <webElementGuid>77c514b8-37ab-48c6-9295-1133a7a43b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>ead7b94d-d8fc-42f4-8662-a9756087b087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Next Month' and @src = 'desktopweb/images/right-arrow.png']</value>
      <webElementGuid>3e87672a-d649-4ca6-a7ba-384437b989f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
