<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoDbnCalendarioConsultarDebinHasta</name>
   <tag></tag>
   <elementGuidId>964b8804-70f2-4393-af3c-aa07088172ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='calendarDateFilterTo_img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendarDateFilterTo_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e234986e-4f99-4bda-89c0-a51468b79e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendarDateFilterTo_img</value>
      <webElementGuid>b0438fe8-d87a-4859-a356-09c7d344cada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>4da66ccb-0054-4db7-80c6-7072901482b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/calendar-regular.svg</value>
      <webElementGuid>52a56847-384b-4705-a516-df7a4211429d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xalign</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>76252b51-8605-4243-833c-29509d91e120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>$KW.Calendar.setCalElementStyle(this,false)</value>
      <webElementGuid>db2a8259-6038-475e-bcb1-02b53e8c4855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>6e6ba0d3-6f32-4535-a8fa-4e97cb5364b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinStatusFilters_DateFilter</value>
      <webElementGuid>506b5d5d-569c-42d7-8264-cedd71197d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb6b0b52-5363-4b67-b74b-25f775f9d779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDateFilterTo_img&quot;)</value>
      <webElementGuid>d9fcc8cd-ddc7-41f1-9d33-fb1d8c81ac7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='calendarDateFilterTo_img']</value>
      <webElementGuid>9c4b0b9d-5933-4029-a0aa-8187e6bdb0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DateFilter_calendarDateFilterTo']/img</value>
      <webElementGuid>5b21b27c-5e5a-4c69-b1dd-e53f26a6f106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Calendar'])[2]</value>
      <webElementGuid>0c0d9a61-2187-480c-9701-9267744b7e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/img</value>
      <webElementGuid>53eec8b8-b75e-4f40-9d06-8b5a217a4c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'calendarDateFilterTo_img' and @type = 'image' and @src = 'desktopweb/images/calendar-regular.svg' and @alt = 'Calendar']</value>
      <webElementGuid>5dc580d3-8268-409f-bad7-2925243ef8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
