<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoDbnCalendarioConsultarDebinDesde</name>
   <tag></tag>
   <elementGuidId>0ba461a0-7a38-4739-8245-cdb526256eec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='calendarDateFilterFrom_img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#calendarDateFilterFrom_img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f98a24d-5abb-4b6c-8d17-096f4c590f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendarDateFilterFrom_img</value>
      <webElementGuid>0df30e6d-93f6-4d8e-a8ca-b6e953b0313e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>401c06a8-4539-48c1-b61c-e898e69e5029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/calendar-regular.svg</value>
      <webElementGuid>3bc4342b-08d7-42e0-a673-9d6eb96c2b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xalign</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>b09fb600-b5c7-4bd8-97b4-edaa1892b24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>$KW.Calendar.setCalElementStyle(this,false)</value>
      <webElementGuid>23c5fe06-06ff-4551-b7d9-3b4b3d016ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>bb228e9a-c6ed-42d6-a44a-07e9d9d85bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinStatusFilters_DateFilter</value>
      <webElementGuid>ef42d071-0e54-4421-ab4d-ddd79da50c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b9a51c4f-5b79-4196-931d-0c18a6485352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDateFilterFrom_img&quot;)</value>
      <webElementGuid>db04fb95-f0da-4813-80ad-ab1d79212949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='calendarDateFilterFrom_img']</value>
      <webElementGuid>9c3a5b06-47b6-4799-abbf-b85a29e0b74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DateFilter_calendarDateFilterFrom']/img</value>
      <webElementGuid>2016c795-e8a6-444f-86f1-4ceff8cd6f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Calendar']</value>
      <webElementGuid>ec007caf-c7b4-4349-8e5c-429bcf7bb83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>5b940931-d3c1-4a12-808a-a9faa4c90c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'calendarDateFilterFrom_img' and @type = 'image' and @src = 'desktopweb/images/calendar-regular.svg' and @alt = 'Calendar']</value>
      <webElementGuid>fe6ec6ce-b4ac-4a78-9abb-2177d2afffb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
