<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkDbnSolapaGeneradosPendientes</name>
   <tag></tag>
   <elementGuidId>81cb6776-164a-437d-a6a0-cb98e580e479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmDebinPaymentsHomeBccl_Tabs_frmDebinPaymentsHomeBcclTabsRtx1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinPaymentsHomeBccl_Tabs_frmDebinPaymentsHomeBcclTabsRtx1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53723bd1-d358-4004-8d31-88dd864c1dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl_Tabs_frmDebinPaymentsHomeBcclTabsRtx1</value>
      <webElementGuid>c4388922-b032-4b0c-aa51-b8b72c0fec73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>RichText</value>
      <webElementGuid>858f99e4-8d38-4f62-824a-05a05c01a163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl</value>
      <webElementGuid>81eecc63-3597-4064-8e64-875ef9259eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Tabs</value>
      <webElementGuid>20e89f24-db89-4aac-9555-9bccc0526155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknRtxLatoReg1466 </value>
      <webElementGuid>90ec33c0-764e-44be-9154-d4888c36eef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generados pendientes</value>
      <webElementGuid>7215cee2-675b-489f-a21d-bc403c55c629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinPaymentsHomeBccl_Tabs_frmDebinPaymentsHomeBcclTabsRtx1&quot;)</value>
      <webElementGuid>a7198a75-ad34-4368-a9d0-4cee5c11ba37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinPaymentsHomeBccl_Tabs_frmDebinPaymentsHomeBcclTabsRtx1']</value>
      <webElementGuid>2be1ba6a-41a3-4621-bea3-07b314a7685f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinPaymentsHomeBccl_Tabs_frmDebinPaymentsHomeBcclTabsFlx1']/div/div</value>
      <webElementGuid>e5f6cb28-a698-4872-8bde-eaebec677f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recibidos pendientes'])[1]/following::div[5]</value>
      <webElementGuid>41b89492-e04b-4919-9ed1-205608e967cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[4]/following::div[27]</value>
      <webElementGuid>6fadd8e7-0a7b-4aff-b5c5-fca0ee2ce4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[7]</value>
      <webElementGuid>df85f3e7-7710-4687-845d-0847f88017ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[18]</value>
      <webElementGuid>86e8c882-c9fb-40af-8729-018a496194fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generados pendientes']/parent::*</value>
      <webElementGuid>cbdcb8ba-05d4-4f9e-8245-11318f97599f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>06e7828d-b46a-469c-a2b4-9cfa9ffbc746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinPaymentsHomeBccl_Tabs_frmDebinPaymentsHomeBcclTabsRtx1' and (text() = 'Generados pendientes' or . = 'Generados pendientes')]</value>
      <webElementGuid>18bacb6e-dbd1-45e0-a525-54a23657e370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
