<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnListaGeneradosMonto</name>
   <tag></tag>
   <elementGuidId>117ba0d2-8ece-4882-aa91-4cdb80c50283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxDebinStatusGeneratedsRow_lblAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxDebinStatusGeneratedsRow_lblAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f6e6549-49b0-4d8a-851f-1e5314f877ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxDebinStatusGeneratedsRow_lblAmount</value>
      <webElementGuid>97dbccb8-0e48-459a-91c8-e7bc4b7afce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f3369cf8-9ad6-4c29-8f69-b60913ce9cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxDebinStatusGeneratedsRow</value>
      <webElementGuid>689f96dd-13e2-415f-b565-d453e6402dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segGenerateds</value>
      <webElementGuid>59237efe-840e-497a-869d-2179c12493ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>B4269579-7D24-4E43-96D8-6D4AD3E26A35</value>
      <webElementGuid>4de0d45c-b25e-4196-b5f5-ac45c30ddf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddlerightalign disableSelection</value>
      <webElementGuid>f6b6bd3d-61ad-45d3-84ae-cbb3f4d165db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 4,00</value>
      <webElementGuid>2558cf94-558b-4d2e-96fe-4258e9512325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_segGenerateds&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinStatusGeneratedsRow_flxDebinStatusGeneratedsRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinStatusGeneratedsRow_flxAmount&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableCommonData&quot;]/div[@id=&quot;flxDebinStatusGeneratedsRow_lblAmount&quot;]</value>
      <webElementGuid>7fc0b77d-59e7-4c96-80d4-046838a97a0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxDebinStatusGeneratedsRow_lblAmount']</value>
      <webElementGuid>221153ce-c4d0-4a84-a567-4cabc98b43d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxDebinStatusGeneratedsRow_flxAmount']/div/div</value>
      <webElementGuid>7045472e-0468-4e09-80b7-95fde1d573fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vencido'])[1]/following::div[5]</value>
      <webElementGuid>429eb288-b479-40f1-8958-8f459298b681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[17]/following::div[7]</value>
      <webElementGuid>0eecb896-cf57-4d44-82db-1692ad288e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enrico Edie Agustin'])[3]/preceding::div[6]</value>
      <webElementGuid>07b650ac-93bc-4fff-af0b-215ce949f201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alquiler'])[16]/preceding::div[8]</value>
      <webElementGuid>f1e1991b-63e3-48b2-83b2-fbadb8d87cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 4,00']/parent::*</value>
      <webElementGuid>7a1ffa5d-1949-4618-a7d5-ca90324c7b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/ul/li/div/div/div[6]/div/div/div/div</value>
      <webElementGuid>003ea5c7-025b-4856-a040-a43834dbf0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxDebinStatusGeneratedsRow_lblAmount' and (text() = '$ 4,00' or . = '$ 4,00')]</value>
      <webElementGuid>e4a9ce8f-7adb-4e7a-b6d4-b1fcae689d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
