<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnConsultaEstadosVencidos</name>
   <tag></tag>
   <elementGuidId>f26b83c7-ce8b-469a-92b6-7fd1a2ecf0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon4lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon4lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bfd0b27f-51e1-4d28-8298-6598c76d7ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon4lblOptionTitle</value>
      <webElementGuid>67c5e8b7-3d5f-4a5d-b821-90d353a376b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f7581c00-1b10-4ce3-b970-4111b122070b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>f1e342b7-75d7-48c7-91a5-1c1385124bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinStatusFilters_DropDownStatus</value>
      <webElementGuid>f95eb590-2f8b-4a1f-a9dc-6a8e05542f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountTitleDropDown cntmiddleleftalign disableSelection</value>
      <webElementGuid>926dbb73-6137-4278-9c26-7c2d0ef73510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vencidos</value>
      <webElementGuid>b574293f-c560-4a9b-afac-a0fb780212cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon4lblOptionTitle&quot;)</value>
      <webElementGuid>d9b3b595-e091-43e2-8d92-8e2beba27eba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon4lblOptionTitle']</value>
      <webElementGuid>ad56736e-83b0-4a06-a63a-9745f271eca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon4flxOptionInfo']/div/div</value>
      <webElementGuid>7d195a3b-de83-458a-819a-1d907dd9b0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[13]/following::div[8]</value>
      <webElementGuid>6b028cd9-0f6f-4ee0-9de8-cbf70b0cdd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagados'])[1]/following::div[10]</value>
      <webElementGuid>351f468c-fa9c-4000-8c26-edfe3ab2d9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[14]/preceding::div[1]</value>
      <webElementGuid>b9f0c10c-8e84-4ff6-9e43-6773536fcbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otros'])[1]/preceding::div[3]</value>
      <webElementGuid>d9d4b817-a181-4239-b24c-9bcc343575c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vencidos']/parent::*</value>
      <webElementGuid>8cea003a-063f-41b7-a37f-33d78c3a991b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div[4]/div/div/div/div/div/div/div</value>
      <webElementGuid>80b8d9d4-3396-4c29-a7c6-cfd972f21a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon4lblOptionTitle' and (text() = 'Vencidos' or . = 'Vencidos')]</value>
      <webElementGuid>cb2490ed-cd51-4a61-85be-12bdb4ed67ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
