<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnConsultaEstadoGeneradosAcreditados</name>
   <tag></tag>
   <elementGuidId>c0035ca3-f3db-4935-8b3d-31168afce94b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon8lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon8lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ea30c10-c1e2-4536-a9dd-b534a465d974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon8lblOptionTitle</value>
      <webElementGuid>00699cdc-7427-4a2e-9443-3890133ae3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>aed42fa5-8424-4fcf-a593-28217ff5a22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>d2960838-6f4a-4f61-8571-cba1538bd3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinStatusFilters_DropDownStatus</value>
      <webElementGuid>47677734-eb0c-4ad2-b633-4f07ded2ed00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>4ad530d2-7126-41d1-966f-7ecdc6447b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acreditados</value>
      <webElementGuid>20621d52-d45e-4d30-8954-8ec12d92e073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon8lblOptionTitle&quot;)</value>
      <webElementGuid>55c0fc67-49ab-4ff3-b6ee-b1e403cea035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon8lblOptionTitle']</value>
      <webElementGuid>8039699c-8da5-48ee-9eb3-92d59d87b1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon8flxOptionInfo']/div/div</value>
      <webElementGuid>47f193ed-19d4-4797-bb73-fb0293231622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[11]/following::div[8]</value>
      <webElementGuid>1768e37f-8263-4d5c-852f-e6b5534a51e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendientes'])[1]/following::div[10]</value>
      <webElementGuid>af241bce-c5d1-4a5f-9576-f6e6af1f5c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[12]/preceding::div[1]</value>
      <webElementGuid>8452dd63-bc79-461b-ad80-e9643409cfad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vencidos'])[1]/preceding::div[3]</value>
      <webElementGuid>bf2a61c8-f8b0-413c-a9a7-2c7c32fdf568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acreditados']/parent::*</value>
      <webElementGuid>b11b4532-241b-4996-9cdf-4a9bc30c9ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>2a2c5865-42e9-4864-a915-91ac3849de1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon8lblOptionTitle' and (text() = 'Acreditados' or . = 'Acreditados')]</value>
      <webElementGuid>defefb35-11ad-4ade-a92d-c5e024668696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
