<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnListaRecibidosEstado</name>
   <tag></tag>
   <elementGuidId>2ca50e6d-ea54-42d9-aee0-1620fa477cbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxDebinStatusReceivedsRow_lblStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxDebinStatusReceivedsRow_lblStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5e32563-c54e-4636-bc59-0959ed59d1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxDebinStatusReceivedsRow_lblStatus</value>
      <webElementGuid>69b3d49a-b996-490e-8d50-8b423576755a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0a77e838-6e04-46ba-ad0f-6765946ad408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxDebinStatusReceivedsRow</value>
      <webElementGuid>29910870-3f76-44d3-b4f0-2aed8df4681c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segReceiveds</value>
      <webElementGuid>d636d7db-2da5-482e-9d03-39e12dc76e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>91C10892-A6CE-48C6-A60E-9546CAC7BADE</value>
      <webElementGuid>1996f74d-a089-42a2-bf76-6b49821dea98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddleleftalign disableSelection</value>
      <webElementGuid>8681a338-ac84-4b55-9577-d2ce60d304c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acreditado</value>
      <webElementGuid>4e885f16-64fa-4b1c-a2d3-63ce726005c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_segReceiveds&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinStatusReceivedsRow_flxDebinStatusReceivedsRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinStatusReceivedsRow_flxStatusContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxDebinStatusReceivedsRow_lblStatus&quot;]</value>
      <webElementGuid>d84171ae-030e-433e-ab0e-556e5e399d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxDebinStatusReceivedsRow_lblStatus']</value>
      <webElementGuid>80146d8f-0d23-46a8-af5e-9bb1c6621212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxDebinStatusReceivedsRow_flxStatusContainer']/div[2]/div</value>
      <webElementGuid>d0717ff6-12d1-4871-b9c8-3ee59f39cd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[2]</value>
      <webElementGuid>132f08aa-3ba9-4232-a79c-d07b6c369013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EZ4K6DVNORREPRMN5J8LQ7'])[1]/following::div[7]</value>
      <webElementGuid>21c80cf7-698d-4201-8082-abb129535c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 100,00'])[1]/preceding::div[1]</value>
      <webElementGuid>34280ade-a1a7-4276-8317-d7107814df71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Romero Benjamin Gabriel'])[2]/preceding::div[11]</value>
      <webElementGuid>3c473f38-f117-44e2-83e4-d633343a893a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Acreditado']/parent::*</value>
      <webElementGuid>e981c53b-5e7f-431b-8352-38518792c4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[5]/div/div/div[2]/div</value>
      <webElementGuid>00b41059-8168-4638-9a8e-0d7a7ce5c191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxDebinStatusReceivedsRow_lblStatus' and (text() = 'Acreditado' or . = 'Acreditado')]</value>
      <webElementGuid>d272491b-1d55-4bed-9c40-bde80048867f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
