<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnMontoCero</name>
   <tag></tag>
   <elementGuidId>4f7b1834-5bc7-458f-9abb-c4602778afd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount&quot;)[count(. | //*[@id = 'frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount' and @type = 'text' and @kdisabled = 'false']) = count(//*[@id = 'frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount' and @type = 'text' and @kdisabled = 'false'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da920295-da61-4b5b-9768-577ed9bfc536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount</value>
      <webElementGuid>3861aca1-e9b1-4a3e-976e-c6d50f72efed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>da738740-f767-4ffb-b768-d36172dc0940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAdhereDebin</value>
      <webElementGuid>b2e60951-3aac-453c-953e-413b5081c3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CreateDebinForm_AmountInput</value>
      <webElementGuid>d350b1fb-5d50-4bfd-814c-8f36a8582bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknTbxInputMaskedDebin</value>
      <webElementGuid>ebe23433-63df-4aa2-980e-4959bd56941a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>42ac663b-e62b-487c-b59b-c3eb9a90c41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>872701f8-4b05-4438-b336-c6567ec68af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ab9bd961-c7ff-4d41-8786-97564badd094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c3d93d41-f5e2-4e91-852a-3666e355248b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>8996bff4-83a9-4172-aad2-9f8a78707a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>a5cb283b-f91f-477b-b754-ee14745033bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6aecef1-e87c-46f1-a62e-2984347edcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount&quot;)</value>
      <webElementGuid>f89c1ac1-1a4c-4278-870f-d0b33cee664e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount']</value>
      <webElementGuid>9136f0a8-5865-424b-93d1-600cf1c61282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_CreateDebinForm_AmountInput_flxInputContainer']/div/input</value>
      <webElementGuid>1f4f40a8-6091-4370-9538-24fe8e0524aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>9c861b73-d863-4345-8cb8-6ee4ee0bfce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmAdhereDebin_CreateDebinForm_AmountInput_tbxAmount' and @type = 'text']</value>
      <webElementGuid>8787d066-2b09-4362-8f00-a0f29e8e007d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
