<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnDetalleRecibidosEstado</name>
   <tag></tag>
   <elementGuidId>572e6e40-5cf4-40a4-9a4f-610344fe5e32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d57567c-4482-424a-88a3-3a3aa2d1c9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus</value>
      <webElementGuid>70f7400c-432c-4102-aac9-e12c2fe780f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>ac8011bf-a263-4269-a8ab-63e3b8955d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>dc763fd5-60f3-4809-9ce1-81bf617a1657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinDetailPanel_DebinPaymentDetails</value>
      <webElementGuid>3455a2fa-d91e-4868-8e15-44ee9e18e1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddleleftalign disableSelection</value>
      <webElementGuid>4a7094f5-3ba8-4b50-ab43-8205f713973c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Acreditado</value>
      <webElementGuid>5dfbfaa2-6467-47e1-819d-a79c621a1792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus&quot;)</value>
      <webElementGuid>3bd09aab-3edd-42e3-a6dd-b13afc97057b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus']</value>
      <webElementGuid>c6bc5aa7-5c5c-436e-9461-cf3a99ebe838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_flxStatus']/div/div</value>
      <webElementGuid>c76b06b4-f173-442a-8351-6d2e2a212150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado del DEBIN'])[1]/following::div[8]</value>
      <webElementGuid>875ffef6-7649-48ec-9f16-a7128f172630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear debin test automation'])[1]/following::div[13]</value>
      <webElementGuid>aa90e966-cdf8-4e24-9989-3c874e47c6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[17]/preceding::div[1]</value>
      <webElementGuid>fee73679-5e41-43b6-ae6e-8bbdf35284cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se debitará de tu cuenta'])[1]/preceding::div[3]</value>
      <webElementGuid>f4a8c0f7-cb82-40d9-b045-84273ed7fe5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>76a7bca6-fbb5-4132-9345-a6910ec3455d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus' and (text() = 'Acreditado' or . = 'Acreditado')]</value>
      <webElementGuid>2f62a29d-c396-4cf6-b719-1da1d702142f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
