<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnAliasSolicitud</name>
   <tag></tag>
   <elementGuidId>f4b04c18-d66d-484c-8753-a085685155ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAdhereDebin_BeneficiarySearch_DropDownCommon_flxOptionCommon2lblOptionTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAdhereDebin_BeneficiarySearch_DropDownCommon_flxOptionCommon2lblOptionTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e960a91c-dfe3-40c4-8d38-e0feae7bad8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAdhereDebin_BeneficiarySearch_DropDownCommon_flxOptionCommon2lblOptionTitle</value>
      <webElementGuid>61b719ea-f53a-4d04-ae3e-c7667882b146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>39cc21ef-677c-44fe-acc1-c10387c927ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAdhereDebin</value>
      <webElementGuid>674e09dd-0c8d-4b65-8e20-1fe6733a2a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>BeneficiarySearch_DropDownCommon</value>
      <webElementGuid>b7708564-eb9e-4a0e-9f48-f108a269bab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>7ab65700-7668-45fb-a44a-9d96dfbd2ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alias</value>
      <webElementGuid>c37585c3-4c6c-42e5-99c0-77e27fe7a37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAdhereDebin_BeneficiarySearch_DropDownCommon_flxOptionCommon2lblOptionTitle&quot;)</value>
      <webElementGuid>bbd32ee0-6eda-4c0e-8c56-54248c03129a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_BeneficiarySearch_DropDownCommon_flxOptionCommon2lblOptionTitle']</value>
      <webElementGuid>f0959061-0b14-44ee-986d-d62e0583805f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_BeneficiarySearch_DropDownCommon_flxOptionCommon2flxOptionInfo']/div/div</value>
      <webElementGuid>e5f336eb-6099-41fb-852f-69510d0ff998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/following::div[8]</value>
      <webElementGuid>7a04dae1-007c-4e83-ab25-f9cbf987a537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU'])[2]/following::div[10]</value>
      <webElementGuid>2a49040c-2027-4380-9001-17e9f5629a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[5]/preceding::div[1]</value>
      <webElementGuid>f449d172-4780-4366-9d9c-4f11dbaf92a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Límite disponible para transferir: $ 80.000,00'])[1]/preceding::div[3]</value>
      <webElementGuid>443f70bf-2384-4571-871a-8fd38554a45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alias']/parent::*</value>
      <webElementGuid>b12ac3c1-8e52-4b05-af22-d6f19e21bb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>b43bc4a8-af40-44b0-8897-84fd2121ca52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAdhereDebin_BeneficiarySearch_DropDownCommon_flxOptionCommon2lblOptionTitle' and (text() = 'Alias' or . = 'Alias')]</value>
      <webElementGuid>65c3c837-b0e9-4dee-b19d-6e4f58e5672c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
