<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnListaRecibidosFechaExpiracion</name>
   <tag></tag>
   <elementGuidId>e7915d2c-327d-463c-9c92-a7d381e00ae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxDebinStatusReceivedsRow_lblDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxDebinStatusReceivedsRow_lblDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5e7982f-0e09-4f94-b2ee-5bfd592ed88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxDebinStatusReceivedsRow_lblDate</value>
      <webElementGuid>d93dd70a-98c5-4382-a642-f25a91ce6733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>d2d0d5be-0874-4613-94a6-ab709548dc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxDebinStatusReceivedsRow</value>
      <webElementGuid>2228d3b9-aaa8-45c3-87f9-707b62fa792f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segReceiveds</value>
      <webElementGuid>6d38dec5-b392-4d7b-b6c4-c20c4371612a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>0A17BFF2-9031-46C6-A0CD-FF5E5D7FD33E</value>
      <webElementGuid>2572a2fb-7e24-452b-9820-e85158a8478b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddleleftalign disableSelection</value>
      <webElementGuid>3a58f0d5-75e0-48ee-ae84-ccf294362c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24 May 2023 - 14:00</value>
      <webElementGuid>7a98e187-5a09-4bec-a3b1-62af6adf20ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_segReceiveds&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinStatusReceivedsRow_flxDebinStatusReceivedsRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinStatusReceivedsRow_flxDateTimeContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxDebinStatusReceivedsRow_lblDate&quot;]</value>
      <webElementGuid>2efe02d6-c95a-44c2-967e-ef1d067fa3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxDebinStatusReceivedsRow_lblDate']</value>
      <webElementGuid>bb897926-8d29-4e4b-be61-a6beea2161ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxDebinStatusReceivedsRow_flxDateTimeContainer']/div/div</value>
      <webElementGuid>b2ece72c-5648-4ec2-ba69-4d8450217b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[1]/following::div[12]</value>
      <webElementGuid>8f9734d9-e440-4242-acb5-d1ff1ab9240d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[2]/following::div[14]</value>
      <webElementGuid>346e90e5-cc07-474a-98e7-489cb9fb5f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Romero Benjamin Gabriel'])[1]/preceding::div[1]</value>
      <webElementGuid>b06a95f9-df44-4bb3-94d1-0b1e61fe9ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alquiler'])[1]/preceding::div[3]</value>
      <webElementGuid>549c41b8-1cc3-43b0-8497-9c5eb769d87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24 May 2023 - 14:00']/parent::*</value>
      <webElementGuid>f5d4e315-3e98-442d-a166-964e763d23b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div/div/div/div/div</value>
      <webElementGuid>61b587ad-c746-410a-bf14-d2e6f08959e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxDebinStatusReceivedsRow_lblDate' and (text() = '24 May 2023 - 14:00' or . = '24 May 2023 - 14:00')]</value>
      <webElementGuid>c16c9c84-6da5-4ea1-aae7-4ee81446387e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
