<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnDuracionHoras</name>
   <tag></tag>
   <elementGuidId>122c5036-9f87-487d-860d-f618eac957c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAdhereDebin_CreateDebinForm_DropDownDuration_flxOptionCommon4lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAdhereDebin_CreateDebinForm_DropDownDuration_flxOptionCommon4lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c3e94219-4bce-461d-a285-364fb4019096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAdhereDebin_CreateDebinForm_DropDownDuration_flxOptionCommon4lblOptionTitle</value>
      <webElementGuid>30a04af7-5db0-438b-bca5-3bd1259499f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>d2f42aa5-51c8-450d-a4d2-de3e069433ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAdhereDebin</value>
      <webElementGuid>64cdbe45-b2e2-4bba-8bf0-f1b3ba2167a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CreateDebinForm_DropDownDuration</value>
      <webElementGuid>a06d30e6-c2c0-4679-9ced-3c0f58a25191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountTitleDropDown cntmiddleleftalign disableSelection</value>
      <webElementGuid>e449fac7-15ea-4c0e-abf2-3be020d9f042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8 horas</value>
      <webElementGuid>ede6c5fe-124a-4bc5-9f65-91c797debc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAdhereDebin_CreateDebinForm_DropDownDuration_flxOptionCommon4lblOptionTitle&quot;)</value>
      <webElementGuid>04123d21-6734-4d12-ba3c-2e3fab30213e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_CreateDebinForm_DropDownDuration_flxOptionCommon4lblOptionTitle']</value>
      <webElementGuid>6b99ac3b-e5f5-43de-98b9-c817652f82b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_CreateDebinForm_DropDownDuration_flxOptionCommon4flxOptionInfo']/div/div</value>
      <webElementGuid>b3ff692f-12eb-423e-b53f-b80ff438ad1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[9]/following::div[8]</value>
      <webElementGuid>7629968c-2ae4-4abc-9cc9-2059f8e2a46e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[8]/following::div[18]</value>
      <webElementGuid>e55db96b-c750-4108-a694-956935e1effa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[10]/preceding::div[1]</value>
      <webElementGuid>46cb7554-3037-47a5-9743-ae54599963cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[11]/preceding::div[8]</value>
      <webElementGuid>4eebf1a0-10a2-440e-8224-954863335ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/div/div/div/div/div</value>
      <webElementGuid>e5816892-f24d-4809-b4ec-b89652fd8b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAdhereDebin_CreateDebinForm_DropDownDuration_flxOptionCommon4lblOptionTitle' and (text() = '8 horas' or . = '8 horas')]</value>
      <webElementGuid>854ff8ba-29df-4548-91e7-5e3925fed396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
