<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnConsultarEstadoCuentasTodas</name>
   <tag></tag>
   <elementGuidId>ddab1938-9c49-4004-a159-5f65779d090b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon1lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon1lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>94b6596c-9ddc-4573-8bfb-6de362a6de65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon1lblOptionTitle</value>
      <webElementGuid>c3f1812b-863f-4890-bf63-dc4cab8d2395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>a1cf9da5-04e5-4c8a-80fb-44e7fbc38c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>ca5255b8-3ee8-46fc-b359-78c540d728ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinStatusFilters_DropDownAccounts</value>
      <webElementGuid>37d33a63-9243-4542-83cb-dfaee0167dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>ba5965f4-9d5e-4305-935d-6eeda0a8ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Todas</value>
      <webElementGuid>328a874b-636a-4595-b2f4-1f8217edc3b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon1lblOptionTitle&quot;)</value>
      <webElementGuid>9c1df269-d0c3-4e2d-8c93-2d8249c61a62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon1lblOptionTitle']</value>
      <webElementGuid>1ec75218-9fbc-4f0a-8339-b5cbc8bf1cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon1flxOptionInfo']/div/div</value>
      <webElementGuid>2fbf4440-2a95-464e-9389-ab620454425d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/following::div[10]</value>
      <webElementGuid>8622d81d-f474-4b7d-a690-270d94ee6a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todas'])[1]/following::div[12]</value>
      <webElementGuid>95d81f04-7f84-415b-8820-f59b8183b70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/preceding::div[1]</value>
      <webElementGuid>ea872f6f-d636-4736-a414-8f467ae3d0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 119-011835/9'])[1]/preceding::div[3]</value>
      <webElementGuid>f354f164-f6d2-4c57-aee1-97a97aa37da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>fe35c6c9-929c-493b-90d5-f68b0c4ada96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon1lblOptionTitle' and (text() = 'Todas' or . = 'Todas')]</value>
      <webElementGuid>a606a6f1-0ec7-4415-9e9c-f2be95c26bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
