<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnNoTitular</name>
   <tag></tag>
   <elementGuidId>0dd4405c-fcd1-458a-8807-411f2b203af2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAdhereDebin_CreateDebinForm_DropDownOwnership_flxOptionCommon3lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAdhereDebin_CreateDebinForm_DropDownOwnership_flxOptionCommon3lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3944ebf1-429c-4e2d-a1a3-ac29892a36a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAdhereDebin_CreateDebinForm_DropDownOwnership_flxOptionCommon3lblOptionTitle</value>
      <webElementGuid>7522487e-99db-4208-bad6-038876c6c835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0eeb8601-0aa7-4a71-a2e5-86f6f05baae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAdhereDebin</value>
      <webElementGuid>6e201662-2521-4959-bde1-a388333d021c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CreateDebinForm_DropDownOwnership</value>
      <webElementGuid>a06f2c0c-ce8a-4027-9f21-de1b2f6e474c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountTitleDropDown cntmiddleleftalign disableSelection</value>
      <webElementGuid>f96a1704-87f7-48ca-ae94-99f68c6eb7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No soy titular</value>
      <webElementGuid>8e44d404-fd65-4e61-b5d0-e3639302c12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAdhereDebin_CreateDebinForm_DropDownOwnership_flxOptionCommon3lblOptionTitle&quot;)</value>
      <webElementGuid>40965a95-6dd1-487b-b22c-72f2fd0faca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_CreateDebinForm_DropDownOwnership_flxOptionCommon3lblOptionTitle']</value>
      <webElementGuid>0308a069-ba7c-474b-8810-b8bdbdb8d4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAdhereDebin_CreateDebinForm_DropDownOwnership_flxOptionCommon3flxOptionInfo']/div/div</value>
      <webElementGuid>fdf6dc56-a6e6-4189-b611-d1aac498a77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[36]/following::div[8]</value>
      <webElementGuid>cb6b3350-5e63-40c7-956b-0293c47d652b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Soy titular'])[1]/following::div[10]</value>
      <webElementGuid>5ed6ec8d-13c1-439c-98c0-32a85ff8393e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[37]/preceding::div[1]</value>
      <webElementGuid>674f9b16-d04e-40d9-91b1-f931eff29a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tengo titularidad compartida'])[1]/preceding::div[3]</value>
      <webElementGuid>a7307ef2-5b56-42ec-adfe-a615898c79a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No soy titular']/parent::*</value>
      <webElementGuid>6e4208e7-f7fa-4881-9a9e-6f7d909f430e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>2610a145-56da-4072-a16b-a9efea9f586d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAdhereDebin_CreateDebinForm_DropDownOwnership_flxOptionCommon3lblOptionTitle' and (text() = 'No soy titular' or . = 'No soy titular')]</value>
      <webElementGuid>2cd9f8d6-dd63-439b-b23e-3cfd050e1eb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
