<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnDetalleRecibidosConcepto</name>
   <tag></tag>
   <elementGuidId>78ee961e-edcb-4cf0-b1f3-6fe40deb3b64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblConcept']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblConcept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>382649d2-33f4-4481-aa30-fc8a0bda2a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblConcept</value>
      <webElementGuid>1132cd34-c32d-4584-9517-697dcc6d9002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>3e5257a2-505c-4078-ae1f-c9b6ed1c5c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>8d0182be-9470-425b-9644-650882d33a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinDetailPanel_DebinPaymentDetails</value>
      <webElementGuid>69b5ee03-f4e5-4fd1-8642-4dcb2d416e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblPanelProductRowData cntmiddlerightalign disableSelection</value>
      <webElementGuid>642f36c1-7961-454a-9615-bf9b5c308348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alquiler</value>
      <webElementGuid>d1c9ed50-3295-442e-95c4-bfaf79badc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblConcept&quot;)</value>
      <webElementGuid>39625484-7721-4645-a311-556f729e2937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblConcept']</value>
      <webElementGuid>3bc7effb-2673-41c5-b657-80cdb04e1344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_flxConceptContainer']/div[2]/div</value>
      <webElementGuid>a5eadd3d-1342-46cf-9351-a7b748018794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[3]/following::div[2]</value>
      <webElementGuid>10bb551a-6c7f-4d98-b769-4db955431c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de expiración'])[3]/following::div[9]</value>
      <webElementGuid>712f86e1-4071-46c3-9e78-c466cb6eabc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[1]/preceding::div[1]</value>
      <webElementGuid>ac08cb6b-720b-4243-976c-3af245b87fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crear debin test automation'])[1]/preceding::div[3]</value>
      <webElementGuid>a922326b-8c2f-4b76-8166-6894634912f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[7]/div/div/div[2]/div</value>
      <webElementGuid>0681c4db-5611-44da-88a6-6bbd059fe886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblConcept' and (text() = 'Alquiler' or . = 'Alquiler')]</value>
      <webElementGuid>c8314530-8019-4538-9801-cf525c60ea62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
