<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnConsultaDebinEstadoEstados</name>
   <tag></tag>
   <elementGuidId>e63b3538-8aa3-4d8d-bbca-27164914c704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon3lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon3lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8925c431-e095-4a5d-93c2-a3d2fcba9b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon3lblOptionTitle</value>
      <webElementGuid>cec693c5-3db5-402f-a05d-21a7de8b7ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>b886a2f1-1f6d-4648-8e17-6a0d43878d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>0a44cdee-a180-41b7-80c9-41d45ed51971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinStatusFilters_DropDownStatus</value>
      <webElementGuid>a3248839-d23a-4bb9-be8e-c7d6862738ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountTitleDropDown cntmiddleleftalign disableSelection</value>
      <webElementGuid>ebe18f1a-3268-4cfd-8081-469bd4ce682b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pagados</value>
      <webElementGuid>0f9cc746-a07b-4bcb-80a6-b5a855024b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon3lblOptionTitle&quot;)</value>
      <webElementGuid>3696632a-bfe1-44a6-ae10-86723bfa0990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon3lblOptionTitle']</value>
      <webElementGuid>af3952fb-a2ca-4695-a02f-01e4ee805ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon3flxOptionInfo']/div/div</value>
      <webElementGuid>0185289a-76c6-4428-8f15-d11bd55a7f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[12]/following::div[8]</value>
      <webElementGuid>4372f6f3-97c3-4b6b-bfbd-d9f189b2dd7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendientes'])[1]/following::div[10]</value>
      <webElementGuid>d213376b-8d2b-45c9-aed3-200d93bcaed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[13]/preceding::div[1]</value>
      <webElementGuid>436a601c-c925-460f-abbf-97a7108c5119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vencidos'])[1]/preceding::div[3]</value>
      <webElementGuid>c34f0465-c133-4818-b223-64790f6ae143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pagados']/parent::*</value>
      <webElementGuid>53f10013-9b53-4597-ae90-b93ae1532f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>5aabac13-0819-4ac0-8123-e8cd01ebb929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinStatusFilters_DropDownStatus_flxOptionCommon3lblOptionTitle' and (text() = 'Pagados' or . = 'Pagados')]</value>
      <webElementGuid>263a827b-a77f-4afb-99e4-f491c829647e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
