<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnConsultarEstadoCuenta</name>
   <tag></tag>
   <elementGuidId>780a1407-9f2a-447a-a2a9-e3929a70c604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon2lblOptionTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon2lblOptionTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25cfa0c0-f839-4545-a2d3-0a9903c23237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon2lblOptionTitle</value>
      <webElementGuid>114c7480-4ed2-4f48-8961-466fd4b6b637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>af5df66c-eb00-48a2-a3d0-1cea03a8a652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>1dce8e54-90b3-4e94-8795-fbdcdf87ca60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinStatusFilters_DropDownAccounts</value>
      <webElementGuid>90944cc2-ed97-4430-b2a5-10ecebe7c3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknLblAccountTitleDropDown cntmiddleleftalign</value>
      <webElementGuid>f9bf00ec-91c2-4f61-8372-dad33d2a76c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA $ 119-011835/9</value>
      <webElementGuid>cf1647e8-ac9b-42fa-8bb2-474015f09922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon2lblOptionTitle&quot;)</value>
      <webElementGuid>39407885-3264-427f-80a0-9a3c5467ae51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon2lblOptionTitle']</value>
      <webElementGuid>2d448fa5-7f3a-4357-8710-dca70996ca45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon2flxOptionInfo']/div/div</value>
      <webElementGuid>c5b24f4a-a8c9-4ea2-809a-41b48266aaa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/following::div[8]</value>
      <webElementGuid>55853a1c-693e-47ac-ba72-63b17f97cbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Todas'])[2]/following::div[10]</value>
      <webElementGuid>46371b66-a5c2-4c52-a529-f83fd269ef5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[5]/preceding::div[1]</value>
      <webElementGuid>b94a4a66-22e3-4079-86ea-c6bc48dc7310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA U$S 119-011835/9'])[1]/preceding::div[3]</value>
      <webElementGuid>f1967477-988e-4b37-a40b-28f5858a5aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA $ 119-011835/9']/parent::*</value>
      <webElementGuid>a0928264-5cc1-4619-9515-a5670a361942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>2346d8c3-d33d-4f14-a9be-f6755d99d1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinStatusFilters_DropDownAccounts_flxOptionCommon2lblOptionTitle' and (text() = 'CA $ 119-011835/9' or . = 'CA $ 119-011835/9')]</value>
      <webElementGuid>9eae303b-c0e9-4f7d-88cf-29c25ff8b5d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
