<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnDetalleRecibidosMonto</name>
   <tag></tag>
   <elementGuidId>ca6188d7-f77c-4cae-a42e-8afe9555b9ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7a6774f-9d9e-4d61-8ed5-5e3bf21ef011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount</value>
      <webElementGuid>7e5a1c5d-bf25-4c22-ab96-9a2c3103b1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>4aa47d3c-028f-44b5-8424-e7119da5728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>f9b053a4-4197-4670-b2da-05fdea07e92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinDetailPanel_DebinPaymentDetails</value>
      <webElementGuid>adc24a8d-8cc6-4283-8a80-16e44e665214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblPanelProductRowData cntmiddlerightalign disableSelection</value>
      <webElementGuid>349bc7a3-6a10-47ce-86b2-5c4d12a161bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 100,00</value>
      <webElementGuid>d1de834a-8226-4eb9-8e22-6379b26935f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount&quot;)</value>
      <webElementGuid>f33cea4b-2fdc-4873-acb1-251e473bea30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount']</value>
      <webElementGuid>1e3c9c3d-4496-43d7-b092-197d9e93eec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_flxAmountContainer']/div[2]/div</value>
      <webElementGuid>abdb6042-5b2e-4230-8df3-a7b134a4c858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[3]/following::div[2]</value>
      <webElementGuid>b592a563-c2f7-47bb-bcf6-a0f0d8b318e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEBIN solicitado por ROMERO BENJAMIN GABRIEL'])[1]/following::div[16]</value>
      <webElementGuid>c47000ed-82c4-4246-9e11-101ff84dbe84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número'])[3]/preceding::div[1]</value>
      <webElementGuid>fab4a03d-a42c-4d99-ad34-f80555dda7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EZ4K6DVNORREPRMN5J8LQ7'])[2]/preceding::div[3]</value>
      <webElementGuid>878dd668-1700-40dd-a8d0-ba19bb54a43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>6a079f8c-8612-48f6-b5af-c9fe4fb4145c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount' and (text() = '$ 100,00' or . = '$ 100,00')]</value>
      <webElementGuid>6cb388f5-4769-41a7-bf5e-a88c6cc6d1bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
