<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnDetalleGeneradosMonto</name>
   <tag></tag>
   <elementGuidId>e973f571-f4dc-482a-9c1d-9e26065320bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95a4bb54-7d26-4015-928b-9ec968142db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount</value>
      <webElementGuid>bc489b0e-5734-4579-a2cd-32de7e09be0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>ad2ba82b-6980-45bc-a8e4-9ad5f5c42bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>e97c9aa9-5b44-4eb7-a5f1-b4be4b91a85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinDetailPanel_DebinPaymentDetails</value>
      <webElementGuid>c7513a33-c1a1-4feb-8d78-aacf62874463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblPanelProductRowData cntmiddlerightalign disableSelection</value>
      <webElementGuid>10b69846-e116-4111-b71e-8feb4f24b746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 4,00</value>
      <webElementGuid>62a60c9f-c9be-4789-bacc-ea8843fa525f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount&quot;)</value>
      <webElementGuid>5eaba898-9885-430c-9768-573735b51fd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount']</value>
      <webElementGuid>8ab9bd82-6756-4895-ba48-8b9054ea4a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_flxAmountContainer']/div[2]/div</value>
      <webElementGuid>a955f3a0-02c7-4615-a4fb-6914bfc86bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[3]/following::div[2]</value>
      <webElementGuid>a8409ed6-26c8-4dcb-96ef-2200d9b8ba34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEBIN solicitado a ENRICO EDIE AGUSTIN'])[1]/following::div[16]</value>
      <webElementGuid>ed12a8f3-14b1-4fbf-be1e-174ec50ad443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número'])[3]/preceding::div[1]</value>
      <webElementGuid>171071c0-5986-4ab0-bd6f-10b56257b7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WZ0KV8794OOVYXE9PEYDX4'])[2]/preceding::div[3]</value>
      <webElementGuid>dfb36bff-9e80-4d48-9932-d543fecb38ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>f1147eb5-8546-4862-ae26-948834f4b572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblAmount' and (text() = '$ 4,00' or . = '$ 4,00')]</value>
      <webElementGuid>3728149d-8244-4d00-ba4e-9288576c60ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
