<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnListaRecibidosConcepto</name>
   <tag></tag>
   <elementGuidId>3230885b-c1ea-4d8e-b16d-2c06d40f9530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxDebinStatusReceivedsRow_lblConcept']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxDebinStatusReceivedsRow_lblConcept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8660ef79-2279-4d5f-b541-766df26ffe96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxDebinStatusReceivedsRow_lblConcept</value>
      <webElementGuid>82870fad-151e-4d18-8e1a-1b4b81564d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>dac327dc-665e-424a-8ef0-2a765017f54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxDebinStatusReceivedsRow</value>
      <webElementGuid>5a2a78ce-fabc-4ba1-b29c-39bba54ab3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segReceiveds</value>
      <webElementGuid>ca099dd8-9cd3-44d2-a2fc-e86f69467f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>63BFDB7F-FA2C-40DF-B491-DFE6BED5B87D</value>
      <webElementGuid>87ebe0e3-e69d-41f2-9326-47bef3bec1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddleleftalign disableSelection</value>
      <webElementGuid>dc9ce6ee-d933-46ab-be5c-a27b776e70c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alquiler</value>
      <webElementGuid>3885c7b1-101f-40e2-9aca-783ff080ddf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_segReceiveds&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxDebinStatusReceivedsRow_flxDebinStatusReceivedsRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxDebinStatusReceivedsRow_lblConcept&quot;]</value>
      <webElementGuid>e4e0e28a-9cf7-4880-b2ee-519d4842658a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxDebinStatusReceivedsRow_lblConcept']</value>
      <webElementGuid>529e09fe-706d-4069-b26b-e2ebe9d48ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxDebinStatusReceivedsRow_flxDebinStatusReceivedsRow']/div[3]/div</value>
      <webElementGuid>c912c564-89ef-41d9-b4b1-aa13ac63021f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Romero Benjamin Gabriel'])[1]/following::div[2]</value>
      <webElementGuid>f920e6e8-5fdc-492c-a6e0-0cd654493c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[1]/following::div[16]</value>
      <webElementGuid>029f3de3-0c6a-46da-8940-0eeb323ec4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EZ4K6DVNORREPRMN5J8LQ7'])[1]/preceding::div[1]</value>
      <webElementGuid>f29af4e6-7634-4f92-9338-3fa8ff282b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[6]</value>
      <webElementGuid>5d13b6fc-03dc-470d-8f1c-54ccb14a0a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alquiler']/parent::*</value>
      <webElementGuid>04d28c28-fa55-41e8-be76-8b83af9a1648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div[3]/div</value>
      <webElementGuid>3e000118-a138-431d-8f89-46f78be3ab8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxDebinStatusReceivedsRow_lblConcept' and (text() = 'Alquiler' or . = 'Alquiler')]</value>
      <webElementGuid>39b98105-56a3-4225-9e9b-fc9df146516d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
