<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnConsultarDebinPorEstadoCuenta</name>
   <tag></tag>
   <elementGuidId>a947f341-0b1b-4ec8-89f1-3c6e57e31dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinPaymentsHomeBccl_CFloatingMenu_lbldebinStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinPaymentsHomeBccl_CFloatingMenu_lbldebinStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab2ce80e-2672-432a-99ca-e938eda9d535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl_CFloatingMenu_lbldebinStatus</value>
      <webElementGuid>283170a7-4ce0-4f37-919a-9071333d8215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>04e24a41-e2df-45bb-aa3a-42a8392d3b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinPaymentsHomeBccl</value>
      <webElementGuid>0f021007-3266-475a-b2e9-565280b91a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CFloatingMenu</value>
      <webElementGuid>9c5832fd-e6ee-4776-8913-5f5d1a5bac89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblOptionFloatMenu cntmiddleleftalign disableSelection</value>
      <webElementGuid>4fe8f638-ef55-4526-b8e1-658891ee392b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consultar DEBIN por estado</value>
      <webElementGuid>b6f36be1-8c58-4b35-9279-457b648347b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinPaymentsHomeBccl_CFloatingMenu_lbldebinStatus&quot;)</value>
      <webElementGuid>15d86113-6fec-4a20-9fa4-34c69a08fa49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinPaymentsHomeBccl_CFloatingMenu_lbldebinStatus']</value>
      <webElementGuid>f0b732c9-78b4-4da0-bc9a-5807d3e593d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinPaymentsHomeBccl_CFloatingMenu_flxdebinStatus']/div/div</value>
      <webElementGuid>d1766f7f-c79f-433b-8678-ec0593ac53e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[8]</value>
      <webElementGuid>4a77125d-4b75-4b62-9b2f-bb35831387f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[43]/following::div[17]</value>
      <webElementGuid>2f33e1c8-9969-482a-843b-748437fa54ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[3]</value>
      <webElementGuid>fbdb7329-8bce-476b-88b9-b9a0b6b8b3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[5]</value>
      <webElementGuid>82ee0a15-cb8e-400f-8b3d-84b6794e58b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consultar DEBIN por estado']/parent::*</value>
      <webElementGuid>2aae7d28-f608-4e53-afc1-6a1bab2275d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>d1cc75dc-e2db-4a7c-b86e-92599b5815b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinPaymentsHomeBccl_CFloatingMenu_lbldebinStatus' and (text() = 'Consultar DEBIN por estado' or . = 'Consultar DEBIN por estado')]</value>
      <webElementGuid>71f38dd5-8fd5-4925-822a-513d4b01d51d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
