<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtDbnConsultaEstadoDetalleVencido</name>
   <tag></tag>
   <elementGuidId>21c6fea7-5d0f-40d4-82c0-2fbce36f4af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9cbd88a-97c3-41ff-a98d-ae8395d20c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus</value>
      <webElementGuid>36507ccc-456a-4d81-aa0b-a8c94b480430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f6efb6d8-c839-48ae-b088-03ffe9dc44e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinStatusBccl</value>
      <webElementGuid>48ebbcf9-fc40-4724-beb9-6ee3e515489c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>DebinDetailPanel_DebinPaymentDetails</value>
      <webElementGuid>3c3d71a1-3811-4de1-9597-e83bc4b00819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddleleftalign disableSelection</value>
      <webElementGuid>978551bd-c1c4-4a3a-93dc-028744cde0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vencido</value>
      <webElementGuid>29c987cd-24fb-4e3b-99bb-0239744fd9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus&quot;)</value>
      <webElementGuid>ded95ff0-61fc-450d-a5a2-91a0928f339e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus']</value>
      <webElementGuid>286400f5-12f8-440c-93ae-089aea091e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_flxStatus']/div/div</value>
      <webElementGuid>5fb2b285-fe5c-4ce3-b9db-dc6037ba7d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado del DEBIN'])[1]/following::div[8]</value>
      <webElementGuid>5798ca1d-64fb-465d-987e-f1da6561c646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--'])[1]/following::div[13]</value>
      <webElementGuid>0eeb8d92-edc6-46f0-9996-fa4a69496323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[8]/preceding::div[1]</value>
      <webElementGuid>e6b0d1c3-3b5f-4273-8725-09965c5f7055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se debitará de tu cuenta'])[1]/preceding::div[3]</value>
      <webElementGuid>ae91999e-27c7-46ad-a829-2b1752513700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>f50cf946-aec9-46d2-b12c-14ab14698322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinStatusBccl_DebinDetailPanel_DebinPaymentDetails_lblStatus' and (text() = 'Vencido' or . = 'Vencido')]</value>
      <webElementGuid>9ad1c265-ef3d-4fbc-a369-23c85c774d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
