<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPopUpDesadherirDEBIN</name>
   <tag></tag>
   <elementGuidId>7e74c424-b228-42ae-b26e-0d67bcbd8bd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmDebinAdhesionBccl_ConfirmPopup_lblHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmDebinAdhesionBccl_ConfirmPopup_lblHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>05d703db-0d98-4cc6-a5d8-03f0ed9f0ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmDebinAdhesionBccl_ConfirmPopup_lblHeading</value>
      <webElementGuid>39636ffd-e495-45f6-99e2-91c024b254e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e3a63991-b96b-4d19-84fd-e5fafa5cd0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmDebinAdhesionBccl</value>
      <webElementGuid>6af74567-78e6-46dd-854e-db1cbefabe2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ConfirmPopup</value>
      <webElementGuid>94b5b67c-48b1-430e-a145-3bd80d37515e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblPopupHeading cntmiddleleftalign disableSelection</value>
      <webElementGuid>2842245d-870f-4794-9c27-df572a78d5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desadherir DEBIN</value>
      <webElementGuid>25fff4d1-d8eb-452b-88c2-4c106dc551de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmDebinAdhesionBccl_ConfirmPopup_lblHeading&quot;)</value>
      <webElementGuid>35500068-5016-4074-ba6a-dcc779bfc9b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmDebinAdhesionBccl_ConfirmPopup_lblHeading']</value>
      <webElementGuid>f73d694f-7a5e-4637-8518-b0d2c52c9c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmDebinAdhesionBccl_ConfirmPopup_flxHeader']/div/div</value>
      <webElementGuid>590ec0b4-ec5e-4dd1-9c37-fea953169240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[14]</value>
      <webElementGuid>da1a7147-1114-45a8-ad42-ac83a17de89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[26]</value>
      <webElementGuid>2c056b36-128d-479b-85dc-1fa843fc486a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[5]/preceding::div[1]</value>
      <webElementGuid>60d411e4-8fd1-4a94-9a63-d0e00dce0a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Estás seguro que querés desadherir la cuenta CA$119-011835/9 de Pagos DEBIN?'])[1]/preceding::div[9]</value>
      <webElementGuid>e1e20799-74a1-452f-a7d2-c6b40a4f85ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Desadherir DEBIN']/parent::*</value>
      <webElementGuid>ae9179b3-2705-49a5-99f2-29bb2e567a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>6ef7a4f1-2da5-4634-9da2-57f31db1fb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmDebinAdhesionBccl_ConfirmPopup_lblHeading' and (text() = 'Desadherir DEBIN' or . = 'Desadherir DEBIN')]</value>
      <webElementGuid>dd0d235a-3cc3-4b66-af1c-4358d9120989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
