<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnInvPFConfirmar</name>
   <tag></tag>
   <elementGuidId>722da481-d17b-4ad9-ba9e-8a2b4e8ef51d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmConfirmFixedTermBccl_btnConfirm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmConfirmFixedTermBccl_btnConfirm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7375454-32a5-4512-88c8-148b78ec153e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl_btnConfirm</value>
      <webElementGuid>f37bdd97-e2a8-4547-a129-6cd94a4bf82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>7b276cbd-ebf0-4ee9-bfb1-bde90488b4a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl</value>
      <webElementGuid>53e5993a-1dd6-4957-ad88-397b3b2875c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc304b94-d032-4467-8fcb-05965806e91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>eaa65643-8df8-4421-a4b6-683e72691552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>753f8f0e-c3aa-4c72-9bba-0b1571163e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>04c82c85-4b71-4630-80e0-ea4f4c13a320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfirmFixedTermBccl_btnConfirm&quot;)</value>
      <webElementGuid>c2b6acbb-457e-4f66-9f29-4d8e08e3e259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmConfirmFixedTermBccl_btnConfirm']</value>
      <webElementGuid>9e410052-b7b5-4a65-b2f8-b565542593ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmConfirmFixedTermBccl_flxBtns']/div[2]/input</value>
      <webElementGuid>a36fd3ef-2ed0-4ec0-9875-fe20304b16c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>32283b66-cc62-4f34-bb98-61036c6f2e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmConfirmFixedTermBccl_btnConfirm' and @type = 'button']</value>
      <webElementGuid>abac281a-ce61-4035-bdcb-a8c22ea7d806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
