<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnInvPFConfirmarBypass</name>
   <tag></tag>
   <elementGuidId>0ed1e569-0a07-4c9a-a828-8554ed990f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmConfirmFixedTermBccl_SecondFactor_ButtonConfirm_btnWithLoader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmConfirmFixedTermBccl_SecondFactor_ButtonConfirm_btnWithLoader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a3a0627-c3fa-480f-9280-cad9d86625a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Log in </value>
      <webElementGuid>4aa62154-3b76-4007-9f88-e62ee491cb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl_SecondFactor_ButtonConfirm_btnWithLoader-hint</value>
      <webElementGuid>c76065be-adcc-4b6a-a973-89ca76a612ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl_SecondFactor_ButtonConfirm_btnWithLoader</value>
      <webElementGuid>d4ce541c-2919-4234-81a2-342cd01af84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>68902c1a-da4e-4db5-b9b7-7c3aa37ca73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl</value>
      <webElementGuid>4d85bf74-4790-41cd-bab0-356c2f95694b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>SecondFactor_ButtonConfirm</value>
      <webElementGuid>40c60894-1697-4d07-90f1-f42c3ed2462c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e18447e7-392a-4cee-a0bb-0b10f4e63a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknBtnPrimary disableSelection</value>
      <webElementGuid>7b48b57e-5ab4-47cb-b21d-b743bbd60d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirmar</value>
      <webElementGuid>9f4bb86f-89c3-4915-9966-5f54edbf68c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimary</value>
      <webElementGuid>e5108e0f-ab2b-4160-92e4-da92d03839fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfirmFixedTermBccl_SecondFactor_ButtonConfirm_btnWithLoader&quot;)</value>
      <webElementGuid>b2221822-f53c-4575-9737-b528bcfd9c94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmConfirmFixedTermBccl_SecondFactor_ButtonConfirm_btnWithLoader']</value>
      <webElementGuid>8a970fc9-38f1-4831-8ec1-556230c9ecc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmConfirmFixedTermBccl_SecondFactor_ButtonConfirm']/div/input</value>
      <webElementGuid>31ff5411-9357-4131-90d4-e97cd962881d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>0eb2db42-9eea-4660-b3eb-f1d43f95962e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmConfirmFixedTermBccl_SecondFactor_ButtonConfirm_btnWithLoader' and @type = 'button']</value>
      <webElementGuid>50ecb1dd-3e1b-4622-bf48-4cb580099413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
