<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chqbxInvPFDeclaracionJurada</name>
   <tag></tag>
   <elementGuidId>3b212938-6ee5-407a-b40b-db6a95a75b42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmConfirmFixedTermBccl_CheckboxWithValidation_flxCustomCheckbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmConfirmFixedTermBccl_CheckboxWithValidation_flxCustomCheckbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0db95bed-f63a-43f8-9a61-59dee65f702d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  sknFlxCustomCheckbox </value>
      <webElementGuid>d0311cd3-acce-40d1-a29b-0a1a2c24a716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl_CheckboxWithValidation_flxCustomCheckbox</value>
      <webElementGuid>3a569034-2a0a-4873-bba2-0dd96e7307b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>01209f5b-d575-4c32-bb89-532c4304b6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl</value>
      <webElementGuid>779564d2-3069-4bd6-b2c5-94d0a45ad6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CheckboxWithValidation</value>
      <webElementGuid>fdd03382-c0dd-4330-8fb9-aac6f8fe8248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>63a72153-2ae6-453b-a104-5b39358c4dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfirmFixedTermBccl_CheckboxWithValidation_flxCustomCheckbox&quot;)</value>
      <webElementGuid>18c7177e-364d-47c8-91ad-c75773899de3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmConfirmFixedTermBccl_CheckboxWithValidation_flxCustomCheckbox']</value>
      <webElementGuid>555e5a23-6c88-4871-972f-2abadb62dc3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[306]</value>
      <webElementGuid>872539bd-c483-4577-a18a-3f93cbc837e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[34]</value>
      <webElementGuid>a44d3c6b-50b0-4591-bc88-1080635f6d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[6]/following::div[36]</value>
      <webElementGuid>c11d3e21-f205-40d7-9994-6baea0c467ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[7]/preceding::div[5]</value>
      <webElementGuid>9c32ae11-6def-4046-8f24-945ae61de67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>60a9be0b-0ab2-454a-9b39-7c8c422ecc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmConfirmFixedTermBccl_CheckboxWithValidation_flxCustomCheckbox' and (text() = '' or . = '')]</value>
      <webElementGuid>1e8da966-c861-4b4e-8dbe-050c4400e370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
