<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoCtaDetalleCerrar</name>
   <tag></tag>
   <elementGuidId>444c71e6-6152-414a-820a-3939cde042ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsDetailsBccl_Panel_lblCloseIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsDetailsBccl_Panel_lblCloseIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6d14c14-24eb-4bbf-85d9-93a619239401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl_Panel_lblCloseIcon</value>
      <webElementGuid>72dd9354-d20c-41b3-aae2-ea958480b941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0757f347-35fe-4c38-9923-3cc04656232e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl</value>
      <webElementGuid>6045ae72-07c0-4a37-a144-9b56e47be8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Panel</value>
      <webElementGuid>99b30847-e45c-4903-bdb7-c3926b8530c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cntmiddlecenteralign disableSelection sknLblPanelCloseIcon</value>
      <webElementGuid>1c650f84-2cea-4d1a-80ed-e9d4e5f3d14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>3ce99a02-6db4-4c27-b05d-ef31bf9c43f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_Panel_lblCloseIcon&quot;)</value>
      <webElementGuid>1aa69812-0c62-4793-aef7-8e0a757a7f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_Panel_lblCloseIcon']</value>
      <webElementGuid>c603d510-996e-40be-a5fd-d3dcfc20c9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_Panel_flxCloseIcon']/div/div</value>
      <webElementGuid>d30d7394-d88a-419c-b476-37fd148be492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El máximo permitido es 50 caracteres'])[1]/following::div[33]</value>
      <webElementGuid>fe12db82-ba90-4f1f-9d64-f2bd2aabaa30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Máximo 50 caracteres'])[1]/following::div[35]</value>
      <webElementGuid>51de410f-5f01-4530-a850-922be8723afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>e4bbe0a2-7942-4899-8d69-74c496fb9158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle de Movimiento'])[1]/preceding::div[9]</value>
      <webElementGuid>c4dc4722-1124-451e-b3bb-6ce3ebfefa8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>a9f8e3fe-d525-4fa2-ae1e-2b69f2327a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsDetailsBccl_Panel_lblCloseIcon' and (text() = '' or . = '')]</value>
      <webElementGuid>0a01fb88-b451-4ef6-8654-a6e9c2b85596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
