<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icoTrxConfirmarFecha</name>
   <tag></tag>
   <elementGuidId>20b48bdc-39d2-4a25-8ffe-7857fe7f5bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendarDateFilterFrom-k-w-c-navigator-']/div/div/div[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.-kony-w-c-go-nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>742c1c39-c2b6-42aa-8ee3-4cecdd90f6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>70525bc2-77d1-45d3-82ff-388c012d380e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>dc620e13-2b96-41bf-adb3-8b1e03ecfa43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-w-c-go-nav</value>
      <webElementGuid>85039539-1c56-4396-a496-4d70307f2aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>desktopweb/images/k-go.png</value>
      <webElementGuid>721aa347-bbf8-49da-8dc8-0fb78f91a654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>[object HTMLDivElement]</value>
      <webElementGuid>7f916651-5d7d-47dc-a6c0-65be5e757f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>18992c98-e0cb-4af3-988e-558f09a8a295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>cd3b04e9-c254-4ab7-8714-82fc8c68df9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferHistory_DateFilter</value>
      <webElementGuid>aa98f7ce-8d30-4007-89c5-a70e9e55902a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDateFilterFrom-k-w-c-navigator-&quot;)/div[@class=&quot;-kony-w-c-navigator-table&quot;]/div[1]/div[@class=&quot;-kony-w-c-go-nav&quot;]/img[@class=&quot;-kony-w-c-go-nav&quot;]</value>
      <webElementGuid>c9ab42d9-241c-4f49-acee-f6bc378404e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendarDateFilterFrom-k-w-c-navigator-']/div/div/div[3]/img</value>
      <webElementGuid>ae0d43d6-03a9-4a7b-b54e-91d05477c45a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='undefined'])[2]</value>
      <webElementGuid>846d5e51-bd3e-4795-b0f1-11b279c5207d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[3]/img</value>
      <webElementGuid>e79b18b2-9887-4a2d-9bdd-31dec2a588ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'undefined' and @src = 'desktopweb/images/k-go.png']</value>
      <webElementGuid>d8d0f67b-426c-4ec9-8a9c-36d7271afe4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
