<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCtasMovimConcepto</name>
   <tag></tag>
   <elementGuidId>6756b0fa-c450-4b16-b5bd-c99d6aabdb19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsDetailsBccl_lblTransactionConcept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsDetailsBccl_lblTransactionConcept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29c69694-55d7-4a1a-8403-b5650259040f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl_lblTransactionConcept</value>
      <webElementGuid>dde7c262-a0f3-417a-a871-1131e251a13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0ae7976e-6b5b-45cf-85ce-f2272fb434c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl</value>
      <webElementGuid>7b6208b9-974f-4661-849d-6c8204fd630a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTransactionTableHeader cntmiddleleftalign disableSelection</value>
      <webElementGuid>321026b5-4145-47ff-88c2-69fb1f4c2016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Concepto</value>
      <webElementGuid>97565ad7-adfe-46a9-9f9c-5726a65407c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_lblTransactionConcept&quot;)</value>
      <webElementGuid>3ffc1fe3-beb5-479c-a36c-c10281fd87b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_lblTransactionConcept']</value>
      <webElementGuid>fc3db014-9855-45fd-b3f7-7fbb1098d466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_flxTransactionConcept']/div/div</value>
      <webElementGuid>abcb28e6-81e7-4b04-bded-41ce02b48dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/following::div[5]</value>
      <webElementGuid>4df43396-7be9-42e0-a675-5c441b66ea5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha'])[2]/following::div[7]</value>
      <webElementGuid>0497b210-2f88-4668-87d0-5b287c0e5dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[5]/preceding::div[1]</value>
      <webElementGuid>6892c674-2d20-4021-9417-db5075c36d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[6]/preceding::div[3]</value>
      <webElementGuid>3d7feb4b-33cf-4531-8a25-02c5e7dc767c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Concepto']/parent::*</value>
      <webElementGuid>2de78cee-0415-498a-a278-d28812d003e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>53a45b66-e477-4eae-9a7f-52f4f4c1691e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsDetailsBccl_lblTransactionConcept' and (text() = 'Concepto' or . = 'Concepto')]</value>
      <webElementGuid>35f3a92a-a7c9-4722-bd1f-744c7c6d055c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
