<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCtasMovimImporte</name>
   <tag></tag>
   <elementGuidId>e43e81ca-4160-4c4a-b430-38165da57ef9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsDetailsBccl_lblTransactionAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsDetailsBccl_lblTransactionAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f5f04be-d7cd-4fc0-947d-ddb502d26684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl_lblTransactionAmount</value>
      <webElementGuid>1c9fb438-8164-442e-a8f5-fbb643344bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>5075f650-1ec6-4367-8860-08882aff7d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl</value>
      <webElementGuid>a71cd893-04f6-44c1-9b3b-c8512341a231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTransactionTableHeader cntmiddlerightalign disableSelection</value>
      <webElementGuid>70baa1ac-cbc6-42a6-9ef2-7622c0f23a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Importe</value>
      <webElementGuid>96f1d20d-1bde-4a7e-bd52-82c4671b7081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_lblTransactionAmount&quot;)</value>
      <webElementGuid>6fd15dbb-98e3-40ed-9285-b2d4af46d54d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_lblTransactionAmount']</value>
      <webElementGuid>dad5218e-5082-4b08-915a-b4fae6deddf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_flxTransactionAmount']/div[2]/div</value>
      <webElementGuid>8df08fc1-6d99-4c9c-857c-b8ce4ebabb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[6]/following::div[2]</value>
      <webElementGuid>c488536a-c66b-46b5-9ea7-ee0198de187e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[5]/following::div[7]</value>
      <webElementGuid>59fdd84b-4d40-43e5-8313-513d058007a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[7]/preceding::div[1]</value>
      <webElementGuid>54f895c4-59dd-4b4f-9e61-9a9781232c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo'])[1]/preceding::div[3]</value>
      <webElementGuid>16396014-3bc2-405c-883d-f62aef33cf61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Importe']/parent::*</value>
      <webElementGuid>81a1fae3-7ec3-4543-a3df-622e50f3dcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div[3]/div/div/div[2]/div</value>
      <webElementGuid>16b77df2-6dd1-4d53-91f1-626c183ee09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsDetailsBccl_lblTransactionAmount' and (text() = 'Importe' or . = 'Importe')]</value>
      <webElementGuid>f5b98d4e-5672-422b-b128-f2ff60aed4aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
