<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCtaCuentaPesos</name>
   <tag></tag>
   <elementGuidId>54606033-02e8-475f-8d5e-90cb1022a7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxAccountsHomeTableRow_lblAccountDetail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxAccountsHomeTableRow_lblAccountDetail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3fd99273-d40d-480f-a823-8b763e1b2f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow_lblAccountDetail</value>
      <webElementGuid>bbfb072c-20f6-4c60-b50b-ee9fc0337272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e500d51e-1d4a-44eb-8ef0-d6d2317b93fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow</value>
      <webElementGuid>635e8748-7794-477d-9728-898683a5b54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>34fb6e3e-451e-4006-bb06-cbe17f55cb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>FFA96C37-8377-4DFF-86CE-8D598366ED34</value>
      <webElementGuid>69c661c7-015a-42d1-9769-72bc04d457a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountDetail cntmiddleleftalign disableSelection</value>
      <webElementGuid>5d7dc46a-fa8a-405f-bbbf-f97ee1db1694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA $ 119-011835/9</value>
      <webElementGuid>cb788fd1-67e1-4a1b-88a5-39e57b3346a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_segAccounts&quot;)/ul[1]/li[@class=&quot;sknSegAccountTable&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountsHomeTableRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxLeftContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountTitleContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblAccountDetail&quot;]/div[@id=&quot;flxAccountsHomeTableRow_lblAccountDetail&quot;]</value>
      <webElementGuid>53c594f8-9387-400d-9e2a-2529ced4b8c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxAccountsHomeTableRow_lblAccountDetail']</value>
      <webElementGuid>0af2d24d-c93f-440c-a98a-81be02110b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxAccountsHomeTableRow_flxAccountTitleContainer']/div[2]/div</value>
      <webElementGuid>d5235641-8db0-465a-832d-afd7ef9a810b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro sueldo prueba $'])[1]/following::div[2]</value>
      <webElementGuid>2522e6e0-d064-441a-998d-2cbac876300a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[7]</value>
      <webElementGuid>66f8a807-e7c6-4719-a544-8afb028f0af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[1]</value>
      <webElementGuid>5d1baa8d-65a0-4fee-b779-979ed9fb4109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[1]/preceding::div[9]</value>
      <webElementGuid>386e5612-81b9-4787-a502-1fcfac023722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA $ 119-011835/9']/parent::*</value>
      <webElementGuid>5eeb14ea-5598-4cbe-af9d-2571fe7ca8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li/div/div/div/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>3f66b1d6-aeb2-4c36-a7dd-b211c418efd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountsHomeTableRow_lblAccountDetail' and (text() = 'CA $ 119-011835/9' or . = 'CA $ 119-011835/9')]</value>
      <webElementGuid>26067249-d1f4-4986-8c6f-181825464622</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
