<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCtaCuentaDolares</name>
   <tag></tag>
   <elementGuidId>91859c96-10a4-434f-b128-2054d005a6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxAccountsHomeTableRow_lblAccountDetail'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db029885-085f-415c-9d5e-b92a0d317a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow_lblAccountDetail</value>
      <webElementGuid>17a937ba-9400-484e-b9a5-1502090c99e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e41db51c-e224-4871-b602-6220e0c98481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountsHomeTableRow</value>
      <webElementGuid>e55e2bf5-6485-4305-8048-3e29d906d919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAccounts</value>
      <webElementGuid>e4752646-580b-47c0-8051-9660f483888a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>04471BA6-A970-44A9-8F4E-DFBCF76F0A2F</value>
      <webElementGuid>aebb51e1-e006-4d25-a49c-df50cd6d7024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblAccountDetail cntmiddleleftalign disableSelection</value>
      <webElementGuid>b8205ba5-e318-4111-8125-f833bed1f0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA U$S 119-011835/9</value>
      <webElementGuid>c73a085c-4ebd-4152-9191-4e6507ebb081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsHome_segAccounts&quot;)/ul[1]/li[@class=&quot;sknSegAccountTable&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountsHomeTableRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxLeftContainer&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountsHomeTableRow_flxAccountTitleContainer&quot;]/div[@class=&quot;kcell middlecenteralignsknLblAccountDetail&quot;]/div[@id=&quot;flxAccountsHomeTableRow_lblAccountDetail&quot;]</value>
      <webElementGuid>0fe6e57a-fea0-4ded-bbf1-5ccf621ecbb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountsHomeTableRow_lblAccountDetail'])[2]</value>
      <webElementGuid>595f4c33-b071-4303-813a-949449f23ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flxAccountsHomeTableRow_flxAccountTitleContainer']/div[2]/div)[2]</value>
      <webElementGuid>25449648-dd7c-4a87-a394-dad6afff4df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja de Ahorro en dólares'])[1]/following::div[2]</value>
      <webElementGuid>74824061-c7fd-49ea-9390-a54f1416cc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[7]</value>
      <webElementGuid>57acb290-c1d4-4d69-b4c8-302c3a4b93f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>2e49ebd6-c75b-41fc-b8a6-e84adfc7db5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S'])[1]/preceding::div[9]</value>
      <webElementGuid>217e888d-3598-47ef-8932-f4943681a355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA U$S 119-011835/9']/parent::*</value>
      <webElementGuid>203386d3-8591-4455-9ccc-ca1e7f5993fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[2]/div/div/div/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>a673b9d1-ce8d-46f2-b28d-8b2564d29667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountsHomeTableRow_lblAccountDetail' and (text() = 'CA U$S 119-011835/9' or . = 'CA U$S 119-011835/9')]</value>
      <webElementGuid>b35d8cba-dd16-45b3-b5d1-a67b3e7af84f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
