<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCtasMovimFecha</name>
   <tag></tag>
   <elementGuidId>5b847497-a924-4d97-877d-6078e2b2a38f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsDetailsBccl_lblTransactionDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsDetailsBccl_lblTransactionDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>97c19321-3cb9-49dc-bcec-b9cfd5d32393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl_lblTransactionDate</value>
      <webElementGuid>87052b74-8e94-475a-9148-088c985ad8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f3a4dfea-bd56-4f38-a4ec-411cbff46ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl</value>
      <webElementGuid>c819ac68-3b06-40c1-8c34-373b85f70bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTransactionTableHeader cntmiddleleftalign disableSelection</value>
      <webElementGuid>45f1fde3-ba7e-4aeb-b97a-67d8bd782084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha</value>
      <webElementGuid>40306903-962c-4c52-a0bf-3f85e4e85613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_lblTransactionDate&quot;)</value>
      <webElementGuid>6674e238-9d8c-496a-8638-7a7654417c8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_lblTransactionDate']</value>
      <webElementGuid>db27644d-a5e8-4ed6-ba2c-76a537b56dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_flxTransactionDate']/div/div</value>
      <webElementGuid>c7ab061c-d3bb-4e79-9d80-dc38651731da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[6]/following::div[11]</value>
      <webElementGuid>00876b72-4fd9-4b13-89a0-9181ba7cf5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[5]/following::div[13]</value>
      <webElementGuid>601cdfda-f8d9-45d3-90c3-e60163389cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/preceding::div[1]</value>
      <webElementGuid>e4600e24-f2fe-458a-9fe2-72f11dc683c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[1]/preceding::div[3]</value>
      <webElementGuid>a5ab065d-d3a8-4a84-bab0-a8f33ae873ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>55e11959-9f6d-4e59-9bde-0ffcb8a3bca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsDetailsBccl_lblTransactionDate' and (text() = 'Fecha' or . = 'Fecha')]</value>
      <webElementGuid>e05053ef-8dc0-4828-b492-bec3daeaf694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
