<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblInvFondosComunesInversin</name>
   <tag></tag>
   <elementGuidId>70b80617-a524-41c4-84f9-49d1227e18ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_lblTitleCommonInvestmentFund']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_lblTitleCommonInvestmentFund</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd2e0d18-bd33-41ed-9c75-d02822b79361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_lblTitleCommonInvestmentFund</value>
      <webElementGuid>a90676b5-4f2a-4b80-8c87-004c46e0682a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>9f28e7c7-f768-4bde-8019-8ac353a84aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>41c2486c-24b9-4e65-a4fa-3a0667e3996b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTitleBox cntmiddleleftalign disableSelection</value>
      <webElementGuid>0368b242-b2bd-43ca-9339-417288d69d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fondos Comunes de Inversión</value>
      <webElementGuid>47579b00-df2d-4752-8b43-a28040fa5b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_lblTitleCommonInvestmentFund&quot;)</value>
      <webElementGuid>998dd3c7-01fd-438e-92a8-0bf82b0c6ff7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_lblTitleCommonInvestmentFund']</value>
      <webElementGuid>66ef0029-f457-431f-82b6-71bc68d54517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_flxLeft']/div/div</value>
      <webElementGuid>fd0d5ed2-37d0-476f-a27d-bddca960c218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compra'])[2]/following::div[14]</value>
      <webElementGuid>557b0573-e0c4-4189-8da7-892f6d9ece08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 79,88'])[1]/following::div[16]</value>
      <webElementGuid>bbdbdbe2-f6ca-4a15-923b-ea76f9b93283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/preceding::div[2]</value>
      <webElementGuid>ddae3b32-b37a-49ad-8306-1585cb163d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/preceding::div[25]</value>
      <webElementGuid>5b579e8e-3c70-4957-ba60-e0bc5ec9dac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>90fdc334-f390-4f4b-b2a1-e9f6cab372d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_lblTitleCommonInvestmentFund' and (text() = 'Fondos Comunes de Inversión' or . = 'Fondos Comunes de Inversión')]</value>
      <webElementGuid>28113e6b-ad4f-43f3-bcda-d5d9f7a15802</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
