<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblInvCompraVentaDlares</name>
   <tag></tag>
   <elementGuidId>b3d769df-e2ed-49e1-bf77-909599d4bf74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_lblTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_CotizacionDolar_lblTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c501533-3e03-4520-882e-d2d04826a7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CotizacionDolar_lblTitle</value>
      <webElementGuid>7fab8088-924b-4dc3-b197-7f0151da084d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>cb42c2bd-3b97-4799-aa4d-285b9003890e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>d18b810a-f73e-4690-9707-c3c080d4d428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CotizacionDolar</value>
      <webElementGuid>5c95e2b6-51a3-4a7a-815b-d0a87b667fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCotizacionDolar cntmiddleleftalign disableSelection</value>
      <webElementGuid>600dfaa9-0eeb-4b68-817f-31073031d9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compra Venta de Dólares</value>
      <webElementGuid>b00bc8df-0e4a-4354-956a-e740bbbb47a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_CotizacionDolar_lblTitle&quot;)</value>
      <webElementGuid>e675c26c-12ff-4f54-be03-faf24ada0bca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_lblTitle']</value>
      <webElementGuid>93cded97-e96a-4795-b53a-57df7e0cb8d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_flxTitleContainer']/div/div</value>
      <webElementGuid>820f2d42-6e72-40f0-ada6-745ab341205c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[5]</value>
      <webElementGuid>82ce92db-c8d7-44e8-bb6b-efe4bb8ce6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Label'])[7]/following::div[11]</value>
      <webElementGuid>cf4573eb-7537-4a7f-9693-5ec1c3cd5bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver movimientos de compra/venta'])[1]/preceding::div[1]</value>
      <webElementGuid>b6716f3c-1f27-4f08-ab37-5c234ab704fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización de Referencia'])[1]/preceding::div[13]</value>
      <webElementGuid>27f2cb16-c3cd-4024-a355-68019c392397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compra Venta de Dólares']/parent::*</value>
      <webElementGuid>a57ce49b-956d-445e-8077-da6f26132651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>d3a48320-f136-4878-b4d9-56b605616659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_CotizacionDolar_lblTitle' and (text() = 'Compra Venta de Dólares' or . = 'Compra Venta de Dólares')]</value>
      <webElementGuid>0baca02d-a9a8-42c8-b205-1a5a9f2d6e39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
