<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtaMovimPesosImporte</name>
   <tag></tag>
   <elementGuidId>7e3c5cad-9694-4e4e-ae36-4d8c20ddc43f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxAccountTransactionRow_lblTransactionAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxAccountTransactionRow_lblTransactionAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46a927de-0673-4e5d-b1f3-e46082baf83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountTransactionRow_lblTransactionAmount</value>
      <webElementGuid>3911303e-9c53-4391-adfe-7eb54fe53918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>ed26e85a-5af6-48f3-9e39-aa2dcf661579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountTransactionRow</value>
      <webElementGuid>e11a0d60-2c11-4861-b3c5-2e2cbbd49b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segTransactions</value>
      <webElementGuid>cdf9d563-6946-4dff-948a-d1dc4ebbcb70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>F9384003-CEE9-42BA-B3AB-B76B8D4AA369</value>
      <webElementGuid>c77ccb20-a547-40b1-8806-296c86da308c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTransactionAmountNegative cntmiddlerightalign disableSelection</value>
      <webElementGuid>dfd8ca5a-ff25-4218-a2ef-8dd277b755f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- 5,04</value>
      <webElementGuid>854c59f6-0d23-43ce-945f-fed080ac7b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_segTransactions&quot;)/ul[1]/li[1]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountTransactionRow_flxAccountTransactionRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTransactionAmountNegative&quot;]/div[@id=&quot;flxAccountTransactionRow_lblTransactionAmount&quot;]</value>
      <webElementGuid>8b15404b-6893-4b33-a1e3-826bafc55a0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxAccountTransactionRow_lblTransactionAmount']</value>
      <webElementGuid>34ce9cbb-b388-4718-aa2c-6c6dce5b2411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxAccountTransactionRow_flxAccountTransactionRow']/div[3]/div</value>
      <webElementGuid>a63ba51b-2477-4ce8-a38d-4c89774b17b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IVA - Alicuota Consumidor Final'])[1]/following::div[2]</value>
      <webElementGuid>9a1c553f-0f4d-4faf-846b-46a59a8611bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo'])[1]/following::div[13]</value>
      <webElementGuid>79836827-a8d7-4017-b275-1d940223d28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Constitucion de Plazo Fijo (Exento) Operacion: 12989311 - Circular: 108'])[1]/preceding::div[5]</value>
      <webElementGuid>651f6eea-5332-42f0-8e0c-85b9534b016d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- 4.000,00'])[1]/preceding::div[7]</value>
      <webElementGuid>314c6727-2532-427f-93ab-c68113b7ef87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='- 5,04']/parent::*</value>
      <webElementGuid>8756dd54-9c88-4340-bac0-eb536e091aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div[3]/div</value>
      <webElementGuid>57b7977c-7095-44b1-9392-a325e3d181a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountTransactionRow_lblTransactionAmount' and (text() = '- 5,04' or . = '- 5,04')]</value>
      <webElementGuid>81656230-50b9-4015-a336-31221bd049b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
