<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtasMovimDolarImporte</name>
   <tag></tag>
   <elementGuidId>4cd40619-6422-4f44-8cb8-8e33d9fa9d29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxAccountTransactionRow_lblTransactionAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxAccountTransactionRow_lblTransactionAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cda749f1-3345-4564-abb2-8b67a3a4a3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountTransactionRow_lblTransactionAmount</value>
      <webElementGuid>a41e9edd-74e6-4135-bd4e-1652199cac4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0f566082-e202-4efc-a4dd-3d9f4f935509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountTransactionRow</value>
      <webElementGuid>f2dcc509-70e6-4e23-851f-108c427e91ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segTransactions</value>
      <webElementGuid>a5ed92c3-99ea-4155-bd6c-2cc14601ee13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>4438DA7C-972D-4235-A610-2A849E13BE05</value>
      <webElementGuid>74801dd0-6bad-42e2-85f9-c99793389f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblTransactionAmountNegative cntmiddlerightalign disableSelection</value>
      <webElementGuid>dcff2265-d831-4592-8557-df4976619b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- 0,42</value>
      <webElementGuid>f1b9aea2-87e8-42ab-b4a3-79254e45ab1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_segTransactions&quot;)/ul[1]/li[1]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountTransactionRow_flxAccountTransactionRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblTransactionAmountNegative&quot;]/div[@id=&quot;flxAccountTransactionRow_lblTransactionAmount&quot;]</value>
      <webElementGuid>39413ad2-deb3-4d50-895f-7521f211b170</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxAccountTransactionRow_lblTransactionAmount']</value>
      <webElementGuid>132dd487-8b9c-4549-84ed-a5ff422254fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxAccountTransactionRow_flxAccountTransactionRow']/div[3]/div</value>
      <webElementGuid>e07a09d6-9b8c-4d8f-9e49-39363c4aeaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IVA - Alicuota Consumidor Final'])[1]/following::div[2]</value>
      <webElementGuid>d8fbff51-ec2c-4262-bf0b-e47a9c880a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo'])[1]/following::div[13]</value>
      <webElementGuid>111025cb-4bf7-4590-b6e6-4c157767091f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compra/Venta de Moneda Extranjera 19/MAY 13:26 Venta - Cotiz.: 183.51'])[1]/preceding::div[5]</value>
      <webElementGuid>1a293221-5ed5-466e-aecc-10cb5b785fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- 3,00'])[1]/preceding::div[7]</value>
      <webElementGuid>632236b7-7656-4556-bb5d-aa50b59fe707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='- 0,42']/parent::*</value>
      <webElementGuid>312e2e3b-ae52-4951-a0fc-d22c5321cd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div[3]/div</value>
      <webElementGuid>1c2ec82d-cc06-4920-a2a3-a43b1f6a7047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountTransactionRow_lblTransactionAmount' and (text() = '- 0,42' or . = '- 0,42')]</value>
      <webElementGuid>f35ceda5-bbd1-451f-9ea8-8ff751e171e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
