<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtaMovimDolarSaldo</name>
   <tag></tag>
   <elementGuidId>4c183062-2114-41dc-ba34-258257b19b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxAccountTransactionRow_lblTransactionPartialBalance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxAccountTransactionRow_lblTransactionPartialBalance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>13787037-7c06-443e-8f9d-86692c65bd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountTransactionRow_lblTransactionPartialBalance</value>
      <webElementGuid>d0e78da4-8122-4a55-8c52-e7d44836bd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>a34c51d6-97a9-48c2-9246-3fbe5671497b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountTransactionRow</value>
      <webElementGuid>6e6a5bd6-a166-4ee9-bc0b-2c79c751670b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segTransactions</value>
      <webElementGuid>4d8e3142-174d-41e4-8fda-d0155713c167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>790AE82A-38AE-4621-90B2-5E2E147825B9</value>
      <webElementGuid>f5e4601e-585c-48ee-9b66-b447a9707995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCellSecondaryMD cntmiddlerightalign disableSelection</value>
      <webElementGuid>8d5bb9fb-7757-437c-a5fa-527d4250e089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.998.312,85</value>
      <webElementGuid>68a77c34-6cdd-4c0d-a1ce-493a3d023484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_segTransactions&quot;)/ul[1]/li[1]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountTransactionRow_flxAccountTransactionRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblCellSecondaryMD&quot;]/div[@id=&quot;flxAccountTransactionRow_lblTransactionPartialBalance&quot;]</value>
      <webElementGuid>d376a853-a0f1-4ee8-aa32-54cf6523d1c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxAccountTransactionRow_lblTransactionPartialBalance']</value>
      <webElementGuid>56ae9326-813e-43c5-8c9f-5f9a10bd877d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxAccountTransactionRow_flxAccountTransactionRow']/div[4]/div</value>
      <webElementGuid>b5178697-f5a3-4182-a089-bee4771d38fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- 0,42'])[1]/following::div[2]</value>
      <webElementGuid>ea778495-650b-4da1-b6fa-6b976ad4a5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IVA - Alicuota Consumidor Final'])[1]/following::div[4]</value>
      <webElementGuid>42c89537-ad83-49c1-84a6-2e845b4b18bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compra/Venta de Moneda Extranjera 19/MAY 13:26 Venta - Cotiz.: 183.51'])[1]/preceding::div[3]</value>
      <webElementGuid>43bc2fc8-a770-4f3a-8f6a-ad424d7a1323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- 3,00'])[1]/preceding::div[5]</value>
      <webElementGuid>fa8936a8-81ea-4191-b449-6168f57deeb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2.998.312,85']/parent::*</value>
      <webElementGuid>37501609-ba1f-4d17-bdba-a35701b443db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[4]/div</value>
      <webElementGuid>746d7949-df94-4968-a740-68d0657c9e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountTransactionRow_lblTransactionPartialBalance' and (text() = '2.998.312,85' or . = '2.998.312,85')]</value>
      <webElementGuid>639fcd70-377d-49aa-81ed-77f59afef51b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
