<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtasMovimDolarFecha</name>
   <tag></tag>
   <elementGuidId>becc468b-d8a9-4c0e-ae5b-dcb0f63b6015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flxAccountTransactionRow_lblTransactionDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxAccountTransactionRow_lblTransactionDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9d980e40-2556-4461-a76d-5d3ee1201e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxAccountTransactionRow_lblTransactionDate</value>
      <webElementGuid>e8441500-21c0-4ed9-ad18-f6d3e4e9d340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>a504a06e-e681-4fc7-b399-15bb047c1031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxAccountTransactionRow</value>
      <webElementGuid>3fd6c441-c502-4806-8388-27f20f14857c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segTransactions</value>
      <webElementGuid>d1ee45fc-d26d-4de0-abe6-317a05cf592b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>C78D1ABA-65F0-44A5-AE90-C2DE70B8E6DB</value>
      <webElementGuid>19c22927-ca55-429d-8aa2-5e7a8f34f7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCellSecondaryMD cntmiddleleftalign disableSelection</value>
      <webElementGuid>4cd3b9be-d698-4d0b-80af-3cb9171bb642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23 Ene 2023</value>
      <webElementGuid>4b6c16fc-d4a5-4660-8604-5004af9de4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_segTransactions&quot;)/ul[1]/li[1]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxAccountTransactionRow_flxAccountTransactionRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblCellSecondaryMD&quot;]/div[@id=&quot;flxAccountTransactionRow_lblTransactionDate&quot;]</value>
      <webElementGuid>597dc31e-fc71-4e08-94bb-3ed6fa613938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxAccountTransactionRow_lblTransactionDate']</value>
      <webElementGuid>67efc31d-e444-47a3-9356-2838097bc5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxAccountTransactionRow_flxAccountTransactionRow']/div/div</value>
      <webElementGuid>a711144c-d3ac-46ab-b3be-20274d0b14a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo'])[1]/following::div[9]</value>
      <webElementGuid>6c3d800d-b1b3-4aeb-b5fe-cc5b2b64d464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[7]/following::div[11]</value>
      <webElementGuid>c8cf0b4c-5328-48a8-bbd7-322152acbabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IVA - Alicuota Consumidor Final'])[1]/preceding::div[1]</value>
      <webElementGuid>61705827-6c94-4a9d-8ae1-220baf9ca89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- 0,42'])[1]/preceding::div[3]</value>
      <webElementGuid>b82a3867-7020-448f-a15d-fc299dec62be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='23 Ene 2023']/parent::*</value>
      <webElementGuid>082557c8-c807-4cf0-a70e-da179442065a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div/div</value>
      <webElementGuid>2b26b841-723a-472e-ba11-a1520d3eea56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxAccountTransactionRow_lblTransactionDate' and (text() = '23 Ene 2023' or . = '23 Ene 2023')]</value>
      <webElementGuid>7ecd0c18-63b7-4a85-86dd-5578cf9381d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
