<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCtaDetalleCuenta</name>
   <tag></tag>
   <elementGuidId>b34a6228-625b-4789-86d8-c66b5eb4c594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsDetailsBccl_Panel_MovementDetails_lblSourceAccountData']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsDetailsBccl_Panel_MovementDetails_lblSourceAccountData</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf51ed30-64ec-40ad-858f-f81a4dafa302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl_Panel_MovementDetails_lblSourceAccountData</value>
      <webElementGuid>9d6828c7-8f27-477b-8e2a-00c78684ab8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>878b7df0-3126-472c-b8cd-6527d6acca62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsDetailsBccl</value>
      <webElementGuid>5c179ed6-06f7-4f5f-bff6-f3114e6f7291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Panel_MovementDetails</value>
      <webElementGuid>c894834c-b143-4432-a1ac-a0fb56ba882e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblPanelProductRowData cntmiddlerightalign disableSelection</value>
      <webElementGuid>4558b6b9-20fd-481e-988a-513839d7422f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA $ 119-011835/9</value>
      <webElementGuid>3858dde3-814d-4311-9521-422f5c36aeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsDetailsBccl_Panel_MovementDetails_lblSourceAccountData&quot;)</value>
      <webElementGuid>16613ec2-eb54-4e24-8e1c-492606e43363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_Panel_MovementDetails_lblSourceAccountData']</value>
      <webElementGuid>3f73f2a1-d1bf-4d3e-8999-a605a3fc359a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsDetailsBccl_Panel_MovementDetails_flxSourceAccountContainer']/div[2]/div</value>
      <webElementGuid>671f1a86-d2ee-4c3f-ab2c-fc8daae6eaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta de Origen'])[1]/following::div[2]</value>
      <webElementGuid>0894d858-875e-4673-b31e-a9e644d95c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de transacción'])[1]/following::div[9]</value>
      <webElementGuid>4cb720b0-27b3-4967-a6b5-6d571f536063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[3]/preceding::div[1]</value>
      <webElementGuid>7980fdc1-2876-49df-bbb5-77ca8c73d082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descargar comprobante'])[1]/preceding::div[3]</value>
      <webElementGuid>f12a9f8c-4e52-4d2c-a884-d56b2f309db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[4]/div/div/div[2]/div</value>
      <webElementGuid>925d0206-d368-4f24-83b8-66e714fd5607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsDetailsBccl_Panel_MovementDetails_lblSourceAccountData' and (text() = 'CA $ 119-011835/9' or . = 'CA $ 119-011835/9')]</value>
      <webElementGuid>6cc8576b-b839-4f85-b65f-373ff0ec3226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
