<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtFCRegistroTransferenciasRecibidasMonto</name>
   <tag></tag>
   <elementGuidId>c77047cb-292b-45cf-97e3-717435600023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxReceivedRow_lblReceivedAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxReceivedRow_lblReceivedAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5825e500-0788-4b38-8a7e-dd3993a5524d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxReceivedRow_lblReceivedAmount</value>
      <webElementGuid>45f4896e-9303-4211-b169-e0888560ec9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>f24e7d4b-d5e1-417b-84d3-90ced0f0e3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxReceivedRow</value>
      <webElementGuid>568af947-e8ec-472f-b89a-ddc7d852dad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segReceived</value>
      <webElementGuid>8ab7dc5c-3edc-4d61-be82-036e5371efea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>A5FCB79D-0461-4A65-8126-62ABAECBDCE7</value>
      <webElementGuid>235b9464-0e71-4dc9-9056-af35fbb88482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddlerightalign disableSelection</value>
      <webElementGuid>60616eaa-4bf1-4631-8010-a8567eb3ae4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 1,00</value>
      <webElementGuid>ed756d8e-31bd-4078-a5ff-a336d1226010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_TransferHistory_segReceived&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxReceivedRow_flxReceivedRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxReceivedRow_flxReceivedAmount&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxReceivedRow_lblReceivedAmount&quot;]</value>
      <webElementGuid>856a204a-516c-4b37-8fbd-9f33c68bd2d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxReceivedRow_lblReceivedAmount']</value>
      <webElementGuid>59a3d4ab-d18a-4ec3-872f-8e12b9b7fe7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxReceivedRow_flxReceivedAmount']/div/div</value>
      <webElementGuid>ae97f3c6-130e-4025-b9fa-87dc5cc1de46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credito Inmediato (DEBIN) dist titular 20138236502-FAC-APELLIDO NOMBRE'])[1]/following::div[5]</value>
      <webElementGuid>3c3dae32-59db-46e7-a95f-09a47df1152d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 001-065350/4'])[1]/following::div[7]</value>
      <webElementGuid>fe31af51-77e5-46e2-80f9-1b67f9bd9453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CC $ 001-065350/4'])[2]/preceding::div[6]</value>
      <webElementGuid>f6a8f895-32a1-416e-872e-e464296773f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credito Inmediato (DEBIN) dist titular 20138236502-HON-APELLIDO NOMBRE'])[1]/preceding::div[11]</value>
      <webElementGuid>9df94ca8-f193-4968-bef1-4a38286676cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 1,00']/parent::*</value>
      <webElementGuid>68d23edc-9ca6-453a-8e58-f13b5319c762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>e4fc6ffc-d6b7-4122-93e1-3a963a6c18cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxReceivedRow_lblReceivedAmount' and (text() = '$ 1,00' or . = '$ 1,00')]</value>
      <webElementGuid>912f0ca9-5d09-49b6-bc70-09b87c159092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
