<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtFCRegistroTransferenciasRecibidasCuentaDestino</name>
   <tag></tag>
   <elementGuidId>1970d0bc-ec6c-426a-ad59-9018e2cf1d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxReceivedRow_lblReceivedDestinationAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxReceivedRow_lblReceivedDestinationAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3cb68b2c-2020-41a3-9574-3e746a661a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxReceivedRow_lblReceivedDestinationAccount</value>
      <webElementGuid>e043d0e0-2e79-456e-8229-32f42b634b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>c01ce707-fc4d-4570-ad4e-0d7945844fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxReceivedRow</value>
      <webElementGuid>2c9fa6ba-feab-4bec-a811-11160ed1341b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segReceived</value>
      <webElementGuid>34c49589-6a96-49b9-bc89-c0811313ad7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>6FE39CE4-6F87-4FB9-BFE8-110AC471A14A</value>
      <webElementGuid>b4d58a49-c157-4b3c-ba6e-87e026f13b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableNumberData cntmiddleleftalign disableSelection</value>
      <webElementGuid>2dd62f5c-344d-48a2-b4ab-ddc538049088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CC $ 001-065350/4</value>
      <webElementGuid>31347e97-ef8b-456d-ab87-c0225d7a11b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmBcclTransfers_TransferHistory_segReceived&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxReceivedRow_flxReceivedRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxReceivedRow_flxReceivedDestinationAccount&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableNumberData&quot;]/div[@id=&quot;flxReceivedRow_lblReceivedDestinationAccount&quot;]</value>
      <webElementGuid>0d22a80f-c921-42af-b5f3-871c1a3b720a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxReceivedRow_lblReceivedDestinationAccount']</value>
      <webElementGuid>8899d9b1-df2a-4432-a293-27bab618e339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxReceivedRow_flxReceivedDestinationAccount']/div/div</value>
      <webElementGuid>2639f836-f1ca-4d4d-bf06-50513ab645e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto'])[1]/following::div[17]</value>
      <webElementGuid>037f103d-40b4-46b7-8298-bcb3d075c3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[1]/following::div[22]</value>
      <webElementGuid>d8651756-7157-4b20-b425-32ee4b6d5436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credito Inmediato (DEBIN) dist titular 20138236502-FAC-APELLIDO NOMBRE'])[1]/preceding::div[1]</value>
      <webElementGuid>ad224cef-079c-4a41-b639-42eec09a94c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 1,00'])[1]/preceding::div[3]</value>
      <webElementGuid>8fc1ae59-b967-4cea-beed-a7491c4e3536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CC $ 001-065350/4']/parent::*</value>
      <webElementGuid>8b034137-9f33-4f9d-95bc-a05f381d5580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>71c5df3e-96ca-4fbf-b8c8-5836f3c06706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxReceivedRow_lblReceivedDestinationAccount' and (text() = 'CC $ 001-065350/4' or . = 'CC $ 001-065350/4')]</value>
      <webElementGuid>be7dd8ca-b523-49f8-bd00-69533bede1d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
