<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvFCITablaSaldoEstimado</name>
   <tag></tag>
   <elementGuidId>f04b6ca9-ce4e-4000-9a05-4e676bb12753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_CommonInvestmentFund_lblEstimatedAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_CommonInvestmentFund_lblEstimatedAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>15384507-5ac2-4c9d-94d5-1bf06189c94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CommonInvestmentFund_lblEstimatedAmount</value>
      <webElementGuid>6642e0f3-07fb-4f8a-9d47-d75ab6b9bf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>bdeff7e0-0c95-4224-8130-983b36d2d335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>239a6508-0cff-4256-9247-80a506a2f3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CommonInvestmentFund</value>
      <webElementGuid>b1f15e1c-722b-47fb-aa62-4939201ad155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTitleTableBox cntmiddleleftalign disableSelection</value>
      <webElementGuid>fbce30d3-208f-4cee-8dfc-e9e0df597de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saldo estimado</value>
      <webElementGuid>734d9cd2-d44d-4e4b-9524-8765ed8808e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_CommonInvestmentFund_lblEstimatedAmount&quot;)</value>
      <webElementGuid>d9f7c8cb-78a1-4f61-85de-3a2fa34091a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CommonInvestmentFund_lblEstimatedAmount']</value>
      <webElementGuid>2db14345-5589-42ad-a67c-3da3dbd0309b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CommonInvestmentFund_flxEstimatedAmount']/div/div</value>
      <webElementGuid>cb38d374-f7ec-48da-bbe2-9488290de300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de cotización'])[1]/following::div[5]</value>
      <webElementGuid>ff1384fa-c364-459f-80b0-7463bd05dc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización'])[1]/following::div[10]</value>
      <webElementGuid>a5ea7f88-f70d-4af8-8c64-70bbdf7f22ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FCAD'])[1]/preceding::div[1]</value>
      <webElementGuid>e342c9a0-7141-4db5-89ca-c5c74183ecbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 538.874,09'])[2]/preceding::div[23]</value>
      <webElementGuid>6339fd11-40f0-430a-af77-3171de930eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Saldo estimado']/parent::*</value>
      <webElementGuid>04332183-e2e9-4266-adac-fea5a333db41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[6]/div/div/div/div</value>
      <webElementGuid>a6126997-20a5-4c10-bf0c-4692a4a32175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_CommonInvestmentFund_lblEstimatedAmount' and (text() = 'Saldo estimado' or . = 'Saldo estimado')]</value>
      <webElementGuid>6abfed0c-fd49-4710-91f3-a7ebdf3d929e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
