<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvTituTablaNominal</name>
   <tag></tag>
   <elementGuidId>d4d5ce51-6ef3-469c-8c21-3dc659ffce0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_TitleInvestment_lblNominalValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_TitleInvestment_lblNominalValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>977566ec-2c8a-4e5c-b685-a701b75a227b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_TitleInvestment_lblNominalValue</value>
      <webElementGuid>1ff63185-340e-4ea1-9cd0-c62031bbdbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>40afd900-0a0c-479d-bbda-ecf8c21fd2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>4c2b6e73-d96c-4367-8afb-511ce013e28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TitleInvestment</value>
      <webElementGuid>681b1196-2195-4bb1-aec3-cf49695e6314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTitleTableBox cntmiddlerightalign disableSelection</value>
      <webElementGuid>a966098b-0d83-42cb-bcb3-b4a74f6f211b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Valor nominal</value>
      <webElementGuid>3d91051a-6356-46fe-b7db-cf33b6f49982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_TitleInvestment_lblNominalValue&quot;)</value>
      <webElementGuid>1328deac-d8c8-466f-bfdc-a11cc76c4f1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_TitleInvestment_lblNominalValue']</value>
      <webElementGuid>723d853f-1640-40b9-92dd-fca08e82a19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_TitleInvestment_flxTableHeaderNominalValue']/div/div</value>
      <webElementGuid>fd45df8b-5990-4731-ba50-38e2d227770d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripción'])[2]/following::div[5]</value>
      <webElementGuid>f18915fd-511b-4129-9fd8-63e4e6017dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo'])[3]/following::div[10]</value>
      <webElementGuid>cb36da87-e4bc-4bb3-9fea-c93335e1e7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valor residual'])[1]/preceding::div[1]</value>
      <webElementGuid>b943174f-57d2-43d4-b94d-f725ac57a065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización'])[2]/preceding::div[6]</value>
      <webElementGuid>b7900a72-26a8-4203-91f8-94941ec2b9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Valor nominal']/parent::*</value>
      <webElementGuid>a2a5955b-21f4-4adb-820d-add976a3a166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>f3d6381a-9126-4c03-aeb1-e532838f5ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_TitleInvestment_lblNominalValue' and (text() = 'Valor nominal' or . = 'Valor nominal')]</value>
      <webElementGuid>573f9c38-fc15-4aef-a590-0971cec521da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
