<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvFCITablaFechaCotizacin</name>
   <tag></tag>
   <elementGuidId>ffc95727-69c6-4c91-9848-c3b32aae554c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_CommonInvestmentFund_lblQuotationDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_CommonInvestmentFund_lblQuotationDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c868518-5cf0-4f4c-9299-6f06e9e7ea65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CommonInvestmentFund_lblQuotationDate</value>
      <webElementGuid>f4434908-a631-444e-9a0a-c423b3bb1ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0f374cf9-2fb9-4382-b633-f9f2facb543a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>ffc7e4ed-8f4c-4d32-8c57-46173a3d895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CommonInvestmentFund</value>
      <webElementGuid>76b08172-fa01-4cc4-89c0-ab649955a25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTitleTableBox cntmiddleleftalign disableSelection</value>
      <webElementGuid>710ebd3e-e85d-46dd-94f3-bbc511056bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha de cotización</value>
      <webElementGuid>1783b18f-439a-4dd9-a271-5167536aaeaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_CommonInvestmentFund_lblQuotationDate&quot;)</value>
      <webElementGuid>c2229497-cdeb-448f-b094-58bbead8c6bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CommonInvestmentFund_lblQuotationDate']</value>
      <webElementGuid>74ca42b4-9e32-4067-82ca-c43ad44f9369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CommonInvestmentFund_flxQuotationDate']/div/div</value>
      <webElementGuid>ade74155-67d0-485c-81cd-c53c9de6bf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización'])[1]/following::div[5]</value>
      <webElementGuid>cd4b5f62-8d59-4d72-9751-bf2c30eb1c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuotapartes'])[1]/following::div[10]</value>
      <webElementGuid>8885c34f-99a0-4d9a-8c66-20281427a06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo estimado'])[1]/preceding::div[1]</value>
      <webElementGuid>7b7874c5-3f2d-4aea-a119-73947be54627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FCAD'])[1]/preceding::div[6]</value>
      <webElementGuid>bfc70fc1-c61a-44b0-b45b-9b231f4337e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fecha de cotización']/parent::*</value>
      <webElementGuid>7b2f355d-3825-461c-a841-4b7411ef52d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[5]/div/div/div/div</value>
      <webElementGuid>3c67c53a-5084-4711-b1eb-a4bba9e4a612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_CommonInvestmentFund_lblQuotationDate' and (text() = 'Fecha de cotización' or . = 'Fecha de cotización')]</value>
      <webElementGuid>4babe83c-18e5-47b7-be85-75e77efd010b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
