<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvPFNroOperComprobante</name>
   <tag></tag>
   <elementGuidId>f059b3c1-84df-4c73-97ae-b67582c9a384</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmConfirmFixedTermBccl_ComprobantePlazoFijo_lblNumOperacionValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmConfirmFixedTermBccl_ComprobantePlazoFijo_lblNumOperacionValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>edd3e9bf-1903-4dd9-b6f2-80caa12b8857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl_ComprobantePlazoFijo_lblNumOperacionValue</value>
      <webElementGuid>48b9e236-e9a1-455b-a74d-305a1761a404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>0baac850-7517-48e7-ae80-6a919b70d0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmConfirmFixedTermBccl</value>
      <webElementGuid>6a87333d-adef-44d4-8cef-80afe486600f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ComprobantePlazoFijo</value>
      <webElementGuid>354dc051-323e-458c-86a5-3479ec5f1b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblLatoReg1433 cntmiddlerightalign disableSelection</value>
      <webElementGuid>d09e5fb4-069a-4ad7-b8a5-28752deb129a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7400</value>
      <webElementGuid>fcfbe624-6cb8-4f06-bfe8-6941ea5d8112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfirmFixedTermBccl_ComprobantePlazoFijo_lblNumOperacionValue&quot;)</value>
      <webElementGuid>b1980103-57f9-445c-9ba9-e7a037d1c552</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmConfirmFixedTermBccl_ComprobantePlazoFijo_lblNumOperacionValue']</value>
      <webElementGuid>d6d3c040-436e-4006-9a67-b293986f0236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmConfirmFixedTermBccl_ComprobantePlazoFijo_flxNumOperacionValue']/div/div</value>
      <webElementGuid>db4b470c-94db-4a54-b284-70a71571c0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Núm. de operación'])[3]/following::div[5]</value>
      <webElementGuid>d2d6e7c2-5b11-4b0e-acf1-ba870da8ecd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de emisión de comprobante'])[2]/following::div[18]</value>
      <webElementGuid>7907ad88-807a-44bd-9c0c-2e576c5f842a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta de débito'])[2]/preceding::div[1]</value>
      <webElementGuid>27277eb4-90a8-42db-8c83-0012c0bd68e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CA $ 119-011835/9'])[2]/preceding::div[6]</value>
      <webElementGuid>67c926ea-7d0a-4d4d-bc48-abd5ad4b0e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>e1559175-0f46-477c-b1a3-afacb6e9f384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmConfirmFixedTermBccl_ComprobantePlazoFijo_lblNumOperacionValue' and (text() = '7400' or . = '7400')]</value>
      <webElementGuid>a6db095d-f331-4615-86e6-3b197b1f2ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
