<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvCVCotizacinCompra</name>
   <tag></tag>
   <elementGuidId>9a24d1ff-0ee5-40ac-9154-1d71ac158e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_lblImporteCompra']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_CotizacionDolar_lblImporteCompra</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d1b598f-3d14-4a31-b61d-1f0230a448ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_CotizacionDolar_lblImporteCompra</value>
      <webElementGuid>dcb47f1e-3c45-42a3-b088-754e9195b196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>189d73bf-8d15-4f76-a16f-c33da73cb498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>d4f07174-06ce-4cd2-a979-87890a5d6bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>CotizacionDolar</value>
      <webElementGuid>133ee0d8-b107-4591-83c1-156c76a7b119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblCotizacionDolares cntmiddleleftalign disableSelection</value>
      <webElementGuid>e5ee8ab5-eb3b-4dda-a0f6-b9b354876e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 189,70</value>
      <webElementGuid>edb37916-886a-461a-a6fb-a6451cb3ea78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_CotizacionDolar_lblImporteCompra&quot;)</value>
      <webElementGuid>bd2a22a3-02bd-402e-ab07-c1411ad08d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_lblImporteCompra']</value>
      <webElementGuid>d7060faf-cf34-408c-a7ba-384dd6333bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_CotizacionDolar_flxSellContainer']/div/div</value>
      <webElementGuid>634d5546-d4e8-4f33-be05-2fd9b7750c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización de Referencia'])[2]/following::div[33]</value>
      <webElementGuid>fac473a5-7eb4-48ae-8142-929e1e9cceb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización de Referencia'])[1]/following::div[44]</value>
      <webElementGuid>37342a20-4b3f-4634-a1d0-b39a840c45ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Venta'])[1]/preceding::div[1]</value>
      <webElementGuid>0ff38ad2-6962-43ab-b330-ef1c0803091c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Procesando'])[1]/preceding::div[4]</value>
      <webElementGuid>3a6ef93a-a6be-4f26-b704-6d66758c53de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$ 189,70']/parent::*</value>
      <webElementGuid>545f62b1-955f-41f1-b808-1278e3dc5e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>412d9e25-9378-42e6-b4d7-b2129836d14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_CotizacionDolar_lblImporteCompra' and (text() = '$ 189,70' or . = '$ 189,70')]</value>
      <webElementGuid>b6095b7e-1b2e-4005-a719-3e8263d4e746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
