<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvTituTablaSaldoEstimado</name>
   <tag></tag>
   <elementGuidId>08521303-cef9-45ac-a1f7-08b73c7708f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_TitleInvestment_lblEstimatedBalance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_TitleInvestment_lblEstimatedBalance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7914386b-6e60-4bf9-ac67-9c530617b39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_TitleInvestment_lblEstimatedBalance</value>
      <webElementGuid>b7cfc877-67b3-40dd-9ea2-85faf948a4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>26ebdb18-5f8a-4a09-97cd-b2ab2c499df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>df9fda25-5f99-4031-90eb-6bf1ebba7127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TitleInvestment</value>
      <webElementGuid>ea61b7d8-e255-415b-b5f3-073803a50bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTitleTableBox cntmiddlerightalign disableSelection</value>
      <webElementGuid>8ba50d85-1360-42aa-9627-187140e9645a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saldo estimado</value>
      <webElementGuid>fb236c72-6006-47eb-ae4d-49b1cc8bdb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_TitleInvestment_lblEstimatedBalance&quot;)</value>
      <webElementGuid>d64dae5c-8a01-4126-aeca-dd0d24a2f9c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_TitleInvestment_lblEstimatedBalance']</value>
      <webElementGuid>e6b9e0c6-ca4c-4bad-961d-9e093f09db5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_TitleInvestment_flxTableHeaderEstimatedBalance']/div/div</value>
      <webElementGuid>14bf329a-cb96-425a-bd68-9521013071a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha de cotización'])[2]/following::div[5]</value>
      <webElementGuid>a18d43ee-ac40-4b70-8065-3b01b9de431d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización'])[2]/following::div[10]</value>
      <webElementGuid>44586421-608d-4db0-8267-4fc4d65a51c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TX23-BONO TES. NAC. $ AJ. CER 1.40% V. 25/03/23'])[1]/preceding::div[1]</value>
      <webElementGuid>3431bf7f-917d-4b3a-bb05-420db6a3885f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/preceding::div[7]</value>
      <webElementGuid>ee5e8d82-8750-4222-b6cb-c5f9eeb15a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[7]/div/div/div/div</value>
      <webElementGuid>e835364c-b7f1-493c-9ab6-9a1eb1568a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_TitleInvestment_lblEstimatedBalance' and (text() = 'Saldo estimado' or . = 'Saldo estimado')]</value>
      <webElementGuid>511814f8-b45f-44ad-9ffe-acb51ff5aab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
