<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvMontoPF</name>
   <tag></tag>
   <elementGuidId>89f0eb27-d6e2-44b1-bc45-9924370969ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmSimulateFixedTerm_AmountInput_tbxAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmSimulateFixedTerm_AmountInput_tbxAmount</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmSimulateFixedTerm_AmountInput_tbxAmount&quot;)[count(. | //*[@id = 'frmSimulateFixedTerm_AmountInput_tbxAmount' and @class = 'sknTbxAutonumeric' and @type = 'text' and @onfocus = '$KW.TextField.onfocusEventHandler(arguments[0],this)' and @onblur = '$KW.TextField.onblurEventHandler(arguments[0],this)' and @placeholder = '$ 0,00']) = count(//*[@id = 'frmSimulateFixedTerm_AmountInput_tbxAmount' and @class = 'sknTbxAutonumeric' and @type = 'text' and @onfocus = '$KW.TextField.onfocusEventHandler(arguments[0],this)' and @onblur = '$KW.TextField.onblurEventHandler(arguments[0],this)' and @placeholder = '$ 0,00'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f153deb-aa7c-401a-9fb5-9fad556880bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmSimulateFixedTerm_AmountInput_tbxAmount</value>
      <webElementGuid>5ce3c26c-7294-4292-91f5-df2d777ee1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>9e996062-2a8d-4d4f-965e-c30a7e55f120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmSimulateFixedTerm</value>
      <webElementGuid>9c27eb51-7228-43e2-9758-30e4628efbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>AmountInput</value>
      <webElementGuid>e16a2c50-9771-4a12-bcf6-aff4ae32127e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sknTbxAutonumeric</value>
      <webElementGuid>7c87b0d3-063b-4417-9d72-e1b4b07f4e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>863c874b-49a4-4b6f-9fc2-ef2cee9bf724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7cb54197-8098-4377-bd84-fc7daa431535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b6496075-a6bd-4623-bbb8-fbe27ef25f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1029ce00-6601-4452-8dd8-e13b1c94c3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>39daacf0-757f-433f-8531-e0aec837dcb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>6dc03dd1-deab-44f3-af28-6c34a7fb5844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>$ 0,00</value>
      <webElementGuid>bbd7283c-20d6-47b8-8279-310e7fb9ee90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSimulateFixedTerm_AmountInput_tbxAmount&quot;)</value>
      <webElementGuid>cd2f75b4-3667-4e0a-8821-69bc05e657d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmSimulateFixedTerm_AmountInput_tbxAmount']</value>
      <webElementGuid>c85ffe94-db9a-49a7-841c-95c353369ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmSimulateFixedTerm_AmountInput_flxInputContainer']/div/input</value>
      <webElementGuid>a427d03e-a840-43e7-86bf-35169f1260a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>eca99035-bcce-4750-a77e-8a2176530225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmSimulateFixedTerm_AmountInput_tbxAmount' and @type = 'text' and @placeholder = '$ 0,00']</value>
      <webElementGuid>134ac9cb-dbf8-420a-91bc-0af88180ee09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
