<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvACCListaAcciones</name>
   <tag></tag>
   <elementGuidId>bf21d7a3-6b8a-4c11-8460-b1876701b9e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flxActionRow_lblDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#flxActionRow_lblDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f69471e8-a7dc-4bd1-b351-bd98d6de68b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxActionRow_lblDescription</value>
      <webElementGuid>2e1d84e6-ea07-4b88-85e7-fe296a92dcc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>e4ce7649-3b1c-4cd6-b8d4-e3cbcb543ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxActionRow</value>
      <webElementGuid>1444fc0e-ec25-4200-9f0b-13cc49a31dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segAction</value>
      <webElementGuid>91774989-738e-4a5e-a5f6-7a209c86cf6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>7B7FC0CC-6AB0-4D36-9CF9-5ADB01971E44</value>
      <webElementGuid>7b14614d-6509-43c7-ae19-9535db6bbc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTableCommonData cntmiddleleftalign disableSelection</value>
      <webElementGuid>0b719946-874e-426f-8ce4-f5fc962a6223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAMPA ENERGIA SA</value>
      <webElementGuid>c6dafc42-3a9b-4cf3-aa4a-28af85d082e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_Action_segAction&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxActionRow_flxActionRow&quot;]/div[@class=&quot;kcell middlecenteralignsknLblProductTableCommonData&quot;]/div[@id=&quot;flxActionRow_lblDescription&quot;]</value>
      <webElementGuid>1a10aefc-fc67-4b47-9d61-eb4c30baf4c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flxActionRow_lblDescription']</value>
      <webElementGuid>92deddbe-9a2e-42f8-87f1-98c6d3f94f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flxActionRow_flxActionRow']/div[2]/div</value>
      <webElementGuid>a3e0f398-d368-4f01-97a4-44239bddad85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAMP'])[1]/following::div[2]</value>
      <webElementGuid>2da801c0-9623-43ca-a4c9-ad4c6ba91312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo estimado'])[3]/following::div[8]</value>
      <webElementGuid>da5f8751-e6f3-44c7-9c8e-a57ceac2918f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 3.007.099,00'])[1]/preceding::div[10]</value>
      <webElementGuid>64df4cb1-16c3-4fca-be17-ab99b58f0c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDN'])[1]/preceding::div[15]</value>
      <webElementGuid>bcab02f5-16b5-4d0f-8c8e-a395db14f1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAMPA ENERGIA SA']/parent::*</value>
      <webElementGuid>a9343850-71b6-4e46-81d9-825f1c50d10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/ul/li/div/div/div[2]/div</value>
      <webElementGuid>4a1a11d7-c517-4fa2-a6bc-6d5459b0ba98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxActionRow_lblDescription' and (text() = 'PAMPA ENERGIA SA' or . = 'PAMPA ENERGIA SA')]</value>
      <webElementGuid>dcba8faf-e538-41b1-b342-5bbac7013a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
