<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvACCTablaDescripcin</name>
   <tag></tag>
   <elementGuidId>0dd5dfcb-d4ae-49e5-9628-a6b815c588fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmInvestmentsHomeBccl_Action_lblDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmInvestmentsHomeBccl_Action_lblDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79df2e3e-1213-41bc-8ff0-167aa225bf6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl_Action_lblDescription</value>
      <webElementGuid>07269e84-6280-4cc0-b9ee-9215ef4c37e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>c8108a5a-eff1-4855-939e-dec7edb68e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmInvestmentsHomeBccl</value>
      <webElementGuid>a93b6a85-65c1-4221-ad72-fd94dd6f1ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>Action</value>
      <webElementGuid>db87ec99-0895-47d4-9e0e-ce9a9acc3ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblProductTitleTableBox cntmiddleleftalign disableSelection</value>
      <webElementGuid>f002552c-23d4-42c1-b2f4-a3555680cc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Descripción</value>
      <webElementGuid>fcfe812c-f225-419c-a659-ddfd1cce6c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_Action_lblDescription&quot;)</value>
      <webElementGuid>9d38cecd-9ef3-4ddf-a554-c297b7c5fca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_Action_lblDescription']</value>
      <webElementGuid>94072ea7-3e57-4309-8b5c-b9f3efa62ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmInvestmentsHomeBccl_Action_flxTableHeaderDescription']/div/div</value>
      <webElementGuid>d09be758-670a-4e81-8df9-156657c3a3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo'])[4]/following::div[5]</value>
      <webElementGuid>1a2a3660-92bb-4197-991f-986d0b10f37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[5]/following::div[25]</value>
      <webElementGuid>754b2611-184f-43ff-80e7-1408c0106034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valor nominal'])[2]/preceding::div[1]</value>
      <webElementGuid>cb7614dd-6a45-429f-ae52-b5d61e927bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cotización'])[3]/preceding::div[6]</value>
      <webElementGuid>6c862530-5838-4e42-89bf-8af071ec6c2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>88a3a6b0-ff84-4c25-8bf8-e473c84ca7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmInvestmentsHomeBccl_Action_lblDescription' and (text() = 'Descripción' or . = 'Descripción')]</value>
      <webElementGuid>a7f384f5-ff79-42de-81b0-6e76cc762d74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
