<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtInvPFlListaPlazosFijos</name>
   <tag></tag>
   <elementGuidId>8fa8a7b9-f7a6-4bb8-8280-38fd0c221e70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='flxFixedTermRow_flxFixedTermRowInner'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be293f03-668b-4300-ac84-d5bc09eb5277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kwt100  sknSegProductSegmentSeparator </value>
      <webElementGuid>0a571353-c620-4d18-ac5a-dad43f72dc9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flxFixedTermRow_flxFixedTermRowInner</value>
      <webElementGuid>2a312428-4a81-4f26-b887-11e6b3217b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>FlexContainer</value>
      <webElementGuid>271610ca-5307-48b1-bc7c-2b41d7da4fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>flxFixedTermRow</value>
      <webElementGuid>35296731-affa-4380-9c9e-82dca5c4433b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kcontainerid</name>
      <type>Main</type>
      <value>segFixedTerm</value>
      <webElementGuid>46f5c5a9-beb2-4018-a9c7-94814f65dc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kuid</name>
      <type>Main</type>
      <value>E76E530F-3859-408F-A309-F4B40A4936C1</value>
      <webElementGuid>d4252f13-84bf-44d6-837e-58388dd95075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plazo FijoPesos Intransferible - Tradicional  Personas - BPI- C. Movil y BEE22 Feb 2023$ 1.060,12</value>
      <webElementGuid>82f1feb6-c4b7-45dc-b23c-8c4649ff0383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInvestmentsHomeBccl_FixedTerm_segFixedTerm&quot;)/ul[1]/li[@class=&quot;seg2Normal&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxFixedTermRow_flxFixedTermRow&quot;]/div[@class=&quot;kcell middlecenteralign&quot;]/div[@id=&quot;flexcontainer_wrapper&quot;]/div[@id=&quot;flxFixedTermRow_flxFixedTermRowInner&quot;]</value>
      <webElementGuid>20eef661-857e-41ef-b621-5f80512a5e9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='flxFixedTermRow_flxFixedTermRowInner'])[2]</value>
      <webElementGuid>6753ebcf-13b1-48a0-bb64-4a7a6ef14872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='flexcontainer_wrapper']/div)[308]</value>
      <webElementGuid>916b8f24-9b6f-492b-a4b7-716c4aa28e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='U$S 35.012,27'])[1]/following::div[5]</value>
      <webElementGuid>feea102e-bd2e-4e23-aeec-d99d983852c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/div/div/div/div/div</value>
      <webElementGuid>f288ef88-5105-44f8-b3c0-38414b25a6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flxFixedTermRow_flxFixedTermRowInner' and (text() = 'Plazo FijoPesos Intransferible - Tradicional  Personas - BPI- C. Movil y BEE22 Feb 2023$ 1.060,12' or . = 'Plazo FijoPesos Intransferible - Tradicional  Personas - BPI- C. Movil y BEE22 Feb 2023$ 1.060,12')]</value>
      <webElementGuid>0ca70a49-0d4a-48de-b1af-09807e1a5318</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
