<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxAnioDesde2021</name>
   <tag></tag>
   <elementGuidId>bca480a9-6442-47b5-94e5-bac994137081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > div.-kony-w-c-navigator-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendarDateFilterFrom-k-w-c-navigator-']/div[4]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20598569-e4ab-4b09-b905-d827c26be859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>ad8e86a7-33ac-48d4-a1e6-2200c47145a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>109855c5-1c1d-4231-9df8-8b4042328ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>2021</value>
      <webElementGuid>cc5cb0a5-351f-4be2-b512-0407949b8cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-w-c-navigator-year</value>
      <webElementGuid>969cce33-9fcb-4049-8294-356689fb6fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-hold</name>
      <type>Main</type>
      <value>2021</value>
      <webElementGuid>c3fc7f59-15c6-4234-ba94-3dbeebce911d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>[object HTMLDivElement]</value>
      <webElementGuid>a7127129-192c-4b29-a6b8-7516cb9fb639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>d1edfce1-cdb3-4963-9805-6ac14e1a43d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>235b2845-2ffb-4c81-a233-114fc808c5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferHistory_DateFilter</value>
      <webElementGuid>5a78c1e0-2edf-441a-b6a0-edc396b26c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2021</value>
      <webElementGuid>160b1e6d-b81b-4f3b-afc4-fa20c8a5c38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDateFilterFrom-k-w-c-navigator-&quot;)/div[@class=&quot;-kony-w-c-navigator-table&quot;]/div[2]/div[@class=&quot;-kony-w-c-navigator-year&quot;]</value>
      <webElementGuid>5fd2f7cd-8ca1-4e1e-a2ce-c13597a7150f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendarDateFilterFrom-k-w-c-navigator-']/div[4]/div[2]/div</value>
      <webElementGuid>6667e2a3-b717-41b1-a41e-8b998bf7bcf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dic'])[1]/following::div[13]</value>
      <webElementGuid>64e00216-a337-4dbe-b787-3668ea447fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov'])[1]/following::div[14]</value>
      <webElementGuid>1d096388-1522-4298-a5fb-6f083410a9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chatbot'])[1]/preceding::div[14]</value>
      <webElementGuid>8e759b38-e4e6-4d34-aa94-d2abb5ae8e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[15]</value>
      <webElementGuid>9462b43e-a8b9-4b46-b604-f718fa5be729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2021']/parent::*</value>
      <webElementGuid>839db17a-a6e9-4f7f-b93b-fb201219f638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>3f85b970-d1f0-4d47-99d8-c7619fb0a59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2021' or . = '2021')]</value>
      <webElementGuid>6f881ed7-5bb9-49ad-965c-c672ccad5ecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
