<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxMesDesdeJulio</name>
   <tag></tag>
   <elementGuidId>cd7559c6-5a29-4efd-a09c-480b64fbc46b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendarDateFilterFrom-k-w-c-navigator-']/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > div.-kony-w-c-navigator-month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b50700c0-0b5c-4071-897a-44d5b746731b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>04812d7e-d1c6-4857-9f75-cfddfc7f38ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ee66f74b-673a-46cb-8b17-ed9e88da6189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Julio</value>
      <webElementGuid>8fe4e82c-b6e9-4269-ad49-c7cd12a9c6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-kony-w-c-navigator-month</value>
      <webElementGuid>292e9391-1973-47b9-9f91-ada572b93446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-hold</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>de995cd9-412a-4311-95fc-1a93ccb322a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>[object HTMLDivElement]</value>
      <webElementGuid>95c1d89b-2840-4fcd-9962-56a3e9a788ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>ef7ef710-da0d-44b6-92d2-14d61ffb8108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmBcclTransfers</value>
      <webElementGuid>06ea7737-e5eb-4847-88c6-cd29c86f5f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferHistory_DateFilter</value>
      <webElementGuid>8e974f33-b86e-4cba-adcd-8dfc93d6fd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jul</value>
      <webElementGuid>dadedcc5-61ef-415c-9184-99b3a817886e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendarDateFilterFrom-k-w-c-navigator-&quot;)/div[@class=&quot;-kony-w-c-navigator-table&quot;]/div[2]/div[@class=&quot;-kony-w-c-navigator-month&quot;]</value>
      <webElementGuid>566a41d9-2b1d-40c3-8a8b-e226af7b7e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendarDateFilterFrom-k-w-c-navigator-']/div[2]/div[2]/div</value>
      <webElementGuid>09dd3786-bca5-4356-a2cb-2100b0428e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jun'])[1]/following::div[2]</value>
      <webElementGuid>90991c0f-fdac-4461-9f84-37ad149d5120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May'])[1]/following::div[3]</value>
      <webElementGuid>fa10ba97-3aa4-4678-979a-36a111e297d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ago'])[1]/preceding::div[1]</value>
      <webElementGuid>35f0a67b-d6fd-491e-ab8a-044b6fab77f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sep'])[1]/preceding::div[2]</value>
      <webElementGuid>9c70e98a-15fb-4125-b938-00159ac5a6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jul']/parent::*</value>
      <webElementGuid>f44dd2fe-8ba8-433b-bb61-582d849f4a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]/div[2]/div</value>
      <webElementGuid>241971be-6858-4227-8b59-92de8e271d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jul' or . = 'Jul')]</value>
      <webElementGuid>6f376d5b-a1a2-405e-8b19-7b3df5b2e327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
