<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtTrxDiaDesde</name>
   <tag></tag>
   <elementGuidId>ce55eb7d-39d1-4912-843b-f5a05b186bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-kony-w-c-cell-28</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-kony-w-c-cell-28']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>42f1ee41-6247-4ac3-b03c-85c0e968a4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>w-type</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>7608f7b1-7ce5-44f2-811c-194dd763b39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>TransferHistory_DateFilter</value>
      <webElementGuid>6aca6e28-fe45-4551-b902-1ce04e11c681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Calendar</value>
      <webElementGuid>7d2192c4-183d-40cb-9bde-9df49e1dd1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-k-w-c-weekday-6 -kony-w-c-day- sknCalendarWeekend</value>
      <webElementGuid>df461684-262c-45d9-bd4f-fa95ffdfa170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-kony-w-c-cell-28</value>
      <webElementGuid>cfe61d5f-94ec-46d0-ae17-9b8dd8c9131f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-id</name>
      <type>Main</type>
      <value>frmBcclTransfers_TransferHistory_DateFilter_calendarDateFilterFrom</value>
      <webElementGuid>d506d9ef-ca6b-4f18-9d63-4d40a14f320e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weekday</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>8b322de8-d0fa-43bf-8266-a06e29c8c5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-hold-day</name>
      <type>Main</type>
      <value>16,10,2021</value>
      <webElementGuid>c8e5463e-6e88-473f-84bb-3d4347673ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>k-w-c-date-retrieve</name>
      <type>Main</type>
      <value>16,10,2021</value>
      <webElementGuid>99069d2c-3568-42d2-952a-570875179513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e448ad4e-893b-41e6-94e9-425de638f249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value> 16th October 2021</value>
      <webElementGuid>0685f257-fa9a-4012-8d2e-a2a3e3bcfbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>167a6d93-4b5f-40dd-a3c0-e8ac5d43c04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-kony-w-c-cell-28&quot;)</value>
      <webElementGuid>cc12a43b-e58f-4779-b42c-b25997122f33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='-kony-w-c-cell-28']</value>
      <webElementGuid>a95ebda5-d3fd-4a4f-87c6-22ae707d58c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-k-w-c-month-cmp-10-2021']/div[2]/div[3]/div/div[7]</value>
      <webElementGuid>a80039db-ef92-4269-a696-cb953d156b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sáb'])[1]/following::div[28]</value>
      <webElementGuid>95c17d0f-5177-4873-9074-7f1db72aa3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vie'])[1]/following::div[29]</value>
      <webElementGuid>fc813b79-5ef3-4773-8da4-01bd1703902b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Número de la Tarjeta'])[1]/preceding::div[30]</value>
      <webElementGuid>c7182be7-6166-4ed3-a98d-4bbfcebd8cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consta de 16 dígitos. Aquí sólo deberás ingresar los últimos 4.'])[1]/preceding::div[32]</value>
      <webElementGuid>c2a8e80f-faaf-4952-920c-29885a2dd31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16']/parent::*</value>
      <webElementGuid>d99b6f76-076f-4e96-93e3-ffb0d15e0aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[7]</value>
      <webElementGuid>921a6afe-0131-49d9-a847-2531514e1da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '-kony-w-c-cell-28' and (text() = '16' or . = '16')]</value>
      <webElementGuid>562246af-5f43-4f6b-83a1-3508b405d0b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
