<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnLgnBanner</name>
   <tag></tag>
   <elementGuidId>5bbc5e15-7fea-4ffa-8b1d-9ed6d04a36e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmLogin_InformativeModal_CancelAcceptButtons_AcceptButton_btnCommon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmLogin_InformativeModal_CancelAcceptButtons_AcceptButton_btnCommon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa109501-fdc5-45ea-b3a6-ca3a2b2bf44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmLogin_InformativeModal_CancelAcceptButtons_AcceptButton_btnCommon</value>
      <webElementGuid>073fa2bb-7cf8-4fc5-b588-9d9a8c51a907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>3be76c41-9518-4197-a5a7-dfb3502a71cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmLogin</value>
      <webElementGuid>aa32fb42-d86a-4efc-9dfa-8a9ba80015dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>InformativeModal_CancelAcceptButtons_AcceptButton</value>
      <webElementGuid>265b8d25-2d40-452c-8b59-bc75866e830f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90e0c3df-acd3-4cff-ac2f-8b1050f0327b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disableSelection sknBtnPrimaryBold</value>
      <webElementGuid>b8373332-fd75-40fd-b5af-4e367f3221c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Aceptar cookies</value>
      <webElementGuid>0367cf12-9891-4414-a321-1c0e48ca2a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kprogressskin</name>
      <type>Main</type>
      <value>sknBtnPrimaryBold</value>
      <webElementGuid>0e1a1fc7-4fed-47d7-963d-d1141d79296e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin_InformativeModal_CancelAcceptButtons_AcceptButton_btnCommon&quot;)</value>
      <webElementGuid>aa3f0457-b951-4116-8127-51a5221dfd5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmLogin_InformativeModal_CancelAcceptButtons_AcceptButton_btnCommon']</value>
      <webElementGuid>cddb57ba-1f39-4768-a3ce-dbfa71df060e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmLogin_InformativeModal_CancelAcceptButtons_AcceptButton']/div/input</value>
      <webElementGuid>6d8e86a0-b3b1-45e1-be01-8d6a921e34de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>aac30817-9e41-4963-aa2e-68425e3ec1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmLogin_InformativeModal_CancelAcceptButtons_AcceptButton_btnCommon' and @type = 'button']</value>
      <webElementGuid>91613907-97d3-401c-a750-44f2a7d717c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
