<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblLgnBanner</name>
   <tag></tag>
   <elementGuidId>81ea3ef4-fb69-4577-9a47-bd4fa295446a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmLogin_InformativeModal_lblTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmLogin_InformativeModal_lblTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c10e02a9-2b2e-4ee9-8ec5-a871c5414cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmLogin_InformativeModal_lblTitle</value>
      <webElementGuid>6de1c525-cb4f-422f-b3b9-acdb664e1af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>c2d22fed-20ef-4104-b212-b2345f17436c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmLogin</value>
      <webElementGuid>90efbd64-054f-43f2-ad6f-e7dec203231a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>InformativeModal</value>
      <webElementGuid>58380581-073a-448a-8fb7-b54798405e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblMont36Medium414042 cntmiddleleftalign disableSelection</value>
      <webElementGuid>01b0e992-d847-4941-a6f4-cdbd4629b15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡Te damos la bienvenida!</value>
      <webElementGuid>355711d2-44ad-46d4-968b-1d9989ef78c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin_InformativeModal_lblTitle&quot;)</value>
      <webElementGuid>859745fd-face-4e65-b44f-5bb2f11d4421</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmLogin_InformativeModal_lblTitle']</value>
      <webElementGuid>afebe9d2-8c14-491c-80b0-94c19b160696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmLogin_InformativeModal_flxTitle']/div/div</value>
      <webElementGuid>4ce4356f-4f07-45ea-82e4-fd3313908be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clave Móvil'])[1]/following::div[20]</value>
      <webElementGuid>6aa9a93f-6d05-4d2d-8cfb-e3650624efc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[22]</value>
      <webElementGuid>8eb72ad9-e12a-458e-be24-d6ee0aeeb0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[4]/preceding::div[38]</value>
      <webElementGuid>93921dbc-dfd5-465c-ac4a-f5a6786782cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tu clave de ingreso fue actualizada. No se pudo completar tu solicitud, intentá en unos minutos.'])[1]/preceding::div[40]</value>
      <webElementGuid>c441db20-33c7-4dca-9941-4d2d4bb62eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡Te damos la bienvenida!']/parent::*</value>
      <webElementGuid>51d6f174-910d-4298-80b0-a3d02cf98c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]/div/div/div[3]/div/div/div/div/div/div/div</value>
      <webElementGuid>d260a997-e9d3-4442-becb-8ee1a0d828f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmLogin_InformativeModal_lblTitle' and (text() = '¡Te damos la bienvenida!' or . = '¡Te damos la bienvenida!')]</value>
      <webElementGuid>8eb251de-3ee9-453c-86fc-6ca664378a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
