<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblLgnClaveNoCoincide</name>
   <tag></tag>
   <elementGuidId>160cebc9-07fa-4f9c-8a80-42c505e3837f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmResetPasswordBccl_ChangePassword_RePassword_lblValidationErrorMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmResetPasswordBccl_ChangePassword_RePassword_lblValidationErrorMessage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>54f506f0-c4aa-4954-a72b-ebbb0aeea4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmResetPasswordBccl_ChangePassword_RePassword_lblValidationErrorMessage</value>
      <webElementGuid>78bd600f-32b2-4087-9184-07b1d9f92419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>cda7e420-7daa-4089-acfc-66e7c01f3904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmResetPasswordBccl</value>
      <webElementGuid>6c3c0127-fc6d-4752-92ce-2e76e1da01e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ChangePassword_RePassword</value>
      <webElementGuid>8269aa1f-b089-48f3-b5f7-ac8194e504a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblValidationErrorMessage cnttopleftalign disableSelection</value>
      <webElementGuid>9e99dec7-b10b-493d-9f2d-a79c2c9a8c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>La clave ingresada no coincide con la anterior.</value>
      <webElementGuid>9e06ce1a-8ff3-4268-a8b3-77221883319c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmResetPasswordBccl_ChangePassword_RePassword_lblValidationErrorMessage&quot;)</value>
      <webElementGuid>965d8f18-3274-4574-9ec1-761cee2dda16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmResetPasswordBccl_ChangePassword_RePassword_lblValidationErrorMessage']</value>
      <webElementGuid>8598e87e-8475-4053-a752-2103c20c7798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmResetPasswordBccl_ChangePassword_RePassword_flxValidationError']/div/div</value>
      <webElementGuid>51eeba6c-9269-43e4-9e4c-5d34e9baf0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDIA'])[3]/following::div[8]</value>
      <webElementGuid>1e5d5535-803b-4cd8-a463-7af1cc68d330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fortaleza de la clave'])[3]/following::div[10]</value>
      <webElementGuid>01fb3c83-f007-46e6-bc39-534368306407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>9a874b10-07dc-4c6a-80ff-5040f0b96f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/preceding::div[3]</value>
      <webElementGuid>c5bae2bb-afc2-441b-8f04-aaa90de2a3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='La clave ingresada no coincide con la anterior.']/parent::*</value>
      <webElementGuid>d4752838-4a52-4bca-829b-12d555675fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>91bd619b-32da-4e6f-9af0-f32d1237a154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmResetPasswordBccl_ChangePassword_RePassword_lblValidationErrorMessage' and (text() = 'La clave ingresada no coincide con la anterior.' or . = 'La clave ingresada no coincide con la anterior.')]</value>
      <webElementGuid>6753c7b8-56de-42de-840b-f0e7e9c0ea51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
