<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnuLgnUsuario</name>
   <tag></tag>
   <elementGuidId>2ac4199b-af24-4ce5-9719-c14d043f2399</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_lblChevron']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmAccountsLanding_customheader_WelcomeProfile_lblChevron</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b623ca8e-8319-4baf-8cc4-75081cb67be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmAccountsLanding_customheader_WelcomeProfile_lblChevron</value>
      <webElementGuid>39c43f5c-243c-4d09-835c-6a1c20b0d68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>Label</value>
      <webElementGuid>c30f3bba-2329-4831-a7b9-2d52d9a3da3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmAccountsLanding</value>
      <webElementGuid>d24b11ab-e2f7-4cb5-a62b-3ab4c04d1c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>customheader_WelcomeProfile</value>
      <webElementGuid>939ddc76-1ae1-4d91-b3db-876a0936e091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknLblFontAwesomeReg16FF cntmiddleleftalign disableSelection</value>
      <webElementGuid>6b7127fd-e0d7-40a1-9eca-71d4724a0042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a1d17375-588a-49e6-8e53-909f7066fd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmAccountsLanding_customheader_WelcomeProfile_lblChevron&quot;)</value>
      <webElementGuid>8eae90f2-7263-424a-b0b4-f18bf62c17ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_lblChevron']</value>
      <webElementGuid>227ae8f9-89c3-452a-a4ef-53f09935365c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmAccountsLanding_customheader_WelcomeProfile_flxContainerChevron']/div/div</value>
      <webElementGuid>15707ce1-b034-41a0-b0a2-d130aaffcf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[6]</value>
      <webElementGuid>36e4ea61-122d-471b-b135-5692c22c6e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Última sesión: 03/05/2023 17:39 hs.'])[1]/following::div[11]</value>
      <webElementGuid>00ce7d40-c664-4525-9521-8f74113f0ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[1]</value>
      <webElementGuid>b52f1609-d187-4d86-8ad2-0dd55c5b24c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil'])[1]/preceding::div[6]</value>
      <webElementGuid>947cde24-09ac-47bc-9331-613b00c18452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>bbdd708d-4092-4d33-befc-a18d5cede51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div[3]/div/div/div/div</value>
      <webElementGuid>3f2554c5-eeeb-4550-88be-c620cfba654b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'frmAccountsLanding_customheader_WelcomeProfile_lblChevron' and (text() = '' or . = '')]</value>
      <webElementGuid>65b3d0ef-aa26-4106-9a40-dddc2dd31a17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
