<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtLgnClaveActual</name>
   <tag></tag>
   <elementGuidId>58b10311-c7fe-4a4a-b7e3-2fa87db70bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked&quot;)[count(. | //*[@id = 'frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked' and @type = 'password' and @placeholder = 'Ingresar clave actual']) = count(//*[@id = 'frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked' and @type = 'password' and @placeholder = 'Ingresar clave actual'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffb08765-09f0-4e0a-b616-e29c0d12d6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked</value>
      <webElementGuid>48e8d6bf-0ea9-4241-aa32-073f850913ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>308d3242-a7ca-4935-9f77-7a42e610e9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmResetPasswordBccl</value>
      <webElementGuid>f5c68f95-3e54-49a6-b801-e280b97e3f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ChangePassword_ActualPassword</value>
      <webElementGuid>d2a9940c-c11c-40bd-a1c8-2b7d6b61d702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknTbxInputMasked </value>
      <webElementGuid>8ccd5c76-9d18-46d1-9490-87bc8e56f0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>04d828d8-f851-457c-a805-14fb2dd8bcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7b3bfddf-ca6e-4982-85f8-e74f11df24ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cf6ba8b7-c131-45bf-8218-93fd1da12535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>52a55308-a141-4cc5-8af5-15c065ea41a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>167098de-4d90-4f22-93fd-1f1a62749cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>2a826e93-03f1-4ea1-9037-7d22f6d731d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresar clave actual</value>
      <webElementGuid>290acc13-edba-460a-b102-f23b7484ca2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>3dea7f10-4ca8-4141-8029-d936c03fffb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked&quot;)</value>
      <webElementGuid>7853b77d-a92e-47d4-84c3-58ba8b4af7a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked']</value>
      <webElementGuid>082de0e6-3afb-4f48-b4e8-7e343ac956ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmResetPasswordBccl_ChangePassword_ActualPassword_flxInputMaskedContainer']/div/input</value>
      <webElementGuid>e1782038-09c0-4069-93d1-b7c2a04422b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>4b0d5838-9613-47c2-9458-7bf8246ba0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmResetPasswordBccl_ChangePassword_ActualPassword_tbxMasked' and @type = 'password' and @placeholder = 'Ingresar clave actual']</value>
      <webElementGuid>066c477d-3ccd-4427-8eef-3c1d3fc2ef27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
