<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtLgnUsuario</name>
   <tag></tag>
   <elementGuidId>2e4a5af3-1f1e-4ec3-abf9-b7f80d36780d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmLogin_main_UserInputMasked_tbxMasked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmLogin_main_UserInputMasked_tbxMasked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ffdfd1c-bf3a-46b5-a9f7-56deff6ecaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmLogin_main_UserInputMasked_tbxMasked</value>
      <webElementGuid>49da1e18-1aa5-41df-8247-f661a21f8e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>0cf27410-dd7f-4f71-a13d-418617af5324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmLogin</value>
      <webElementGuid>187fb3b7-5b4c-4d1b-a8af-7f0dba183b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>main_UserInputMasked</value>
      <webElementGuid>a428a856-9e3c-439f-8a66-e74e0feb07ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bfaa19cf-e2f1-42aa-b582-dbf5d59b0592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknTbxInputMasked </value>
      <webElementGuid>e14fab96-d0d4-48e5-bb55-768427d1a53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>35501230-1900-4e2b-a654-6fb02999cf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2b6652cd-57c2-4256-a346-6530c0bf95c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>09117f7c-9e5d-49b7-b5d0-31ddee4ff435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>197379e6-c112-4539-b939-742d69aaad7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>fe3b2baf-7448-4a11-98e7-253457496295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>63836d6f-91b9-42f7-aa84-195cca7da29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingresar usuario</value>
      <webElementGuid>762b3e1f-9b2a-4f1a-9d0c-8e6e24dce2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>77c8058b-98aa-47b1-986a-b1fadcaf6cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Campo nombre de usuario. Se puede ingresar texto.</value>
      <webElementGuid>998f2ed2-bced-4568-83ca-038c72f66642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>frmLogin_main_UserInputMasked_tbxMasked-hint</value>
      <webElementGuid>d21bf1b1-e08a-4796-a1fb-cec2b040e61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin_main_UserInputMasked_tbxMasked&quot;)</value>
      <webElementGuid>04925fdb-012e-4000-80a8-84d70644913a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmLogin_main_UserInputMasked_tbxMasked']</value>
      <webElementGuid>c1c432f9-7731-4eb8-ab48-d12b6fb70f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmLogin_main_UserInputMasked_flxInput']/div/input</value>
      <webElementGuid>1c776b12-b99a-4d91-b0a0-b83c0598c4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div/div[2]/div/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>33e129b3-f8db-4168-a50c-74b76e239c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmLogin_main_UserInputMasked_tbxMasked' and @type = 'text' and @placeholder = 'Ingresar usuario']</value>
      <webElementGuid>df2e3cbc-256b-4a8a-ae2d-24d4fd1e10d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
