<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtReingresarClave</name>
   <tag></tag>
   <elementGuidId>a6995977-ca07-4bb3-a604-59381a145527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#frmResetPasswordBccl_ChangePassword_RePassword_tbxMasked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmResetPasswordBccl_ChangePassword_RePassword_tbxMasked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c82269b-c6e7-4d80-8d2c-52dc0bf413ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmResetPasswordBccl_ChangePassword_RePassword_tbxMasked</value>
      <webElementGuid>404c584a-dc5c-4130-be94-2f21273213d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kwidgettype</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>f6a31d60-e1c9-4c57-9071-88351743c028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kformname</name>
      <type>Main</type>
      <value>frmResetPasswordBccl</value>
      <webElementGuid>d34c9846-d092-48ad-bb83-52e364ff05dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kmasterid</name>
      <type>Main</type>
      <value>ChangePassword_RePassword</value>
      <webElementGuid>07f90611-09d3-4074-8969-f35679ce5be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kdisabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f635eb94-2a97-4d7d-ad6b-da8fb845e123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b10f846d-0d1f-47e8-81f3-c8ebb9fd13b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> sknTbxInputMasked </value>
      <webElementGuid>405519c8-2768-4347-a703-42367384842b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>53174d47-f3f6-4774-95a9-29f9e7e7a893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8efdf2c9-b507-4bb6-81b7-226834d5e3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0498cfee-61cc-463a-bdf8-459e22f3fb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4c0e9541-3a5f-424c-be4c-8904b4f768d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$KW.TextField.onfocusEventHandler(arguments[0],this)</value>
      <webElementGuid>23e917e2-608d-40bb-93b4-84de499ec0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>$KW.TextField.onblurEventHandler(arguments[0],this)</value>
      <webElementGuid>9d1d1ea9-0392-4a78-9163-0413cbc0f724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Reingresar nueva clave</value>
      <webElementGuid>1cb07948-6cf1-4fda-9bc1-e93a24393297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>7ca74332-5a6f-4465-ac1c-3cd8066175c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmResetPasswordBccl_ChangePassword_RePassword_tbxMasked&quot;)</value>
      <webElementGuid>899aad5c-3222-45c9-8ff6-00d20db4331f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmResetPasswordBccl_ChangePassword_RePassword_tbxMasked']</value>
      <webElementGuid>136085a6-3561-438a-a468-0738a13d95f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmResetPasswordBccl_ChangePassword_RePassword_flxInputMaskedContainer']/div/input</value>
      <webElementGuid>335d3fb4-68a4-494a-b213-f5ac53376796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>1e0429db-87b6-4dba-9ea1-d7e9b2a1f934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmResetPasswordBccl_ChangePassword_RePassword_tbxMasked' and @type = 'password' and @placeholder = 'Reingresar nueva clave']</value>
      <webElementGuid>5c6b41d9-2543-4f0d-879b-592878725613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
